force/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Bypass_VC_Validation_Rules__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass VC Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vision_Care_Location_Key__c</fullName>
        <encrypted>true</encrypted>
        <label>Vision Care Location Key</label>
        <length>125</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact_Role__c.object
<CustomObject>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force/src/objects/Network_Relationship__c.object
<CustomObject>
    <description>Custom object to track Payment Relationships between doctors and offices.</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Network Relationships</relationshipLabel>
        <relationshipName>Network_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Bypass_VC_Validation_Rules__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass VC Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact_Role__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact Role</label>
        <referenceTo>Contact_Role__c</referenceTo>
        <relationshipName>Payment_Relationships</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Effective_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Program Effective Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Program_End_Date__c</fullName>
        <label>Program End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Program_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup relationship field from Network Relationship to General Table object</description>
        <label>Program ID</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>General_Table__c.Table__c</field>
                <operation>equals</operation>
                <value>PRSP</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>General_Table__c</referenceTo>
        <relationshipLabel>Network Relationships</relationshipLabel>
        <relationshipName>Network_Relationships</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_Care_Location_Key__c</fullName>
        <label>Vision Care Location Key</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Network Relationship</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Network Relationship Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Network Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/VSPR19b_restrictOverlappingNR.cls
public class VSPR19b_restrictOverlappingNR {
    
    public static boolean goDo_recursion = true;
    public static void goDo(List<Network_Relationship__c> records) 
    {
        if(goDo_recursion){
        goDo_recursion = false;
        
            List<Profile> getUserProfile = [SELECT Id, Name FROM Profile WHERE Id=:userinfo.getProfileId() LIMIT 1];
            String profileName = getUserProfile[0].Name;
            
            Map<Id,Account> netRelAccMap = new Map<Id,Account>();
            Set<Id> netRelAccIds = new Set<Id>();
            for(Network_Relationship__c netRels : records){
                netRelAccIds.add(netRels.Account_Name__c);
            }
            if(!netRelAccIds.isEmpty()){
                for(Account nRAcc : [SELECT Id, Vision_Care_Location_Key__c FROM Account WHERE Id IN :netRelAccIds]){
                    netRelAccMap.put(nrAcc.Id, nrAcc);
                }
            }     
            
            List<String> cRoles = new List<String>();
            for(Network_Relationship__c y : records){
                cRoles.add(y.Contact_Role__c);
            }
                 
            List<Network_Relationship__c> nrRecs = 
                [SELECT Id, Contact_Role__c, Program_ID__c, Program_End_Date__c, Vision_Care_Location_Key__c
                 FROM Network_Relationship__c
                 WHERE Contact_Role__c =: cRoles
                 AND Id !=: records
                 AND Bypass_VC_Validation_Rules__c = FALSE];
                        
            if(!nrRecs.isEmpty()){
                for(Network_Relationship__c z : records){
                    for(Network_Relationship__c x : nrRecs){
                        if(x.Contact_Role__c == z.Contact_Role__c &&
                           x.Program_ID__c == z.Program_ID__c &&
                           x.Vision_Care_Location_Key__c == netRelAccMap.get(z.Account_Name__c).Vision_Care_Location_Key__c &&  /// Allow overlapping Net Rels if Vision Care Location Keys are different
                           (
                            ((x.Program_End_Date__c >= z.Program_End_Date__c) && z.Program_End_Date__c != NULL)
                            ||
                            (x.Program_End_Date__c == NULL && z.Program_End_Date__c != NULL)
                            ||
                            (x.Program_End_Date__c != NULL && z.Program_End_Date__c == NULL && (z.Program_Effective_Date__c <= x.Program_End_Date__c))
                            ||
                            (x.Program_End_Date__c == NULL && z.Program_End_Date__c == NULL)
                           )){
                            if(profileName != 'VSP Technical User' &&
                               profileName != 'System Administrator' &&
                               profileName != 'VSP Integration User' &&
                               z.Bypass_VC_Validation_Rules__c == FALSE){
    
                                z.addError('Network Relationship effective dates must not overlap with existing Network Relationship records.');
                            }
                        }
    
                    }
                }
            }
        }
    }

}