force/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <description>For Practice and Business accounts so that the data can be populated for use in premier tier calculation.
Population on Business account will be manual or through data loader.</description>
        <inlineHelpText>Identifies the location&apos;s relationship with VSP for Premier Tiering</inlineHelpText>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Affiliate</fullName>
                </value>
                <value>
                    <fullName>AOP</fullName>
                </value>
                <value>
                    <fullName>CAT2</fullName>
                </value>
                <value>
                    <fullName>Conflict</fullName>
                </value>
                <value>
                    <fullName>GAP</fullName>
                </value>
                <value>
                    <fullName>Independent</fullName>
                </value>
                <value>
                    <fullName>LVC</fullName>
                </value>
                <value>
                    <fullName>Near Site</fullName>
                </value>
                <value>
                    <fullName>Net Dev Excluded</fullName>
                </value>
                <value>
                    <fullName>Net Dev Purchasing Requirement</fullName>
                </value>
                <value>
                    <fullName>Not Supported</fullName>
                </value>
                <value>
                    <fullName>Onsite</fullName>
                </value>
                <value>
                    <fullName>Pearle Vision CO</fullName>
                </value>
                <value>
                    <fullName>Pearle Vision LO</fullName>
                </value>
                <value>
                    <fullName>Pop Up</fullName>
                </value>
                <value>
                    <fullName>Rollup</fullName>
                </value>
                <value>
                    <fullName>School</fullName>
                </value>
                <value>
                    <fullName>VSP Retail</fullName>
                </value>
                <value>
                    <fullName>VSP Ventures</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Eyewear_Location_Spend_LTM__c</fullName>
        <inlineHelpText>Location&apos;s spend on Eyewear in the last 12 months</inlineHelpText>
        <label>Eyewear Location Spend LTM</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Non_VC_Exception__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Non VC Exception</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Optics_Location_Spend_LTM__c</fullName>
        <inlineHelpText>Location&apos;s spend on Optics in the last 12 months</inlineHelpText>
        <label>Optics Location Spend LTM</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Premier_Tax_ID_Roll_Up_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Indicates whether an Account is being evaluated for Premier qualification in conjunction with other accounts with different Tax ID&apos;s.</inlineHelpText>
        <label>Tax ID Roll Up Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Offering_s__c</fullName>
        <label>Service Offering (s)</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CCLOC - CareCredit Program Participant</fullName>
                </value>
                <value>
                    <fullName>CVLKT - CIGNA Luxottica Collection</fullName>
                </value>
                <value>
                    <fullName>CVVKT - CIGNA VisionWorks Collection</fullName>
                </value>
                <value>
                    <fullName>EXAM - Exam only location</fullName>
                </value>
                <value>
                    <fullName>EYEWR - Dispensing only location</fullName>
                </value>
                <value>
                    <fullName>FFAA - Free Fitting and Adjustments</fullName>
                </value>
                <value>
                    <fullName>LEVEL - Level Provider</fullName>
                </value>
                <value>
                    <fullName>PEDKT - Otis and Piper Collection</fullName>
                </value>
                <value>
                    <fullName>PTSF - PROTEC Safety Fame Kit - Free</fullName>
                </value>
                <value>
                    <fullName>RTLIM - Retinal Imaging</fullName>
                </value>
                <value>
                    <fullName>SFTY - Safety Eyewear</fullName>
                </value>
                <value>
                    <fullName>SPRTS - Sports Eyewear</fullName>
                </value>
                <value>
                    <fullName>TELEH - Telehealth Provider</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of Account.</description>
        <inlineHelpText>A = Active 
Inactive = Not a Current Customer of any LOB. 
Closed = Business has ceased operations 
New = In process of becoming an Active account</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Submit for Approval</fullName>
                </value>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Inactive Ownership Change</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
                <value>
                    <fullName>Marked for Deletion</fullName>
                </value>
                <value>
                    <fullName>Archive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tax_ID__c</fullName>
        <description>Account Tax ID.</description>
        <encrypted>true</encrypted>
        <inlineHelpText>Account Tax ID.</inlineHelpText>
        <label>Tax ID</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tier_Agreement_Type__c</fullName>
        <label>Tier Agreement Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Location_Spend_LTM__c</fullName>
        <inlineHelpText>Location&apos;s spend on Eyewear and Optics in the last 12 months</inlineHelpText>
        <label>Total Location Spend LTM</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>VC__c</fullName>
        <formula>IF( Vision_Care_Effective_Date__c &lt;= TODAY()  &amp;&amp; (Vision_Care_End_Date__c &gt;=TODAY() ||  ISBLANK(Vision_Care_End_Date__c)) , TRUE, FALSE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>VC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vision_Care_Effective_Date__c</fullName>
        <label>Vision Care Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Care_End_Date__c</fullName>
        <label>Vision Care End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Care_Good_Standing__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is account in good standing with Vision Care.</description>
        <inlineHelpText>Is account in good standing with Vision Care.</inlineHelpText>
        <label>Vision Care Good Standing</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force/src/objects/Global_Rewards_Group__c.object
<CustomObject>
    <description>Parent object in a relationship that groups multiple Business/Practice Accounts under one Global Rewards Program (child object is Global Rewards Group Relationship)</description>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Affiliate</fullName>
                </value>
                <value>
                    <fullName>AOP</fullName>
                </value>
                <value>
                    <fullName>CAT2</fullName>
                </value>
                <value>
                    <fullName>Conflict</fullName>
                </value>
                <value>
                    <fullName>GAP</fullName>
                </value>
                <value>
                    <fullName>Independent</fullName>
                </value>
                <value>
                    <fullName>LVC</fullName>
                </value>
                <value>
                    <fullName>Near Site</fullName>
                </value>
                <value>
                    <fullName>Net Dev Excluded</fullName>
                </value>
                <value>
                    <fullName>Net Dev Purchasing Requirement</fullName>
                </value>
                <value>
                    <fullName>Not Supported</fullName>
                </value>
                <value>
                    <fullName>Onsite</fullName>
                </value>
                <value>
                    <fullName>Pearle Vision CO</fullName>
                </value>
                <value>
                    <fullName>Pearle Vision LO</fullName>
                </value>
                <value>
                    <fullName>Pop Up</fullName>
                </value>
                <value>
                    <fullName>Rollup</fullName>
                </value>
                <value>
                    <fullName>School</fullName>
                </value>
                <value>
                    <fullName>VSP Retail</fullName>
                </value>
                <value>
                    <fullName>VSP Ventures</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF( OR( Start_Date__c = TODAY() , AND( Start_Date__c &lt; TODAY() , OR( End_Date__c &gt;= TODAY() , ISBLANK( End_Date__c ) ) ) ) , &quot;Active&quot;, &apos;Inactive&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tier_Agreement_Type__c</fullName>
        <inlineHelpText>The Agreement Type used to calculate the Premier Tier</inlineHelpText>
        <label>Tier Agreement Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Care_Good_Standing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Vision Care Good Standing</label>
        <type>Checkbox</type>
    </fields>
    <label>Global Rewards Group</label>
    <nameField>
        <label>Global Rewards Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Global Rewards Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force/src/objects/Global_Rewards_Group_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Child_Account__c</fullName>
        <label>Child Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Global Rewards Group Relationships</relationshipLabel>
        <relationshipName>Global_Rewards_Group_Relationships</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>Date the child record was ended its relationship with the Parent Roll up account.</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Global_Rewards_Group__c</fullName>
        <label>Global Rewards Group</label>
        <referenceTo>Global_Rewards_Group__c</referenceTo>
        <relationshipLabel>Global Rewards Group Relationships</relationshipLabel>
        <relationshipName>Global_Rewards_Group</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Date the child record was added to the Parent Roll up account.</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF((Start_Date__c &lt;= TODAY() &amp;&amp; (ISBLANK(End_Date__c) ||  End_Date__c &gt;= TODAY())), &apos;Active&apos;, 
IF((Start_Date__c &gt; Today()), &apos;Future&apos;, &apos;Inactive&apos;))</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Global Rewards Group Relationship</label>
    <nameField>
        <displayFormat>PREMIER-{0000}</displayFormat>
        <label>Global Rewards Group Relationship ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Global Rewards Group Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force/src/classes/VSPR31_Premier_Prac_Bus_Acc_Avg_Batch.cls
global class VSPR31_Premier_Prac_Bus_Acc_Avg_Batch implements Database.Batchable<sObject>, Database.Stateful{
    
    global final String Query;
    
    global List<String> exception_List = new List<String>();
    private static Id accBusRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
    private Set<Id> pAccIdSet = new Set<Id>();
    
    global VSPR31_Premier_Prac_Bus_Acc_Avg_Batch(Set<Id> prAccId){
        pAccIdSet = prAccId;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator([SELECT Id, Tax_ID__c, Premier_Tax_ID_Roll_Up_Account__c, Tier_Agreement_Type__c 
                                         FROM Account
                                         WHERE Id IN :pAccIdSet]);
    }
    
    global void execute(Database.BatchableContext BC, List<Account> scope){
        
        
        VSPUtility.stopAccountTrigger=true;
        
        Map<Id,Account> pracAccSetSameContractType = new Map<Id,Account>();
        for(Account s : scope){
            pracAccSetSameContractType.put(s.Id,s);
        }
        
        
        
        
        ////Premier 1.0/////
        if(!pracAccSetSameContractType.isEmpty()){ 
            List<Global_Rewards_Group_Relationship__c> grgRLstUpd = new List<Global_Rewards_Group_Relationship__c>();
            List<Account> pracAccToUpdate = new List<Account>();
            
            Map<Id,List<Decimal>> busAccTotalPurchasesMap = new Map<Id,List<Decimal>>();
            Map<Id,List<Decimal>> busAccFramePurchasesMap = new Map<Id,List<Decimal>>();
            Map<Id,List<Decimal>> busAccLensPurchasesMap = new Map<Id,List<Decimal>>();
            ///////////////if contract type is all the same//////////////
            //
            //
            
            
            /*    List<Account> busAccCTquery = [Select Id, Name, Contract_Type__c, ParentId FROM Account Where ParentId in :pracAccSetSameContractType AND
Vision_Care_Good_Standing__c = True AND Status__c = 'A' AND
Vision_Care_Effective_Date__c <= TODAY AND (Vision_Care_End_Date__c >= TODAY OR Vision_Care_End_Date__c = null) AND
RecordTypeId = :accBusRecordTypeId AND Contract_Type__c != NULL];*/
            
            List<Global_Rewards_Group_Relationship__c> existBusGrpRelation = [SELECT Active__c, Child_Account__c, Global_Rewards_Group__c, Global_Rewards_Group__r.Name, Start_Date__c, 
                                                                              End_Date__c, Global_Rewards_Group__r.RecordTypeId, Child_Account__r.ParentId
                                                                              FROM Global_Rewards_Group_Relationship__c WHERE Child_Account__r.ParentId IN :pracAccSetSameContractType.keySet() AND End_Date__c = NULL];
            
            List<Account> allBusAccAvg = [SELECT ParentId, Id, Total_Location_Spend_LTM__c, Eyewear_Location_Spend_LTM__c, Optics_Location_Spend_LTM__c, Contract_Type__c 
                                          FROM Account 
                                          WHERE (ParentId in :pracAccSetSameContractType.keySet() 
                                                 AND Vision_Care_Good_Standing__c = True AND VC__c = True
                                                 AND RecordTypeId = :accBusRecordTypeId)
                                          OR
                                          (ParentId in :pracAccSetSameContractType.keySet()
                                           AND RecordTypeId = :accBusRecordTypeId
                                           AND Non_VC_Exception__c = True)];
            
            
            
            
            AggregateResult[] busActiveAccCount =  [SELECT ParentId, Count(Id) Total 
                                                    FROM Account 
                                                    Where ParentId in :pracAccSetSameContractType.keySet() 
                                                    AND Vision_Care_Good_Standing__c = True AND VC__c = True
                                                    //   AND Status__c = 'A' 
                                                    //  AND Vision_Care_Effective_Date__c <= TODAY 
                                                    //  AND (Vision_Care_End_Date__c >= TODAY OR Vision_Care_End_Date__c = null) 
                                                    AND Contract_Type__c != NULL AND
                                                    RecordTypeId = :accBusRecordTypeId
                                                    Group By ParentId];
            
            AggregateResult[] busAccRetinalImgCount =  [SELECT ParentId, Count(Id) Total FROM Account Where ParentId in :pracAccSetSameContractType.keySet() AND
                                                        Vision_Care_Good_Standing__c = True AND VC__c = True AND
                                                        //Status__c = 'A' AND
                                                        //Vision_Care_Effective_Date__c <= TODAY AND (Vision_Care_End_Date__c >= TODAY OR Vision_Care_End_Date__c = null) AND
                                                        Service_Offering_s__c includes ('RTLIM - Retinal Imaging') AND
                                                        RecordTypeId = :accBusRecordTypeId
                                                        Group By ParentId];
            
            AggregateResult[] busAccFreeFittingCount =  [SELECT ParentId, Count(Id) Total FROM Account Where ParentId in :pracAccSetSameContractType.keySet() AND
                                                         Vision_Care_Good_Standing__c = True AND VC__c = True AND
                                                         // Status__c = 'A' AND
                                                         // Vision_Care_Effective_Date__c <= TODAY AND (Vision_Care_End_Date__c >= TODAY OR Vision_Care_End_Date__c = null) AND
                                                         Service_Offering_s__c includes ('FFAA - Free Fitting and Adjustments') AND
                                                         RecordTypeId = :accBusRecordTypeId
                                                         Group By ParentId];
            
            AggregateResult[] busAccNODISCount =  [SELECT ParentId, Count(Id) Total FROM Account Where ParentId in :pracAccSetSameContractType.keySet() AND
                                                   Vision_Care_Good_Standing__c = True AND VC__c = True AND
                                                   //Status__c = 'A' AND
                                                   //Vision_Care_Effective_Date__c <= TODAY AND (Vision_Care_End_Date__c >= TODAY OR Vision_Care_End_Date__c = null) AND
                                                   Participation_Exclusions__c includes ('NODIS – Opts out of discounts')  AND
                                                   RecordTypeId = :accBusRecordTypeId
                                                   Group By ParentId];      
            
            
            
            for(Id pAccId: pracAccSetSameContractType.keySet()){
                Account pAcc = pracAccSetSameContractType.get(pAccId);
                System.debug('pAcc for loop '+ pAcc.Id);
                pAcc.Number_of_Eligible_Locations__c = 0;
                pAcc.Total_Average_Purchases_LTM_Calculated__c = 0;
                pAcc.Average_Frame_Purchases_LTM_Calculated__c = 0;
                pAcc.Average_Lens_Purchases_LTM_Calculated__c = 0;
                pAcc.Retinal_Imaging_Indicator__c = false;
                pAcc.Exclusive_VSP_Patient_Offers__c = true;
                pAcc.Free_Fitting_and_Adjustments__c = true;
                
                //   pAcc.Contract_Type__c = null; //For Contract Type of a Practice Account
                
                for(AggregateResult ar : busActiveAccCount){
                    if(ar.get('ParentId') == pAcc.Id){                   
                        pAcc.Number_of_Eligible_Locations__c = ((decimal)ar.get('Total'));
                        //       pAcc.Total_Average_Purchases_LTM_Calculated__c = ((decimal)ar.get('Total_Average_Purchases_LTM')); 
                        //      pAcc.Average_Frame_Purchases_LTM_Calculated__c = ((decimal)ar.get('Average_Frame_Purchases_LTM__c'));
                        //     pAcc.Average_Lens_Purchases_LTM_Calculated__c = ((decimal)ar.get('Average_Lens_Purchases_LTM__c')); 
                    }
                }//end Aggregate For Loop
                
                for(AggregateResult ar1 :busAccRetinalImgCount){
                    if(ar1.get('ParentId') == pAcc.Id){
                        pAcc.Retinal_Imaging_Indicator__c = true;
                    }
                }//end Aggregate1 For Loop
                
                for(AggregateResult ar2 :busAccNODISCount){
                    if(ar2.get('ParentId') == pAcc.Id){
                        pAcc.Exclusive_VSP_Patient_Offers__c = false;
                    }
                }//end Aggregate2 For Loop
                
                for(AggregateResult ar3 :busAccFreeFittingCount){
                    if(ar3.get('ParentId') == pAcc.Id){
                        pAcc.Free_Fitting_and_Adjustments__c = false;
                    }
                }//end Aggregate3 For Loop
                
                /*          for(Account busAccCT : busAccCTquery){ //Set Contract Type of a Practice Account
if(busAccCT.ParentId == pAcc.Id){

pAcc.Contract_Type__c = busAccCT.Contract_Type__c;
break;

}
}*///end Contract Type Update
                
                
                /////end any Business Account Group Reward Relationships that are still active////
                for(Global_Rewards_Group_Relationship__c grgR :existBusGrpRelation){
                    if(grgR.Child_Account__r.ParentId == pAcc.Id){
                        grgR.End_Date__c = Date.today();
                        grgRLstUpd.add(grgR);
                    }
                }
                
                //////Calculate the Avg for Total_Location_Spend_LTM__c, Eyewear_Location_Spend_LTM__c, Lens_Purchases_LTM__c
                for(Account busAccAvg :allBusAccAvg){
                    if(busAccAvg.ParentId == pAcc.Id){
                        if(busAccTotalPurchasesMap.containsKey(busAccAvg.ParentId)){
                            List<Decimal> existingvalue = busAccTotalPurchasesMap.get(busAccAvg.ParentId);
                            if(busAccAvg.Total_Location_Spend_LTM__c != null){
                                existingvalue.add(busAccAvg.Total_Location_Spend_LTM__c);
                                busAccTotalPurchasesMap.put(busAccAvg.ParentId, existingvalue);
                            }
                            else{
                                existingvalue.add(0);
                                busAccTotalPurchasesMap.put(busAccAvg.ParentId, existingvalue);
                            }
                        } 
                        else{
                            if(busAccAvg.Total_Location_Spend_LTM__c != null){
                                busAccTotalPurchasesMap.put(busAccAvg.ParentId, new List<Decimal>{busAccAvg.Total_Location_Spend_LTM__c});
                            }
                            else{
                                busAccTotalPurchasesMap.put(busAccAvg.ParentId, new List<Decimal>{0});
                            }
                        }
                        
                        if(busAccFramePurchasesMap.containsKey(busAccAvg.ParentId)){
                            List<Decimal> existingvalue = busAccFramePurchasesMap.get(busAccAvg.ParentId);
                            if(busAccAvg.Eyewear_Location_Spend_LTM__c != null){
                                existingvalue.add(busAccAvg.Eyewear_Location_Spend_LTM__c);
                                busAccFramePurchasesMap.put(busAccAvg.ParentId, existingvalue);
                            }
                            else{
                                existingvalue.add(0);
                                busAccFramePurchasesMap.put(busAccAvg.ParentId, existingvalue);
                            }
                        }
                        else{
                            if(busAccAvg.Eyewear_Location_Spend_LTM__c != null){
                                busAccFramePurchasesMap.put(busAccAvg.ParentId, new List<Decimal>{busAccAvg.Eyewear_Location_Spend_LTM__c});
                            }
                            else{
                                busAccFramePurchasesMap.put(busAccAvg.ParentId, new List<Decimal>{0});
                            }
                        }
                        
                        if(busAccLensPurchasesMap.containsKey(busAccAvg.ParentId)){
                            List<Decimal> existingvalue = busAccLensPurchasesMap.get(busAccAvg.ParentId);
                            if(busAccAvg.Optics_Location_Spend_LTM__c != null){
                                existingvalue.add(busAccAvg.Optics_Location_Spend_LTM__c);
                                busAccLensPurchasesMap.put(busAccAvg.ParentId, existingvalue);
                            }
                            else{
                                existingvalue.add(0);
                                busAccLensPurchasesMap.put(busAccAvg.ParentId, existingvalue);
                            }
                        }
                        else{
                            if(busAccAvg.Optics_Location_Spend_LTM__c != null){
                                busAccLensPurchasesMap.put(busAccAvg.ParentId, new List<Decimal>{busAccAvg.Optics_Location_Spend_LTM__c});
                            }
                            else{
                                busAccLensPurchasesMap.put(busAccAvg.ParentId, new List<Decimal>{0});
                            }
                        }
                        
                    }                    
                }//////finish for loop Avg Calc
                
                if(!busAccTotalPurchasesMap.isEmpty()){
                    for(Id key :busAccTotalPurchasesMap.keySet()){
                        if(pAcc.Id == key){
                            Decimal total = 0;
                            Double tPAvg = 0;
                            Decimal[] totalPurchase = busAccTotalPurchasesMap.get(key);
                            
                            for(Decimal d :totalPurchase){
                                total += d;
                            }
                            if(pAcc.Number_of_Eligible_Locations__c != 0){
                                tPAvg = Double.valueOf(total) / pAcc.Number_of_Eligible_Locations__c;
                            }                                
                            pAcc.Total_Average_Purchases_LTM_Calculated__c = tPAvg; 
                        }
                    }
                }
                if(!busAccFramePurchasesMap.isEmpty()){
                    for(Id key :busAccFramePurchasesMap.keySet()){
                        if(pAcc.Id == key){
                            Decimal total = 0;
                            Double fPAvg = 0;
                            Decimal[] framePurchase = busAccFramePurchasesMap.get(key);
                            
                            for(Decimal d :framePurchase){
                                total += d;
                            }
                            if(pAcc.Number_of_Eligible_Locations__c != 0){
                                fPAvg = Double.valueOf(total) / pAcc.Number_of_Eligible_Locations__c;
                            }                                
                            pAcc.Average_Frame_Purchases_LTM_Calculated__c = fPAvg; 
                        }
                    }
                }
                
                if(!busAccLensPurchasesMap.isEmpty()){
                    for(Id key :busAccLensPurchasesMap.keySet()){
                        if(pAcc.Id == key){
                            Decimal total = 0;
                            Double lPAvg = 0;
                            Decimal[] lensPurchase = busAccLensPurchasesMap.get(key);
                            
                            for(Decimal d :lensPurchase){
                                total += d;
                            }
                            if(pAcc.Number_of_Eligible_Locations__c != 0){
                                lPAvg = Double.valueOf(total) / pAcc.Number_of_Eligible_Locations__c;
                            }                                
                            pAcc.Average_Lens_Purchases_LTM_Calculated__c = lPAvg; 
                        }
                    }
                }
                
                pracAccToUpdate.add(pAcc);
            }
            
            system.debug('pracAccToUpdate List '+ pracAccToUpdate);
            if(!pracAccToUpdate.isEmpty()){
                //  update pracAccToUpdate;
                
                Database.SaveResult[] SaveResultList = Database.update(pracAccToUpdate,false); 
                
                for(integer i =0; i<SaveResultList.size();i++){
                    String msg='';
                    If(!SaveResultList[i].isSuccess()){
                        
                        msg += 'Account Record Id: ' + pracAccToUpdate.get(i).id + '\n'+'Error: "';        
                        for(Database.Error err: SaveResultList[i].getErrors()){  
                            msg += err.getmessage()+'"\n\n';
                        } 
                    }
                    if(msg!= '')
                        exception_List.add(msg);
                } 
            }
            
            system.debug('grgRLstUpd List '+ grgRLstUpd);
            if(!grgRLstUpd.isEmpty()){
                //  update grgRLstUpd;
                
                Database.SaveResult[] SaveResultList = Database.update(grgRLstUpd,false); 
                
                for(integer i =0; i<SaveResultList.size();i++){
                    String msg='';
                    If(!SaveResultList[i].isSuccess()){
                        
                        msg += 'Account Record Id: ' + grgRLstUpd.get(i).id + '\n'+'Error: "';        
                        for(Database.Error err: SaveResultList[i].getErrors()){  
                            msg += err.getmessage()+'"\n\n';
                        } 
                    }
                    if(msg!= '')
                        exception_List.add(msg);
                } 
            }
            
        }
    }
    
    global void finish(Database.BatchableContext BC){
        
        if(!exception_List.isEmpty() || Test.isRunningTest()){          
            
            String[] toAddresses = new String[]{};
                
                for(Exception_Handler_Email__c obj:[select Name from Exception_Handler_Email__c]){
                    toAddresses.add(obj.Name);
                }
            
            if(!toAddresses.isEmpty()){
                Messaging.reserveSingleEmailCapacity(2);
                
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                
                mail.setToAddresses(toAddresses);
                
                mail.setSenderDisplayName('Salesforce Support');
                
                mail.setSubject('Premier Admin Tool Batch Job failure - Practice Update Failed');
                
                mail.setBccSender(false);
                
                mail.setUseSignature(false);
                
                // Specify the text content of the email.
                mail.setPlainTextBody('Number of records failed = ' + exception_List.size());
                
                mail.setHtmlBody('Number of records failed = ' + exception_List.size() + '<br><br>' + exception_List + '<br><br>');
                
                // Send the email you have created.
                if(!Test.isRunningTest()){
                    Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
                }
            }
            
        }
        
        if(!Test.isRunningTest()){
            VSPR31_Grg_Path_To_Premier_Batch obj = new VSPR31_Grg_Path_To_Premier_Batch();
            Database.executeBatch(obj, 200);
        }
    }
}