force/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Eyefinity_Access__c</fullName>
        <label>Eyefinity Access</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>B - Basic</fullName>
                </value>
                <value>
                    <fullName>J - Participates in E-Claim</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fee_Calculation_Code__c</fullName>
        <label>Fee Calculation Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>O - Old Calculated Fee Schedule</fullName>
                </value>
                <value>
                    <fullName>N - New Calculated Fee Schedule</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IRS_Tax_ID__c</fullName>
        <encrypted>true</encrypted>
        <label>IRS Tax ID</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location_Type__c</fullName>
        <label>Location Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>M - VSP Member Location</fullName>
                </value>
                <value>
                    <fullName>A - Affiliate Provider Location</fullName>
                </value>
                <value>
                    <fullName>F - Laser Vision Correction (LVC)</fullName>
                </value>
                <value>
                    <fullName>X - Client Authorized Location (GAP)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Distribution__c</fullName>
        <description>Vision Care Practice receives one total payment or individual payments for each Business Account</description>
        <label>Payment Distribution</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Practice Account</fullName>
                </value>
                <value>
                    <fullName>Business Account(s)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <description>Practice Account Payment Method</description>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Check</fullName>
                </value>
                <value>
                    <fullName>Direct Deposit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Practice_Business_Type__c</fullName>
        <label>Practice Business Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>S - Sole Proprietor</fullName>
                </value>
                <value>
                    <fullName>C - Corporation</fullName>
                </value>
                <value>
                    <fullName>F - Laser Vision Correction</fullName>
                </value>
                <value>
                    <fullName>P - Partnership</fullName>
                </value>
                <value>
                    <fullName>U - Optometric School or University</fullName>
                </value>
                <value>
                    <fullName>V - Affiliate Provider</fullName>
                </value>
                <value>
                    <fullName>W - Applicant Doctor</fullName>
                </value>
                <value>
                    <fullName>X - Group Authorized Provider</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Products_and_Assets__c</fullName>
        <label>Products and Assets</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>L&amp;R Frame Lens Package</fullName>
                </value>
                <value>
                    <fullName>Level</fullName>
                </value>
                <value>
                    <fullName>RightEye</fullName>
                </value>
                <value>
                    <fullName>Shift Series</fullName>
                </value>
                <value>
                    <fullName>TRICARE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tax_ID__c</fullName>
        <description>Account Tax ID.</description>
        <encrypted>true</encrypted>
        <inlineHelpText>Account Tax ID.</inlineHelpText>
        <label>Tax ID</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Care_Effective_Date__c</fullName>
        <label>Vision Care Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Care_End_Date__c</fullName>
        <label>Vision Care End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Care_Location_Key__c</fullName>
        <encrypted>true</encrypted>
        <label>Vision Care Location Key</label>
        <length>125</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Care_Location_Phone_Number__c</fullName>
        <label>Vision Care Location Phone Number</label>
        <type>Phone</type>
    </fields>
    <recordTypes>
        <fullName>Business_Account</fullName>
        <active>true</active>
        <description>A business entity doing business/providing a service or expressing an intent to do business/provide service with at least one VSP Global line of business.</description>
        <label>Business Account</label>
    </recordTypes>
    <recordTypes>
        <fullName>Practice_Account</fullName>
        <active>true</active>
        <description>A business entity representing the practice (identified by Tax ID) having a parent relationship over one or more Business Accounts.</description>
        <label>Practice Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/VSPR26_PopulateVisionCareKeyTest.cls
@isTest(SeeAllData=false)
private class VSPR26_PopulateVisionCareKeyTest {
    //static Id PracticeId;
    @testSetup private static void setupData(){ 
        test.startTest();
        Id practiceRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Practice_Account').getRecordTypeId();
        Account pracc1= new Account();
        pracc1.Name='Practice Account Name1';
        pracc1.Vision_Care_Effective_Date__c = Date.newInstance(2018, 07, 01);
        pracc1.Tax_ID__c = '123456789';
        pracc1.Phone = '1234567890';
        pracc1.ShippingStreet = '123456 Test Streetssssssssssssssssss';
        pracc1.ShippingCity = 'Somewhere';
        pracc1.ShippingState = 'CA';
        pracc1.ShippingPostalCode = '90210';
        pracc1.ShippingCountry = 'USA';
        pracc1.Practice_Business_Type__c = 'S - Sole Proprietor';
        pracc1.Fee_Calculation_Code__c = 'N - New Calculated Fee Schedule';
        pracc1.Payment_Method__c = 'Direct Deposit';
        pracc1.Payment_Distribution__c = 'Practice Account';
        pracc1.Vision_Care_Effective_Date__c = system.today();
        pracc1.Vision_Care_Location_Key__c = '123456789101112';
        pracc1.IRS_Tax_ID__c = '123456789';
        pracc1.RecordTypeId =  practiceRecordTypeId;
        
        insert pracc1;
        //   PracticeId = acc.Id;
        
        Account pracc2= new Account();
        pracc2.Name='Practice Account Name2';
        pracc2.Vision_Care_Effective_Date__c = Date.newInstance(2018, 07, 01);
        pracc2.Tax_ID__c = '123456789';
        pracc2.Phone = '1234567890';
        pracc2.ShippingStreet = '123456 Test Streetssssssssssssssssss';
        pracc2.ShippingCity = 'Somewhere';
        pracc2.ShippingState = 'CA';
        pracc2.ShippingPostalCode = '90210';
        pracc2.ShippingCountry = 'USA';
        pracc2.Practice_Business_Type__c = 'S - Sole Proprietor';
        pracc2.Fee_Calculation_Code__c = 'N - New Calculated Fee Schedule';
        pracc2.Payment_Method__c = 'Direct Deposit';
        pracc2.Payment_Distribution__c = 'Practice Account';
        pracc2.Vision_Care_Effective_Date__c = system.today();
        pracc2.Vision_Care_Location_Key__c = '123456789101112';
        pracc2.IRS_Tax_ID__c = '123456789';
        pracc2.RecordTypeId =  practiceRecordTypeId; 
        
        insert pracc2;
        
        Account acc1= new Account();
        Id businessRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Business_Account').getRecordTypeId();
        acc1.Name='Business Account Name';       
        acc1.ParentId = pracc1.id;
        acc1.Fax = '123456789';
        acc1.ShippingStreet = '123 Test Street';
        acc1.ShippingCity = 'Somewhere';
        acc1.ShippingState = 'CA';
        acc1.ShippingPostalCode = '90210';
        acc1.ShippingCountry = 'USA';
        acc1.Vision_Care_Location_Phone_Number__c = '123456789';
        acc1.Eyefinity_Access__c = 'B - Basic';
        acc1.Location_Type__c = 'A - Affiliate Provider Location';
        acc1.Tax_ID__c = '123456789';
        acc1.Vision_Care_Effective_Date__c = Date.newInstance(2018, 07, 01);
        acc1.Vision_Care_End_Date__c = System.today() + 3;
        acc1.Products_and_Assets__c = 'Level';
        acc1.RecordTypeId =  businessRecordTypeId; 
        
        insert acc1;
        
        Account acc2= new Account();
        acc2.Name='BA Account';       
        acc2.ParentId = pracc1.id;
        acc2.Fax = '123456789';
        acc2.ShippingStreet = '32343 Test Street';
        acc2.ShippingCity = 'Nowhere';
        acc2.ShippingState = 'ND';
        acc2.ShippingPostalCode = '58072';
        acc2.ShippingCountry = 'USA';
        acc2.Vision_Care_Location_Phone_Number__c = '5556667777';
        acc2.Eyefinity_Access__c = 'B - Basic';
        acc2.Location_Type__c = 'A - Affiliate Provider Location';
        acc2.Tax_ID__c = '123456789';
        acc2.Vision_Care_Effective_Date__c = Date.newInstance(2018, 07, 01);
        acc2.Vision_Care_End_Date__c = System.today() + 3;
        acc2.Products_and_Assets__c = 'Level';
        acc2.RecordTypeId =  businessRecordTypeId; 
        acc2.Vision_Care_Location_Key__c = '1234567891234,123';
        
        insert acc2;
        test.stopTest();
    }
    
    private static testmethod void testUpdateAccTypewithEndDate() { 
        
        Id businessRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Business_Account').getRecordTypeId();
        Id practiceRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Practice_Account').getRecordTypeId();
        
        Account pracAcc1 = [SELECT Id, Name, Vision_Care_Effective_Date__c, Vision_Care_End_Date__c from Account WHERE RecordTypeId = :practiceRecordTypeId
                            // AND ParentId != null
                            AND Vision_Care_Effective_Date__c != null 
                            AND Name = 'Practice Account Name1'LIMIT 1];
        //AND Vision_Care_Location_Key__c = null LIMIT 1]; 
        
        Account pracAcc2 = [SELECT Id, Name, Vision_Care_Effective_Date__c, Vision_Care_End_Date__c from Account WHERE RecordTypeId = :practiceRecordTypeId
                            
                            AND Vision_Care_Effective_Date__c != null
                            AND Name = 'Practice Account Name2' LIMIT 1];       
        pracAcc1.ShippingStreet = '123456 Main Stssssssssssss';
        pracAcc1.RecordTypeId = businessRecordTypeId;
        pracAcc1.Vision_Care_Location_Key__c = null;
        pracAcc1.ParentId = pracAcc2.Id;
        test.startTest();
        update pracAcc1;
        test.stopTest();
        
    }
    
    private static testmethod void testInsertBaAccType() { 
        Id businessRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Business_Account').getRecordTypeId();
        Id practiceRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Practice_Account').getRecordTypeId();
        Account praAcc = [SELECT Id, Name FROM Account WHERE Name = 'Practice Account Name1' AND RecordTypeId = :practiceRecordTypeId LIMIT 1];
        
        Account acc2= new Account();
        acc2.Name='BA Account';       
        acc2.ParentId = praAcc.id;
        acc2.Fax = '123456789';
        acc2.ShippingStreet = '12345 Test Street';
        acc2.ShippingCity = 'Nowhere';
        acc2.ShippingState = 'ND';
        acc2.ShippingPostalCode = '58072';
        acc2.ShippingCountry = 'USA';
        acc2.Vision_Care_Location_Phone_Number__c = '5556667777';
        acc2.Eyefinity_Access__c = 'B - Basic';
        acc2.Location_Type__c = 'A - Affiliate Provider Location';
        acc2.Tax_ID__c = '123456789';
        acc2.Vision_Care_Effective_Date__c = Date.newInstance(2018, 07, 01);
        acc2.Vision_Care_End_Date__c = System.today() + 3;
        acc2.Products_and_Assets__c = 'Level';
        acc2.RecordTypeId =  businessRecordTypeId; 
        //acc2.Vision_Care_Location_Key__c = '1234567891234';
        test.startTest();
        insert acc2;
        test.stopTest();
    }
}