force/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <label>Line of Business</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Vision Benefits</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>D2C</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <inlineHelpText>The Line of Business responsible for working the Case.</inlineHelpText>
        <label>Line of Business</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Altair</fullName>
                    <color>#0B6FCE</color>
                    <label>Altair</label>
                </value>
                <value>
                    <fullName>Eyefinity</fullName>
                    <color>#78C953</color>
                    <label>Eyefinity</label>
                </value>
                <value>
                    <fullName>Global Customer Care</fullName>
                </value>
                <value>
                    <fullName>Marchon</fullName>
                    <color>#E27001</color>
                    <label>Marchon</label>
                </value>
                <value>
                    <fullName>Optics Group</fullName>
                    <color>#A845DC</color>
                    <label>Optics Group</label>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Vision Care</fullName>
                    <color>#F3D904</color>
                    <label>Vision Care</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Topic</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Line_of_Business__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Inventory</fullName>
                </value>
                <value>
                    <fullName>Special Order Request</fullName>
                </value>
                <value>
                    <fullName>Stock Order Status</fullName>
                </value>
                <value>
                    <fullName>Product Mapping</fullName>
                </value>
                <value>
                    <fullName>System</fullName>
                </value>
                <value>
                    <fullName>2020 Source (Affiliate)</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Cash Receipts</fullName>
                </value>
                <value>
                    <fullName>Data Entry</fullName>
                </value>
                <value>
                    <fullName>EDI Membership</fullName>
                </value>
                <value>
                    <fullName>Email Update</fullName>
                </value>
                <value>
                    <fullName>Explanation of Payment (EOP)</fullName>
                </value>
                <value>
                    <fullName>Eyeconic Ops</fullName>
                </value>
                <value>
                    <fullName>Eyeconic USC</fullName>
                </value>
                <value>
                    <fullName>Eye Health Management (EHM)</fullName>
                </value>
                <value>
                    <fullName>Lab Opt Out</fullName>
                </value>
                <value>
                    <fullName>Level</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>HP Plan Admin</fullName>
                </value>
                <value>
                    <fullName>HP Billing</fullName>
                </value>
                <value>
                    <fullName>Membership</fullName>
                </value>
                <value>
                    <fullName>MetLife</fullName>
                </value>
                <value>
                    <fullName>Molina</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>Office Hours Update</fullName>
                </value>
                <value>
                    <fullName>otto</fullName>
                </value>
                <value>
                    <fullName>Practice Report</fullName>
                </value>
                <value>
                    <fullName>Premier</fullName>
                </value>
                <value>
                    <fullName>Regence</fullName>
                </value>
                <value>
                    <fullName>Reimbursement Fees</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Eyeconic</fullName>
        <active>true</active>
        <businessProcess>VSP Global</businessProcess>
        <description>Used to track Eyeconic cases</description>
        <label>Eyeconic</label>
    </recordTypes>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Personal_Email__c</fullName>
        <description>The contacts email address.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>The contacts email address.</inlineHelpText>
        <label>Personal Email</label>
        <type>Email</type>
    </fields>
    <recordTypes>
        <fullName>Consumer</fullName>
        <active>true</active>
        <label>Consumer</label>
    </recordTypes>
</CustomObject>

force/src/objects/DVIWebService__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Setting for the DVI Web Service URL and token header</description>
    <fields>
        <fullName>DVI_Token_Header__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>DVI Token Header</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DVI_Web_Service_Version__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>DVI Web Service Version</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DVI_Web_Service__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>DVI Web Service</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DVI Web Service</label>
</CustomObject>

src/classes/VSPR25_GetConsumerIDTest.cls
@isTest(SeeAllData=false)
public class VSPR25_GetConsumerIDTest {   
/*
    //Test method for when a Case Record Type = Eyeconic and a Contact Record Type = Consumer.
    static testMethod void myCaseUnitTest() {
        DVIWebService__c dviWeb = new DVIWebService__c();
        //dviWeb.DVI_Token_Header__c = 'c2ZkYy1wcm92aWRlcjpwa3BaTUpPMw==';
        //dviWeb.DVI_Web_Service_Version__c = '2.7' ;
        //dviWeb.DVI_Web_Service__c = 'https://api.vspglobal.com	';
        dviWeb.Name = 'DVI Values';
        
        insert dviWeb;
        
        //Create an Account
        Id recordtype = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
        Account acc = new Account();
        acc.Name = 'TestDummy';
        acc.RecordTypeId = recordtype;
        insert acc;
        
        //Create a Contact for case
        Id conRecType = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Consumer').getRecordTypeId();
        Contact c = new Contact();
        c.FirstName = 'Test';
        c.LastName = 'Dummy';
        c.AccountId = acc.Id;
        c.RecordTypeId = conRecType;
        //c.Email = 'Crazy1234@test.com';
        insert c;
        
        //Createa a case
        Id caseRecType = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Eyeconic').getRecordTypeId();    
        Case cases = new Case();
        cases.Subject = 'Sample Subject';
        cases.ContactId = c.Id;
        cases.RecordTypeId = caseRecType;
        cases.Origin = 'Email';
        cases.Line_of_Business__c = 'Global Customer Care';
        cases.Type = 'Issue';
        cases.Status = 'New';
        cases.Product__c = 'Eyeconic USC';
        cases.SuppliedName = c.FirstName + ' ' + c.LastName; 
        cases.SuppliedEmail = 'testdummy@test.com';
        
        insert cases;       
    }    
    //Test method for when a Case Record Type = Eyeconic and a Contact Record Type = Eye Care Professional and has and Account Associated to it.
    public static testMethod void myCaseUnitTest1(){
        DVIWebService__c dviWeb = new DVIWebService__c();
        dviWeb.Name = 'DVI Values';
        insert dviWeb;
        
        //Create an Account
        Id recordtype = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
        Account acc = new Account();
        acc.Name = 'TestDummy';
        acc.RecordTypeId = recordtype;
        insert acc;
        
        //Create a Contact
        Id conRecType = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Eye Care Professional').getRecordTypeId();
        Contact c = new Contact();
        c.FirstName = 'Test';
        c.LastName = 'Dummy';
        c.AccountId = acc.Id;
        c.RecordTypeId = conRecType;    
        insert c;
        
        //Createa a case
        Id caseRecType = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Eyeconic').getRecordTypeId();      
        Case cases = new Case();
        cases.Subject = 'Sample Subject';
        cases.ContactId = c.Id;
        cases.RecordTypeId = caseRecType;
        cases.Origin = 'Email';
        cases.Line_of_Business__c = 'Global Customer Care';
        cases.Type = 'Issue';
        cases.Status = 'New';
        cases.Product__c = 'Eyeconic USC';
        cases.Description = 'TESTING EYECONIC';
        cases.SuppliedName = c.FirstName + ' ' + c.LastName; 
        cases.SuppliedEmail = 'testdummy@test.com';
        cases.AccountId = acc.Id;
        insert cases;
        
    }
    
    public static testMethod void myCaseUnitTest2(){
        DVIWebService__c dviWeb = new DVIWebService__c();
        dviWeb.Name = 'DVI Values';
        insert dviWeb;
        
        //Create an Account
        Id recordtype =[select Id from recordType where Name ='Business Account' and sObjectType ='Account' limit 1].Id;
        Account acc = new Account();
        acc.Name = 'VSP Consumer';
        acc.RecordTypeId = recordtype;
        insert acc;
        
        //Create a Contact
        Id conRecType = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Eye Care Professional').getRecordTypeId();
        Contact c = new Contact();
        c.FirstName = 'TEST1';
        c.LastName = 'DUMMY1';
        c.AccountId = acc.Id;
        c.RecordTypeId = conRecType;
        c.Email = 'testdummy2@test.com';
        c.Personal_Email__c = 'testdummy2@test.com';        
        insert c;
        
        //Createa a case
        Id caseRecType = [select id from recordtype where sObjectType='Case' and name='Eyeconic'].id;       
        Case cases = new Case();
        cases.Subject = 'Sample Subject';
        cases.ContactId = c.Id;
        cases.RecordTypeId = caseRecType;
        cases.Origin = 'Email';
        cases.Line_of_Business__c = 'Global Customer Care';
        cases.Type = 'Issue';
        cases.Status = 'New';
        cases.Product__c = 'Eyeconic USC';
        //cases.SuppliedName = c.FirstName + ' ' + c.LastName;
        cases.SuppliedName = 'Henry' + ' ' + 'Osborn';
        cases.SuppliedEmail = 'testdummy@test.com';
        cases.AccountId = acc.id;
        insert cases;        
    }   
    //Method for when Case Record Type Eyeconic and has no Contact.
    public static testMethod void myCaseUnitTest3(){
        DVIWebService__c dviWeb = new DVIWebService__c();
        dviWeb.Name = 'DVI Values';
        insert dviWeb;
        
        //Create an Account
        Id recordtype =[select Id from recordType where Name ='Business Account' and sObjectType ='Account' limit 1].Id;
        Account acc = new Account();
        acc.Name = 'VSP Consumer';
        acc.RecordTypeId = recordtype;
        insert acc;
        
        //Createa a case
        Id caseRecType = [select id from recordtype where sObjectType='Case' and name='Eyeconic'].id;
        Case cases = new Case();
        cases.Subject = 'Sample Subject';
        //cases.ContactId = c.Id;
        cases.RecordTypeId = caseRecType;
        cases.Origin = 'Email';
        cases.Line_of_Business__c = 'Global Customer Care';
        cases.Type = 'Issue';
        cases.Status = 'New';
        cases.Product__c = 'Eyeconic USC';
        cases.Description = 'TESTING EYECONIC';
        cases.SuppliedName = 'Henry' + ' ' + 'Osborn';
        cases.SuppliedEmail = 'testdummy@test.com';
        insert cases;
        
    } 
    
    public static testMethod void myCaseUnitTest4(){
        DVIWebService__c dviWeb = new DVIWebService__c();
        dviWeb.Name = 'DVI Values';
        insert dviWeb;
        
        //Create an Account
        Id recordtype =[select Id from recordType where Name ='Business Account' and sObjectType ='Account' limit 1].Id;
        Account acc = new Account();
        acc.Name = 'VSP Consumer';
        acc.RecordTypeId = recordtype;
        insert acc;
        
        //Create a Contact
        Id conRecType = [SELECT Id from recordType where Name = 'Eye Care Professional' and sObjectType = 'Contact' limit 1].Id;
        Contact c = new Contact();
        c.FirstName = 'Test';
        c.LastName = 'Dummy';
        c.AccountId = acc.Id;
        c.RecordTypeId = conRecType;
        c.Email = 'TestDummy@test.com';
        insert c;
        
        //Createa a case
        Id caseRecType = [select id from recordtype where sObjectType='Case' and name='Customer Care'].id;
        Case cases = new Case();
        cases.Subject = 'Sample Subject';
        cases.ContactId = c.Id;
        cases.RecordTypeId = caseRecType;
        cases.Origin = 'Email';
        cases.Line_of_Business__c = 'Global Customer Care';
        cases.Type = 'Issue';
        cases.Status = 'New';
        cases.Product__c = 'Eyeconic USC';
        cases.Description = '\n VSP Member: \n No \nIs this a complaint? \n No \nLast Four of SSN or Member ID: \n 6677 \n';
        cases.Description+= '\n E-mail Address: \n TestDummy@test.com< \nDate of Birth: \n September 3, 1982 \nMember Name: \n Test abcd \n';
        cases.Description+= '\n Sender Name: \n test test.com \n';
        cases.SuppliedName = c.FirstName + ' ' + c.LastName;
        cases.AccountId = acc.Id;
        insert cases;
        Test.setMock(HttpCalloutMock.class, new VSPR16_consumerMockGen());
        
    }
    
    public static testMethod void myCaseUnitTest5(){
        DVIWebService__c dviWeb = new DVIWebService__c();
        dviWeb.Name = 'DVI Values';
        insert dviWeb;
        
        //Create an Account
        Id recordtype =[select Id from recordType where Name ='Business Account' and sObjectType ='Account' limit 1].Id;
        Account acc = new Account();
        acc.Name = 'VSP Consumer';
        acc.RecordTypeId = recordtype;
        insert acc;
        
        //Create a Contact
        Id conRecType = [SELECT Id from recordType where Name = 'Eye Care Professional' and sObjectType = 'Contact' limit 1].Id;
        Contact c = new Contact();
        c.FirstName = 'Test';
        c.LastName = 'Dummy';
        c.AccountId = acc.Id;
        c.RecordTypeId = conRecType;
        c.Email = 'TestDummy@test.com';
        insert c;
        
        //Createa a case
        Id caseRecType = [select id from recordtype where sObjectType='Case' and name='Customer Care'].id;
        Case cases = new Case();
        cases.Subject = 'Sample Subject';
        //cases.ContactId = c.Id;
        cases.RecordTypeId = caseRecType;
        cases.Origin = 'Email';
        cases.Line_of_Business__c = 'Global Customer Care';
        cases.Type = 'Issue';
        cases.Status = 'New';
        cases.Product__c = 'Eyeconic USC';
        cases.Description = '\n VSP Member: \n Yes \nIs this a complaint? \n No \nLast Four of SSN or Member ID: \n 6677 \n';
        cases.Description+= '\n E-mail Address: \n TestDummy@test.com< \nDate of Birth: \n February 3, 1982 \nMember Name: \n Test Dummy \n';
        cases.Description+= '\n Sender Name: \n test test.com \n';
        cases.SuppliedEmail = c.Email;
        insert cases;
        Test.setMock(HttpCalloutMock.class, new VSPR16_consumerMockGen());
        
    }
    
    public static testMethod void myCaseUnitTest6(){
        DVIWebService__c dviWeb = new DVIWebService__c();
        dviWeb.Name = 'DVI Values';
        insert dviWeb;
        
        //Create an Account
        Id recordtype =[select Id from recordType where Name ='Business Account' and sObjectType ='Account' limit 1].Id;
        Account acc = new Account();
        acc.Name = 'VSP Consumer';
        acc.RecordTypeId = recordtype;
        insert acc;
        
        //Create a Contact
        Id conRecType = [SELECT Id from recordType where Name = 'Eye Care Professional' and sObjectType = 'Contact' limit 1].Id;
        Contact c = new Contact();
        c.FirstName = 'Test';
        c.LastName = 'Dummy';
        c.AccountId = acc.Id;
        c.RecordTypeId = conRecType;
        c.Email = 'TestDummy@test.com';
        insert c;
        
        //Createa a case
        Id caseRecType = [select id from recordtype where sObjectType='Case' and name='Customer Care'].id;
        Case cases = new Case();
        cases.Subject = 'Sample Subject';
        //cases.ContactId = c.Id;
        cases.RecordTypeId = caseRecType;
        cases.Origin = 'Email';
        cases.Line_of_Business__c = 'Global Customer Care';
        cases.Type = 'Issue';
        cases.Status = 'New';
        cases.Product__c = 'Eyeconic USC';
        cases.Description = '\n VSP Member: \n No \nIs this a complaint? \n No \nLast Four of SSN or Member ID: \n 6677 \n';
        cases.Description+= '\n E-mail Address: \n TestDummy@test.com< \nDate of Birth: \n August 3, 1982 \nMember Name: \n Test Dummy \n';
        cases.Description+= '\n Sender Name: \n Test Dummy \n';
        cases.SuppliedEmail = c.Email;
        insert cases;
        Test.setMock(HttpCalloutMock.class, new VSPR16_consumerMockGen());
        
    }
    
    static void soslQueryMethod(){
        
        Id conRecType = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Eye Care Professional').getRecordTypeId();
        Contact c = new Contact();
        c.FirstName = 'TEST1';
        c.LastName = 'DUMMY1';
        //c.AccountId = acc.Id;
        c.RecordTypeId = conRecType;
        c.Email = 'testdummy2@test.com';
        c.Personal_Email__c = 'testdummy2@test.com';        
        insert c;
        
        //Createa a case
        Id caseRecType = [select id from recordtype where sObjectType='Case' and name='Eyeconic'].id;       
        Case cases = new Case();
        cases.Subject = 'Sample Subject';
        cases.ContactId = c.Id;
        cases.RecordTypeId = caseRecType;
        cases.Origin = 'Email';
        cases.Line_of_Business__c = 'Global Customer Care';
        cases.Type = 'Issue';
        cases.Status = 'New';
        cases.Product__c = 'Eyeconic USC';
        //cases.SuppliedName = c.FirstName + ' ' + c.LastName;
        cases.SuppliedName = 'Henry' + ' ' + 'Osborn';
        cases.SuppliedEmail = 'testdummy1@test.com';
        //cases.AccountId = acc.id;
        insert cases;          
    }
    
    public static testMethod void myCaseUnitTest7(){
        DVIWebService__c dviWeb = new DVIWebService__c();
        dviWeb.Name = 'DVI Values';
        insert dviWeb;
        
        //Create an Account
        Id recordtype =[select Id from recordType where Name ='Business Account' and sObjectType ='Account' limit 1].Id;
        Account acc = new Account();
        acc.Name = 'VSP Consumer';
        acc.RecordTypeId = recordtype;
        insert acc;
        
        //Create a Contact
        Id conRecType = [SELECT Id from recordType where Name = 'Eye Care Professional' and sObjectType = 'Contact' limit 1].Id;
        Contact c = new Contact();
        c.FirstName = 'Test';
        c.LastName = 'Dummy';
        c.AccountId = acc.Id;
        c.RecordTypeId = conRecType;
        c.Email = 'TestDummy@test.com';
        insert c;
        
        //Createa a case
        Id caseRecType = [select id from recordtype where sObjectType='Case' and name='Customer Care'].id;
        Case cases = new Case();
        cases.Subject = 'Sample Subject';
        cases.ContactId = c.Id;
        cases.RecordTypeId = caseRecType;
        cases.Origin = 'Email';
        cases.Line_of_Business__c = 'Global Customer Care';
        cases.Type = 'Issue';
        cases.Status = 'New';
        cases.Product__c = 'Eyeconic USC';
        cases.Description = '\n VSP Member: \n Yes \nIs this a complaint? \n No \nLast Four of SSN or Member ID: \n 6677 \n';
        cases.Description+= '\n E-mail Address: \n TestDummy@test.com< \nDate of Birth: \n July 3, 1982 \nMember Name: \n Test Dummy \n';
        cases.Description+= '\n Sender Name: \n Test Dummy \n';
        cases.SuppliedEmail = c.Email;
        insert cases;
        Test.setMock(HttpCalloutMock.class, new VSPR16_consumerMockGen());
        
    }
    public static testMethod void myCaseUnitTest8(){
        DVIWebService__c dviWeb = new DVIWebService__c();
        dviWeb.Name = 'DVI Values';
        insert dviWeb;
        
        //Create an Account
        Id recordtype =[select Id from recordType where Name ='Business Account' and sObjectType ='Account' limit 1].Id;
        Account acc = new Account();
        acc.Name = 'VSP Consumer';
        acc.RecordTypeId = recordtype;
        insert acc;
        
        //Create a Contact
        Id conRecType = [SELECT Id from recordType where Name = 'Consumer' and sObjectType = 'Contact' limit 1].Id;
        Contact c = new Contact();
        c.FirstName = 'Test';
        c.LastName = 'Dummy';
        c.AccountId = acc.Id;
        c.RecordTypeId = conRecType;
        c.Email = 'TestDummy@test.com';
        insert c;
        
        //Createa a case
        Id caseRecType = [select id from recordtype where sObjectType='Case' and name='Customer Care'].id;
        Case cases = new Case();
        cases.Subject = 'Sample Subject';
        cases.ContactId = c.Id;
        cases.RecordTypeId = caseRecType;
        cases.Origin = 'Email';
        cases.Line_of_Business__c = 'Global Customer Care';
        cases.Type = 'Issue';
        cases.Status = 'New';
        cases.Product__c = 'Eyeconic USC';
        cases.Description = '\n VSP Member: \n Yes \nIs this a complaint? \n No \nLast Four of SSN or Member ID: \n 6677 \n';
        cases.Description+= '\n E-mail Address: \n TestDummy@test.com< \nDate of Birth: \n June 3, 1982 \nMember Name: \n Test Dummy \n';
        cases.Description+= '\n Sender Name: \n Test Dummy \n';
        cases.SuppliedEmail = c.Email;
        insert cases;
        Test.setMock(HttpCalloutMock.class, new VSPR16_consumerMockGen());
        
    }
    
    public static testmethod void myCaseUnitTest9(){
        DVIWebService__c dviWeb = new DVIWebService__c();
        dviWeb.Name = 'DVI Values';
        insert dviWeb;
        
        //Createa a case for Janurary
        Id caseRecType = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Customer Care').getRecordTypeId();
        Case cases = new Case();
        cases.Subject = 'Sample Subject';
        //cases.ContactId = c.Id;
        cases.RecordTypeId = caseRecType;
        cases.Origin = 'Email';
        cases.Line_of_Business__c = 'Global Customer Care';
        cases.Type = 'Issue';
        cases.Status = 'New';
        cases.Product__c = 'Eyeconic USC';
        cases.Description = '\n VSP Member: \n Yes \nIs this a complaint? \n No \nLast Four of SSN or Member ID: \n 6677 \n';
        cases.Description+= '\n E-mail Address: \n TestDummy@test.com< \nDate of Birth: \n January 3, 1982 \nMember Name: \n Test Dummy \n';
        cases.Description+= '\n Sender Name: \n Test Dummy \n';
        //cases.SuppliedEmail = c.Email;
        insert cases;
        
        
        //Createa a case for March
        //Id caseRecType = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Customer Care').getRecordTypeId();
        Case cases2 = new Case();
        cases2.Subject = 'Sample Subject';
        //cases.ContactId = c.Id;
        cases2.RecordTypeId = caseRecType;
        cases2.Origin = 'Email';
        cases2.Line_of_Business__c = 'Global Customer Care';
        cases2.Type = 'Issue';
        cases2.Status = 'New';
        cases2.Product__c = 'Eyeconic USC';
        cases2.Description = '\n VSP Member: \n Yes \nIs this a complaint? \n No \nLast Four of SSN or Member ID: \n 6677 \n';
        cases2.Description+= '\n E-mail Address: \n TestDummy@test.com< \nDate of Birth: \n March 3, 1982 \nMember Name: \n Test Dummy \n';
        cases2.Description+= '\n Sender Name: \n Test Dummy \n';
        //cases.SuppliedEmail = c.Email;
        insert cases2;
        
        //Createa a case for April
        //Id caseRecType = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Customer Care').getRecordTypeId();
        Case cases3 = new Case();
        cases3.Subject = 'Sample Subject';
        //cases.ContactId = c.Id;
        cases3.RecordTypeId = caseRecType;
        cases3.Origin = 'Email';
        cases3.Line_of_Business__c = 'Global Customer Care';
        cases3.Type = 'Issue';
        cases3.Status = 'New';
        cases3.Product__c = 'Eyeconic USC';
        cases3.Description = '\n VSP Member: \n Yes \nIs this a complaint? \n No \nLast Four of SSN or Member ID: \n 6677 \n';
        cases3.Description+= '\n E-mail Address: \n TestDummy@test.com< \nDate of Birth: \n April 3, 1982 \nMember Name: \n Test Dummy \n';
        cases3.Description+= '\n Sender Name: \n Test Dummy \n';
        //cases.SuppliedEmail = c.Email;
        insert cases3;
        
        //Createa a case for May
        //Id caseRecType = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Customer Care').getRecordTypeId();
        Case cases4 = new Case();
        cases4.Subject = 'Sample Subject';
        //cases.ContactId = c.Id;
        cases4.RecordTypeId = caseRecType;
        cases4.Origin = 'Email';
        cases4.Line_of_Business__c = 'Global Customer Care';
        cases4.Type = 'Issue';
        cases4.Status = 'New';
        cases4.Product__c = 'Eyeconic USC';
        cases4.Description = '\n VSP Member: \n Yes \nIs this a complaint? \n No \nLast Four of SSN or Member ID: \n 6677 \n';
        cases4.Description+= '\n E-mail Address: \n TestDummy@test.com< \nDate of Birth: \n May 3, 1982 \nMember Name: \n Test Dummy \n';
        cases4.Description+= '\n Sender Name: \n Test Dummy \n';
        //cases.SuppliedEmail = c.Email;
        insert cases4;
        Test.setMock(HttpCalloutMock.class, new VSPR16_consumerMockGen());
    }
*/
}