force/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Vision_Care_Effective_Date__c</fullName>
        <label>Vision Care Effective Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force/src/objects/Eyewear_Brand_Sales__c.object
<CustomObject>
    <fields>
        <fullName>Account_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Associated Account ID from Salesforce</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Eyewear Brand Sales</relationshipLabel>
        <relationshipName>Eyewear_Brand_Sales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Date_Ordered__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Date Ordered</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Marketing_Group_Description__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Marketing Group Description</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Net_Frame_Sales_LTM__c</fullName>
        <label>Net Frame Sales LTM</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Net_Sales_LTM__c</fullName>
        <label>Net Sales LTM</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Sales Org</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Eyewear Brand Sales</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Eyewear Brand Sales Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eyewear Brand Sales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/VSPR30_Acc_Brand_History_LTM_Ctrl_Test.cls
@isTest
public class VSPR30_Acc_Brand_History_LTM_Ctrl_Test {
    
    static testMethod void test_Acc_EBS(){
        
        Id accRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
        
        //Insert New Business Account
        Account ba = new Account();
        ba.Name = 'testbizAccount';
        ba.RecordTypeId = accRecordTypeId;
        ba.Vision_Care_Effective_Date__c = date.today();
        insert ba;
        
        Eyewear_Brand_Sales__c eBS = new Eyewear_Brand_Sales__c();
        eBS.Sales_Org__c = '2010';
        eBS.Brand_Code__c = '123';
        eBS.Marketing_Group_Description__c = 'Test Group Description';
        eBS.Net_Frame_Sales_LTM__c = 500;
        eBS.Net_Sales_LTM__c = 5000;
        eBS.Last_Date_Ordered__c = system.today();
        eBS.Account_ID__c = ba.Id;
        insert eBS;
                
        Apexpages.StandardController sc = new Apexpages.StandardController(ba);
        VSPR30_Acc_Brand_History_LTM_Ctrl ext = new VSPR30_Acc_Brand_History_LTM_Ctrl(sc);
        ext.geteBS();
        
    }
}