force/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Agreement_Type__c</fullName>
        <inlineHelpText>The type of business agreement the practice is participating with VSP for a set amount of time.</inlineHelpText>
        <label>Agreement Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location_Type__c</fullName>
        <label>Location Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>M - VSP Member Location</fullName>
                </value>
                <value>
                    <fullName>A - Affiliate Provider Location</fullName>
                </value>
                <value>
                    <fullName>F - Laser Vision Correction (LVC)</fullName>
                </value>
                <value>
                    <fullName>X - Client Authorized Location (GAP)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_Company__c</fullName>
        <label>Parent Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AEHG- Acuity Eyecare Holding Group</fullName>
                </value>
                <value>
                    <fullName>CLRK - Clarkson Eyecare Location</fullName>
                </value>
                <value>
                    <fullName>COHN - Cohen&apos;s Fashion Optical</fullName>
                </value>
                <value>
                    <fullName>COST - Costco Location</fullName>
                </value>
                <value>
                    <fullName>CVS - CVS Location</fullName>
                </value>
                <value>
                    <fullName>ECCA - ECCA or Visionworks Location</fullName>
                </value>
                <value>
                    <fullName>FEGV - For Eyes Grand Vision</fullName>
                </value>
                <value>
                    <fullName>GRRA - Grand Rapids Ophthalmology</fullName>
                </value>
                <value>
                    <fullName>INTL - International Eyecare Center Location</fullName>
                </value>
                <value>
                    <fullName>JVNTR - Joint Ventures</fullName>
                </value>
                <value>
                    <fullName>MEDR - MyEyeDr. Location</fullName>
                </value>
                <value>
                    <fullName>OCNB - Near-site Clinic Location, VSP</fullName>
                </value>
                <value>
                    <fullName>OCSI - Onsite Clinic Location, VSP</fullName>
                </value>
                <value>
                    <fullName>OPTX - Optyx Location</fullName>
                </value>
                <value>
                    <fullName>PERL - Pearle Vision Location</fullName>
                </value>
                <value>
                    <fullName>POP - Pop-Up Clinic Location, VSP</fullName>
                </value>
                <value>
                    <fullName>PRIT - Pritchett Eye Care Location</fullName>
                </value>
                <value>
                    <fullName>RXOP - Rx Optical Location</fullName>
                </value>
                <value>
                    <fullName>SHOP - Shopko Location</fullName>
                </value>
                <value>
                    <fullName>TECP - Total Eyecare Partners</fullName>
                </value>
                <value>
                    <fullName>TOTV - Total Vision Inc</fullName>
                </value>
                <value>
                    <fullName>VNTR - VSP Ventures</fullName>
                </value>
                <value>
                    <fullName>WALM - Walmart Location</fullName>
                </value>
                <value>
                    <fullName>WVIS - Wisconsin Vision Location</fullName>
                </value>
                <value>
                    <fullName>OCCV - CVS Location, VSP</fullName>
                    <isActive>false</isActive>
                    <label>OCCV - CVS Location, VSP</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Provider_Category__c</fullName>
        <label>Provider Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AOP - Approved OON Provider</fullName>
                </value>
                <value>
                    <fullName>CAT2 - Non-Standard Ownership Model</fullName>
                </value>
                <value>
                    <fullName>CNTRC - Contract Provider</fullName>
                </value>
                <value>
                    <fullName>OFPCS - Pearle Vision Corp Sublease Holder</fullName>
                </value>
                <value>
                    <fullName>OFPLS - Pearle Vision L.O Sublease Holder</fullName>
                </value>
                <value>
                    <fullName>PEARL - License Operator Pearle Vision</fullName>
                </value>
                <value>
                    <fullName>PVCO - Corp Managed Pearle Vision</fullName>
                </value>
                <value>
                    <fullName>RETL - VSP Retail</fullName>
                </value>
                <value>
                    <fullName>SCHLS - Optometric School or University</fullName>
                </value>
                <value>
                    <fullName>VNTR - VSP Ventures</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of Account.</description>
        <inlineHelpText>A = Active 
Inactive = Not a Current Customer of any LOB. 
Closed = Business has ceased operations 
New = In process of becoming an Active account</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Submit for Approval</fullName>
                </value>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Inactive Ownership Change</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
                <value>
                    <fullName>Marked for Deletion</fullName>
                </value>
                <value>
                    <fullName>Archive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vision_Care_Effective_Date__c</fullName>
        <label>Vision Care Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Care_Good_Standing__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is account in good standing with Vision Care.</description>
        <inlineHelpText>Is account in good standing with Vision Care.</inlineHelpText>
        <label>Vision Care Good Standing</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force/src/objects/Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Practice Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Date_Reason__c</fullName>
        <label>End Date Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>End of Agreement</fullName>
                </value>
                <value>
                    <fullName>Termination of Agreement</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF( OR( Effective_Date__c = TODAY() , AND( Effective_Date__c &lt; TODAY() , OR( End_Date__c &gt;= TODAY() , ISBLANK( End_Date__c ) ) ) ) , &quot;Active&quot;, IF( Effective_Date__c&gt; TODAY() , &apos;Future&apos;, &apos;Inactive&apos;) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pathways - Expansion</fullName>
                </value>
                <value>
                    <fullName>Global Strategic Agreement</fullName>
                </value>
                <value>
                    <fullName>Shift Series</fullName>
                </value>
                <value>
                    <fullName>DOLP4</fullName>
                </value>
                <value>
                    <fullName>Optics Agreements</fullName>
                </value>
                <value>
                    <fullName>DOLP3</fullName>
                </value>
                <value>
                    <fullName>DOLP2</fullName>
                </value>
                <value>
                    <fullName>DOLP1</fullName>
                </value>
                <value>
                    <fullName>Pathways - Recruitment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agreement</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Agreement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Exception_handler_Email__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Exception Handler Email</label>
</CustomObject>

src/classes/VSPR31_AgreementsBusinessAccBatch_TC.cls
@isTest public class VSPR31_AgreementsBusinessAccBatch_TC {
    
    private static Id businessRecordTypeID = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
    private static Id practiceRecordTypeID = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Practice Account').getRecordTypeId();
    private static final Date startDate = System.today();
    //below part added on 08/19/2019
    private static String CRON_EXP = '0 00 01 * * ?';

    @IsTest
    static void testmethod1(){

        List<Account> busAccList = new List<Account>();
        Account ba1 = new Account();
        Account ba2 = new Account();

        Account a = new Account();
        a.recordTypeId = practiceRecordTypeID;
        a.Name = 'Practice Account';
        a.Vision_Care_Good_Standing__c = true;
        insert a;

        ba1.Name = 'Testing Business Account 1';
        ba1.Location_Type__c = 'X - Client Authorized Location (GAP)';
        ba1.Vision_Care_Good_Standing__c = true;
        ba1.Provider_Category__c = 'PVCO - Corp Managed Pearle Vision';
        ba1.Parent_Company__c = 'PERL - Pearle Vision Location';
        ba1.recordTypeID = businessRecordTypeID;
        ba1.ParentId = a.id;
        ba1.Vision_Care_Effective_Date__c = System.today().addDays(-1);
        busAccList.add(ba1);

        ba2.Name = 'Testing Business Account 2';
        ba2.Location_Type__c = 'X - Client Authorized Location (GAP)';
        ba2.Provider_Category__c = 'PVCO - Corp Managed Pearle Vision';
        ba2.Parent_Company__c = 'PERL - Pearle Vision Location';
        ba2.recordTypeID = businessRecordTypeID;
        ba2.ParentId = a.id;
        ba2.Vision_Care_Effective_Date__c = System.today().addDays(-1);
        busAccList.add(ba2);

        insert busAccList;

        List<Agreement__c> agList = new List<Agreement__c>();
        Agreement__c ag1 = new Agreement__c();
        Agreement__c ag2 = new Agreement__c();

        ag1.Type__c = 'DOLP1';
        ag1.Effective_Date__c = startDate;
        ag1.Account__c = a.Id;
        agList.add(ag1);

        ag2.Type__c = 'DOLP4';
        ag2.Effective_Date__c = startDate;
        ag2.Account__c = a.Id;
        ag2.End_Date__c = startDate.addMonths(2);
        ag2.End_Date_Reason__c = 'Error';
        //ag2.Status__c = 'Active'; //Need to removed once the trigger on the agreement obj is up and running.
        agList.add(ag2);

        Agreement__c ag3 = new Agreement__c();
        ag3.Type__c = 'DOLP2';
        ag3.Account__c = a.Id;
        ag3.Effective_Date__c = startDate.addDays(1);
        agList.add(ag3);

        insert agList;

        Exception_handler_Email__c toAddress = new Exception_handler_Email__c();
        toAddress.Name = 'test@vsp.com';
        insert toAddress;

        VSPR31_AgreementsBusinessAcc_Batch job = new VSPR31_AgreementsBusinessAcc_Batch();
        
        Test.startTest();
        Id jobId = Database.executeBatch(job);
        Test.stopTest();

        Account ba3 = [Select id, Agreement_Type__c from Account where Name = 'Testing Business Account 1'];
        System.assertEquals('DOLP1; DOLP4', ba3.Agreement_Type__c);
        
    }

    @IsTest
    static void testmethod2(){

        List<Account> busAccList = new List<Account>();
        Account ba1 = new Account();
        Account ba2 = new Account();

        Account a = new Account();
        a.recordTypeId = practiceRecordTypeID;
        a.Name = 'Practice Account';
        a.Vision_Care_Good_Standing__c = true;
        insert a;

        ba1.Name = 'Testing Business Account 1';
        ba1.Location_Type__c = 'X - Client Authorized Location (GAP)';
        ba1.Vision_Care_Good_Standing__c = true;
        ba1.Provider_Category__c = 'PVCO - Corp Managed Pearle Vision';
        ba1.Parent_Company__c = 'PERL - Pearle Vision Location';
        ba1.recordTypeID = businessRecordTypeID;
        ba1.ParentId = a.id;
        ba1.Vision_Care_Effective_Date__c = System.today().addDays(-1);
        busAccList.add(ba1);

        ba2.Name = 'Testing Business Account 2';
        ba2.Location_Type__c = 'X - Client Authorized Location (GAP)';
        ba2.Provider_Category__c = 'PVCO - Corp Managed Pearle Vision';
        ba2.Parent_Company__c = 'PERL - Pearle Vision Location';
        ba2.recordTypeID = businessRecordTypeID;
        ba2.ParentId = a.id;
        ba2.Vision_Care_Effective_Date__c = System.today().addDays(-1);
        busAccList.add(ba2);

        insert busAccList;

        List<Agreement__c> agList = new List<Agreement__c>();
        Agreement__c ag1 = new Agreement__c();
        Agreement__c ag2 = new Agreement__c();

        ag1.Type__c = 'DOLP1';
        ag1.Effective_Date__c = startDate;
        ag1.Account__c = a.Id;
        agList.add(ag1);

        ag2.Type__c = 'DOLP4';
        ag2.Effective_Date__c = startDate;
        ag2.Account__c = a.Id;
        ag2.End_Date__c = startDate.addMonths(2);
        ag2.End_Date_Reason__c = 'Error';
        //ag2.Status__c = 'Active'; //Need to removed once the trigger on the agreement obj is up and running.
        agList.add(ag2);

        Agreement__c ag3 = new Agreement__c();
        ag3.Type__c = 'DOLP2';
        ag3.Account__c = a.Id;
        ag3.Effective_Date__c = startDate.addDays(1);
        agList.add(ag3);

        Agreement__c ag4 = new Agreement__c();
        ag4.Type__c = 'DOLP1';
        ag4.Account__c = a.Id;
        ag4.Effective_Date__c = startDate;
        agList.add(ag4);

        Agreement__c ag5 = new Agreement__c();
        ag5.Type__c = 'DOLP4';
        ag5.Effective_Date__c = startDate;
        ag5.Account__c = a.Id;
        ag5.End_Date__c = startDate.addMonths(1);
        ag5.End_Date_Reason__c = 'Error';
        //ag2.Status__c = 'Active'; //Need to removed once the trigger on the agreement obj is up and running.
        agList.add(ag5);

        Agreement__c ag6 = new Agreement__c();
        ag6.Type__c = 'DOLP4';
        ag6.Effective_Date__c = startDate;
        ag6.Account__c = a.Id;
        ag6.End_Date__c = startDate.addMonths(1);
        ag6.End_Date_Reason__c = 'Error';
        //ag2.Status__c = 'Active'; //Need to removed once the trigger on the agreement obj is up and running.
        agList.add(ag6);

        insert agList;

        Exception_handler_Email__c toAddress = new Exception_handler_Email__c();
        toAddress.Name = 'test@vsp.com';
        insert toAddress;

        VSPR31_AgreementsBusinessAcc_Batch job = new VSPR31_AgreementsBusinessAcc_Batch();
        
        Test.startTest();
        Id jobId = Database.executeBatch(job);
        Test.stopTest();

        Account ba3 = [Select id, Agreement_Type__c from Account where Name = 'Testing Business Account 1'];
        System.assertEquals('DOLP1; DOLP4', ba3.Agreement_Type__c);
        
    }

    //Below part added to run the test against the premier admin tool daily batch job scheduler class. 
    @IsTest
    static void methodName3(){
        
        VSPR31_AgreementStatusBatch_Sch job = new VSPR31_AgreementStatusBatch_Sch();

        Test.startTest();
        String jobId = System.schedule('Test Territory Check', CRON_EXP, job);

		CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, 
                          NextFireTime
                          FROM CronTrigger WHERE id = :jobId];
        
        // Verify the expressions are the same
        System.assertEquals(CRON_EXP, 
                            ct.CronExpression);
        
        // Verify the job has not run
        System.assertEquals(0, ct.TimesTriggered);
        Test.stopTest();
        
    }
}