force/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Eyefinity_Access__c</fullName>
        <label>Eyefinity Access</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>B - Basic</fullName>
                </value>
                <value>
                    <fullName>J - Participates in E-Claim</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fee_Calculation_Code__c</fullName>
        <label>Fee Calculation Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>O - Old Calculated Fee Schedule</fullName>
                </value>
                <value>
                    <fullName>N - New Calculated Fee Schedule</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Location_Type__c</fullName>
        <label>Location Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>M - VSP Member Location</fullName>
                </value>
                <value>
                    <fullName>A - Affiliate Provider Location</fullName>
                </value>
                <value>
                    <fullName>F - Laser Vision Correction (LVC)</fullName>
                </value>
                <value>
                    <fullName>X - Client Authorized Location (GAP)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Distribution__c</fullName>
        <description>Vision Care Practice receives one total payment or individual payments for each Business Account</description>
        <label>Payment Distribution</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Practice Account</fullName>
                </value>
                <value>
                    <fullName>Business Account(s)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <description>Practice Account Payment Method</description>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Check</fullName>
                </value>
                <value>
                    <fullName>Direct Deposit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Practice_Business_Type__c</fullName>
        <label>Practice Business Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>S - Sole Proprietor</fullName>
                </value>
                <value>
                    <fullName>C - Corporation</fullName>
                </value>
                <value>
                    <fullName>F - Laser Vision Correction</fullName>
                </value>
                <value>
                    <fullName>P - Partnership</fullName>
                </value>
                <value>
                    <fullName>U - Optometric School or University</fullName>
                </value>
                <value>
                    <fullName>V - Affiliate Provider</fullName>
                </value>
                <value>
                    <fullName>W - Applicant Doctor</fullName>
                </value>
                <value>
                    <fullName>X - Group Authorized Provider</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tax_ID__c</fullName>
        <description>Account Tax ID.</description>
        <encrypted>true</encrypted>
        <inlineHelpText>Account Tax ID.</inlineHelpText>
        <label>Tax ID</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Care_Effective_Date__c</fullName>
        <label>Vision Care Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Care_End_Date__c</fullName>
        <label>Vision Care End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Care_Location_Phone_Number__c</fullName>
        <label>Vision Care Location Phone Number</label>
        <type>Phone</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Birthdate__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Birthdate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <formula>HYPERLINK(&quot;/&quot; + Id, &quot;Contact Record&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Record</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Degree__c</fullName>
        <description>The educational degree of the Vision Care Doctor.</description>
        <inlineHelpText>The educational degree of the Vision Care Doctor.</inlineHelpText>
        <label>Degree</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>OD</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>DO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Doctor_ID__c</fullName>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Doctor ID</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Doctor_Type__c</fullName>
        <label>Doctor Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>M - VSP Member Doctor</fullName>
                </value>
                <value>
                    <fullName>A - Affiliate Provider</fullName>
                </value>
                <value>
                    <fullName>F - Laser Vision Correction (LVC)</fullName>
                </value>
                <value>
                    <fullName>S - School Faculty Provider</fullName>
                </value>
                <value>
                    <fullName>X - Client Authorized Provider (GAP)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>Gender of the Vision Care Doctor.</description>
        <inlineHelpText>Gender of Contact.</inlineHelpText>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NPI__c</fullName>
        <description>National Provider Indicator for a Vision Care Doctor.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>National Provider Indicator for a Vision Care Doctor.</inlineHelpText>
        <label>NPI</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Care_Effective_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Vision Care Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Care_End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Vision Care End Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Eye_Care_Professional</fullName>
        <active>true</active>
        <label>Eye Care Professional</label>
    </recordTypes>
</CustomObject>

src/objects/Contact_Role__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Eye Care Professional</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Fee_Calculation_Code__c</fullName>
        <formula>LEFT(TEXT( Account__r.Parent.Fee_Calculation_Code__c ), 1)</formula>
        <label>Fee Calculation Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <encryptionScheme>None</encryptionScheme>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accounting</fullName>
                </value>
                <value>
                    <fullName>Board Member/ Officer</fullName>
                </value>
                <value>
                    <fullName>Dean</fullName>
                </value>
                <value>
                    <fullName>Doctor-Employee</fullName>
                </value>
                <value>
                    <fullName>Doctor-Owner</fullName>
                </value>
                <value>
                    <fullName>Doctor-Unspecified</fullName>
                </value>
                <value>
                    <fullName>Group Administrator</fullName>
                </value>
                <value>
                    <fullName>Lab Technician</fullName>
                </value>
                <value>
                    <fullName>Member</fullName>
                </value>
                <value>
                    <fullName>Office Administration</fullName>
                </value>
                <value>
                    <fullName>Office Manager</fullName>
                </value>
                <value>
                    <fullName>Optical Buyer</fullName>
                </value>
                <value>
                    <fullName>Optical Manager</fullName>
                </value>
                <value>
                    <fullName>Optician</fullName>
                </value>
                <value>
                    <fullName>Optician-Owner</fullName>
                </value>
                <value>
                    <fullName>Owner</fullName>
                </value>
                <value>
                    <fullName>Student</fullName>
                </value>
                <value>
                    <fullName>Unspecified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/General_Table__c.object
<CustomObject>
    <fields>
        <fullName>Table__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Table</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>General Table</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>General Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force/src/objects/Network_Relationship__c.object
<CustomObject>
    <description>Custom object to track Payment Relationships between doctors and offices.</description>
    <fields>
        <fullName>Contact_Role__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact Role</label>
        <referenceTo>Contact_Role__c</referenceTo>
        <relationshipName>Payment_Relationships</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Doctor_ID__c</fullName>
        <description>Doctor ID of associated Contact record</description>
        <label>Doctor ID</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program_End_Date__c</fullName>
        <label>Program End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Program_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup relationship field from Network Relationship to General Table object</description>
        <label>Program ID</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>General_Table__c.Table__c</field>
                <operation>equals</operation>
                <value>PRSP</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>General_Table__c</referenceTo>
        <relationshipLabel>Network Relationships</relationshipLabel>
        <relationshipName>Network_Relationships</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Provider Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Network Relationships</relationshipLabel>
        <relationshipName>Network_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Network Relationship</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Network Relationship Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Network Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/VSPR26_ContactTriggerTest.cls
@isTest(SeeAllData=false)
private class VSPR26_ContactTriggerTest {
    /*This is a test class for the ContactTrigger_Handler*/
    @testSetup private static void createContact(){
        //public static testmethod void createContact(){
        
        String uniqueUserName = 'standarduser' + DateTime.now().getTime() + '@vsp.com'; 
        Profile p = [SELECT Id FROM Profile WHERE Name='VSP Network Recruitment User'];
        User u = new User(Alias = 'standt', Email='standarduser@vsp.com',
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                          LocaleSidKey='en_US', ProfileId = p.Id,
                          TimeZoneSidKey='America/Los_Angeles',
                          UserName=uniqueUserName);
        
        System.runAs(u){
        
            //Create Practice Account/Parent Account
            Id acrtPA = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Practice Account').getRecordTypeId();
            Account paacc = new Account();
            paacc.Name='Practice Account Name';
            paacc.Vision_Care_Effective_Date__c = Date.newInstance(2018, 07, 01);
            paacc.Tax_ID__c = '123456789';
            paacc.Phone = '1234567890';
            paacc.ShippingStreet = '123 Test Street';
            paacc.ShippingCity = 'Somewhere';
            paacc.ShippingState = 'CA';
            paacc.ShippingPostalCode = '90210';
            paacc.ShippingCountry = 'USA';
            paacc.Practice_Business_Type__c = 'S - Sole Proprietor';
            paacc.Fee_Calculation_Code__c = 'N - New Calculated Fee Schedule';
            paacc.Payment_Method__c = 'Direct Deposit';
            paacc.Payment_Distribution__c = 'Practice Account';
            paacc.RecordTypeId =  acrtPA;  
            insert paacc;
            
            //Create Business Accont/Child Account
            Id acrtBA = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
            Account baacc = new Account();
            baacc.Name='Business Account Name';       
            baacc.ParentId = paacc.id;
            baacc.Fax = '123456789';
            baacc.ShippingStreet = '123 Test Street';
            baacc.ShippingCity = 'Somewhere';
            baacc.ShippingState = 'CA';
            baacc.ShippingPostalCode = '90210';
            baacc.ShippingCountry = 'USA';
            baacc.Vision_Care_Location_Phone_Number__c = '123456789';
            baacc.Eyefinity_Access__c = 'B - Basic';
            baacc.Location_Type__c = 'A - Affiliate Provider Location';
            baacc.Tax_ID__c = '123456789';
            baacc.Vision_Care_Effective_Date__c = Date.newInstance(2018, 07, 01);
            baacc.Vision_Care_End_Date__c = System.today() + 3;
            baacc.RecordTypeId =  acrtBA;
            insert baacc;
            
            Id eyeCareRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Eye_Care_Professional').getRecordTypeId();
            Contact con = new Contact();
            con.FirstName = 'Eye';
            con.LastName = 'Tennis';
            con.AccountId = baacc.Id;
            con.Doctor_Type__c = 'M - VSP Member Doctor';
            con.Vision_Care_End_Date__c = null;
            con.Vision_Care_Effective_Date__c =  System.today() - 3;
            con.Degree__c = 'OD';
            con.NPI__c = '1073919239';
            con.Doctor_ID__c = '654654654';
            con.Gender__c = 'Male';
            con.Birthdate__c = Date.newInstance(1990, 07, 31);
            con.RecordTypeId = eyeCareRecordTypeId;
            insert con;
            //system.assertNotEquals(null, con.id);
            //system.assertNotEquals(null, con.Vision_Care_End_Date__c);
            
            General_Table__c gt = new General_Table__c();
            gt.Name = 'VSP';
            gt.Table__c = 'PRSP';
            insert gt;
            
            Contact_Role__c cr = new Contact_Role__c();
            cr.Account__c = baacc.Id;
            cr.Contact__c = con.Id;
            //cr.Start_Date__c = date.today().adddays(-30);
            cr.Type__c = 'Doctor-Owner';
            insert cr;
            
            Network_Relationship__c nr = new Network_Relationship__c();
            nr.Program_End_Date__c = NULL;
            nr.Provider_Name__c = con.Id;
            nr.Contact_Role__c = cr.Id;
            nr.Program_ID__c = gt.Id;
            test.startTest();
            insert nr;
            test.stopTest();
        }
    }
    //When a contact has a contact role associated to a BA and has a PA.
    private static testmethod void updateContactBA(){  
        String uniqueUserName = 'standarduser' + DateTime.now().getTime() + '@vsp.com'; 
        Profile p = [SELECT Id FROM Profile WHERE Name='VSP Network Recruitment User'];
        User u = new User(Alias = 'standt', Email='standarduser@vsp.com',
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                          LocaleSidKey='en_US', ProfileId = p.Id,
                          TimeZoneSidKey='America/Los_Angeles',
                          UserName=uniqueUserName);
        
        //System.runAs(u){
            General_Table__c gt = new General_Table__c();
            gt.Name = 'VSP';
            gt.Table__c = 'PRS6';
            gt.Status__c = 'Active';
            insert gt;
        
            Contact con = [SELECT Id, FirstName, LastName, Doctor_ID__c, Vision_Care_End_Date__c FROM Contact WHERE LastName = 'Tennis' AND NPI__c = '1073919239' Limit 1];
            con.Vision_Care_End_Date__c = date.today().adddays(+30);
            con.Vision_Care_Term_Reason__c = gt.Id;
            update con;
            test.startTest();
            ContactTrigger_Handler.VisionCareEndDateNotFuture(new List<id>{con.id});
            test.stopTest(); 
        //}       
    }
    //Update Doctor Ids should hit the error message from ContactTrigger_Handler class.
    private static testmethod void updateContactBA2(){
        String uniqueUserName = 'standarduser' + DateTime.now().getTime() + '@vsp.com';
        Profile p = [SELECT Id FROM Profile WHERE Name='VSP Network Recruitment User'];
        User u = new User(Alias = 'standt', Email='standarduser@vsp.com',
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                          LocaleSidKey='en_US', ProfileId = p.Id,
                          TimeZoneSidKey='America/Los_Angeles',
                          UserName=uniqueUserName);
        System.runAs(u){
            Contact con = [SELECT Id, FirstName, LastName, Doctor_ID__c, Vision_Care_End_Date__c FROM Contact WHERE LastName = 'Tennis' AND NPI__c = '1073919239' Limit 1];
            con.Doctor_ID__c = 'NewDoc122';
            test.startTest();
            try{
                update con;
            }
            catch(Exception e){
                //System.assert(e.getMessage().contains('Another Contact'));
            }
            ContactTrigger_Handler.VisionCareEndDateNotFuture(new List<id>{con.Id});
            test.stopTest();
        }
    }
    
    //Updates Vision_Care_End_Date__c
    private static testmethod void updateContactBA3(){
        String uniqueUserName = 'standarduser' + DateTime.now().getTime() + '@vsp.com';
        Profile p = [SELECT Id FROM Profile WHERE Name='VSP Network Recruitment User'];
        User u = new User(Alias = 'standt', Email='standarduser@vsp.com',
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                          LocaleSidKey='en_US', ProfileId = p.Id,
                          TimeZoneSidKey='America/Los_Angeles',
                          UserName=uniqueUserName);
       // System.runAs(u){
            General_Table__c gt = new General_Table__c();
            gt.Name = 'VSP';
            gt.Table__c = 'PRS6';
            gt.Status__c = 'Active';
            insert gt;
            
            Contact con = [SELECT Id, FirstName, LastName, Doctor_ID__c, Vision_Care_End_Date__c FROM Contact WHERE LastName = 'Tennis' AND NPI__c='1073919239' Limit 1];
            con.Vision_Care_End_Date__c = date.today().adddays(+30);
            con.Vision_Care_Term_Reason__c = gt.Id;
            update con;
            test.startTest();
            ContactTrigger_Handler.VisionCareEndDateFuture(new List<id>{con.id});
            test.stopTest();        
        //}
    }
}