force/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <label>Line of Business</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Vision Benefits</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>D2C</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Contact_Role__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact Role</label>
        <referenceTo>Contact_Role__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <inlineHelpText>The Line of Business responsible for working the Case.</inlineHelpText>
        <label>Line of Business</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Altair</fullName>
                    <color>#0B6FCE</color>
                    <label>Altair</label>
                </value>
                <value>
                    <fullName>Eyefinity</fullName>
                    <color>#78C953</color>
                    <label>Eyefinity</label>
                </value>
                <value>
                    <fullName>Global Customer Care</fullName>
                </value>
                <value>
                    <fullName>Marchon</fullName>
                    <color>#E27001</color>
                    <label>Marchon</label>
                </value>
                <value>
                    <fullName>Optics Group</fullName>
                    <color>#A845DC</color>
                    <label>Optics Group</label>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Vision Care</fullName>
                    <color>#F3D904</color>
                    <label>Vision Care</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Eyeconic</fullName>
        <active>true</active>
        <businessProcess>VSP Global</businessProcess>
        <description>Used to track Eyeconic cases</description>
        <label>Eyeconic</label>
    </recordTypes>
</CustomObject>

force/src/objects/CaseRecordType__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Id__c</fullName>
        <label>Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Case Record Type</label>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Consumer</fullName>
        <active>true</active>
        <label>Consumer</label>
    </recordTypes>
</CustomObject>

src/objects/Contact_Role__c.object
<CustomObject>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <encryptionScheme>None</encryptionScheme>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/VSPR13_ContactAndCaseExtensionController.cls
public class VSPR13_ContactAndCaseExtensionController
{
    public Case objCase {get;set;}
    public Contact objcontact {get;set;}
    public String contactid{get;set;}
    public String acc{get;set;}
    public String selectedrecordType{get;set;}
    public String caseSelectedRecordType{get;set;}
   
    public VSPR13_ContactAndCaseExtensionController(ApexPages.StandardController controller) {
         Id caseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Eyeconic').getRecordTypeId();
         objCase = new Case(); 
         this.objcontact = new Contact(); 
         this.objcontact = (Contact)controller.getrecord();  
         String AccountId = ApexPages.currentPage().getParameters().get('accid'); objcontact.AccountId = (Id)AccountId;     
         objcontact.AccountId = '0010U00000onxlU'; //AS part of the POST-DEPLOYMENT STEP this is to be changed to account ID : 001U000001jMD3W (of 'VSP Consumer' account)         
         //Case defaults
         objCase.Line_of_Business__c = 'Retail'; 
         objCase.Origin = 'Phone'; 
         objCase.Type = 'Issue'; 
       //  objCase.RecordTypeId = CaseRecordType__c.getInstance('Eyeconic').Id__c;    
         objCase.RecordTypeId = caseRecordTypeId;
    }     
    
    public PageReference save()
    {    
       try
       {                
          if(selectedrecordType == 'Consumer') { 
            String strRecordTypeId=[SELECT Id 
                                    FROM RecordType 
                                    WHERE SObjectType = 'Contact' 
                                    AND Name='Consumer'].Id; 
                                    objcontact.RecordTypeId = strRecordTypeId; }
          if(caseSelectedRecordType == 'Eyeconic') { 
            String caseRecordTypeId=[SELECT Id 
                                     FROM RecordType 
                                     WHERE SObjectType = 'Case' 
                                     AND Name='Eyeconic'].Id; 
                                     objCase.RecordTypeId = caseRecordTypeId; }
          objcase.AccountId = objcontact.AccountId;           
          Insert objCase; Insert objcontact;
          objCase.ContactId = objcontact.Id; 
          objCase.AccountId = objcontact.AccountId; 
          Upsert objCase;       
          
          PageReference pageRef = new pageReference('/apex/VSPR5_ContactRenameTab?id=' + objcontact.Id 
                                                    + '&salutation=' + objcontact.Salutation 
                                                    + '&fname=' + objcontact.FirstName 
                                                    + '&lname=' + objcontact.LastName);
          pageRef.setRedirect(true);
          return pageRef; 
       } 
       catch(DmlException ex){
          ApexPages.addmessages(ex);
          return null;
       }
    }
    
   public PageReference cancel(){
       PageReference pageRef = new pageReference('/003/o'); pageRef.setRedirect(true);
       return pageRef;        
   }
    
   public PageReference doSaveAndNew(){ try { if(selectedrecordType == 'Consumer'){ String strRecordTypeId=[SELECT Id FROM RecordType WHERE SObjectType = 'Contact' AND Name='Consumer'].Id; objcontact.RecordTypeId = strRecordTypeId;} if(caseSelectedRecordType == 'Eyeconic'){ String caseRecordTypeId=[SELECT Id FROM RecordType WHERE SObjectType = 'Case' AND Name='Eyeconic'].Id; objCase.RecordTypeId = caseRecordTypeId;}
          objcase.AccountId = objcontact.AccountId; Insert objCase; Insert objcontact; objCase.ContactId = objcontact.Id; objCase.AccountId = objcontact.AccountId; Upsert objCase;  PageReference pageRef = new pageReference('/apex/VSPR5_ContactVFP?accid='+objcontact.AccountId+'&retURL=%2F003K000000pBTKt&save_newsfdc.override=1'); pageRef.setRedirect(true); return pageRef; } catch(DmlException ex){ ApexPages.addmessages(ex); return null;}
   
      /*
    //Contact and Contact Role values are reset and 'Common Account Name' field is prepopulated with AccountId upon clicking save&new button 
    Id acctId = objcontact.AccountId;
    objcontact = new Contact();
    objcontact.AccountId = acctId ;    
    objCrole = new Contact_Role__c();
    objCrole.Start_Date__c = date.today();
    return null;
   */   
      }     
  }