force/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <label>Line of Business</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Vision Benefits</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>D2C</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Amount_Value_Timeframe__c</fullName>
        <description>Timeline for expected Amount.</description>
        <label>Amount Value Timeframe</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1 Month</fullName>
                </value>
                <value>
                    <fullName>12 Months</fullName>
                </value>
                <value>
                    <fullName>24 Months</fullName>
                </value>
                <value>
                    <fullName>36 Months</fullName>
                </value>
                <value>
                    <fullName>48 Months</fullName>
                </value>
                <value>
                    <fullName>60 Months</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <description>Which LOB is the Opportunity for?</description>
        <label>Line of Business</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Optics</fullName>
                </value>
                <value>
                    <fullName>Eyewear</fullName>
                </value>
                <value>
                    <fullName>Eyefinity</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Planned_Closed_Month__c</fullName>
        <description>When is the Opportunity planning on Closing?</description>
        <label>Planned Closed Month</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>January</fullName>
                </value>
                <value>
                    <fullName>February</fullName>
                </value>
                <value>
                    <fullName>March</fullName>
                </value>
                <value>
                    <fullName>April</fullName>
                </value>
                <value>
                    <fullName>May</fullName>
                </value>
                <value>
                    <fullName>June</fullName>
                </value>
                <value>
                    <fullName>July</fullName>
                </value>
                <value>
                    <fullName>August</fullName>
                </value>
                <value>
                    <fullName>September</fullName>
                </value>
                <value>
                    <fullName>October</fullName>
                </value>
                <value>
                    <fullName>November</fullName>
                </value>
                <value>
                    <fullName>December</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Program__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Product/Program</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

force/src/classes/MPM4_Opportunity_Project_Creation_Test.cls
/* 
* 
* Test Class for MPM4_Opportunity_Project_Creation_Test
*  
*/
@isTest
private class MPM4_Opportunity_Project_Creation_Test {

    static testMethod void unitTest(){
        
        Id accRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Practice Account').getRecordTypeId();
        // Insert sample Account 
        Account acc = new Account();
        acc.Name = 'Sample Account 0';
        acc.RecordTypeId = accRecordTypeId;
       
        insert acc;
        
        
        Id oppRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Shift Opportunity').getRecordTypeId();
        // Insert Oportunity record with account id but without record Type
        Opportunity opty0 = new Opportunity();
        opty0.Name = 'Sample Opty 0';
        opty0.RecordTypeId = oppRecordTypeId;
        opty0.AccountId = acc.Id;
        opty0.Amount_Value_Timeframe__c = '1 Month';
        opty0.Amount = 1000;
        opty0.Line_of_Business__c = 'Optics';
        opty0.Product_Program__c = 'SampleText 0';
        opty0.StageName = 'Closed Won';
        opty0.Probability = 100;
        opty0.Closedate = system.today();                           
        opty0.Planned_Closed_Month__c = 'December'; 
        Test.startTest();
        insert opty0;  
        Test.stopTest();
        
        
        
    }
}