force/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Birthdate__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Birthdate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CAQH_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>CAQH ID</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <formula>HYPERLINK(&quot;/&quot; + Id, &quot;Contact Record&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Record</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Degree__c</fullName>
        <description>The educational degree of the Vision Care Doctor.</description>
        <inlineHelpText>The educational degree of the Vision Care Doctor.</inlineHelpText>
        <label>Degree</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>OD</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>DO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Doctor_ID__c</fullName>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Doctor ID</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NPI__c</fullName>
        <description>National Provider Indicator for a Vision Care Doctor.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>National Provider Indicator for a Vision Care Doctor.</inlineHelpText>
        <label>NPI</label>
        <length>55</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Contact_Role__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>CAQH_ID_of_Contact__c</fullName>
        <formula>Contact__r.CAQH_ID__c</formula>
        <label>CAQH ID of Contact</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Eye Care Professional</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Degree_on_Contact__c</fullName>
        <formula>TEXT(Contact__r.Degree__c)</formula>
        <label>Degree on Contact</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_of_Account__c</fullName>
        <formula>Account__r.Email__c</formula>
        <label>Email of Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fax_of_Account__c</fullName>
        <formula>Account__r.Fax</formula>
        <label>Fax of Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name_of_Contact__c</fullName>
        <formula>Contact__r.FirstName &amp; &quot; &quot; &amp; Contact__r.LastName</formula>
        <label>Name of Contact</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name_of_Physical_City__c</fullName>
        <formula>Account__r.ShippingCity</formula>
        <label>Name of Physical City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name_of_Physical_State__c</fullName>
        <formula>Account__r.ShippingState</formula>
        <label>Name of Physical State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name_of_Physical_Street__c</fullName>
        <formula>Account__r.ShippingStreet</formula>
        <label>Name of Physical Street</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name_of_Physical_Zip__c</fullName>
        <formula>Account__r.ShippingPostalCode</formula>
        <label>Name of Physical Zip</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_of_Account__c</fullName>
        <formula>Account__r.Phone</formula>
        <label>Phone of Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_NPI__c</fullName>
        <description>NPI of associated Contact record.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Provider NPI</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force/src/objects/Network_Recruitment__c.object
<CustomObject>
    <description>Custom object to track network recruiting activity.</description>
    <fields>
        <fullName>Account_Name_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Network Recruitments</relationshipLabel>
        <relationshipName>Network_Recruitments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CAQH_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>CAQH ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Physical City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Role__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact Role</label>
        <referenceTo>Contact_Role__c</referenceTo>
        <relationshipLabel>Network Recruitments</relationshipLabel>
        <relationshipName>Network_Recruitments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DOB__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>DOB</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Degree__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Degree</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Doctor_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Doctor ID</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Email</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fax__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Fax</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NPI__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>NPI</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Phone</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_Name_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to Contact from Network Recruitment object. To be populated by trigger.</description>
        <label>Provider Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Network Recruitments</relationshipLabel>
        <relationshipName>Network_Recruitments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recruitment_in_Progress_Count__c</fullName>
        <formula>IF(
ISPICKVAL( Recruitment_Status__c , &quot;Completed&quot;)  || 
ISPICKVAL( Recruitment_Status__c , &quot;Completed/Denied at Committee&quot;) ||
ISPICKVAL( Recruitment_Status__c , &quot;Closed&quot;),
0,1)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Recruitment in Progress Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Physical State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Physical Street</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ZIP__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Physical Zip Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Network Recruitment</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Network Recruitment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Network Recruitments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/VSPR3_NetworkRecruitmentBL.cls
/**
 * Class Name: VSPR3_NetworkRecruitmentBL
 * @author: karl.wilson.l.tan
 * Date: 16.SEP.2013
 * Requirement/Project Name: VSP
 * @description: Handles all Business Logic for the Network Recruitment object.
 */
 
public class VSPR3_NetworkRecruitmentBL{
 
    public void recruitmentBeforeTriggerMethod(List<Network_Recruitment__c> newTrigger){ 
 
     Set<ID> setNetRolIds = new Set<ID>();
     for(Network_Recruitment__c netRec : newTrigger){
        if(netRec.Contact_Role__c != null)
        setNetRolIds.add(netRec.Contact_Role__c);
    }
     //system.debug('-------------------------------- NetROle ID : ' + setNetRolIds);


     MAP<ID , Contact_Role__c> mapConRol = new MAP<ID , Contact_Role__c>([Select Id, Account__c, Contact__c, CAQH_ID_of_Contact__c, Provider_NPI__c, 
         Phone_of_Account__c, Degree_on_Contact__c, Fax_of_Account__c, Email_of_Account__c, Name_of_Physical_City__c, Name_of_Physical_State__c, Name_of_Physical_Street__c, 
         Name_of_Physical_Zip__c from Contact_Role__c where id in: setNetRolIds]);
     //system.debug('--------------------------------MAP  : ' +mapConRol);

     for(Network_Recruitment__c netConRol : newTrigger)
       {
        if(netConRol.Contact_Role__c != null)
            {
            Contact_Role__c c = mapConRol.get(netConRol.Contact_Role__c);
            //system.debug('--------------------------------Account Name : ' + netConRol.Contact_Role__c);
            
            Contact con = [Select Birthdate__c, Doctor_ID__c from Contact where id = :c.Contact__c];
            Date contactBirthdate = con.Birthdate__c;
            String contactDoctorID = con.Doctor_ID__c;
            
            netConRol.DOB__c = contactBirthdate;
            netConRol.Account_Name_Lookup__c = c.Account__c;                       
            netConRol.CAQH_ID__c = c.CAQH_ID_of_Contact__c;
            netConRol.NPI__c = c.Provider_NPI__c;
            netConRol.Doctor_ID__c = contactDoctorID;    
            netConRol.City__c = c.Name_of_Physical_City__c;
            netConRol.Degree__c = c.Degree_on_Contact__c;
            netConRol.Email__c = c.Email_of_Account__c;
            netConRol.Fax__c = c.Fax_of_Account__c;
            netConRol.Phone__c = c.Phone_of_Account__c;
            netConRol.Provider_Name_Lookup__c = c.Contact__c;
            //netConRol.Provider_Name__c = c.Name_of_Contact__c;
            netConRol.ZIP__c = c.Name_of_Physical_Zip__c;
            netConRol.Street_Address__c = c.Name_of_Physical_Street__c;
            netConRol.State__c = c.Name_of_Physical_State__c;
            
            
            }
       }
    }
    
    public static void recruitmentAfterTriggerMethod(List<Network_Recruitment__c> newTrigger, List<Network_Recruitment__c> oldTrigger, Map<id,Network_Recruitment__c> oldTriggerMap, Boolean isDelete, Boolean isInsert){
    Set<Id> contactIds= new Set<Id>();
    Set<Id> oldcontactIds= new Set<Id>();
     
    if(isDelete){
      for(Network_Recruitment__c oldnetRec : oldTrigger){
         //accountIds.add(oldContact.AccountId);
         contactIds.add(oldTriggerMap.get(oldnetRec.id).Provider_Name_Lookup__c);
       }
    }else{
       for(Network_Recruitment__c netRec : newTrigger){
         if(!isInsert && netRec.Provider_Name_Lookup__c != oldTriggerMap.get(netRec.id).Provider_Name_Lookup__c){
           System.debug('>>>>Update' + oldTriggerMap.get(netRec.id).Provider_Name_Lookup__c);
           oldcontactIds.add(oldTriggerMap.get(netRec.id).Provider_Name_Lookup__c);
           System.debug('>>>>OldContactIds' + oldTriggerMap.get(netRec.id).Provider_Name_Lookup__c);
           System.debug('>>>>NewContactIds' + netRec.Provider_Name_Lookup__c);
         }
         contactIds.add(netRec.Provider_Name_Lookup__c);         
       }
     }
     updateCheckboxFields(contactIds);
     updateCheckboxFields(oldcontactIds);
     System.debug('>>>>ContactIds' + contactIds);
     System.debug('>>>>oldContactIds' + oldcontactIds);      
   }
   
   public static void updateCheckboxFields(Set<Id> contactIds){
     Map<Id,Double> totNetRecInProg = new Map<Id,Double>();
    Double netRecInProgCnt = 0; 
    Boolean hasNetRec;
    
    System.debug('>>>>ContactIds' + contactIds);    
     List<Network_Recruitment__c> netRecDetails = [Select Recruitment_in_Progress_Count__c,Provider_Name_Lookup__c from Network_Recruitment__c where 
                                     Provider_Name_Lookup__c IN: contactIds];
     System.debug('>>>>netRecDetails ' + netRecDetails);
     
     if (netRecDetails.size() > 0){
       System.debug('>>>>netRecDetailsSize' + netRecDetails.size());
       hasNetRec = true;
       System.debug('>>>>hasNetRec' + hasNetRec);
       
       for(Network_Recruitment__c netRecDetail : netRecDetails){
       
         if(totNetRecInProg.containsKey(netRecDetail.Provider_Name_Lookup__c)){         
          netRecInProgCnt = totNetRecInProg.get(netRecDetail.Provider_Name_Lookup__c);
            netRecInProgCnt = netRecInProgCnt + netRecDetail.Recruitment_in_Progress_Count__c;
 
            totNetRecInProg.put(netRecDetail.Provider_Name_Lookup__c,netRecInProgCnt);

            System.debug('>>>>IFnetRecDetail.id' + netRecDetail.id);
            System.debug('>>>>IFnetRecInProgCnt' + netRecInProgCnt);
            
          
        }else{        
          netRecInProgCnt = netRecInProgCnt + netRecDetail.Recruitment_in_Progress_Count__c;

          totNetRecInProg.put(netRecDetail.Provider_Name_Lookup__c,netRecInProgCnt);

            System.debug('>>>>IFnetRecDetail.id' + netRecDetail.id);
            System.debug('>>>>IFnetRecInProgCnt' + netRecInProgCnt);
            
        }      
       }
       System.debug('>>>>totNetRecInProg' + totNetRecInProg);
       
     }else{
       hasNetRec = false;
       System.debug('>>>>hasNetRec ' + hasNetRec );
       for(Id contId : contactIds){
         totNetRecInProg.put(contId,0);         
       }
     }
       
     VSPR3_NetworkRecruitmentDML.updateContactDetails(totNetRecInProg, hasNetRec);
    
    
    
    }

}