force/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <description>For Practice and Business accounts so that the data can be populated for use in premier tier calculation.
Population on Business account will be manual or through data loader.</description>
        <inlineHelpText>Identifies the location&apos;s relationship with VSP for Premier Tiering</inlineHelpText>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Affiliate</fullName>
                </value>
                <value>
                    <fullName>AOP</fullName>
                </value>
                <value>
                    <fullName>CAT2</fullName>
                </value>
                <value>
                    <fullName>Conflict</fullName>
                </value>
                <value>
                    <fullName>GAP</fullName>
                </value>
                <value>
                    <fullName>Independent</fullName>
                </value>
                <value>
                    <fullName>LVC</fullName>
                </value>
                <value>
                    <fullName>Near Site</fullName>
                </value>
                <value>
                    <fullName>Net Dev Excluded</fullName>
                </value>
                <value>
                    <fullName>Net Dev Purchasing Requirement</fullName>
                </value>
                <value>
                    <fullName>Not Supported</fullName>
                </value>
                <value>
                    <fullName>Onsite</fullName>
                </value>
                <value>
                    <fullName>Pearle Vision CO</fullName>
                </value>
                <value>
                    <fullName>Pearle Vision LO</fullName>
                </value>
                <value>
                    <fullName>Pop Up</fullName>
                </value>
                <value>
                    <fullName>Rollup</fullName>
                </value>
                <value>
                    <fullName>School</fullName>
                </value>
                <value>
                    <fullName>VSP Retail</fullName>
                </value>
                <value>
                    <fullName>VSP Ventures</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Eyewear_Location_Spend_LTM__c</fullName>
        <inlineHelpText>Location&apos;s spend on Eyewear in the last 12 months</inlineHelpText>
        <label>Eyewear Location Spend LTM</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Optics_Location_Spend_LTM__c</fullName>
        <inlineHelpText>Location&apos;s spend on Optics in the last 12 months</inlineHelpText>
        <label>Optics Location Spend LTM</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Participation_Exclusions__c</fullName>
        <label>Participation Exclusions</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ADMCD – Opts out of Medicaid All Doctors</fullName>
                    <label>ADMCD – Opts out of Medicaid All Doctor</label>
                </value>
                <value>
                    <fullName>NODIS – Opts out of discounts</fullName>
                </value>
                <value>
                    <fullName>NOMCR – Opts out of Medicare</fullName>
                </value>
                <value>
                    <fullName>NOCNT – Opts out of providing contacts</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Premier_Tax_ID_Roll_Up_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Indicates whether an Account is being evaluated for Premier qualification in conjunction with other accounts with different Tax ID&apos;s.</inlineHelpText>
        <label>Tax ID Roll Up Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Offering_s__c</fullName>
        <label>Service Offering (s)</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CCLOC - CareCredit Program Participant</fullName>
                </value>
                <value>
                    <fullName>CVLKT - CIGNA Luxottica Collection</fullName>
                </value>
                <value>
                    <fullName>CVVKT - CIGNA VisionWorks Collection</fullName>
                </value>
                <value>
                    <fullName>EXAM - Exam only location</fullName>
                </value>
                <value>
                    <fullName>EYEWR - Dispensing only location</fullName>
                </value>
                <value>
                    <fullName>FFAA - Free Fitting and Adjustments</fullName>
                </value>
                <value>
                    <fullName>LEVEL - Level Provider</fullName>
                </value>
                <value>
                    <fullName>PEDKT - Otis and Piper Collection</fullName>
                </value>
                <value>
                    <fullName>PTSF - PROTEC Safety Fame Kit - Free</fullName>
                </value>
                <value>
                    <fullName>RTLIM - Retinal Imaging</fullName>
                </value>
                <value>
                    <fullName>SFTY - Safety Eyewear</fullName>
                </value>
                <value>
                    <fullName>SPRTS - Sports Eyewear</fullName>
                </value>
                <value>
                    <fullName>TELEH - Telehealth Provider</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of Account.</description>
        <inlineHelpText>A = Active 
Inactive = Not a Current Customer of any LOB. 
Closed = Business has ceased operations 
New = In process of becoming an Active account</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Submit for Approval</fullName>
                </value>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Inactive Ownership Change</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
                <value>
                    <fullName>Marked for Deletion</fullName>
                </value>
                <value>
                    <fullName>Archive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tax_ID__c</fullName>
        <description>Account Tax ID.</description>
        <encrypted>true</encrypted>
        <inlineHelpText>Account Tax ID.</inlineHelpText>
        <label>Tax ID</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Location_Spend_LTM__c</fullName>
        <inlineHelpText>Location&apos;s spend on Eyewear and Optics in the last 12 months</inlineHelpText>
        <label>Total Location Spend LTM</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>VC__c</fullName>
        <formula>IF( Vision_Care_Effective_Date__c &lt;= TODAY()  &amp;&amp; (Vision_Care_End_Date__c &gt;=TODAY() ||  ISBLANK(Vision_Care_End_Date__c)) , TRUE, FALSE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>VC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vision_Care_Effective_Date__c</fullName>
        <label>Vision Care Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Care_End_Date__c</fullName>
        <label>Vision Care End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Care_Good_Standing__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is account in good standing with Vision Care.</description>
        <inlineHelpText>Is account in good standing with Vision Care.</inlineHelpText>
        <label>Vision Care Good Standing</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Global_Rewards_Group__c.object
<CustomObject>
    <description>Parent object in a relationship that groups multiple Business/Practice Accounts under one Global Rewards Program (child object is Global Rewards Group Relationship)</description>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Affiliate</fullName>
                </value>
                <value>
                    <fullName>AOP</fullName>
                </value>
                <value>
                    <fullName>CAT2</fullName>
                </value>
                <value>
                    <fullName>Conflict</fullName>
                </value>
                <value>
                    <fullName>GAP</fullName>
                </value>
                <value>
                    <fullName>Independent</fullName>
                </value>
                <value>
                    <fullName>LVC</fullName>
                </value>
                <value>
                    <fullName>Near Site</fullName>
                </value>
                <value>
                    <fullName>Net Dev Excluded</fullName>
                </value>
                <value>
                    <fullName>Net Dev Purchasing Requirement</fullName>
                </value>
                <value>
                    <fullName>Not Supported</fullName>
                </value>
                <value>
                    <fullName>Onsite</fullName>
                </value>
                <value>
                    <fullName>Pearle Vision CO</fullName>
                </value>
                <value>
                    <fullName>Pearle Vision LO</fullName>
                </value>
                <value>
                    <fullName>Pop Up</fullName>
                </value>
                <value>
                    <fullName>Rollup</fullName>
                </value>
                <value>
                    <fullName>School</fullName>
                </value>
                <value>
                    <fullName>VSP Retail</fullName>
                </value>
                <value>
                    <fullName>VSP Ventures</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Global Rewards Groups</relationshipLabel>
        <relationshipName>Global_Rewards_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF( OR( Start_Date__c = TODAY() , AND( Start_Date__c &lt; TODAY() , OR( End_Date__c &gt;= TODAY() , ISBLANK( End_Date__c ) ) ) ) , &quot;Active&quot;, &apos;Inactive&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Care_Good_Standing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Vision Care Good Standing</label>
        <type>Checkbox</type>
    </fields>
    <label>Global Rewards Group</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Global Rewards Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Global Rewards Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Global_Rewards_Group_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Child_Account__c</fullName>
        <label>Child Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Global Rewards Group Relationships</relationshipLabel>
        <relationshipName>Global_Rewards_Group_Relationships</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>Date the child record was ended its relationship with the Parent Roll up account.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Global_Rewards_Group__c</fullName>
        <label>Global Rewards Group</label>
        <referenceTo>Global_Rewards_Group__c</referenceTo>
        <relationshipLabel>Global Rewards Group Relationships</relationshipLabel>
        <relationshipName>Global_Rewards_Group</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF((Start_Date__c &lt;= TODAY() &amp;&amp; (ISBLANK(End_Date__c) ||  End_Date__c &gt;= TODAY())), &apos;Active&apos;, 
IF((Start_Date__c &gt; Today()), &apos;Future&apos;, &apos;Inactive&apos;))</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Global Rewards Group Relationship</label>
    <nameField>
        <displayFormat>PREMIER-{0000}</displayFormat>
        <label>Global Rewards Group Relationship ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Global Rewards Group Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/VSPR31_Premier_Prac_Bus_Acc_Avg_Test.cls
@isTest
//Test class for VSPR31_Premier_Prac_Bus_Acc_Avg_Batch
public class VSPR31_Premier_Prac_Bus_Acc_Avg_Test {
    @testSetup
    public static void testData(){
        Test.startTest();
        Id paRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Practice Account').getRecordTypeId();
        Id baRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
        Id grpContractRecordTypeId = Schema.SObjectType.Global_Rewards_Group__c.getRecordTypeInfosByName().get('Contract Type').getRecordTypeId();
        
        Account pa1 = new Account();
        pa1.RecordTypeId = paRecordTypeId;
        pa1.Name = 'PA Test 1234';
        pa1.Status__c = 'A';
        pa1.Vision_Care_Effective_Date__c = system.today() - 3;
        pa1.Vision_Care_End_Date__c = null;//system.today() + 1;
        pa1.Vision_Care_Good_Standing__c = true;
        pa1.Tax_ID__c = '123456789';
        pa1.Premier_Tax_ID_Roll_Up_Account__c = false;
        
        insert pa1;
        
        Account ba1 = new Account();
        ba1.RecordTypeId = baRecordTypeId;
        ba1.Name = 'BA Test 1234';
        ba1.ParentId = pa1.Id;
        ba1.Contract_Type__c = 'Affiliate';
        ba1.Vision_Care_Good_Standing__c = True;
        ba1.Total_Location_Spend_LTM__c = 100;
        ba1.Eyewear_Location_Spend_LTM__c = 100;
        ba1.Optics_Location_Spend_LTM__c = 100;
        ba1.Participation_Exclusions__c = 'NODIS – Opts out of discounts';
        //VC__C is a formula field on the Account
        //IF( Vision_Care_Effective_Date__c <= TODAY() && (Vision_Care_End_Date__c >=TODAY() || ISBLANK(Vision_Care_End_Date__c)) , TRUE, FALSE)
        ba1.Vision_Care_Effective_Date__c = system.today() - 3; 
        
        insert ba1;
        
        Account ba2 = new Account();
        ba2.RecordTypeId = baRecordTypeId;
        ba2.Name = 'BA2 Test 1234';
        ba2.ParentId = pa1.Id;
        ba2.Total_Location_Spend_LTM__c = 100;
        ba2.Eyewear_Location_Spend_LTM__c = 100;
        ba2.Optics_Location_Spend_LTM__c = 100;
        ba2.Contract_Type__c = 'Affiliate';
        ba2.Vision_Care_Good_Standing__c = True;
        ba2.Service_Offering_s__c = 'RTLIM - Retinal Imaging';
        //VC__C is a formula field on the Account
        //IF( Vision_Care_Effective_Date__c <= TODAY() && (Vision_Care_End_Date__c >=TODAY() || ISBLANK(Vision_Care_End_Date__c)) , TRUE, FALSE)
        ba2.Vision_Care_Effective_Date__c = system.today() - 3; 
        
        insert ba2;
        
        Account ba3 = new Account();
        ba3.RecordTypeId = baRecordTypeId;
        ba3.Name = 'BA3 Test 1234';
        ba3.ParentId = pa1.Id;
        ba3.Total_Location_Spend_LTM__c = 100;
        ba3.Eyewear_Location_Spend_LTM__c = 100;
        ba3.Optics_Location_Spend_LTM__c = 100;
        ba3.Contract_Type__c = 'Affiliate';
        ba3.Service_Offering_s__c = 'FFAA - Free Fitting and Adjustments';
        ba3.Vision_Care_Good_Standing__c = True;
        //VC__C is a formula field on the Account
        //IF( Vision_Care_Effective_Date__c <= TODAY() && (Vision_Care_End_Date__c >=TODAY() || ISBLANK(Vision_Care_End_Date__c)) , TRUE, FALSE)
        ba3.Vision_Care_Effective_Date__c = system.today() - 3; 
        
        insert ba3;
        
        Global_Rewards_Group__c grg = new Global_Rewards_Group__c();
        grg.RecordTypeId = grpContractRecordTypeId;
        grg.Name = 'TESTGRP';
        grg.Parent_Account__c = pa1.Id;
        
        insert grg;
        
        Global_Rewards_Group_Relationship__c grgr = new Global_Rewards_Group_Relationship__c();
        grgr.Active__c = True;
        grgr.Child_Account__c = ba1.Id;
        grgr.End_Date__c = null;
        grgr.Global_Rewards_Group__c = grg.Id;
        grgr.Start_Date__c = Date.today()-10;
        
        insert grgr; 
        
        //Used to test the exception in the class
        Exception_handler_Email__c toAddress = new Exception_handler_Email__c();
        toAddress.Name = 'test@vsp.com';
        insert toAddress;
        
    }
    
    @isTest
    public static void pabaAccAvgTest(){ 
        Test.startTest();
        Account paGet = [SELECT Id, Name, Vision_Care_Good_Standing__c FROM Account WHERE Name = 'PA Test 1234' LIMIT 1];
        List<Account> baGet = [SELECT Id, Name, Vision_Care_Good_Standing__c FROM Account WHERE Name LIKE '%BA%' LIMIT 5];
        
        for(Account ac : baGet){
            ac.Contract_Type__c = 'Affiliate';
        }
        update baGet;
        
        Set<Id> Prac1IdSet = new Set<Id>();
        Prac1IdSet.add(paGet.Id);
        
        VSPR31_Premier_Prac_Bus_Acc_Avg_Batch ba = new VSPR31_Premier_Prac_Bus_Acc_Avg_Batch(Prac1IdSet);
        Database.executeBatch(ba,10);
        
        Test.stopTest();  
        
        Account ba1Get = [SELECT Id, Name, Vision_Care_Good_Standing__c, VC__c, Contract_Type__c FROM Account WHERE Id IN: baGet Limit 1];
        system.debug('ba Contract Type : ' + ba1Get.Contract_Type__c);
        system.assertEquals(True, ba1Get.VC__c);
        
    }
    @isTest
    public static void pabaAccAvgNullTest(){ 
        Test.startTest();
        Account paGet = [SELECT Id, Name, Vision_Care_Good_Standing__c FROM Account WHERE Name = 'PA Test 1234' LIMIT 1];
        List<Account> baGet = [SELECT Id, Name, Vision_Care_Good_Standing__c FROM Account WHERE Name LIKE '%BA%' LIMIT 5];
        
        for(Account ac : baGet){
            ac.Contract_Type__c = 'Affiliate';
            ac.Total_Location_Spend_LTM__c = null;
            ac.Eyewear_Location_Spend_LTM__c = null;
            ac.Optics_Location_Spend_LTM__c = null;
        }
        update baGet;
        
        Set<Id> Prac1IdSet = new Set<Id>();
        Prac1IdSet.add(paGet.Id);
        
        VSPR31_Premier_Prac_Bus_Acc_Avg_Batch ba = new VSPR31_Premier_Prac_Bus_Acc_Avg_Batch(Prac1IdSet);
        Database.executeBatch(ba,10);
        
        Test.stopTest();  
        
        Account ba1Get = [SELECT Id, Name, Vision_Care_Good_Standing__c, VC__c, Contract_Type__c, Total_Location_Spend_LTM__c, Eyewear_Location_Spend_LTM__c, Optics_Location_Spend_LTM__c 
                          FROM Account WHERE Id IN: baGet Limit 1];
        system.debug('ba Contract Type : ' + ba1Get.Contract_Type__c);
        system.assertEquals('Affiliate', ba1Get.Contract_Type__c);
        system.assertNotEquals(1000, ba1Get.Total_Location_Spend_LTM__c);
        system.assertNotEquals(1000, ba1Get.Eyewear_Location_Spend_LTM__c);
        system.assertNotEquals(1000, ba1Get.Optics_Location_Spend_LTM__c);
        
    }
}