force/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Has_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Contact?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>High_Profile__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Account has a High Profile Vision Care Doctor.</description>
        <label>High Profile</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MDM_Location_Keys__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>MDM Location Key.</inlineHelpText>
        <label>MDM Location Key</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Physical_County__c</fullName>
        <description>Populated by Data Integration</description>
        <label>Physical County</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Care_VSP_Network_Provider__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Vision Care Member Account.</description>
        <inlineHelpText>Vision Care Member Account.</inlineHelpText>
        <label>Vision Care Network Provider</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/VSPR1_AccountDML_Test.cls
@isTest
private class VSPR1_AccountDML_Test{
  @testSetup
  static void setupTestData(){
    test.startTest();
    Account account_Obj = new Account(Name = 'Name226', ShippingStreet = 'PratapNagar', ShippingCity = 'Jaipur', ShippingState = 'Raj', 
                                      ShippingPostalCode = '302022', ShippingCountry = 'India', Has_Contact__c = true, High_Profile__c = true, MDM_Location_Keys__c = 'MDM_L140',
                                      Vision_Care_VSP_Network_Provider__c = false);
    Insert account_Obj; 
    test.stopTest();
  }

  static testMethod void test_getAccountDetails_UseCase1(){
    List<Account> account_Obj  =  [SELECT Id, ShippingCity,MDM_Location_Keys__c, ShippingCountry, ShippingState, Physical_County__c,
                                                 ShippingStreet, ShippingPostalCode, Has_Contact__c FROM Account];
    System.assertEquals(true,account_Obj.size()>0);
    VSPR1_AccountDML obj01 = new VSPR1_AccountDML();
    VSPR1_AccountDML.getAccountDetails(new Set<Id>());
  }
}