force/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Bank_Name__c</fullName>
        <label>Bank Name</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bank_Routing_Number__c</fullName>
        <label>Bank Routing Number</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bypass_VC_Validation_Rules__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass VC Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of Account.</description>
        <inlineHelpText>A = Active 
Inactive = Not a Current Customer of any LOB. 
Closed = Business has ceased operations 
New = In process of becoming an Active account</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Submit for Approval</fullName>
                </value>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Inactive Ownership Change</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
                <value>
                    <fullName>Marked for Deletion</fullName>
                </value>
                <value>
                    <fullName>Archive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/General_Table__c.object
<CustomObject>
    <fields>
        <fullName>Code_Description__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Code Description</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Table__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Table</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>General Table</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>General Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/VSPR19b_PopulateBankName_Handler.cls
/**
* Class Name: VSPR19b_PopulateBankName
* Date: May 12, 2017
* Project: PROS Decommission
* @author: Kiran Penmatsa
* @description: Populates Bank Name given the routing number
*/

public class VSPR19b_PopulateBankName_Handler{
    public static boolean isExecuting = false;
    public static boolean VSPR19b_PopulateBankName_Handler_recursion = true;
    
    public void VSPR19b_PopulateBankName_Handler(List<Account> newTrigger){
        
        if(VSPR19b_PopulateBankName_Handler_recursion ){
            String pracAccRecordTypeId = [SELECT Id from RecordType where SObjectType = 'Account' and Name='Practice Account'].Id;
    String busAccRecordTypeId = [SELECT Id from RecordType where SObjectType = 'Account' and Name='Business Account'].Id;
    
        VSPR19b_PopulateBankName_Handler_recursion = false;
        
            //if( VSPR19b_PopulateBankName_Handler.isExecuting ){
            //    return;
            //}
            //VSPR19b_PopulateBankName_Handler.isExecuting = true; 
            system.debug('***** entered VSPR19b_PopulateBankName_Handler ***** ');
    
            Set<string> allBankRoutingNbrs = new Set<string>();
            for(Account a : newTrigger){
                if(a.RecordTypeId == pracAccRecordTypeId || a.RecordTypeId == busAccRecordTypeId){
                    if( a.Bank_Routing_Number__c != null){
                        String aBankRoutingNbr = a.Bank_Routing_Number__c;  
                        allBankRoutingNbrs.add(aBankRoutingNbr);
                    }
                }
            }
            system.debug('allBankRoutingNbrs: '+allBankRoutingNbrs);
            List<General_Table__c> geoCode = 
                [SELECT id, Name, Code_Description__c 
                 FROM General_Table__c 
                 WHERE Table__c = 'PRS1211' 
                 AND Status__c = 'Active'
                 AND Name =: allBankRoutingNbrs];
            system.debug('geoCode: '+geoCode);
            map<string,string> geoCodeCD = new Map<string,string>();
            for(General_Table__c gt : geoCode){
                geoCodeCD.put(gt.Name,gt.Code_Description__c);
            }
            system.debug('geoCodeCD: '+geoCodeCD);
    
            map<string,Integer> count1 = new Map<string,Integer>();
            AggregateResult[] geoCodeCounts = 
                [SELECT Name Id, COUNT(Id) geoCodeCount 
                 FROM General_Table__c 
                 WHERE Name != NULL 
                 AND Table__c = 'PRS1211'
                 AND Status__c = 'Active'
                 AND Name =: allBankRoutingNbrs
                 GROUP BY Name];
            system.debug('geoCodeCounts: '+geoCodeCounts);
            for(AggregateResult ar : geoCodeCounts){
                    count1.put((string)ar.get('Id'), (Integer)ar.get('geoCodeCount'));
            }
            system.debug('count1: '+count1);
    
            List<Account> accIds = new List<Account>();
            for(Account a : newTrigger){
                if(a.RecordTypeId == pracAccRecordTypeId || a.RecordTypeId == busAccRecordTypeId){
                    
                    Account dup  = new Account(Id = a.Id);          
                    if(count1.get(a.Bank_Routing_Number__c) == 0){
                        dup.Bank_Name__c   = '';
                        dup.Bypass_VC_Validation_Rules__c = true;
                    }
                    if(count1.get(a.Bank_Routing_Number__c) == 1){
                        dup.Bank_Name__c = geoCode[0].Code_Description__c; 
                        dup.Bypass_VC_Validation_Rules__c = true;
                    }
                    accIds.add(dup);
                }
            }
            update accIds;
            system.debug('***** exiting VSPR19b_PopulateBankName_Handler ***** ');
        }
    }
}