force/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Bypass_VC_Validation_Rules__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass VC Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vision_Care_Effective_Date__c</fullName>
        <label>Vision Care Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Care_End_Date__c</fullName>
        <label>Vision Care End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Care_Location_Key__c</fullName>
        <encrypted>true</encrypted>
        <label>Vision Care Location Key</label>
        <length>125</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force/src/objects/Contact_Role__c.object
<CustomObject>
    <fields>
        <fullName>Fee_Code__c</fullName>
        <label>Fee Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force/src/objects/Network_Relationship__c.object
<CustomObject>
    <description>Custom object to track Payment Relationships between doctors and offices.</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Network Relationships</relationshipLabel>
        <relationshipName>Network_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Bypass_VC_Validation_Rules__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass VC Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact_Role__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact Role</label>
        <referenceTo>Contact_Role__c</referenceTo>
        <relationshipName>Payment_Relationships</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Directory_End_Date__c</fullName>
        <label>Directory End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Fee_Code__c</fullName>
        <defaultValue>&quot;NF&quot;</defaultValue>
        <label>Fee Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LVC_Negotiated_Discount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>LVC Negotiated Discount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Program_Effective_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Program Effective Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Program_End_Date__c</fullName>
        <label>Program End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Program_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup relationship field from Network Relationship to General Table object</description>
        <label>Program ID</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>General_Table__c.Table__c</field>
                <operation>equals</operation>
                <value>PRSP</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>General_Table__c</referenceTo>
        <relationshipLabel>Network Relationships</relationshipLabel>
        <relationshipName>Network_Relationships</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Provider Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Network Relationships</relationshipLabel>
        <relationshipName>Network_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_Care_Location_Key__c</fullName>
        <label>Vision Care Location Key</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Network Relationship</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Network Relationship Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Network Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force/src/classes/Batch_ChangeTaxIdNetRel.cls
global class Batch_ChangeTaxIdNetRel implements Database.Batchable<sObject>{

global List<Account> lstBusinessAccounts;
global Date accTEMP_Vision_Care_End_Date;
global Date acc_Vision_Care_End_Date;
global Date acc_Vision_Care_Effective_Date;
global Map<String,String> lbaMap;
 
string soql = 'SELECT Id,Program_ID__c,Program_End_Date__c,Directory_End_Date__c,Account_Name__c,Contact_Role__c, Provider_Name__c, Vision_Care_Location_Key__c, Fee_Code__c,LVC_Negotiated_Discount__c, Account_Name__r.Vision_Care_Effective_Date__c, Account_Name__r.Vision_Care_End_Date__c, Program_Effective_Date__c, Bypass_VC_Validation_Rules__c FROM Network_Relationship__c WHERE Account_Name__c IN :lstBusinessAccounts';
 
//global final String gstrQuery = ( Test.isRunningTest() ? 'SELECT Id FROM Network_Relationship__c WHERE name != null LIMIT 1' : soql );
global final String gstrQuery = ( soql );

global Database.QueryLocator start(Database.BatchableContext BC){
    return Database.getQueryLocator(gstrQuery);
}
    
global void execute(Database.BatchableContext BC, List<Network_Relationship__c> scope){

    list<Network_Relationship__c> lstBizNetRelationShip = new list<Network_Relationship__c>();     

    for(Network_Relationship__c net : scope){

            if(net.Program_Effective_Date__c > accTEMP_Vision_Care_End_Date){             
                Network_Relationship__c bizNetRelExist = new Network_Relationship__c(Id=net.Id);
                bizNetRelExist.Program_End_Date__c = accTEMP_Vision_Care_End_Date;        
                bizNetRelExist.Directory_End_Date__c = accTEMP_Vision_Care_End_Date; 
                bizNetRelExist.Bypass_VC_Validation_Rules__c = true;
                lstBizNetRelationShip.add(bizNetRelExist);
            }

            if(net.Program_Effective_Date__c <= system.today() && 
                net.Program_End_Date__c != NULL && 
                net.Program_End_Date__c > accTEMP_Vision_Care_End_Date){
                Network_Relationship__c bizNetRelExist = new Network_Relationship__c(Id=net.Id);
                bizNetRelExist.Program_End_Date__c = accTEMP_Vision_Care_End_Date;        
                bizNetRelExist.Directory_End_Date__c = accTEMP_Vision_Care_End_Date; 
                bizNetRelExist.Bypass_VC_Validation_Rules__c = true;
                lstBizNetRelationShip.add(bizNetRelExist);

                Network_Relationship__c bizNetRel = new Network_Relationship__c();
                bizNetRel.Contact_Role__c = net.Contact_Role__c;
                bizNetRel.Account_Name__c = net.Account_Name__c;
                bizNetRel.Program_ID__c = net.Program_ID__c;         
                bizNetRel.Program_Effective_Date__c = acc_Vision_Care_Effective_Date;
                bizNetRel.Program_End_Date__c = acc_Vision_Care_End_Date; 
                bizNetRel.Directory_End_Date__c = acc_Vision_Care_End_Date; 
                bizNetRel.Provider_Name__c = net.Provider_Name__c;
                bizNetRel.Vision_Care_Location_Key__c = lbaMap.get(net.Account_Name__c);
                bizNetRel.Fee_Code__c = net.Fee_Code__c;
                bizNetRel.LVC_Negotiated_Discount__c = net.LVC_Negotiated_Discount__c;
                bizNetRel.Bypass_VC_Validation_Rules__c = true;
                lstBizNetRelationShip.add(bizNetRel);
            }

            if(net.Program_Effective_Date__c <= system.today() && net.Program_End_Date__c == NULL) {
                Network_Relationship__c bizNetRelExist = new Network_Relationship__c(Id=net.Id);
                bizNetRelExist.Program_End_Date__c = accTEMP_Vision_Care_End_Date;        
                bizNetRelExist.Directory_End_Date__c = accTEMP_Vision_Care_End_Date; 
                bizNetRelExist.Bypass_VC_Validation_Rules__c = true;
                lstBizNetRelationShip.add(bizNetRelExist);

                Network_Relationship__c bizNetRel = new Network_Relationship__c();
                bizNetRel.Contact_Role__c = net.Contact_Role__c;
                bizNetRel.Account_Name__c = net.Account_Name__c;
                bizNetRel.Program_ID__c = net.Program_ID__c;         
                bizNetRel.Program_Effective_Date__c = acc_Vision_Care_Effective_Date;
                bizNetRel.Program_End_Date__c = acc_Vision_Care_End_Date; 
                bizNetRel.Directory_End_Date__c = acc_Vision_Care_End_Date; 
                bizNetRel.Provider_Name__c = net.Provider_Name__c;
                bizNetRel.Vision_Care_Location_Key__c = lbaMap.get(net.Account_Name__c);
                bizNetRel.Fee_Code__c = net.Fee_Code__c;
                bizNetRel.LVC_Negotiated_Discount__c = net.LVC_Negotiated_Discount__c;
                bizNetRel.Bypass_VC_Validation_Rules__c = true;
                lstBizNetRelationShip.add(bizNetRel);
            } 

            if(!lstBizNetRelationShip.isEmpty()) { 
                upsert lstBizNetRelationShip;                      
            } 
    }

}

global void finish(Database.BatchableContext BC){
}

}