force/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Address_Type__c</fullName>
        <label>Address Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Physical</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Shipping</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <formula>Street__c &amp; &apos;, &apos; &amp; City__c &amp; &apos;, &apos; &amp; State__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>City</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>State</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Street</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Zip</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force/src/objects/Address_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Address Relationships</relationshipLabel>
        <relationshipName>Address_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Address_Type__c</fullName>
        <label>Address Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Physical</fullName>
                </value>
                <value>
                    <fullName>Shipping</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Address Relationships</relationshipLabel>
        <relationshipName>Address_Relationships</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Address Relationship</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Address Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Address Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/VSPR26_AddressRelationshipTriggerTest.cls
//This test class can only cover 75% if the Try Catch of the AddressRelationshipTrigger is in place. The trigger should never error out and hit the Catch block.
//See AddressTrigger, it has a try and catch removed.
@isTest(SeeAllData=false)
private class VSPR26_AddressRelationshipTriggerTest {
    @testSetup private static void setupData(){
        test.startTest();
        Account accObj = new Account(Name = 'BusinessAccountTest');
        insert accObj;
        
        Address__c addrObj = new Address__c(Street__c = '423 Test Drive', City__c = 'Dallas', State__c = 'TX', Zip__c = '75080');   
        insert addrObj;
        
        Address_Relationship__c addrRelObj = new Address_Relationship__c(Account__c = accObj.Id, Address__c = addrObj.Id, Address_Type__c = 'Physical');
        insert addrRelObj;
        test.stopTest();
    }
    
    private static testmethod void test_UseCase1(){
        Account acc = [SELECT Name FROM Account WHERE Name = 'BusinessAccountTest' Limit 1];
        Address_Relationship__c addRel = [SELECT Name FROM Address_Relationship__c WHERE Account__c = :acc.Id  LIMIT 1];
        addRel.Address_Type__c = 'Shipping';
        test.startTest();
        update addRel;
        test.stopTest();
    }
    
    private static testMethod void test_UseCase2(){
        Account acc = [SELECT Name FROM Account WHERE Name = 'BusinessAccountTest' Limit 1];
        Address__c addr = [SELECT Street__c FROM Address__c WHERE Street__c = '423 Test Drive' Limit 1];
        Address__c newAddr = new Address__c(Street__c = '424 Test Drive', City__c = 'Dallas', State__c = 'TX', Zip__c = '75080');
        Test.startTest();
        insert newAddr;
        Test.stopTest();
        
        Address_Relationship__c addRel = [SELECT Name, Account__c, Address__c FROM Address_Relationship__c WHERE Account__c = :acc.Id LIMIT 1];       
   
        try
        { 
            acc.Description = 'TEST';
            addRel.Address__c = newAddr.Id;
            test.startTest();
            update acc;
            delete addRel;
            test.stopTest();
        }
        catch(Exception e)
        {
            System.assert(true);
        }        
    }
    
}