force/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Altair_Exception__c</fullName>
        <label>Altair - Exception</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Altair_Field_Rep__c</fullName>
        <label>Altair - Field Rep</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Altair_Hybrid_Bebe__c</fullName>
        <label>Altair - Hybrid Bebe</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Altair_Key_Account__c</fullName>
        <label>Altair - Key Account</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Altair_Standard__c</fullName>
        <label>Altair Prospect Rep</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Eyefinity_Inside_Sales__c</fullName>
        <label>Eyefinity Inside Sales</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Eyefinity_Outside_Sales__c</fullName>
        <label>Eyefinity Outside Sales</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Global_Business_Development_Manager__c</fullName>
        <label>Global Business Development Manager</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Global_Business_Development_Partner__c</fullName>
        <label>Global Business Development Boundary</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marchon_Close_Out__c</fullName>
        <label>Marchon - Close Out</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marchon_Key_Account__c</fullName>
        <label>Marchon - Key Account</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marchon_Optical__c</fullName>
        <label>Marchon Prospect Rep</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marchon_Retail__c</fullName>
        <label>Marchon Retail</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ophthalmic_Business_Consultant__c</fullName>
        <label>Ophthalmic Business Consultant</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Optics_Contact_Lens_Consultant__c</fullName>
        <label>Optics Contact Lens Consultant</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Optics_Wholesale__c</fullName>
        <label>Optics Business Development Manager</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of Account.</description>
        <inlineHelpText>A = Active 
Inactive = Not a Current Customer of any LOB. 
Closed = Business has ceased operations 
New = In process of becoming an Active account</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Submit for Approval</fullName>
                </value>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Inactive Ownership Change</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
                <value>
                    <fullName>Marked for Deletion</fullName>
                </value>
                <value>
                    <fullName>Archive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>VC_EDS_NA__c</fullName>
        <label>Vision Care Network Administrator</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VC_Relationship_Manager__c</fullName>
        <defaultValue>&quot;PRMI0001&quot;</defaultValue>
        <label>Vision Care Relationship Manager</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force/src/objects/Account_Rep_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Account_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Associated Account ID from Salesforce</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Rep Assignments</relationshipLabel>
        <relationshipName>Account_Rep_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Marketing_Group_Code__c</fullName>
        <description>Brand or Marketing Group Code from SAP</description>
        <label>Brand/Marketing Group Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marketing_Group_Description__c</fullName>
        <description>Brand or Marketing Group Description from SAP</description>
        <label>Brand/Marketing Group Description</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <description>SAP Sales Organization Code</description>
        <label>Sales Org</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Rep__c</fullName>
        <description>Sales Rep SAP Number</description>
        <label>Sales Rep</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Account Rep Assignment</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Account Rep Assignment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Rep Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Altair_SAP_Number__c</fullName>
        <inlineHelpText>Employee&apos;s SAP Number for Sales Org 2110 (Altair).</inlineHelpText>
        <label>Altair SAP User #</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marchon_SAP_Number__c</fullName>
        <inlineHelpText>Employee&apos;s SAP Number for Sales Org 2010 (Marchon).</inlineHelpText>
        <label>Marchon SAP User #</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MarketingID2__c</fullName>
        <label>Additional GAT Sales Territory Code</label>
        <length>22</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MarketingID__c</fullName>
        <label>GAT Sales Territory Code</label>
        <length>22</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force/src/classes/VSPR1_ViewGlobalAccountTeamContrllerTest.cls
/** 
     * Class Name: VSPR1_ViewGlobalAccountTeamContrllerTest
     * @author: Jinky M. N. Salvador
     * Date: 12.JUL.2013 
     * Requirement/Project Name: VSP 
     * @description: Test class for VSPR1_ViewGlobalAccountTeamController.  
     */
@isTest(SeeAllData = true)
public class VSPR1_ViewGlobalAccountTeamContrllerTest {
    
    static testMethod void unitTest() {
        
        Profile profile = [Select id from Profile where Name =: 'System Administrator'];
        
        Account_Rep_Assignment__c rep = new Account_Rep_Assignment__c();
        rep.Marketing_Group_Description__c = 'CALVIN KLEIN';
        rep.Sales_Org__c = '2010';
        rep.Sales_Rep__c = 'DAVID PINA';
        insert rep;        
        
        List<Account_Rep_Assignment__c> lst = new List<Account_Rep_Assignment__c>();
        Map<String, User> userMap = new Map<String, User>();
        
        User user = new User();
        user.LastName = 'Sample User';
        user.Alias = 'sample';
        user.Email = 'sample@sample.com';
        user.Phone = '5129277151';
        user.Username = 'sampleUsername@sample.com';
        user.CommunityNickname = 'sampleNickname';
        user.ProfileId = profile.id;
        user.MarketingID__c = '001';
        user.MarketingID2__c = '002';
        user.TimeZoneSidKey = 'America/Chicago';
        user.LocaleSidKey = 'en_US';
        user.EmailEncodingKey = 'UTF-8';
        user.LanguageLocaleKey = 'en_US';
        user.Marchon_SAP_Number__c = '1808733';
        user.Altair_SAP_Number__c = '2237728';
        insert user;
        
        User user2 = new User();
        user2.LastName = 'Sample User2';
        user2.Alias = 'sample2';
        user2.Email = 'sample2@sample2.com';
        user2.Phone = '5129277152';
        user2.Username = 'sampleUsername2@sample.com';
        user2.CommunityNickname = 'sampleNickname2';
        user2.ProfileId = profile.id;
        user2.MarketingID__c = '001';
        user2.MarketingID2__c = '002';
        user2.TimeZoneSidKey = 'America/Chicago';
        user2.LocaleSidKey = 'en_US';
        user2.EmailEncodingKey = 'UTF-8';
        user2.LanguageLocaleKey = 'en_US';
        user2.Marchon_SAP_Number__c = '1808733';
        user2.Altair_SAP_Number__c = '22377282';
        insert user2;
        
        Account_Rep_Assignment__c accRep = new Account_Rep_Assignment__c();
        userMap.put(accRep.Sales_Rep__c, user);
        
        Account acc = new Account();
        acc.Name = 'Sample Account';
        acc.Status__c = 'New';
        acc.Altair_Standard__c = '001';
        acc.Altair_Field_Rep__c = '001'; 
        acc.Altair_Key_Account__c = '001';
        acc.Altair_Exception__c = '001'; 
        acc.Altair_Hybrid_Bebe__c = '001'; 
//        acc.Ophthalmic_Business_Consultant__c = '001'; 
        acc.Optics_Contact_Lens_Consultant__c = '002'; 
        acc.Marchon_Key_Account__c = '001'; 
        acc.Marchon_Close_Out__c = '001'; 
        acc.Marchon_Optical__c = '001'; 
        acc.Marchon_Retail__c = '001';
        acc.VC_EDS_NA__c = '001'; 
        acc.Global_Business_Development_Manager__c = '001';
        acc.Global_Business_Development_Partner__c = '001';
        acc.VC_Relationship_Manager__c = '001'; // AMITSH 07/09/2015. Request # 1342. Added new field.
        acc.Optics_Wholesale__c = '001'; 
        acc.Eyefinity_Inside_Sales__c = '001'; 
        acc.Eyefinity_Outside_Sales__c = '002';
        insert acc;
        
        Account_Rep_Assignment__c obj1 = new Account_Rep_Assignment__c();
        obj1.Account_ID__c = acc.Id;
        obj1.Sales_Org__c='2110';
        obj1.Sales_Rep__c = '2237728';
        insert obj1;
        
        Account_Rep_Assignment__c obj2 = new Account_Rep_Assignment__c();
        obj2.Account_ID__c = acc.Id;
        obj2.Sales_Org__c='2010';
        obj2.Sales_Rep__c = '22377282';
        insert obj2;
        
        VSPR1_ViewGlobalAccountTeamController.DataWrapper dw = new VSPR1_ViewGlobalAccountTeamController.DataWrapper('abc','abc','abc','abc');
        dw.name = 'abc';
        dw.email = 'abc';
        dw.phone = 'abc';
        dw.mgDesc = 'abc';
        
        PageReference pageRef = Page.VSPR1_ViewGlobalAccountTeam;     
        
        pageRef.getParameters().put('id',acc.id);
        
        System.Test.setCurrentPage(pageRef); 
        //Instantiate and construct the controller class.     
        ApexPages.StandardController sc = new ApexPages.standardController(acc);
        // create an instance of the controller
        VSPR1_ViewGlobalAccountTeamController controller = new VSPR1_ViewGlobalAccountTeamController(sc);
        
        //controller.sapNumberSet.add(accRep.Sales_Rep__c);
        
        controller.Initialize();
        controller.getUsers();     
    }
    
     static testMethod void unitTestallure() {
        
        Profile profile = [Select id from Profile where Name =: 'System Administrator'];
        
        Account_Rep_Assignment__c rep = new Account_Rep_Assignment__c();
        rep.Marketing_Group_Description__c = 'CALVIN KLEIN';
        rep.Sales_Org__c = '2050';
        rep.Sales_Rep__c = 'DAVID PINA';
        insert rep;        
        
        List<Account_Rep_Assignment__c> lst = new List<Account_Rep_Assignment__c>();
        Map<String, User> userMap = new Map<String, User>();
        
        User user = new User();
        user.LastName = 'Sample User';
        user.Alias = 'sample';
        user.Email = 'sample@sample.com';
        user.Phone = '5129277151';
        user.Username = 'sampleUsername@sample.com';
        user.CommunityNickname = 'sampleNickname';
        user.ProfileId = profile.id;
        user.MarketingID__c = '001';
        user.MarketingID2__c = '002';
        user.TimeZoneSidKey = 'America/Chicago';
        user.LocaleSidKey = 'en_US';
        user.EmailEncodingKey = 'UTF-8';
        user.LanguageLocaleKey = 'en_US';
        user.Marchon_SAP_Number__c = '1808733';
        user.Altair_SAP_Number__c = '2237728';
        insert user;
        
        User user2 = new User();
        user2.LastName = 'Sample User2';
        user2.Alias = 'sample2';
        user2.Email = 'sample2@sample2.com';
        user2.Phone = '5129277152';
        user2.Username = 'sampleUsername2@sample.com';
        user2.CommunityNickname = 'sampleNickname2';
        user2.ProfileId = profile.id;
        user2.MarketingID__c = '001';
        user2.MarketingID2__c = '002';
        user2.TimeZoneSidKey = 'America/Chicago';
        user2.LocaleSidKey = 'en_US';
        user2.EmailEncodingKey = 'UTF-8';
        user2.LanguageLocaleKey = 'en_US';
        user2.Marchon_SAP_Number__c = '1808733';
        user2.Altair_SAP_Number__c = '22377282';
        insert user2;
        
        Account_Rep_Assignment__c accRep = new Account_Rep_Assignment__c();
        userMap.put(accRep.Sales_Rep__c, user);
        
        Account acc = new Account();
        acc.Name = 'Sample Account';
        acc.Status__c = 'New';
        acc.Altair_Standard__c = '001';
        acc.Altair_Field_Rep__c = '001'; 
        acc.Altair_Key_Account__c = '001';
        acc.Altair_Exception__c = '001'; 
        acc.Altair_Hybrid_Bebe__c = '001'; 
//        acc.Ophthalmic_Business_Consultant__c = '001'; 
        acc.Optics_Contact_Lens_Consultant__c = '002'; 
        acc.Marchon_Key_Account__c = '001'; 
        acc.Marchon_Close_Out__c = '001'; 
        acc.Marchon_Optical__c = '001'; 
        acc.Marchon_Retail__c = '001';
        acc.VC_EDS_NA__c = '001'; 
        acc.Global_Business_Development_Manager__c = '001';
        acc.Global_Business_Development_Partner__c = '001';
        acc.VC_Relationship_Manager__c = '001'; // AMITSH 07/09/2015. Request # 1342. Added new field.
        acc.Optics_Wholesale__c = '001'; 
        acc.Eyefinity_Inside_Sales__c = '001'; 
        acc.Eyefinity_Outside_Sales__c = '002';
        insert acc;
        
        Account_Rep_Assignment__c obj1 = new Account_Rep_Assignment__c();
        obj1.Account_ID__c = acc.Id;
        obj1.Sales_Org__c='2050';
        obj1.Sales_Rep__c = '2237728';
        insert obj1;
        
        Account_Rep_Assignment__c obj2 = new Account_Rep_Assignment__c();
        obj2.Account_ID__c = acc.Id;
        obj2.Sales_Org__c='2050';
        obj2.Sales_Rep__c = '22377282';
        insert obj2;
        
        VSPR1_ViewGlobalAccountTeamController.DataWrapper dw = new VSPR1_ViewGlobalAccountTeamController.DataWrapper('abc','abc','abc','abc');
        dw.name = 'abc';
        dw.email = 'abc';
        dw.phone = 'abc';
        dw.mgDesc = 'abc';
        
        PageReference pageRef = Page.VSPR1_ViewGlobalAccountTeam;     
        
        pageRef.getParameters().put('id',acc.id);
        
        System.Test.setCurrentPage(pageRef); 
        //Instantiate and construct the controller class.     
        ApexPages.StandardController sc = new ApexPages.standardController(acc);
        // create an instance of the controller
        VSPR1_ViewGlobalAccountTeamController controller = new VSPR1_ViewGlobalAccountTeamController(sc);
        
        //controller.sapNumberSet.add(accRep.Sales_Rep__c);
        
        controller.Initialize();
        controller.getUsers();     
    }
    
       static testMethod void unitTestaltair() {
        
        Profile profile = [Select id from Profile where Name =: 'System Administrator'];
        
        Account_Rep_Assignment__c rep = new Account_Rep_Assignment__c();
        rep.Marketing_Group_Description__c = 'CALVIN KLEIN';
        rep.Sales_Org__c = '2050';
        rep.Sales_Rep__c = 'DAVID PINA';
        insert rep;        
        
        List<Account_Rep_Assignment__c> lst = new List<Account_Rep_Assignment__c>();
        Map<String, User> userMap = new Map<String, User>();
        
        User user = new User();
        user.LastName = 'Sample User';
        user.Alias = 'sample';
        user.Email = 'sample@sample.com';
        user.Phone = '5129277151';
        user.Username = 'sampleUsername@sample.com';
        user.CommunityNickname = 'sampleNickname';
        user.ProfileId = profile.id;
        user.MarketingID__c = '001';
        user.MarketingID2__c = '002';
        user.TimeZoneSidKey = 'America/Chicago';
        user.LocaleSidKey = 'en_US';
        user.EmailEncodingKey = 'UTF-8';
        user.LanguageLocaleKey = 'en_US';
        user.Marchon_SAP_Number__c = '1808733';
        user.Altair_SAP_Number__c = '2237728';
        insert user;
        
        User user2 = new User();
        user2.LastName = 'Sample User2';
        user2.Alias = 'sample2';
        user2.Email = 'sample2@sample2.com';
        user2.Phone = '5129277152';
        user2.Username = 'sampleUsername2@sample.com';
        user2.CommunityNickname = 'sampleNickname2';
        user2.ProfileId = profile.id;
        user2.MarketingID__c = '001';
        user2.MarketingID2__c = '002';
        user2.TimeZoneSidKey = 'America/Chicago';
        user2.LocaleSidKey = 'en_US';
        user2.EmailEncodingKey = 'UTF-8';
        user2.LanguageLocaleKey = 'en_US';
        user2.Marchon_SAP_Number__c = '1808733';
        user2.Altair_SAP_Number__c = '22377282';
        insert user2;
        
        Account_Rep_Assignment__c accRep = new Account_Rep_Assignment__c();
        userMap.put(accRep.Sales_Rep__c, user);
        
        Account acc = new Account();
        acc.Name = 'Sample Account';
        acc.Status__c = 'New';
        acc.Altair_Standard__c = '001';
        acc.Altair_Field_Rep__c = '001'; 
        acc.Altair_Key_Account__c = '001';
        acc.Altair_Exception__c = '001'; 
        acc.Altair_Hybrid_Bebe__c = '001'; 
//        acc.Ophthalmic_Business_Consultant__c = '001'; 
        acc.Optics_Contact_Lens_Consultant__c = '002'; 
        acc.Marchon_Key_Account__c = '001'; 
        acc.Marchon_Close_Out__c = '001'; 
        acc.Marchon_Optical__c = '001'; 
        acc.Marchon_Retail__c = '001';
        acc.VC_EDS_NA__c = '001'; 
        acc.Global_Business_Development_Manager__c = '001';
        acc.Global_Business_Development_Partner__c = '001';
        acc.VC_Relationship_Manager__c = '001'; // AMITSH 07/09/2015. Request # 1342. Added new field.
        acc.Optics_Wholesale__c = '001'; 
        acc.Eyefinity_Inside_Sales__c = '001'; 
        acc.Eyefinity_Outside_Sales__c = '002';
        insert acc;
        
        Account_Rep_Assignment__c obj1 = new Account_Rep_Assignment__c();
        obj1.Account_ID__c = acc.Id;
        obj1.Sales_Org__c='2050';
        obj1.Marketing_Group_Code__c = 'ALT';
        obj1.Sales_Rep__c = '2237728';
        insert obj1;
        
        Account_Rep_Assignment__c obj2 = new Account_Rep_Assignment__c();
        obj2.Account_ID__c = acc.Id;
        obj2.Sales_Org__c='2050';
        obj2.Marketing_Group_Code__c = 'ALT';
        obj2.Sales_Rep__c = '22377282';
        insert obj2;
        
        VSPR1_ViewGlobalAccountTeamController.DataWrapper dw = new VSPR1_ViewGlobalAccountTeamController.DataWrapper('abc','abc','abc','abc');
        dw.name = 'abc';
        dw.email = 'abc';
        dw.phone = 'abc';
        dw.mgDesc = 'abc';
        
        PageReference pageRef = Page.VSPR1_ViewGlobalAccountTeam;     
        
        pageRef.getParameters().put('id',acc.id);
        
        System.Test.setCurrentPage(pageRef); 
        //Instantiate and construct the controller class.     
        ApexPages.StandardController sc = new ApexPages.standardController(acc);
        // create an instance of the controller
        VSPR1_ViewGlobalAccountTeamController controller = new VSPR1_ViewGlobalAccountTeamController(sc);
        
        //controller.sapNumberSet.add(accRep.Sales_Rep__c);
        
        controller.Initialize();
        controller.getUsers();     
    }
}