force/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Dispense_Materials__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Dispense Materials</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Eyefinity_Access__c</fullName>
        <label>Eyefinity Access</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>B - Basic</fullName>
                </value>
                <value>
                    <fullName>J - Participates in E-Claim</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fee_Calculation_Code__c</fullName>
        <label>Fee Calculation Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>O - Old Calculated Fee Schedule</fullName>
                </value>
                <value>
                    <fullName>N - New Calculated Fee Schedule</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IRS_Name__c</fullName>
        <label>IRS Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IRS_Tax_ID__c</fullName>
        <encrypted>true</encrypted>
        <label>IRS Tax ID</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location_Type__c</fullName>
        <label>Location Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>M - VSP Member Location</fullName>
                </value>
                <value>
                    <fullName>A - Affiliate Provider Location</fullName>
                </value>
                <value>
                    <fullName>F - Laser Vision Correction (LVC)</fullName>
                </value>
                <value>
                    <fullName>X - Client Authorized Location (GAP)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Distribution__c</fullName>
        <description>Vision Care Practice receives one total payment or individual payments for each Business Account</description>
        <label>Payment Distribution</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Practice Account</fullName>
                </value>
                <value>
                    <fullName>Business Account(s)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Practice_Business_Type__c</fullName>
        <label>Practice Business Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>S - Sole Proprietor</fullName>
                </value>
                <value>
                    <fullName>C - Corporation</fullName>
                </value>
                <value>
                    <fullName>F - Laser Vision Correction</fullName>
                </value>
                <value>
                    <fullName>P - Partnership</fullName>
                </value>
                <value>
                    <fullName>U - Optometric School or University</fullName>
                </value>
                <value>
                    <fullName>V - Affiliate Provider</fullName>
                </value>
                <value>
                    <fullName>W - Applicant Doctor</fullName>
                </value>
                <value>
                    <fullName>X - Group Authorized Provider</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of Account.</description>
        <inlineHelpText>A = Active 
Inactive = Not a Current Customer of any LOB. 
Closed = Business has ceased operations 
New = In process of becoming an Active account</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Submit for Approval</fullName>
                </value>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Inactive Ownership Change</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
                <value>
                    <fullName>Marked for Deletion</fullName>
                </value>
                <value>
                    <fullName>Archive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tax_ID__c</fullName>
        <description>Account Tax ID.</description>
        <encrypted>true</encrypted>
        <inlineHelpText>Account Tax ID.</inlineHelpText>
        <label>Tax ID</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Care_Effective_Date__c</fullName>
        <label>Vision Care Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Care_Location_Phone_Number__c</fullName>
        <label>Vision Care Location Phone Number</label>
        <type>Phone</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CAQH_ID__c</fullName>
        <label>CAQH ID</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <formula>HYPERLINK(&quot;/&quot; + Id, &quot;Contact Record&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Record</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Degree__c</fullName>
        <description>The educational degree of the Vision Care Doctor.</description>
        <inlineHelpText>The educational degree of the Vision Care Doctor.</inlineHelpText>
        <label>Degree</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>OD</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>DO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Doctor_ID__c</fullName>
        <encrypted>true</encrypted>
        <label>Doctor ID</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Doctor_Type__c</fullName>
        <label>Doctor Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>M - VSP Member Doctor</fullName>
                </value>
                <value>
                    <fullName>A - Affiliate Provider</fullName>
                </value>
                <value>
                    <fullName>F - Laser Vision Correction (LVC)</fullName>
                </value>
                <value>
                    <fullName>S - School Faculty Provider</fullName>
                </value>
                <value>
                    <fullName>X - Client Authorized Provider (GAP)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NPI__c</fullName>
        <description>National Provider Indicator for a Vision Care Doctor.</description>
        <inlineHelpText>National Provider Indicator for a Vision Care Doctor.</inlineHelpText>
        <label>NPI</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Status of Contact.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vision_Care_Effective_Date__c</fullName>
        <label>Vision Care Effective Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force/src/objects/Contact_Role__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Eye Care Professional</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Fee_Calculation_Code__c</fullName>
        <formula>LEFT(TEXT( Account__r.Parent.Fee_Calculation_Code__c ), 1)</formula>
        <label>Fee Calculation Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accounting</fullName>
                </value>
                <value>
                    <fullName>Board Member/ Officer</fullName>
                </value>
                <value>
                    <fullName>Dean</fullName>
                </value>
                <value>
                    <fullName>Doctor-Employee</fullName>
                </value>
                <value>
                    <fullName>Doctor-Owner</fullName>
                </value>
                <value>
                    <fullName>Doctor-Unspecified</fullName>
                </value>
                <value>
                    <fullName>Group Administrator</fullName>
                </value>
                <value>
                    <fullName>Lab Technician</fullName>
                </value>
                <value>
                    <fullName>Member</fullName>
                </value>
                <value>
                    <fullName>Office Administration</fullName>
                </value>
                <value>
                    <fullName>Office Manager</fullName>
                </value>
                <value>
                    <fullName>Optical Buyer</fullName>
                </value>
                <value>
                    <fullName>Optical Manager</fullName>
                </value>
                <value>
                    <fullName>Optician</fullName>
                </value>
                <value>
                    <fullName>Optician-Owner</fullName>
                </value>
                <value>
                    <fullName>Owner</fullName>
                </value>
                <value>
                    <fullName>Student</fullName>
                </value>
                <value>
                    <fullName>Unspecified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force/src/objects/General_Table__c.object
<CustomObject>
    <fields>
        <fullName>Code_Description__c</fullName>
        <label>Code Description</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Table__c</fullName>
        <label>Table</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>General Table</label>
    <nameField>
        <label>Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>General Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force/src/objects/Network_Relationship__c.object
<CustomObject>
    <description>Custom object to track Payment Relationships between doctors and offices.</description>
    <fields>
        <fullName>Contact_Role__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact Role</label>
        <referenceTo>Contact_Role__c</referenceTo>
        <relationshipName>Payment_Relationships</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Doctor_ID__c</fullName>
        <description>Doctor ID of associated Contact record</description>
        <label>Doctor ID</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <label>Network Relationship</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Network Relationship Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Network Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force/src/classes/VSPR19b_restrictOverlappingNR_Test.cls
@isTest
public class VSPR19b_restrictOverlappingNR_Test {

    @testSetup
    static void testData(){
       
        	User mike = new User();
              mike.Username= 'mike.white911@company.com';
              mike.Email = 'mike.white911@company.com';
              mike.Lastname = 'mike';
              mike.Firstname = 'white';
              mike.Alias = 'mwhite';
              mike.CommunityNickname = 'mwhite01';
              mike.ProfileId = [ select id, name from profile where name = 'VSP Network Recruitment User' ].Id;                         
              mike.TimeZoneSidKey = 'GMT';
              mike.LocaleSidKey = 'en_US';
              mike.EmailEncodingKey = 'ISO-8859-1';
              mike.LanguageLocaleKey = 'en_US';
              insert mike;
        
         List<User> userX = [SELECT Id FROM User WHERE LastName = 'mike'];
        
         system.Assert(userX.size() == 1);
        
          
              // Insert Account Practice Account
            Account pa = new Account();
            pa.Name = 'testPracAccount';
            pa.RecordTypeId = [SELECT Id FROM RecordType WHERE Name = 'Practice Account' AND SObjectType = 'Account'].Id;
            pa.ShippingStreet = '123 Main Street';
            pa.ShippingCity = 'Rancho Cordova';
            pa.ShippingState = 'CA';
            pa.ShippingPostalCode = '95670';
            pa.Vision_Care_Effective_Date__c = date.today();
            pa.IRS_Name__c = 'testPracAccount';
            pa.Tax_ID__c = '555112222';
            pa.IRS_Tax_ID__c = '555112222';
            pa.Practice_Business_Type__c = 'S - Sole Proprietor';
            pa.Fee_Calculation_Code__c = 'O - Old Calculated Fee Schedule';
            pa.Payment_Distribution__c = 'Business Account(s)';
            insert pa;
            List<Account> acctPa = [SELECT Id FROM Account WHERE Id =: pa.Id];
            system.AssertEquals(acctPa.size(),1);
            
            //Insert New Business Account
            Account ba = new Account();
            ba.Name = 'testbizAccount';
            ba.RecordTypeId = [SELECT Id FROM RecordType WHERE Name = 'Business Account' AND SObjectType = 'Account'].Id;
            ba.ParentId = pa.Id;
            ba.Vision_Care_Effective_Date__c = date.today();
            ba.Vision_Care_Location_Phone_Number__c = '(916) 851-4444';
            ba.Eyefinity_Access__c = 'B - Basic';
            ba.Location_Type__c = 'M - VSP Member Location';
            ba.Dispense_Materials__c = true;
            
            
            insert ba;
            List<Account> acctba = [SELECT Id FROM Account WHERE Id =: ba.Id];
            system.AssertEquals(acctba.size(),1);


            
            // Insert Contact
            Contact c = new Contact();
            c.FirstName = 'Rogers';
            c.LastName = 'Hornsby';
            c.NPI__c = '1245653781';
            c.Degree__c = 'OD';
            c.CAQH_ID__c = '123456679';
            c.Doctor_ID__c = '555112333';
            c.Doctor_Type__c = 'M - VSP Member Doctor';
            c.Vision_Care_Effective_Date__c = date.today();
            c.AccountId = ba.Id;
            insert c;

            List<Contact> contX = [SELECT Id FROM Contact WHERE Id =: c.Id];

            system.AssertEquals(contX.size(),1);
            
            Contact_Role__c cr = new Contact_Role__c();
            cr.Type__c = 'Doctor-Owner';
            cr.Start_Date__c = date.today();
            //cr.End_Date__c = date.newInstance(2017,12,31);
            cr.Account__c = ba.Id;
            cr.Contact__c = c.Id;
            cr.Type__c = 'Doctor-Employee';
            insert cr;

            List<Contact_Role__c> controleX = [SELECT Id FROM Contact_Role__c WHERE Id =: cr.Id];

            system.AssertEquals(controleX.size(),1);
            
            General_Table__c gt = new General_Table__c();
            gt.Name = 'TEST11';
            gt.Code_Description__c = 'test5107';
            gt.Table__c = 'PRSP';
            gt.Status__c = 'Active';
            insert gt;

            List<General_Table__c> gentableX = [SELECT Id FROM General_Table__c WHERE Id =: gt.Id];

            system.AssertEquals(gentableX.size(),1);
            test.StartTest();
            Network_Relationship__c nr = new Network_Relationship__c();
            nr.Contact_Role__c = cr.Id;
            nr.Account_Name__c = ba.id;
            nr.Provider_Name__c = c.id;
            nr.Program_ID__c = gt.Id;
            nr.Program_Effective_Date__c = date.today().addMonths(2);
            nr.Program_End_Date__c = date.today().addMonths(6);
            insert nr;
            
            
            nr.Program_Effective_Date__c = date.today();
            nr.Program_End_Date__c = null;
            
             update nr;
            test.stopTest();
            List<Network_Relationship__c> netrelX = [SELECT Id FROM Network_Relationship__c WHERE Id =: nr.Id];

            system.Assert(netrelX.size() == 1);
    }
    
    static testMethod void unitTest_restrictOverlappingNR(){
        
        
   
        User userMike = [SELECT Id FROM User WHERE Lastname = 'mike'];
        System.runAs(userMike ) {
            
            Id crX = [SELECT Id FROM Contact_Role__c].Id;
            Id gtX = [SELECT Id FROM General_Table__c].Id;
            
            
            test.StartTest();
            
            try{
                Network_Relationship__c nr2 = new Network_Relationship__c();
                nr2.Contact_Role__c = crX;
                nr2.Program_ID__c = gtX;
                nr2.Program_Effective_Date__c = date.today();
                nr2.Program_End_Date__c = date.today().addMonths(6);
                insert nr2;
                
               
            }

            catch(Exception e){
    
                Boolean expectedExceptionThrown =  e.getMessage().contains('Network Relationship effective dates must not overlap with existing Network Relationship records.') ? true : false;
    
                System.AssertEquals(expectedExceptionThrown, true);
    
            }
            test.StopTest();
        }    
    }
    
}