force/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <description>For Practice and Business accounts so that the data can be populated for use in premier tier calculation.
Population on Business account will be manual or through data loader.</description>
        <inlineHelpText>Identifies the location&apos;s relationship with VSP for Premier Tiering</inlineHelpText>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Affiliate</fullName>
                </value>
                <value>
                    <fullName>AOP</fullName>
                </value>
                <value>
                    <fullName>CAT2</fullName>
                </value>
                <value>
                    <fullName>Conflict</fullName>
                </value>
                <value>
                    <fullName>GAP</fullName>
                </value>
                <value>
                    <fullName>Independent</fullName>
                </value>
                <value>
                    <fullName>LVC</fullName>
                </value>
                <value>
                    <fullName>Near Site</fullName>
                </value>
                <value>
                    <fullName>Net Dev Excluded</fullName>
                </value>
                <value>
                    <fullName>Net Dev Purchasing Requirement</fullName>
                </value>
                <value>
                    <fullName>Not Supported</fullName>
                </value>
                <value>
                    <fullName>Onsite</fullName>
                </value>
                <value>
                    <fullName>Pearle Vision CO</fullName>
                </value>
                <value>
                    <fullName>Pearle Vision LO</fullName>
                </value>
                <value>
                    <fullName>Pop Up</fullName>
                </value>
                <value>
                    <fullName>Rollup</fullName>
                </value>
                <value>
                    <fullName>School</fullName>
                </value>
                <value>
                    <fullName>VSP Retail</fullName>
                </value>
                <value>
                    <fullName>VSP Ventures</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Eyewear_Location_Spend_LTM__c</fullName>
        <inlineHelpText>Location&apos;s spend on Eyewear in the last 12 months</inlineHelpText>
        <label>Eyewear Location Spend LTM</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Optics_Location_Spend_LTM__c</fullName>
        <inlineHelpText>Location&apos;s spend on Optics in the last 12 months</inlineHelpText>
        <label>Optics Location Spend LTM</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Participation_Exclusions__c</fullName>
        <label>Participation Exclusions</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ADMCD – Opts out of Medicaid All Doctors</fullName>
                    <label>ADMCD – Opts out of Medicaid All Doctor</label>
                </value>
                <value>
                    <fullName>NODIS – Opts out of discounts</fullName>
                </value>
                <value>
                    <fullName>NOMCR – Opts out of Medicare</fullName>
                </value>
                <value>
                    <fullName>NOCNT – Opts out of providing contacts</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Location_Spend_LTM__c</fullName>
        <inlineHelpText>Location&apos;s spend on Eyewear and Optics in the last 12 months</inlineHelpText>
        <label>Total Location Spend LTM</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>VC__c</fullName>
        <formula>IF( Vision_Care_Effective_Date__c &lt;= TODAY()  &amp;&amp; (Vision_Care_End_Date__c &gt;=TODAY() ||  ISBLANK(Vision_Care_End_Date__c)) , TRUE, FALSE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>VC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vision_Care_Effective_Date__c</fullName>
        <label>Vision Care Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Care_End_Date__c</fullName>
        <label>Vision Care End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Care_Good_Standing__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is account in good standing with Vision Care.</description>
        <inlineHelpText>Is account in good standing with Vision Care.</inlineHelpText>
        <label>Vision Care Good Standing</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Exception_handler_Email__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Exception Handler Email</label>
</CustomObject>

src/objects/Global_Rewards_Group__c.object
<CustomObject>
    <description>Parent object in a relationship that groups multiple Business/Practice Accounts under one Global Rewards Program (child object is Global Rewards Group Relationship)</description>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Affiliate</fullName>
                </value>
                <value>
                    <fullName>AOP</fullName>
                </value>
                <value>
                    <fullName>CAT2</fullName>
                </value>
                <value>
                    <fullName>Conflict</fullName>
                </value>
                <value>
                    <fullName>GAP</fullName>
                </value>
                <value>
                    <fullName>Independent</fullName>
                </value>
                <value>
                    <fullName>LVC</fullName>
                </value>
                <value>
                    <fullName>Near Site</fullName>
                </value>
                <value>
                    <fullName>Net Dev Excluded</fullName>
                </value>
                <value>
                    <fullName>Net Dev Purchasing Requirement</fullName>
                </value>
                <value>
                    <fullName>Not Supported</fullName>
                </value>
                <value>
                    <fullName>Onsite</fullName>
                </value>
                <value>
                    <fullName>Pearle Vision CO</fullName>
                </value>
                <value>
                    <fullName>Pearle Vision LO</fullName>
                </value>
                <value>
                    <fullName>Pop Up</fullName>
                </value>
                <value>
                    <fullName>Rollup</fullName>
                </value>
                <value>
                    <fullName>School</fullName>
                </value>
                <value>
                    <fullName>VSP Retail</fullName>
                </value>
                <value>
                    <fullName>VSP Ventures</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Global Rewards Groups</relationshipLabel>
        <relationshipName>Global_Rewards_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Care_Good_Standing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Vision Care Good Standing</label>
        <type>Checkbox</type>
    </fields>
    <label>Global Rewards Group</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Global Rewards Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Global Rewards Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Global_Rewards_Group_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Child_Account__c</fullName>
        <label>Child Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Global Rewards Group Relationships</relationshipLabel>
        <relationshipName>Global_Rewards_Group_Relationships</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>Date the child record was ended its relationship with the Parent Roll up account.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Global_Rewards_Group__c</fullName>
        <label>Global Rewards Group</label>
        <referenceTo>Global_Rewards_Group__c</referenceTo>
        <relationshipLabel>Global Rewards Group Relationships</relationshipLabel>
        <relationshipName>Global_Rewards_Group</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Date the child record was added to the Parent Roll up account.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Global Rewards Group Relationship</label>
    <nameField>
        <displayFormat>PREMIER-{0000}</displayFormat>
        <label>Global Rewards Group Relationship ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Global Rewards Group Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/VSPR31_Bus_Acc_Tier_Upd_No_Actv_Test.cls
@isTest
//Test class for VSPR31_Bus_Acc_Tier_Upd_Not_Actv_Batch
public class VSPR31_Bus_Acc_Tier_Upd_No_Actv_Test {
    @testSetup
    public static void testdata(){
        Id baRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
        Id grpContractRecordTypeId = Schema.SObjectType.Global_Rewards_Group__c.getRecordTypeInfosByName().get('Contract Type').getRecordTypeId();
        
        Test.startTest();
        Account ba1 = new Account();
        ba1.RecordTypeId = baRecordTypeId;
        ba1.Name = 'BA Test 1234';
        //ba1.ParentId = pa1.Id;
        ba1.Contract_Type__c = 'Affiliate';
        ba1.Vision_Care_Good_Standing__c = True;
        ba1.Total_Location_Spend_LTM__c = 100;
        ba1.Eyewear_Location_Spend_LTM__c = 100;
        ba1.Optics_Location_Spend_LTM__c = 100;
        ba1.Participation_Exclusions__c = 'NODIS – Opts out of discounts';
        //VC__C is a formula field on the Account
        //IF( Vision_Care_Effective_Date__c <= TODAY() && (Vision_Care_End_Date__c >=TODAY() || ISBLANK(Vision_Care_End_Date__c)) , TRUE, FALSE)
        ba1.Vision_Care_Effective_Date__c = system.today() - 3; 
        
        insert ba1;
        
        Global_Rewards_Group__c grg = new Global_Rewards_Group__c();
        grg.RecordTypeId = grpContractRecordTypeId;
        grg.Name = 'TESTGRP';
        grg.Parent_Account__c = ba1.Id;
        
        insert grg;
        
        Global_Rewards_Group_Relationship__c grgr = new Global_Rewards_Group_Relationship__c();
        grgr.Active__c = True;
        grgr.Child_Account__c = ba1.Id;
        grgr.End_Date__c = system.today();
        grgr.Global_Rewards_Group__c = grg.Id;
        grgr.Start_Date__c = system.today()-10;
        
        insert grgr; 
        
        //Used to test the exception in the class
        Exception_handler_Email__c toAddress = new Exception_handler_Email__c();
        toAddress.Name = 'test@vsp.com';
        insert toAddress;
    }
    @isTest
    public static void noActiveGRGRTest(){
        Test.startTest();
        Account baGet = [SELECT Id, Name, Vision_Care_Good_Standing__c FROM Account WHERE Name = 'BA Test 1234' LIMIT 1];
        
        Global_Rewards_Group__c grgGet = [SELECT Id, RecordTypeId, Name, Parent_Account__c FROM Global_Rewards_Group__c WHERE Parent_Account__c =: baGet.Id LIMIT 1];
        Global_Rewards_Group_Relationship__c grgrGet = [SELECT Id, Child_Account__c, Global_Rewards_Group__c, End_Date__c FROM Global_Rewards_Group_Relationship__c
                                                                 WHERE Global_Rewards_Group__c =: grgGet.Id AND Child_Account__c =: baGet.Id];
        Set<Id> grgIdSet = new Set<Id>();
        grgIdSet.add(grgGet.Id);
        
        VSPR31_Bus_Acc_Tier_Upd_Not_Actv_Batch ba = new VSPR31_Bus_Acc_Tier_Upd_Not_Actv_Batch(grgIdSet);  
        Database.executeBatch(ba,10);
        
        Test.stopTest();
        Date TodayDate = Date.today();
        System.assertEquals(TodayDate, grgrGet.End_Date__c);
    }
}