force/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <formula>HYPERLINK(&quot;/&quot; + Id, &quot;Contact Record&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Record</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marketing_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>The contact&apos;s name used for Marketing Campaigns.</inlineHelpText>
        <label>Marketing Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Contact_Role__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Eye Care Professional</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <encryptionScheme>None</encryptionScheme>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accounting</fullName>
                </value>
                <value>
                    <fullName>Board Member/ Officer</fullName>
                </value>
                <value>
                    <fullName>Dean</fullName>
                </value>
                <value>
                    <fullName>Doctor-Employee</fullName>
                </value>
                <value>
                    <fullName>Doctor-Owner</fullName>
                </value>
                <value>
                    <fullName>Doctor-Unspecified</fullName>
                </value>
                <value>
                    <fullName>Group Administrator</fullName>
                </value>
                <value>
                    <fullName>Lab Technician</fullName>
                </value>
                <value>
                    <fullName>Member</fullName>
                </value>
                <value>
                    <fullName>Office Administration</fullName>
                </value>
                <value>
                    <fullName>Office Manager</fullName>
                </value>
                <value>
                    <fullName>Optical Buyer</fullName>
                </value>
                <value>
                    <fullName>Optical Manager</fullName>
                </value>
                <value>
                    <fullName>Optician</fullName>
                </value>
                <value>
                    <fullName>Optician-Owner</fullName>
                </value>
                <value>
                    <fullName>Owner</fullName>
                </value>
                <value>
                    <fullName>Student</fullName>
                </value>
                <value>
                    <fullName>Unspecified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/VSPR5_ContactVFPTest.cls
@isTest(SeeAllData=true)
public class VSPR5_ContactVFPTest {
static testMethod void VSPR5_ContactVFP_Test()
{
//Test converage for the myPage visualforce page
PageReference pageRef = Page.VSPR5_ContactVFP;
Test.setCurrentPageReference(pageRef);

    
//Create Account
Account ac = new Account (name='XYZ Organization');
ac.Name = 'XYZ Organization';
ac.Email__c = 'francisbenzon@gmail.com';
ac.Phone = '3634582';
ac.Fax = '123456';
ac.Website = 'www.google.com';
insert ac;


//Create Contact

//insert c;
/*    
Contact c2 = new Contact(
    LastName = 'Test',
    Marketing_Name__c = 'Test',
    AccountId = ac.id
);
insert c2;

Contact_Role__c cRole = new Contact_Role__c();
cRole.Type__c = 'Accounting';
cRole.Start_Date__c = system.today();
cRole.Account__c = c.AccountId;
cRole.Contact__c = c.id;
insert cRole;
    

    
    Marketing_Name__c = 'Test',
    AccountId = ac.id
);
*/
    
    Contact c = new Contact();
    c.LastName = 'Test';
    c.Marketing_Name__c = 'Test';
    c.AccountId = ac.id;
   
   
    
    Contact c2 = new Contact();
    c2.LastName = 'Test';
    c2.Marketing_Name__c = 'Test';
    c2.AccountId = ac.id;
    
    Contact c3 = new Contact();
    c3.Marketing_Name__c = 'Test';
    c3.AccountId = ac.id;
    
   
    
ApexPages.StandardController sc = new ApexPages.standardController(c);
    
// create an instance of the controller
VSPR5_ContactExtensionController ExtensionControllerTest = new VSPR5_ContactExtensionController(sc);

    
    
ApexPages.StandardController sc2 = new ApexPages.standardController(c2);
// create an instance of the controller
VSPR5_ContactExtensionController ExtensionControllerTest2 = new VSPR5_ContactExtensionController(sc2);  
    
ApexPages.StandardController sc3 = new ApexPages.standardController(c3);
// create an instance of the controller
VSPR5_ContactExtensionController ExtensionControllerTest4 = new VSPR5_ContactExtensionController(sc3);       
           

        Test.startTest();
        Test.setCurrentPage(Page.VSPR5_ContactVFP);
        
        PageReference pagereferenceTest = ExtensionControllerTest2.save();
        PageReference pagereferenceTest2 = ExtensionControllerTest.cancel(); 
        PageReference pagereferenceTest3 = ExtensionControllerTest.doSaveAndNew();
        PageReference pagereferenceTest4 = ExtensionControllerTest4.save();    
        System.assert(true);
        Test.stopTest();
        
        

}

}