force/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of Account.</description>
        <inlineHelpText>A = Active 
Inactive = Not a Current Customer of any LOB. 
Closed = Business has ceased operations 
New = In process of becoming an Active account</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Submit for Approval</fullName>
                </value>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Inactive Ownership Change</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
                <value>
                    <fullName>Marked for Deletion</fullName>
                </value>
                <value>
                    <fullName>Archive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Birthdate__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Birthdate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Marketing_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>The contact&apos;s name used for Marketing Campaigns.</inlineHelpText>
        <label>Marketing Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Status of Contact.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/classes/VSPR1_AccountTest.cls
/** 
     * Class Name: VSPR1_AccountTest
     * @author: karl.wilson.l.tan
     * Date: 12.JUL.2013 
     * Requirement/Project Name: VSP 
     * @description: Test class for VSPR1_Account class.  
     */
@isTest

public with sharing class VSPR1_AccountTest {
    static testMethod void submitApprovalRequest() {
        // Insert an account
        
      RecordType rType = [Select id from RecordType where Name =: 'Pending Account'];
      Profile profile = [Select id from Profile where Name =: 'System Administrator'];
      
      Account a = new Account();
      a.Name = 'Test Sample';
      a.Status__c = 'New';
      insert a;
      
    Contact c = new Contact();
    c.AccountId = a.id;
    c.LastName = 'Sample Contact';
    c.Status__c = 'Active';
    c.Birthdate__c = system.today();
    c.Marketing_Name__c = 'lRak';
    insert c;
    
    update a;   
       
        //Approval.ProcessSubmitRequest reqApp = new Approval.ProcessSubmitRequest();
        //reqApp.setComments('Submitting request for approval.');
        //reqApp.setObjectId(a.id);
        
      
       //Approval.ProcessResult result = Approval.process(reqApp);
        
        
        
    
    }
}