force/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <description>For Practice and Business accounts so that the data can be populated for use in premier tier calculation.
Population on Business account will be manual or through data loader.</description>
        <inlineHelpText>Identifies the location&apos;s relationship with VSP for Premier Tiering</inlineHelpText>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Affiliate</fullName>
                </value>
                <value>
                    <fullName>AOP</fullName>
                </value>
                <value>
                    <fullName>CAT2</fullName>
                </value>
                <value>
                    <fullName>Conflict</fullName>
                </value>
                <value>
                    <fullName>GAP</fullName>
                </value>
                <value>
                    <fullName>Independent</fullName>
                </value>
                <value>
                    <fullName>LVC</fullName>
                </value>
                <value>
                    <fullName>Near Site</fullName>
                </value>
                <value>
                    <fullName>Net Dev Excluded</fullName>
                </value>
                <value>
                    <fullName>Net Dev Purchasing Requirement</fullName>
                </value>
                <value>
                    <fullName>Not Supported</fullName>
                </value>
                <value>
                    <fullName>Onsite</fullName>
                </value>
                <value>
                    <fullName>Pearle Vision CO</fullName>
                </value>
                <value>
                    <fullName>Pearle Vision LO</fullName>
                </value>
                <value>
                    <fullName>Pop Up</fullName>
                </value>
                <value>
                    <fullName>Rollup</fullName>
                </value>
                <value>
                    <fullName>School</fullName>
                </value>
                <value>
                    <fullName>VSP Retail</fullName>
                </value>
                <value>
                    <fullName>VSP Ventures</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Eyewear_Location_Spend_LTM__c</fullName>
        <inlineHelpText>Location&apos;s spend on Eyewear in the last 12 months</inlineHelpText>
        <label>Eyewear Location Spend LTM</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Optics_Location_Spend_LTM__c</fullName>
        <inlineHelpText>Location&apos;s spend on Optics in the last 12 months</inlineHelpText>
        <label>Optics Location Spend LTM</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Participation_Exclusions__c</fullName>
        <label>Participation Exclusions</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ADMCD – Opts out of Medicaid All Doctors</fullName>
                    <label>ADMCD – Opts out of Medicaid All Doctor</label>
                </value>
                <value>
                    <fullName>NODIS – Opts out of discounts</fullName>
                </value>
                <value>
                    <fullName>NOMCR – Opts out of Medicare</fullName>
                </value>
                <value>
                    <fullName>NOCNT – Opts out of providing contacts</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Premier_Tax_ID_Roll_Up_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Indicates whether an Account is being evaluated for Premier qualification in conjunction with other accounts with different Tax ID&apos;s.</inlineHelpText>
        <label>Tax ID Roll Up Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Offering_s__c</fullName>
        <label>Service Offering (s)</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CCLOC - CareCredit Program Participant</fullName>
                </value>
                <value>
                    <fullName>CVLKT - CIGNA Luxottica Collection</fullName>
                </value>
                <value>
                    <fullName>CVVKT - CIGNA VisionWorks Collection</fullName>
                </value>
                <value>
                    <fullName>EXAM - Exam only location</fullName>
                </value>
                <value>
                    <fullName>EYEWR - Dispensing only location</fullName>
                </value>
                <value>
                    <fullName>FFAA - Free Fitting and Adjustments</fullName>
                </value>
                <value>
                    <fullName>LEVEL - Level Provider</fullName>
                </value>
                <value>
                    <fullName>PEDKT - Otis and Piper Collection</fullName>
                </value>
                <value>
                    <fullName>PTSF - PROTEC Safety Fame Kit - Free</fullName>
                </value>
                <value>
                    <fullName>RTLIM - Retinal Imaging</fullName>
                </value>
                <value>
                    <fullName>SFTY - Safety Eyewear</fullName>
                </value>
                <value>
                    <fullName>SPRTS - Sports Eyewear</fullName>
                </value>
                <value>
                    <fullName>TELEH - Telehealth Provider</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of Account.</description>
        <inlineHelpText>A = Active 
Inactive = Not a Current Customer of any LOB. 
Closed = Business has ceased operations 
New = In process of becoming an Active account</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Submit for Approval</fullName>
                </value>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Inactive Ownership Change</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
                <value>
                    <fullName>Marked for Deletion</fullName>
                </value>
                <value>
                    <fullName>Archive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tax_ID__c</fullName>
        <description>Account Tax ID.</description>
        <encrypted>true</encrypted>
        <inlineHelpText>Account Tax ID.</inlineHelpText>
        <label>Tax ID</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Location_Spend_LTM__c</fullName>
        <inlineHelpText>Location&apos;s spend on Eyewear and Optics in the last 12 months</inlineHelpText>
        <label>Total Location Spend LTM</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vision_Care_Effective_Date__c</fullName>
        <label>Vision Care Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Care_End_Date__c</fullName>
        <label>Vision Care End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Care_Good_Standing__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is account in good standing with Vision Care.</description>
        <inlineHelpText>Is account in good standing with Vision Care.</inlineHelpText>
        <label>Vision Care Good Standing</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force/src/objects/Global_Rewards_Group__c.object
<CustomObject>
    <description>Parent object in a relationship that groups multiple Business/Practice Accounts under one Global Rewards Program (child object is Global Rewards Group Relationship)</description>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Affiliate</fullName>
                </value>
                <value>
                    <fullName>AOP</fullName>
                </value>
                <value>
                    <fullName>CAT2</fullName>
                </value>
                <value>
                    <fullName>Conflict</fullName>
                </value>
                <value>
                    <fullName>GAP</fullName>
                </value>
                <value>
                    <fullName>Independent</fullName>
                </value>
                <value>
                    <fullName>LVC</fullName>
                </value>
                <value>
                    <fullName>Near Site</fullName>
                </value>
                <value>
                    <fullName>Net Dev Excluded</fullName>
                </value>
                <value>
                    <fullName>Net Dev Purchasing Requirement</fullName>
                </value>
                <value>
                    <fullName>Not Supported</fullName>
                </value>
                <value>
                    <fullName>Onsite</fullName>
                </value>
                <value>
                    <fullName>Pearle Vision CO</fullName>
                </value>
                <value>
                    <fullName>Pearle Vision LO</fullName>
                </value>
                <value>
                    <fullName>Pop Up</fullName>
                </value>
                <value>
                    <fullName>Rollup</fullName>
                </value>
                <value>
                    <fullName>School</fullName>
                </value>
                <value>
                    <fullName>VSP Retail</fullName>
                </value>
                <value>
                    <fullName>VSP Ventures</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Global Rewards Groups</relationshipLabel>
        <relationshipName>Global_Rewards_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF( OR( Start_Date__c = TODAY() , AND( Start_Date__c &lt; TODAY() , OR( End_Date__c &gt;= TODAY() , ISBLANK( End_Date__c ) ) ) ) , &quot;Active&quot;, &apos;Inactive&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Care_Good_Standing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Vision Care Good Standing</label>
        <type>Checkbox</type>
    </fields>
    <label>Global Rewards Group</label>
    <nameField>
        <label>Global Rewards Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Global Rewards Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force/src/objects/Global_Rewards_Group_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Child_Account__c</fullName>
        <label>Child Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Global Rewards Group Relationships</relationshipLabel>
        <relationshipName>Global_Rewards_Group_Relationships</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>Date the child record was ended its relationship with the Parent Roll up account.</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Global_Rewards_Group__c</fullName>
        <label>Global Rewards Group</label>
        <referenceTo>Global_Rewards_Group__c</referenceTo>
        <relationshipLabel>Global Rewards Group Relationships</relationshipLabel>
        <relationshipName>Global_Rewards_Group</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Date the child record was added to the Parent Roll up account.</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF((Start_Date__c &lt;= TODAY() &amp;&amp; (ISBLANK(End_Date__c) ||  End_Date__c &gt;= TODAY())), &apos;Active&apos;, 
IF((Start_Date__c &gt; Today()), &apos;Future&apos;, &apos;Inactive&apos;))</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Global Rewards Group Relationship</label>
    <nameField>
        <displayFormat>PREMIER-{0000}</displayFormat>
        <label>Global Rewards Group Relationship ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Global Rewards Group Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force/src/classes/VSPR31_Premier_Prac_Upd_Grg_Create_Test.cls
@isTest
//Test class for VSPR31_Premier_Prac_Upd_Grg_Create_Batch
public class VSPR31_Premier_Prac_Upd_Grg_Create_Test {
    @isTest
    public static void testPremierPracUpdGrgCreateBatch(){
        //When there is only one Business Account Contract Type and Tax ID Roll Up Account = True       
        Id accRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Practice Account').getRecordTypeId();
        Id accBusRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
        Id grpTaxIdRecordTypeId = Schema.SObjectType.Global_Rewards_Group__c.getRecordTypeInfosByName().get('Tax ID Rollup').getRecordTypeId();
        
        
        Account Prac3 = new Account();
        Prac3.RecordTypeId = accRecordTypeId;
        Prac3.Name = 'Practice 3 Account';
        Prac3.Status__c = 'A';
        Prac3.Tax_ID__c = '123456789';
        Prac3.Premier_Tax_ID_Roll_Up_Account__c = True;
        
        insert Prac3;
        
        Account BusAcc2 = new Account();
        BusAcc2.RecordTypeId = accBusRecordTypeId;
        BusAcc2.Name = 'Business Account 2';
        BusAcc2.ParentId = Prac3.Id;
        BusAcc2.Contract_Type__c = 'Affiliate';
        
        insert BusAcc2;
        
        Global_Rewards_Group__c grg = new Global_Rewards_Group__c();
        grg.RecordTypeId = grpTaxIdRecordTypeId;
        grg.Name = 'TESTGRP';
        grg.Parent_Account__c = Prac3.Id;
        
        insert grg;

        Account ac = [SELECT Id, ParentId, Name, isDeleted, RecordTypeId FROM Account WHERE Name LIKE '%Prac%'];
        Account bc = [SELECT Id, ParentId, Name, isDeleted, RecordTypeId FROM Account WHERE Name = 'Business Account 2'];
        
        System.debug('P & B Account isDeleted : ' + ac.IsDeleted + ' = ' + bc.IsDeleted);
        Test.startTest();
        //VSPR31_Premier_Prac_Upd_Grg_Create_Batch obj = new VSPR31_Premier_Prac_Upd_Grg_Create_Batch();
       // Database.executeBatch(obj, 200);
         String EXP = '0 0 23 * * ?';
        VSPR31_Premier_Prac_Upd_Grg_Create_Sched sch = new VSPR31_Premier_Prac_Upd_Grg_Create_Sched();
        system.Schedule('Premier Tier Update Test', EXP, sch);
        Test.stopTest();
        
        System.debug('P Account : ' + ac);
        System.debug('B Account : ' + bc);
        System.debug('Compare Account : ' + ac.Id + ' = ' + bc.ParentId);
        System.assertEquals(ac.Id, bc.ParentId);
        
    }
    @isTest
    public static void testPremierPracUpdGrgCreateBatch1(){
        //When more than 1 Business Account Contract Type is different and Tax ID Roll Up Account = True   
        Id accRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Practice Account').getRecordTypeId();
        Id accBusRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
        Id grpTaxIdRecordTypeId = Schema.SObjectType.Global_Rewards_Group__c.getRecordTypeInfosByName().get('Tax ID Rollup').getRecordTypeId();
        
        Account Prac3 = new Account();
        Prac3.RecordTypeId = accRecordTypeId;
        Prac3.Name = 'Practice 3 Account';
        Prac3.Status__c = 'A';
        Prac3.Tax_ID__c = '123456789';
        Prac3.Premier_Tax_ID_Roll_Up_Account__c = True;
        
        insert Prac3;
        
        Account BusAcc2 = new Account();
        BusAcc2.RecordTypeId = accBusRecordTypeId;
        BusAcc2.Name = 'Business Account 2';
        BusAcc2.ParentId = Prac3.Id;
        BusAcc2.Contract_Type__c = 'Affiliate';
        
        insert BusAcc2;
        //BusAcc2.Contract_Type__c = 'Affiliate'; //Need to update because VSPR31_ContractTypeCalculation nulls it out.
        //update BusAcc2;
        
        Account BusAcc3 = new Account();
        BusAcc3.RecordTypeId = accBusRecordTypeId;
        BusAcc3.Name = 'Business Account 2';
        BusAcc3.ParentId = Prac3.Id;
        BusAcc3.Contract_Type__c = 'Conflict';
        
        insert BusAcc3;
        //BusAcc3.Contract_Type__c = 'Conflict'; //Need to update because VSPR31_ContractTypeCalculation nulls it out.
        //update BusAcc3;
        
        Global_Rewards_Group__c grg = new Global_Rewards_Group__c();
        grg.RecordTypeId = grpTaxIdRecordTypeId;
        grg.Name = 'TESTGRP';
        grg.Parent_Account__c = Prac3.Id;
        
        insert grg;

        Test.startTest();
       // VSPR31_Premier_Prac_Upd_Grg_Create_Batch obj = new VSPR31_Premier_Prac_Upd_Grg_Create_Batch();
       // Database.executeBatch(obj, 200);
         String EXP = '0 0 23 * * ?';
        VSPR31_Premier_Prac_Upd_Grg_Create_Sched sch = new VSPR31_Premier_Prac_Upd_Grg_Create_Sched();
        system.Schedule('Premier Tier Update Test', EXP, sch);
        Test.stopTest();
        
        System.assertNotEquals('Conflict', BusAcc2.Contract_Type__c);
        System.assertNotEquals('Affiliate', BusAcc3.Contract_Type__c);

    }
    @isTest
    public static void testPremierPracUpdGrgCreateBatch2(){
        //When there are more than 1 Business Account Contract Type is the same and Tax ID Roll Up Account = False   
        Id accRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Practice Account').getRecordTypeId();
        Id accBusRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
        Id grpTaxIdRecordTypeId = Schema.SObjectType.Global_Rewards_Group__c.getRecordTypeInfosByName().get('Tax ID Rollup').getRecordTypeId();
        
        Account Prac3 = new Account();
        Prac3.RecordTypeId = accRecordTypeId;
        Prac3.Name = 'Practice 3 Account';
        Prac3.Status__c = 'A';
        Prac3.Tax_ID__c = '123456789';
        Prac3.Premier_Tax_ID_Roll_Up_Account__c = False;
        
        insert Prac3;
        
        Account BusAcc2 = new Account();
        BusAcc2.RecordTypeId = accBusRecordTypeId;
        BusAcc2.Name = 'Business Account 2';
        BusAcc2.ParentId = Prac3.Id;
        BusAcc2.Contract_Type__c = 'Affiliate';
        BusAcc2.Vision_Care_Good_Standing__c = True;
        
        insert BusAcc2;
        //BusAcc2.Contract_Type__c = 'Affiliate'; //Need to update because VSPR31_ContractTypeCalculation nulls it out.
        //update BusAcc2;
        
        Account BusAcc3 = new Account();
        BusAcc3.RecordTypeId = accBusRecordTypeId;
        BusAcc3.Name = 'Business Account 2';
        BusAcc3.ParentId = Prac3.Id;
        BusAcc3.Contract_Type__c = 'Affiliate';
        BusAcc3.Vision_Care_Good_Standing__c = True;
        
        insert BusAcc3;
        //BusAcc3.Contract_Type__c = 'Affiliate'; //Need to update because VSPR31_ContractTypeCalculation nulls it out.
        //update BusAcc3;
        
        Global_Rewards_Group__c grg = new Global_Rewards_Group__c();
        grg.RecordTypeId = grpTaxIdRecordTypeId;
        grg.Name = 'TESTGRP';
        grg.Parent_Account__c = Prac3.Id;
        
        insert grg;

        Test.startTest();
       // VSPR31_Premier_Prac_Upd_Grg_Create_Batch obj = new VSPR31_Premier_Prac_Upd_Grg_Create_Batch();
        //Database.executeBatch(obj, 200);
         String EXP = '0 0 23 * * ?';
        VSPR31_Premier_Prac_Upd_Grg_Create_Sched sch = new VSPR31_Premier_Prac_Upd_Grg_Create_Sched();
        system.Schedule('Premier Tier Update Test', EXP, sch);
        Test.stopTest();
        
        System.assertEquals(BusAcc2.Contract_Type__c, BusAcc3.Contract_Type__c);
    }
    @isTest
    public static void testPremierPracUpdGrgCreateBatch3(){
        //When there are more than 1 Business Account Contract Type not the same and Tax ID Roll Up Account = False  
        Id accRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Practice Account').getRecordTypeId();
        Id accBusRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
        Id grpTaxIdRecordTypeId = Schema.SObjectType.Global_Rewards_Group__c.getRecordTypeInfosByName().get('Tax ID Rollup').getRecordTypeId();
        
        Account Prac3 = new Account();
        Prac3.RecordTypeId = accRecordTypeId;
        Prac3.Name = 'Practice 3 Account';
        Prac3.Status__c = 'A';
        Prac3.Tax_ID__c = '123456789';
        Prac3.Premier_Tax_ID_Roll_Up_Account__c = False;
        
        insert Prac3;
        
        Account BusAcc2 = new Account();
        BusAcc2.RecordTypeId = accBusRecordTypeId;
        BusAcc2.Name = 'Business Account 2';
        BusAcc2.ParentId = Prac3.Id;
        BusAcc2.Vision_Care_Good_Standing__c = True;
        BusAcc2.Contract_Type__c = 'Affiliate';
        
        insert BusAcc2;
        //BusAcc2.Contract_Type__c = 'Affiliate'; //Need to update because VSPR31_ContractTypeCalculation nulls it out.
        //update BusAcc2;
        
        Account BusAcc3 = new Account();
        BusAcc3.RecordTypeId = accBusRecordTypeId;
        BusAcc3.Name = 'Business Account 2';
        BusAcc3.ParentId = Prac3.Id;
        BusAcc3.Vision_Care_Good_Standing__c = True;
        BusAcc3.Contract_Type__c = 'Pop Up';
        
        insert BusAcc3;
        //BusAcc3.Contract_Type__c = 'Pop Up'; //Need to update because VSPR31_ContractTypeCalculation nulls it out.
        //update BusAcc3;
        
        Global_Rewards_Group__c grg = new Global_Rewards_Group__c();
        grg.RecordTypeId = grpTaxIdRecordTypeId;
        grg.Name = 'TESTGRP';
        //grg.Parent_Account__c = BusAcc3.Id;
        
        insert grg;
        
        Global_Rewards_Group_Relationship__c grgr = new Global_Rewards_Group_Relationship__c();
        grgr.Active__c = True;
        grgr.Child_Account__c = BusAcc3.Id;
        grgr.End_Date__c = null;
        grgr.Global_Rewards_Group__c = grg.Id;
        grgr.Start_Date__c = Date.today()-10;
        
        insert grgr;
        
        Test.startTest();
      //  VSPR31_Premier_Prac_Upd_Grg_Create_Batch obj = new VSPR31_Premier_Prac_Upd_Grg_Create_Batch();
      //  Database.executeBatch(obj, 200);
         String EXP = '0 0 23 * * ?';
        VSPR31_Premier_Prac_Upd_Grg_Create_Sched sch = new VSPR31_Premier_Prac_Upd_Grg_Create_Sched();
        system.Schedule('Premier Tier Update Test', EXP, sch);
        Test.stopTest();
        
        System.assertNotEquals(null, BusAcc2.Contract_Type__c);
        System.assertNotEquals(null, BusAcc3.Contract_Type__c);
    }
    
    @isTest
    public static void testPremierPracUpdGrgCreateBatch4(){
        //When there are more than 1 Business Account Contract Type is the same and Tax ID Roll Up Account = True and 1 Business Account belongs to another Global Reward Group
        Id accRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Practice Account').getRecordTypeId();
        Id accBusRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
        Id grpTaxIdRecordTypeId = Schema.SObjectType.Global_Rewards_Group__c.getRecordTypeInfosByName().get('Tax ID Rollup').getRecordTypeId();
        Id grpContractRecordTypeId = Schema.SObjectType.Global_Rewards_Group__c.getRecordTypeInfosByName().get('Contract Type').getRecordTypeId();
        
        Account Prac1 = new Account();
        Prac1.RecordTypeId = accRecordTypeId;
        Prac1.Name = 'Practice 1 Account';
        Prac1.Status__c = 'A';
        Prac1.Tax_ID__c = '123456789';
        Prac1.Premier_Tax_ID_Roll_Up_Account__c = True;
        Prac1.Contract_Type__c = 'GAP';
        insert Prac1;
        
        Account BusAcc2 = new Account();
        BusAcc2.RecordTypeId = accBusRecordTypeId;
        BusAcc2.Name = 'Business Account 2';
        BusAcc2.ParentId = Prac1.Id;
        BusAcc2.Contract_Type__c = 'GAP';
        
        insert BusAcc2;
        
        Account BusAcc3 = new Account();
        BusAcc3.RecordTypeId = accBusRecordTypeId;
        BusAcc3.Name = 'Business Account 3';
        BusAcc3.ParentId = Prac1.Id;
        BusAcc3.Contract_Type__c = 'GAP';
        
        insert BusAcc3;
        
        Global_Rewards_Group__c grg = new Global_Rewards_Group__c();
        grg.RecordTypeId = grpTaxIdRecordTypeId;
        grg.Name = 'TESTGRP';
        grg.Parent_Account__c = Prac1.Id;
        
        insert grg;
        
        Global_Rewards_Group__c grg1 = new Global_Rewards_Group__c();
        grg1.RecordTypeId = grpTaxIdRecordTypeId;
        grg1.Name = 'TESTGRP1';
        
        insert grg1;
        
        Global_Rewards_Group__c grg2 = new Global_Rewards_Group__c();
        grg2.RecordTypeId = grpContractRecordTypeId;
        grg2.Name = 'TESTGRP2';
        
        insert grg2;
        
        Global_Rewards_Group_Relationship__c grgr = new Global_Rewards_Group_Relationship__c();
        grgr.Active__c = True;
        grgr.Child_Account__c = Prac1.Id;
        grgr.End_Date__c = null;
        grgr.Global_Rewards_Group__c = grg.Id;
        grgr.Start_Date__c = Date.today()-10;
        
        insert grgr; 
        
        Global_Rewards_Group_Relationship__c grgr1 = new Global_Rewards_Group_Relationship__c();
        grgr1.Active__c = True;
        grgr1.Child_Account__c = BusAcc2.Id;
        grgr1.End_Date__c = null;
        grgr1.Global_Rewards_Group__c = grg1.Id;
        grgr1.Start_Date__c = Date.today()-10;
        
        insert grgr1; 
        
        Global_Rewards_Group_Relationship__c grgr2 = new Global_Rewards_Group_Relationship__c();
        grgr2.Active__c = True;
        grgr2.Child_Account__c = BusAcc2.Id;
        grgr2.End_Date__c = null;
        grgr2.Global_Rewards_Group__c = grg2.Id;
        grgr2.Start_Date__c = Date.today()-10;
        
        insert grgr2; 
        
        Test.startTest();       
        
        System.debug('BA CONTRACT TYPE : ' + BusAcc2.Contract_Type__c);
        
       // VSPR31_Premier_Prac_Upd_Grg_Create_Batch obj = new VSPR31_Premier_Prac_Upd_Grg_Create_Batch();
      //  Database.executeBatch(obj, 200);
         String EXP = '0 0 23 * * ?';
        VSPR31_Premier_Prac_Upd_Grg_Create_Sched sch = new VSPR31_Premier_Prac_Upd_Grg_Create_Sched();
        system.Schedule('Premier Tier Update Test', EXP, sch);
        Test.stopTest();
        
        //System.assertEquals(grgr1.Child_Account__c, BusAcc2.Id);
        //System.assertEquals(grgr2.Child_Account__c, BusAcc2.Id);
    }
    @isTest
    public static void testPremierPracUpdGrgCreateBatch5(){
        //When there are more than 1 Business Account with Participation_Exclusions__c and Service_Offering_s__c and Tax ID Roll Up Account = False  
        Id accRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Practice Account').getRecordTypeId();
        Id accBusRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
        Id grpTaxIdRecordTypeId = Schema.SObjectType.Global_Rewards_Group__c.getRecordTypeInfosByName().get('Tax ID Rollup').getRecordTypeId();
        
        //Use Prac2 from testdata & BusAcc4 & BusAcc5
        Account Prac3 = new Account();
        Prac3.RecordTypeId = accRecordTypeId;
        Prac3.Name = 'Practice 3 Account';
        Prac3.Status__c = 'A';
        Prac3.Tax_ID__c = '123456789';
        Prac3.Premier_Tax_ID_Roll_Up_Account__c = False;
        
        insert Prac3;
        
        Account BusAcc1 = new Account();
        BusAcc1.RecordTypeId = accBusRecordTypeId;
        BusAcc1.Name = 'Business Account 2';
        BusAcc1.ParentId = Prac3.Id;
        BusAcc1.Total_Location_Spend_LTM__c = 100;
        BusAcc1.Eyewear_Location_Spend_LTM__c = 100;
        BusAcc1.Optics_Location_Spend_LTM__c = 100;
        BusAcc1.Contract_Type__c = 'Affiliate';
        BusAcc1.Vision_Care_Good_Standing__c = True;
        BusAcc1.Participation_Exclusions__c = 'NODIS – Opts out of discounts';
        BusAcc1.Vision_Care_Effective_Date__c = system.today()-3;
        BusAcc1.Vision_Care_End_Date__c = null;
        BusAcc1.Status__c = 'A';
        
        insert BusAcc1;
        BusAcc1.Contract_Type__c = 'Affiliate'; //Need to update because VSPR31_ContractTypeCalculation nulls it out.
        update BusAcc1;
        
        Account BusAcc2 = new Account();
        BusAcc2.RecordTypeId = accBusRecordTypeId;
        BusAcc2.Name = 'Business Account 2';
        BusAcc2.ParentId = Prac3.Id;
        BusAcc2.Total_Location_Spend_LTM__c = 100;
        BusAcc2.Eyewear_Location_Spend_LTM__c = 100;
        BusAcc2.Optics_Location_Spend_LTM__c = 100;
        BusAcc2.Contract_Type__c = 'Affiliate';
        BusAcc2.Vision_Care_Good_Standing__c = True;
        BusAcc2.Service_Offering_s__c = 'RTLIM - Retinal Imaging';
        BusAcc2.Status__c = 'A';
        
        insert BusAcc2;
        BusAcc2.Contract_Type__c = 'Affiliate'; //Need to update because VSPR31_ContractTypeCalculation nulls it out.
        update BusAcc2;
        
        Account BusAcc3 = new Account();
        BusAcc3.RecordTypeId = accBusRecordTypeId;
        BusAcc3.Name = 'Business Account 2';
        BusAcc3.ParentId = Prac3.Id;
        BusAcc3.Total_Location_Spend_LTM__c = 100;
        BusAcc3.Eyewear_Location_Spend_LTM__c = 100;
        BusAcc3.Optics_Location_Spend_LTM__c = 100;
        BusAcc3.Contract_Type__c = 'Affiliate';
        BusAcc3.Service_Offering_s__c = 'FFAA - Free Fitting and Adjustments';
        BusAcc3.Vision_Care_Good_Standing__c = True;
        BusAcc3.Status__c = 'A';
        
        insert BusAcc3;
        //BusAcc3.Contract_Type__c = 'Affiliate'; //Need to update because VSPR31_ContractTypeCalculation nulls it out.
        //update BusAcc3;
        
        Global_Rewards_Group__c grg = new Global_Rewards_Group__c();
        grg.RecordTypeId = grpTaxIdRecordTypeId;
        grg.Name = 'TESTGRP';
        //grg.Parent_Account__c = Prac3.Id;
        
        insert grg;
        
        Global_Rewards_Group_Relationship__c grgr = new Global_Rewards_Group_Relationship__c();
        grgr.Active__c = True;
        grgr.Child_Account__c = BusAcc1.Id;
        grgr.End_Date__c = null;
        grgr.Global_Rewards_Group__c = grg.Id;
        grgr.Start_Date__c = Date.today()-10;
        
        insert grgr; 
        
        Test.startTest();
       // VSPR31_Premier_Prac_Upd_Grg_Create_Batch obj = new VSPR31_Premier_Prac_Upd_Grg_Create_Batch();
       // Database.executeBatch(obj, 200);
         String EXP = '0 0 23 * * ?';
        VSPR31_Premier_Prac_Upd_Grg_Create_Sched sch = new VSPR31_Premier_Prac_Upd_Grg_Create_Sched();
        system.Schedule('Premier Tier Update Test', EXP, sch);
        Test.stopTest();
        
        System.assertEquals('NODIS – Opts out of discounts', BusAcc1.Participation_Exclusions__c);
        System.assertEquals('RTLIM - Retinal Imaging', BusAcc2.Service_Offering_s__c);
        System.assertEquals('FFAA - Free Fitting and Adjustments', BusAcc3.Service_Offering_s__c);
    }
    @isTest
    public static void testPremierPracUpdGrgCreateBatch6(){
        //When there are more than 1 Business Account with null values for Total_Location_Spend_LTM__c, Eyewear_Location_Spend_LTM__c, Optics_Location_Spend_LTM__c and Tax ID Roll Up Account = False  
        Id accRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Practice Account').getRecordTypeId();
        Id accBusRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
        Id grpTaxIdRecordTypeId = Schema.SObjectType.Global_Rewards_Group__c.getRecordTypeInfosByName().get('Tax ID Rollup').getRecordTypeId();
        
        //Use Prac2 from testdata & BusAcc4 & BusAcc5
        Account Prac3 = new Account();
        Prac3.RecordTypeId = accRecordTypeId;
        Prac3.Name = 'Practice 3 Account';
        Prac3.Status__c = 'A';
        Prac3.Tax_ID__c = '123456789';
        Prac3.Premier_Tax_ID_Roll_Up_Account__c = False;
        
        insert Prac3;
        
        Account BusAcc1 = new Account();
        BusAcc1.RecordTypeId = accBusRecordTypeId;
        BusAcc1.Name = 'Business Account 2';
        BusAcc1.ParentId = Prac3.Id;
        BusAcc1.Total_Location_Spend_LTM__c = null;
        BusAcc1.Eyewear_Location_Spend_LTM__c = null;
        BusAcc1.Optics_Location_Spend_LTM__c = null;
        BusAcc1.Contract_Type__c = 'Affiliate';
        BusAcc1.Vision_Care_Good_Standing__c = True;
        BusAcc1.Participation_Exclusions__c = 'NODIS – Opts out of discounts';
        BusAcc1.Vision_Care_Effective_Date__c = system.today()-3;
        BusAcc1.Vision_Care_End_Date__c = null;
        BusAcc1.Status__c = 'A';
        
        insert BusAcc1;
        BusAcc1.Contract_Type__c = 'Affiliate'; //Need to update because VSPR31_ContractTypeCalculation nulls it out.
        update BusAcc1;
        
        Account BusAcc2 = new Account();
        BusAcc2.RecordTypeId = accBusRecordTypeId;
        BusAcc2.Name = 'Business Account 2';
        BusAcc2.ParentId = Prac3.Id;
        BusAcc2.Total_Location_Spend_LTM__c = null;
        BusAcc2.Eyewear_Location_Spend_LTM__c = null;
        BusAcc2.Optics_Location_Spend_LTM__c = null;
        BusAcc2.Contract_Type__c = 'Affiliate';
        BusAcc2.Vision_Care_Good_Standing__c = True;
        BusAcc2.Service_Offering_s__c = 'RTLIM - Retinal Imaging';
        BusAcc2.Status__c = 'A';
        
        insert BusAcc2;
        //BusAcc2.Contract_Type__c = 'Affiliate'; //Need to update because VSPR31_ContractTypeCalculation nulls it out.
        //update BusAcc2;
        
        Account BusAcc3 = new Account();
        BusAcc3.RecordTypeId = accBusRecordTypeId;
        BusAcc3.Name = 'Business Account 2';
        BusAcc3.ParentId = Prac3.Id;
        BusAcc3.Total_Location_Spend_LTM__c = null;
        BusAcc3.Eyewear_Location_Spend_LTM__c = null;
        BusAcc3.Optics_Location_Spend_LTM__c = null;
        BusAcc3.Contract_Type__c = 'Affiliate';
        BusAcc3.Service_Offering_s__c = 'FFAA - Free Fitting and Adjustments';
        BusAcc3.Vision_Care_Good_Standing__c = True;
        BusAcc3.Status__c = 'A';
        
        insert BusAcc3;
        //BusAcc3.Contract_Type__c = 'Affiliate'; //Need to update because VSPR31_ContractTypeCalculation nulls it out.
        //update BusAcc3;
        
        Global_Rewards_Group__c grg = new Global_Rewards_Group__c();
        grg.RecordTypeId = grpTaxIdRecordTypeId;
        grg.Name = 'TESTGRP';
        //grg.Parent_Account__c = Prac3.Id;
        
        insert grg;

        Test.startTest();
       // VSPR31_Premier_Prac_Upd_Grg_Create_Batch obj = new VSPR31_Premier_Prac_Upd_Grg_Create_Batch();
       // Database.executeBatch(obj, 200);
         String EXP = '0 0 23 * * ?';
        VSPR31_Premier_Prac_Upd_Grg_Create_Sched sch = new VSPR31_Premier_Prac_Upd_Grg_Create_Sched();
        system.Schedule('Premier Tier Update Test', EXP, sch);
        Test.stopTest();
        
        System.assertEquals(null, BusAcc1.Total_Location_Spend_LTM__c);
        System.assertEquals(null, BusAcc1.Eyewear_Location_Spend_LTM__c);
        System.assertEquals(null, BusAcc1.Optics_Location_Spend_LTM__c);
    }
}