force/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MDM_Location_Keys__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>MDM Location Key.</inlineHelpText>
        <label>MDM Location Key</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Physical_County__c</fullName>
        <description>Populated by Data Integration</description>
        <label>Physical County</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Address_Type__c</fullName>
        <label>Address Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Physical</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Shipping</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <formula>Street__c &amp; &apos;, &apos; &amp; City__c &amp; &apos;, &apos; &amp; State__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>City</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Country</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>County</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LM_MASTER_SKEY__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>MDM Location Key</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>State</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Street</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Zip</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force/src/objects/Address_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Address Relationships</relationshipLabel>
        <relationshipName>Address_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Address_Type__c</fullName>
        <label>Address Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Physical</fullName>
                </value>
                <value>
                    <fullName>Shipping</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Address Relationships</relationshipLabel>
        <relationshipName>Address_Relationships</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Address Relationship</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Address Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Address Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/VSPR1_FindCorrectAddress.cls
public with sharing class VSPR1_FindCorrectAddress { 
    public static List<Account> myAccount;
    
    public static void findAddress(Set<Id> accountIds){
        system.debug('>>> Enter findAddress');
        
        List<Address_Relationship__c> Addresses = new List<Address_Relationship__c>();
        myAccount = new List<Account>(VSPR1_AccountDML.getAccountDetails(accountIds));
        Set<Id> addressIds = new Set<Id>();
        
        system.debug('--------accountIds---'+accountIds);
        Addresses = VSPR1_AddressRelationshipDML.getAddressRelationbyAccount(accountIds); 
         system.debug('--------Addresses---'+Addresses);
         system.debug('--------Addresses------SIZE------'+Addresses.size());
        Map<Id, String> AccIdAccAndAdd = new Map<Id, String>();
        Map<Id, String> AccIdAccAndAdd2 = new Map<Id, String>();
        
         
        List <String> AccAndAdd = new List <String>();
         
        for(Address_Relationship__c Address : Addresses){
                addressIds.add(Address.address__c);
                AccAndAdd.add(String.valueOf(Address.Account__c) + ',' + String.valueOf(Address.address__c));                    

                if (!AccIdAccAndAdd.containsKey(Address.Account__c)) {
                    AccIdAccAndAdd.put(Address.Account__c,String.valueOf(Address.Account__c) + ',' + String.valueOf(Address.address__c) + ',' + String.valueOf(Address.Address_Type__c));
                }
                else {
                    AccIdAccAndAdd2.put(Address.Account__c,String.valueOf(Address.Account__c) + ',' + String.valueOf(Address.address__c) + ',' + String.valueOf(Address.Address_Type__c));
                }

        }

    
        map<id,Address__c> AddressMap = new map<id,Address__c>(VSPR1_AddressDML.getAddressPhysicalOnly(addressIds));
        
        List<String> splitted = new List<String>();  
        List<String> splitted2 = new List<String>(); 
        id curAccountID; 
        id curAddressID;
        id curAccountID2; 
        id curAddressID2;
        Address__c tempListAdd = new Address__c();
    
        if (Addresses.size() <= 0 || AddressMap.size() <= 0 ) {
            for(Account curAccount : myAccount) {
                curAccount.ShippingCity = '';
                curAccount.ShippingCountry = '';
                curAccount.ShippingState = '';
                curAccount.ShippingStreet = '';
                curAccount.ShippingPostalCode = '';
                curAccount.Physical_County__c = '';
                
            }
        }
        else if (Addresses.size() > 0) {
            
            for(Account curAccount : myAccount) {
               
                if (AccIdAccAndAdd.containsKey(curAccount.id)) {
                    String s = AccIdAccAndAdd.get(curAccount.id);
                    splitted = s.split(',');
                    curAccountID = splitted[0];
                    curAddressID = splitted[1];
                }
                else {
                    curAddressID = '000000000000000000';
                }
                
                
                if (AccIdAccAndAdd2.containsKey(curAccount.id)) {
                    String s2 = AccIdAccAndAdd2.get(curAccount.id);
                    splitted2 = s2.split(',');
                    curAccountID2 = splitted2[0];
                    curAddressID2 = splitted2[1];
                }
                else {
                    curAddressID2 = '000000000000000000';
                }
                 
                    
                    if(AddressMap.containsKey(curAddressID) || AddressMap.containsKey(curAddressID2)) {
                        if (AddressMap.containsKey(curAddressID)){
                            tempListAdd = AddressMap.get(curAddressID);
                        }
                        else if (AddressMap.containsKey(curAddressID2)){
                            tempListAdd = AddressMap.get(curAddressID2);
                        }
                                               
                            curAccount.ShippingCity = tempListAdd.City__c;
                            curAccount.ShippingCountry = tempListAdd.Country__c;
                            curAccount.ShippingState = tempListAdd.State__c;
                            curAccount.ShippingStreet = tempListAdd.Street__c;
                            curAccount.ShippingPostalCode = tempListAdd.Zip__c;
                            curAccount.Physical_County__c = tempListAdd.County__c;
                            system.debug('-------curAccount.MDM_Location_Keys__c---------'+curAccount.MDM_Location_Keys__c);
                            if(curAccount.MDM_Location_Keys__c==null || curAccount.MDM_Location_Keys__c=='')
                              curAccount.MDM_Location_Keys__c = tempListAdd.LM_MASTER_SKEY__c;  //Added by Shravani on 07/02/2014
                        

                        
                    }
                    else {
                            
                            curAccount.ShippingCity = '';
                            curAccount.ShippingCountry = '';
                            curAccount.ShippingState = '';
                            curAccount.ShippingStreet = '';
                            curAccount.ShippingPostalCode = '';
                            curAccount.Physical_County__c = '';
                          
                    }
                    
            }
        }
        update  myAccount;
        
    }
    

}