force/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Client_Id__c</fullName>
        <label>Client Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consumer__c</fullName>
        <label>Consumer</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>PrimaryMember</fullName>
                </value>
                <value>
                    <fullName>Dependent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Member_Status__c</fullName>
        <label>Member Status</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Termed</fullName>
                </value>
                <value>
                    <fullName>Pended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of Account.</description>
        <inlineHelpText>A = Active 
Inactive = Not a Current Customer of any LOB. 
Closed = Business has ceased operations 
New = In process of becoming an Active account</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Submit for Approval</fullName>
                </value>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Inactive Ownership Change</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
                <value>
                    <fullName>Marked for Deletion</fullName>
                </value>
                <value>
                    <fullName>Archive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force/src/objects/Alert_ID_Criteria__c.object
<CustomObject>
    <description>This object is used to associate Cases with DivisionID and/or ClientID to an Alert.</description>
    <fields>
        <fullName>Alert__c</fullName>
        <label>Alert</label>
        <referenceTo>Alerts_and_notification__c</referenceTo>
        <relationshipLabel>Alert ID Criterion</relationshipLabel>
        <relationshipName>Alert_ID_Criterion</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ClientID__c</fullName>
        <label>ClientID</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DivisionID__c</fullName>
        <label>DivisionID</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Alert ID Criteria</label>
    <nameField>
        <displayFormat>MPC-{0000000000}</displayFormat>
        <label>MPC Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alert ID Criterion</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force/src/objects/Alerts_and_notification__c.object
<CustomObject>
    <fields>
        <fullName>Consumer__c</fullName>
        <label>Consumer</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>PrimaryMember</fullName>
                </value>
                <value>
                    <fullName>Dependent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Member_Status__c</fullName>
        <label>Member Status</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Termed</fullName>
                </value>
                <value>
                    <fullName>Pended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>(&quot;New&quot;)</defaultValue>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Alert</label>
    <nameField>
        <label>Alert Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Alerts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Client_Id__c</fullName>
        <inlineHelpText>Main client Id field. All other collection fields will pipe to this field. All logic will be based upon this field for client Id.</inlineHelpText>
        <label>Client Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DivisionId__c</fullName>
        <label>DivisionId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Client Delivery</fullName>
                </value>
                <value>
                    <fullName>Onsite Clinics</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Member_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member Plan</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.ContactId</field>
                <operation>equals</operation>
                <valueField>$Source.ContactId</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>MemberPlan</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force/src/objects/DVIWebService__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Setting for the DVI Web Service URL and token header</description>
    <fields>
        <fullName>DVI_Web_Service__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>DVI Web Service</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DVI Web Service</label>
</CustomObject>

force/src/objects/MemberPlan.object
<CustomObject>
    <fields>
        <fullName>Client_ID__c</fullName>
        <label>Client ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division_ID__c</fullName>
        <label>Division ID</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>if((EffectiveFrom &lt;= TODAY() &amp;&amp; EffectiveTo &gt;= TODAY() ) , &quot;Active&quot;, &quot;Inactive&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force/src/classes/AlertNotificationListController_Test.cls
@isTest
public class AlertNotificationListController_Test {
    
    @isTest
    private static void getAlertsTest(){
      	DVIWebService__c cs1 = new DVIWebService__c();
        cs1.name= 'DVI Values';
        cs1.DVI_Web_Service__c = 'https://api-staging.vspglobal.com';
        insert cs1;
        
        Account acc = new Account();
        acc.Name = 'test1';
        acc.Member_Status__c = 'Active';
        acc.Consumer__c = 'PrimaryMember';
        acc.Client_Id__c = '5678666';    
        //acc.Client_ID__pc = '1234';
        insert acc;
        
        Alerts_and_notification__c alert = new Alerts_and_notification__c();
        alert.Name = 'testing_alert';
        alert.Status__c='Published';
        insert alert;
        
        MemberPlan mp = new MemberPlan();
        mp.Name = 'primary member';
        mp.MemberId = acc.Id;
        mp.Division_ID__c ='1234';
        mp.Client_ID__c ='5678666';
            
        insert mp;
        
        Case cs = new Case();
        cs.AccountId = acc.Id;
        //cs.Alerts_and_Notifications__c = alert.Id;
        cs.Division__c = 'Onsite Clinics';
        cs.Member_Plan__c = mp.Id;
        
        insert cs;
    
        Alert_ID_Criteria__c alertClient = new Alert_ID_Criteria__c();
        alertClient.Alert__c = alert.Id;
        alertClient.DivisionID__c = '1234';
        alertClient.ClientID__c ='5678666';
        insert alertClient;
        System.debug('alertClient:'+alertClient);
    
    
        
        AlertNotificationListController.isAuthorUser();
        AlertNotificationListController.getAlertList(cs.Id);
        AlertNotificationListController.getClientAndDivisionIds(alert.Id);
        AlertNotificationListController.removeAlerts( alert.Id,cs.Id);
        
        
    }
}