force/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Premier_Tax_ID_Roll_Up_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Indicates whether an Account is being evaluated for Premier qualification in conjunction with other accounts with different Tax ID&apos;s.</inlineHelpText>
        <label>Tax ID Roll Up Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tax_ID__c</fullName>
        <description>Account Tax ID.</description>
        <encrypted>true</encrypted>
        <inlineHelpText>Account Tax ID.</inlineHelpText>
        <label>Tax ID</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tier_Agreement_Type__c</fullName>
        <label>Tier Agreement Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/VSPR31_Premier_Prac_Upd_Grg_Create_Sched.cls
global class VSPR31_Premier_Prac_Upd_Grg_Create_Sched implements Schedulable {

    global void execute(SchedulableContext sc){
        
        String Query; 
        Id accRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Practice Account').getRecordTypeId();
        Query = 'SELECT Id, Tax_ID__c, Premier_Tax_ID_Roll_Up_Account__c, Tier_Agreement_Type__c FROM Account WHERE IsDeleted = false AND Tax_ID__c != Null AND recordTypeId = \'' + accRecordTypeId + '\''; 
        system.debug('Query='+Query);
        
        VSPR31_Premier_Prac_Upd_Grg_Create_Batch batch = new VSPR31_Premier_Prac_Upd_Grg_Create_Batch(Query);
        database.executeBatch(batch,50);
        
    }
}