force/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of Account.</description>
        <inlineHelpText>A = Active 
Inactive = Not a Current Customer of any LOB. 
Closed = Business has ceased operations 
New = In process of becoming an Active account</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Submit for Approval</fullName>
                </value>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Inactive Ownership Change</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
                <value>
                    <fullName>Marked for Deletion</fullName>
                </value>
                <value>
                    <fullName>Archive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Birthdate__c</fullName>
        <encrypted>true</encrypted>
        <label>Birthdate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <formula>HYPERLINK(&quot;/&quot; + Id, &quot;Contact Record&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Record</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsFromVFPage__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is used for Relocate function purposes</description>
        <label>IsFromVFPage</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Status of Contact.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force/src/objects/Contact_Role__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Eye Care Professional</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accounting</fullName>
                </value>
                <value>
                    <fullName>Board Member/ Officer</fullName>
                </value>
                <value>
                    <fullName>Dean</fullName>
                </value>
                <value>
                    <fullName>Doctor-Employee</fullName>
                </value>
                <value>
                    <fullName>Doctor-Owner</fullName>
                </value>
                <value>
                    <fullName>Doctor-Unspecified</fullName>
                </value>
                <value>
                    <fullName>Group Administrator</fullName>
                </value>
                <value>
                    <fullName>Lab Technician</fullName>
                </value>
                <value>
                    <fullName>Member</fullName>
                </value>
                <value>
                    <fullName>Office Administration</fullName>
                </value>
                <value>
                    <fullName>Office Manager</fullName>
                </value>
                <value>
                    <fullName>Optical Buyer</fullName>
                </value>
                <value>
                    <fullName>Optical Manager</fullName>
                </value>
                <value>
                    <fullName>Optician</fullName>
                </value>
                <value>
                    <fullName>Optician-Owner</fullName>
                </value>
                <value>
                    <fullName>Owner</fullName>
                </value>
                <value>
                    <fullName>Student</fullName>
                </value>
                <value>
                    <fullName>Unspecified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force/src/classes/VSPR1_RelocateController.cls
/**
* Class Name: VSPR1_Relocate
* @author: Marvin B. Gatchalian
* Date: 27.MAY.2013
* Requirement/Project Name: VSP
* @description: Handles relocation of contact to new Account and can create contact role.
*/


public class VSPR1_RelocateController {

    public string Roletype {get;set;}
    public string Myid {get;set;}   
    public string CurrentAccount {get;set;}
    public string CurrentAccountid {get;set;}
    public Contact_Role__c oContactRole;
    public string contactID {get;set;}
    public Contact contact {get;set;}
    public DateTime curRoleEndDate {get;set;}
    public List<Contact_Role__c> cRoleList;
    public Contact_Role__c oldContRole {get;set;} 
    public Boolean endDateValError {get;set;}
    
    public VSPR1_RelocateController(ApexPages.StandardController controller) {
        this.oContactRole = (Contact_Role__c)controller.getRecord();
        contactID = ApexPages.currentPage().getParameters().get('cid'); 
        Myid = contactID;
        Initialize();
    }
    
    Private void Initialize (){
        contact  = new Contact();
        contact  = [SELECT Account.name, AccountID,Birthdate__c from Contact  where id = :contactID];
        CurrentAccount = contact.Account.name;
        CurrentAccountid = contact.AccountId;
        
    }
    
    public List<Contact_Role__c> getcRole () {
          cRoleList = [Select Type__c,Contact__r.Birthdate__c from Contact_Role__c where 
          Account__c= :CurrentAccountid and Contact__c = :contactID];
          //system.assertEquals(cRoleList.size(),10);
          //cRoleList[0].Contact__r.BirthDate = null;
          
          try{              
                oldContRole = [Select id, Contact__r.Birthdate__c from Contact_Role__c LIMIT 1];
                oldContRole.Contact__r.Birthdate__c = null;
              
              //oldContRole = [Select id, Contact__r.BirthDate from Contact_Role__c where Account__c= :CurrentAccountid and Contact__c = :contactID LIMIT 1];              
                             
          }catch( Exception ex ){
          } 
          return cRoleList;
    }

   // public List<SelectOption> getRoletypes() {
   //     List<SelectOption> options = new List<SelectOption>();
   //   List<Schema.picklistEntry> PL = Contact_Role__c.fields.Type__c.getDescribe().getpicklistvalues();
   //     for(schema.PickListEntry p:PL){
   //         options.add(new selectoption(p.getLabel(), p.getvalue()));
   //   }
   //    return options;
   // }
      
    
     public Pagereference DoSave() {
        endDateValError = false;
        
        //system.assertEquals(a.Contact__r.BirthDate,date.today());
        
        //PageReference pageRef = new PageReference('/');
        //List <Contact_Role__c> a = getcrole();
        //system.assertequals (a[0].BirthDate, a[0].BirthDate + 1);
    
        Contact oContact = [select id,Accountid, Birthdate__c from Contact where id = :contactID];
        oContact.accountid = oContactRole.Account__c;
        oContact.IsFromVFPage__c = true;  
        
            
        //try{
        Savepoint sp = Database.setSavepoint();
                                                    
            update oContact;
            oContact.IsFromVFPage__c = false;
            update oContact;               
         //}catch( Exception ex ){
          //}
        
        
        
        /*
        Account account = [select id,Status__c from Account where id = :oContact.accountid LIMIT 1];
        account.Status__c = 'Pending Account';
        try{
           update account;            
          }catch( Exception ex ){
          }
        */
        
        /*
        Set<String> incStatus = new Set<String>();
        incStatus.add('Completed');
        incStatus.add('Deferred');
        */
                
        //List<Task> tasks = [Select WhoId, WhatId, Status from Task where Status NOT IN: incStatus and WhoId =: oContact.id];
        List<Task> tasks = [Select WhoId, WhatId, Status from Task where WhoId =: oContact.id];
        for (Task task : tasks){
            //.debug('Task-----' + task);
            if(!(task.Status == 'Completed' || task.Status == 'Deferred')){
                task.Status = 'Pending New Contact';
            }
            task.WhatId = CurrentAccountid;
            //task.WhoId = null;
            
            
            
        }
        //try{
           update tasks;            
          //}catch( Exception ex ){
          //}
        try{
            Contact_Role__c oContactR = new Contact_Role__c();
        oContactR.Contact__c = contactID;
        oContactR.Account__c = oContactRole.Account__c;
        oContactR.Type__c = oContactRole.Type__c;
        oContactR.Start_Date__c = oContactRole.Start_Date__c;
        oContactR.End_Date__c = oContactRole.End_Date__c;
        //oContactR.Status__c = 'Active';
        //system.assertEquals(a.Contact__r.BirthDate, oContactRole.End_Date__c);
        insert oContactR;
        
        List<Contact_Role__c> updateOldcRole = [Select Type__c,Contact__r.Birthdate__c from Contact_Role__c where Account__c= :CurrentAccountid and Contact__c = :contactID];
        for(Contact_Role__c old : updateOldcRole){
            //system.assertEquals(a.Contact__r.BirthDate,date.today());
            old.End_Date__c = oldContRole.Contact__r.Birthdate__c;
        }
        //try{
           update updateOldcRole;            
          //}catch( Exception ex ){
          //}                
        return new PageReference('/' + oContact.id);
        }catch (DmlException e){
            Database.rollback(sp);
            String error = e.getMessage();
            String validError = 'Setting the “Contact Role End date” that precedes the “Contact Role Start Date” is not allowed';
            
            if (error.contains(validError)){
                //system.assertEquals(error,'hi');
                    endDateValError = true;
                    //ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.ERROR, 'Setting the “Contact Role End date” that precedes the “Contact Role Start Date” is not allowed.');
                    //ApexPages.addMessage(msg);
                    
                }
            return null;    
        }
        
        
        
    }
}