force/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Bypass_VC_Validation_Rules__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass VC Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Location_Type__c</fullName>
        <label>Location Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>M - VSP Member Location</fullName>
                </value>
                <value>
                    <fullName>A - Affiliate Provider Location</fullName>
                </value>
                <value>
                    <fullName>F - Laser Vision Correction (LVC)</fullName>
                </value>
                <value>
                    <fullName>X - Client Authorized Location (GAP)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of Account.</description>
        <inlineHelpText>A = Active 
Inactive = Not a Current Customer of any LOB. 
Closed = Business has ceased operations 
New = In process of becoming an Active account</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Submit for Approval</fullName>
                </value>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Inactive Ownership Change</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
                <value>
                    <fullName>Marked for Deletion</fullName>
                </value>
                <value>
                    <fullName>Archive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vision_Care_Effective_Date__c</fullName>
        <label>Vision Care Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Care_End_Date__c</fullName>
        <label>Vision Care End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Care_Location_Key__c</fullName>
        <encrypted>true</encrypted>
        <label>Vision Care Location Key</label>
        <length>125</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Bypass_VC_Validation_Rules__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass VC Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <formula>HYPERLINK(&quot;/&quot; + Id, &quot;Contact Record&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Record</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Doctor_Type__c</fullName>
        <label>Doctor Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>M - VSP Member Doctor</fullName>
                </value>
                <value>
                    <fullName>A - Affiliate Provider</fullName>
                </value>
                <value>
                    <fullName>F - Laser Vision Correction (LVC)</fullName>
                </value>
                <value>
                    <fullName>S - School Faculty Provider</fullName>
                </value>
                <value>
                    <fullName>X - Client Authorized Provider (GAP)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Status of Contact.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vision_Care_Effective_Date__c</fullName>
        <label>Vision Care Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Care_End_Date__c</fullName>
        <label>Vision Care End Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force/src/objects/Contact_Role__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Eye Care Professional</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Fee_Code__c</fullName>
        <label>Fee Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accounting</fullName>
                </value>
                <value>
                    <fullName>Board Member/ Officer</fullName>
                </value>
                <value>
                    <fullName>Dean</fullName>
                </value>
                <value>
                    <fullName>Doctor-Employee</fullName>
                </value>
                <value>
                    <fullName>Doctor-Owner</fullName>
                </value>
                <value>
                    <fullName>Doctor-Unspecified</fullName>
                </value>
                <value>
                    <fullName>Group Administrator</fullName>
                </value>
                <value>
                    <fullName>Lab Technician</fullName>
                </value>
                <value>
                    <fullName>Member</fullName>
                </value>
                <value>
                    <fullName>Office Administration</fullName>
                </value>
                <value>
                    <fullName>Office Manager</fullName>
                </value>
                <value>
                    <fullName>Optical Buyer</fullName>
                </value>
                <value>
                    <fullName>Optical Manager</fullName>
                </value>
                <value>
                    <fullName>Optician</fullName>
                </value>
                <value>
                    <fullName>Optician-Owner</fullName>
                </value>
                <value>
                    <fullName>Owner</fullName>
                </value>
                <value>
                    <fullName>Student</fullName>
                </value>
                <value>
                    <fullName>Unspecified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force/src/objects/DVIWebService__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Setting for the DVI Web Service URL and token header</description>
    <label>DVI Web Service</label>
</CustomObject>

force/src/objects/General_Table__c.object
<CustomObject>
    <fields>
        <fullName>Code_Description__c</fullName>
        <label>Code Description</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Table__c</fullName>
        <label>Table</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>General Table</label>
    <nameField>
        <label>Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>General Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force/src/objects/Network_Relationship__c.object
<CustomObject>
    <description>Custom object to track Payment Relationships between doctors and offices.</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Network Relationships</relationshipLabel>
        <relationshipName>Network_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Bypass_VC_Validation_Rules__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass VC Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact_Role__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact Role</label>
        <referenceTo>Contact_Role__c</referenceTo>
        <relationshipName>Payment_Relationships</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Directory_End_Date__c</fullName>
        <label>Directory End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Fee_Code__c</fullName>
        <defaultValue>&quot;NF&quot;</defaultValue>
        <label>Fee Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LVC_Negotiated_Discount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>LVC Negotiated Discount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Program_Effective_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Program Effective Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Program_End_Date__c</fullName>
        <label>Program End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Program_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup relationship field from Network Relationship to General Table object</description>
        <label>Program ID</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>General_Table__c.Table__c</field>
                <operation>equals</operation>
                <value>PRSP</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>General_Table__c</referenceTo>
        <relationshipLabel>Network Relationships</relationshipLabel>
        <relationshipName>Network_Relationships</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Provider Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Network Relationships</relationshipLabel>
        <relationshipName>Network_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_Care_Location_Key__c</fullName>
        <label>Vision Care Location Key</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Network Relationship</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Network Relationship Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Network Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force/src/classes/VSPR29_Batch_ChangeTaxIdNetRel_Test.cls
//Test class for Batch_ChangeTaxIdNetRel.apxc
@isTest
private class VSPR29_Batch_ChangeTaxIdNetRel_Test {
    
    private static testMethod void nrTestBatch(){
        //Contact Role or NR needs DVI custom setting
        DVIWebService__c dviWeb = new DVIWebService__c(); 
        dviWeb.Name = 'DVI Values';
        insert dviWeb;
        
        Id artId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
        //Create Account
        Account account_obj = new Account(Name = 'Name904', Status__c = 'New', Location_Type__c = 'A - Affiliate Provider Location', RecordTypeId = artId,
                                          Vision_Care_Effective_Date__c = date.today().adddays(-2), Vision_Care_End_Date__c = date.today().adddays(30));
        Insert account_obj; 
        
        //Create Contact        
        Contact contact_obj = new Contact(AccountId = account_obj.id, LastName = 'LastName241', FirstName = 'First834', Doctor_Type__c = 'A - Affiliate Provider');
        Insert contact_obj; 
        
        //Create Contact Role
        Contact_Role__c cr_obj = new Contact_Role__c(Type__c = 'Doctor-Owner', Start_Date__c = date.today().adddays(-2), End_Date__c = date.today().adddays(30), 
                                                     Account__c = account_obj.Id, Contact__c = contact_obj.Id);
        
        insert cr_obj;
        
        //Create Program
        General_Table__c gt_obj = new General_Table__c(Name = 'TEST', Code_Description__c = 'test5107', Table__c = 'PRSP', Status__c = 'Active');
        insert gt_obj;
        
        //Create Network Relationship
        Network_Relationship__c nr_obj = new Network_Relationship__c(Program_ID__c = gt_obj.Id, Program_End_Date__c = date.today().adddays(10), Directory_End_Date__c = date.today().adddays(10), 
                                                                     Account_Name__c = account_obj.id, Contact_Role__c = cr_obj.Id, Provider_Name__c = contact_obj.id,
                                                                     Vision_Care_Location_Key__c = 'TEST01', Fee_Code__c = 'TS', LVC_Negotiated_Discount__c = 0,
                                                                     Program_Effective_Date__c = date.today().adddays(-2), Bypass_VC_Validation_Rules__c = false);
        System.debug('nr_obj + ' + nr_obj);
        
        Test.startTest();
        insert nr_obj;        
        
        System.debug('nr_obj select ' + [SELECT Id FROM Network_Relationship__c WHERE Account_Name__c = :account_obj.Id AND Fee_Code__c <> NULL]);
        
        //To test for when program end date is not null
        List<Account> ac = [SELECT Id, Name FROM Account WHERe Name = 'Name904' LIMIT 1];
        Map<String,String> lbamap = new Map<String,String>();
        lbamap.put('TEST02','TEST03');
        //End date
        Date dt = date.today().adddays(9);
        //Start Date
        Date stdt = date.today().adddays(-2);
        
        Batch_ChangeTaxIdNetRel BC = new Batch_ChangeTaxIdNetRel();
        BC.lstBusinessAccounts = ac;
        BC.accTEMP_Vision_Care_End_Date = dt;
        BC.lbaMap = lbamap;
        BC.acc_Vision_Care_Effective_Date = stdt;
        BC.acc_Vision_Care_End_Date = dt;
        Id batchId = Database.executeBatch(BC);
        Test.stopTest();
    }
    private static testMethod void nrtestBatch2(){
        
        //Contact Role or NR needs DVI custom setting
        DVIWebService__c dviWeb = new DVIWebService__c(); 
        dviWeb.Name = 'DVI Values';
        insert dviWeb;
        
        Id artId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
        //Create Account
        Account account_obj = new Account(Name = 'Name904', Status__c = 'New', Location_Type__c = 'A - Affiliate Provider Location', RecordTypeId = artId,
                                          Vision_Care_Effective_Date__c = date.today().adddays(-2), Vision_Care_End_Date__c = date.today().adddays(30));
        Insert account_obj; 
        
        //Create Contact        
        Contact contact_obj = new Contact(AccountId = account_obj.id, LastName = 'LastName241', FirstName = 'First834', Doctor_Type__c = 'A - Affiliate Provider');
        Insert contact_obj; 
        
        //Create Contact Role
        Contact_Role__c cr_obj = new Contact_Role__c(Type__c = 'Doctor-Owner', Start_Date__c = date.today().adddays(-2), End_Date__c = date.today().adddays(30), 
                                                     Account__c = account_obj.Id, Contact__c = contact_obj.Id);
        
        insert cr_obj;
        
        //Create Program
        General_Table__c gt_obj = new General_Table__c(Name = 'TEST', Code_Description__c = 'test5107', Table__c = 'PRSP', Status__c = 'Active');
        insert gt_obj;
        
        //Create Network Relationship
        Network_Relationship__c nr_obj = new Network_Relationship__c(Program_ID__c = gt_obj.Id, Program_End_Date__c = null, Directory_End_Date__c = date.today().adddays(10), 
                                                                     Account_Name__c = account_obj.id, Contact_Role__c = cr_obj.Id, Provider_Name__c = contact_obj.id,
                                                                     Vision_Care_Location_Key__c = 'TEST01', Fee_Code__c = 'TS', LVC_Negotiated_Discount__c = 0,
                                                                     Program_Effective_Date__c = date.today().adddays(2), Bypass_VC_Validation_Rules__c = false);
        System.debug('nr_obj + ' + nr_obj);
        
        Test.startTest();
        insert nr_obj;        
        
        System.debug('nr_obj select ' + [SELECT Id FROM Network_Relationship__c WHERE Account_Name__c = :account_obj.Id AND Fee_Code__c <> NULL]);
        
        //Testmethod to test for when program effective date > accTEMP_Vision_Care_End_Date
        List<Account> ac = [SELECT Id, Name FROM Account WHERe Name = 'Name904' LIMIT 1];
        Map<String,String> lbamap = new Map<String,String>();
        lbamap.put('TEST02','TEST03');
        //End date
        Date dt = date.today().adddays(-9);
        //Start Date
        Date stdt = date.today().adddays(-2);
        
        Batch_ChangeTaxIdNetRel BC = new Batch_ChangeTaxIdNetRel();
        BC.lstBusinessAccounts = ac;
        BC.accTEMP_Vision_Care_End_Date = dt;
        BC.lbaMap = lbamap;
        BC.acc_Vision_Care_Effective_Date = stdt;
        BC.acc_Vision_Care_End_Date = dt;
        Id batchId = Database.executeBatch(BC);
        Test.stopTest();
    }
        private static testMethod void nrtestBatch3(){
        
        //Contact Role or NR needs DVI custom setting
        DVIWebService__c dviWeb = new DVIWebService__c(); 
        dviWeb.Name = 'DVI Values';
        insert dviWeb;
        
        Id artId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
        //Create Account
        Account account_obj = new Account(Name = 'Name904', Status__c = 'New', Location_Type__c = 'A - Affiliate Provider Location', RecordTypeId = artId,
                                          Vision_Care_Effective_Date__c = date.today().adddays(-2), Vision_Care_End_Date__c = date.today().adddays(30));
        Insert account_obj; 
        
        //Create Contact        
        Contact contact_obj = new Contact(AccountId = account_obj.id, LastName = 'LastName241', FirstName = 'First834', Doctor_Type__c = 'A - Affiliate Provider');
        Insert contact_obj; 
        
        //Create Contact Role
        Contact_Role__c cr_obj = new Contact_Role__c(Type__c = 'Doctor-Owner', Start_Date__c = date.today().adddays(-2), End_Date__c = date.today().adddays(30), 
                                                     Account__c = account_obj.Id, Contact__c = contact_obj.Id);
        
        insert cr_obj;
        
        //Create Program
        General_Table__c gt_obj = new General_Table__c(Name = 'TEST', Code_Description__c = 'test5107', Table__c = 'PRSP', Status__c = 'Active');
        insert gt_obj;
        
        //Create Network Relationship
        Network_Relationship__c nr_obj = new Network_Relationship__c(Program_ID__c = gt_obj.Id, Program_End_Date__c = null, Directory_End_Date__c = date.today().adddays(10), 
                                                                     Account_Name__c = account_obj.id, Contact_Role__c = cr_obj.Id, Provider_Name__c = contact_obj.id,
                                                                     Vision_Care_Location_Key__c = 'TEST01', Fee_Code__c = 'TS', LVC_Negotiated_Discount__c = 0,
                                                                     Program_Effective_Date__c = date.today().adddays(-2), Bypass_VC_Validation_Rules__c = false);
        System.debug('nr_obj + ' + nr_obj);
        
        Test.startTest();
        insert nr_obj;        
        
        System.debug('nr_obj select ' + [SELECT Id FROM Network_Relationship__c WHERE Account_Name__c = :account_obj.Id AND Fee_Code__c <> NULL]);
        
        //Testmethod to test for when program effective date > accTEMP_Vision_Care_End_Date
        List<Account> ac = [SELECT Id, Name FROM Account WHERe Name = 'Name904' LIMIT 1];
        Map<String,String> lbamap = new Map<String,String>();
        lbamap.put('TEST02','TEST03');
        //End date
        Date dt = date.today().adddays(9);
        //Start Date
        Date stdt = date.today().adddays(-2);
        
        Batch_ChangeTaxIdNetRel BC = new Batch_ChangeTaxIdNetRel();
        BC.lstBusinessAccounts = ac;
        BC.accTEMP_Vision_Care_End_Date = dt;
        BC.lbaMap = lbamap;
        BC.acc_Vision_Care_Effective_Date = stdt;
        BC.acc_Vision_Care_End_Date = dt;
        Id batchId = Database.executeBatch(BC);
        Test.stopTest();
    }
}