force/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Location_Type__c</fullName>
        <label>Location Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>M - VSP Member Location</fullName>
                </value>
                <value>
                    <fullName>A - Affiliate Provider Location</fullName>
                </value>
                <value>
                    <fullName>F - Laser Vision Correction (LVC)</fullName>
                </value>
                <value>
                    <fullName>X - Client Authorized Location (GAP)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of Account.</description>
        <inlineHelpText>A = Active 
Inactive = Not a Current Customer of any LOB. 
Closed = Business has ceased operations 
New = In process of becoming an Active account</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Submit for Approval</fullName>
                </value>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Inactive Ownership Change</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
                <value>
                    <fullName>Marked for Deletion</fullName>
                </value>
                <value>
                    <fullName>Archive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <formula>HYPERLINK(&quot;/&quot; + Id, &quot;Contact Record&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Record</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Doctor_Type__c</fullName>
        <label>Doctor Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>M - VSP Member Doctor</fullName>
                </value>
                <value>
                    <fullName>A - Affiliate Provider</fullName>
                </value>
                <value>
                    <fullName>F - Laser Vision Correction (LVC)</fullName>
                </value>
                <value>
                    <fullName>S - School Faculty Provider</fullName>
                </value>
                <value>
                    <fullName>X - Client Authorized Provider (GAP)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Status of Contact.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force/src/objects/Contact_Role__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Eye Care Professional</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status_Formula__c</fullName>
        <formula>IF( End_Date__c &lt; Today(),&quot;Inactive&quot;,&quot;Active&quot;)</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accounting</fullName>
                </value>
                <value>
                    <fullName>Board Member/ Officer</fullName>
                </value>
                <value>
                    <fullName>Dean</fullName>
                </value>
                <value>
                    <fullName>Doctor-Employee</fullName>
                </value>
                <value>
                    <fullName>Doctor-Owner</fullName>
                </value>
                <value>
                    <fullName>Doctor-Unspecified</fullName>
                </value>
                <value>
                    <fullName>Group Administrator</fullName>
                </value>
                <value>
                    <fullName>Lab Technician</fullName>
                </value>
                <value>
                    <fullName>Member</fullName>
                </value>
                <value>
                    <fullName>Office Administration</fullName>
                </value>
                <value>
                    <fullName>Office Manager</fullName>
                </value>
                <value>
                    <fullName>Optical Buyer</fullName>
                </value>
                <value>
                    <fullName>Optical Manager</fullName>
                </value>
                <value>
                    <fullName>Optician</fullName>
                </value>
                <value>
                    <fullName>Optician-Owner</fullName>
                </value>
                <value>
                    <fullName>Owner</fullName>
                </value>
                <value>
                    <fullName>Student</fullName>
                </value>
                <value>
                    <fullName>Unspecified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>VSP_Network_Provider__c</fullName>
        <defaultValue>false</defaultValue>
        <label>VSP Network Provider</label>
        <type>Checkbox</type>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force/src/objects/General_Table__c.object
<CustomObject>
    <fields>
        <fullName>Code_Description__c</fullName>
        <label>Code Description</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Table__c</fullName>
        <label>Table</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>General Table</label>
    <nameField>
        <label>Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>General Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force/src/objects/Network_Relationship__c.object
<CustomObject>
    <description>Custom object to track Payment Relationships between doctors and offices.</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Network Relationships</relationshipLabel>
        <relationshipName>Network_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Role__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact Role</label>
        <referenceTo>Contact_Role__c</referenceTo>
        <relationshipName>Payment_Relationships</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Effective_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Program Effective Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Program_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup relationship field from Network Relationship to General Table object</description>
        <label>Program ID</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>General_Table__c.Table__c</field>
                <operation>equals</operation>
                <value>PRSP</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>General_Table__c</referenceTo>
        <relationshipLabel>Network Relationships</relationshipLabel>
        <relationshipName>Network_Relationships</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Provider Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Network Relationships</relationshipLabel>
        <relationshipName>Network_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Network Relationship</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Network Relationship Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Network Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force/src/classes/NetworkRelTriggerForProgramIdHandlerTest.cls
@isTest(SeeAllData=false)
private class NetworkRelTriggerForProgramIdHandlerTest{
    //@testSetup
    private static testmethod void setupTestData(){
        
        // get RecordType Name
        Id recType = [SELECT Id from RecordType WHERE sObjectType = 'Account' AND Name = 'Business Account'].Id; 
        
        //Create Account
        Account account_obj = new Account(Name = 'Name904', Status__c = 'New', Location_Type__c = 'M - VSP Member Location', RecordTypeId = recType);
        Insert account_obj; 
        
        Id ConRecType = [SELECT Id from RecordType WHERE sObjectType = 'Contact' AND Name = 'Eye Care Professional'].Id; 
        
        //Create Contact        
        Contact contact_obj = new Contact(AccountId = account_obj.id, LastName = 'LastName241', FirstName = 'First834', Doctor_Type__c = 'M - VSP Member Doctor', RecordTypeId = ConRecType);
        Insert contact_obj; 
        
        //Create 2 Contact Role
        Contact_Role__c cr_obj = new Contact_Role__c(Type__c = 'Doctor-Employee', Start_Date__c = date.today().adddays(-2), End_Date__c = date.today().adddays(+2), 
                                                     Account__c = account_obj.Id, Contact__c = contact_obj.Id, VSP_Network_Provider__c = true);
        Contact_Role__c cr_obj2 = new Contact_Role__c(Type__c = 'Doctor-Owner', Start_Date__c = date.today().adddays(-2), End_Date__c = date.today().adddays(+2), 
                                                      Account__c = account_obj.Id, Contact__c = contact_obj.Id, VSP_Network_Provider__c = true);
        insert cr_obj;
        insert cr_obj2;
        
        //Create Program
        General_Table__c gt_obj = new General_Table__c(Name = 'ADVTG', Code_Description__c = 'test5107', Table__c = 'PRSP', Status__c = 'Active');
        insert gt_obj;
        
        
        //Create 2 Network Relationship
        Network_Relationship__c nr_obj = new Network_Relationship__c(Contact_Role__c = cr_obj.Id, Account_Name__c = account_obj.id, Provider_Name__c = contact_obj.id, 
                                                                     Program_ID__c = gt_obj.Id, Program_Effective_Date__c = date.today().adddays(-2));
        test.startTest();
        insert nr_obj;
        test.stopTest();
        
        //System.debug(LoggingLevel.ERROR);
        NetworkRelTriggerForProgramIdHandler.applyActiveCostcoPIToNewDoctor(new set<id>{nr_obj.id});
        //NetworkRelationshipTriggerHandler.applyActiveCostcoPIToNewDoctor(new set<id>{nr_obj.id});
        //System.debug(LoggingLevel.ERROR);
        
        
    }
    /*    static testMethod void test_applyActiveCostcoPIToNewDoctor_UseCase1(){
test.startTest();
List<Account> account_obj  =  [SELECT Name, Status__c from Account WHERE Name = 'Name904' AND Location_Type__c = 'M - VSP Member Location' LIMIT 1];
System.assertEquals(true,account_obj.size()>0);

//Account account_obj  =  [SELECT Name, Status__c from Account WHERE Name = 'Name904' AND Location_Type__c = 'M - VSP Member Location' LIMIT 1];
List<Contact> contact_obj  =  [SELECT AccountId, LastName, FirstName from Contact WHERE LastName = 'LastName241' AND FirstName = 'First834' AND Doctor_Type__c = 'M - VSP Member Doctor' LIMIT 1];
System.assertEquals(true,contact_obj.size()>0);
List<Contact_Role__c> cr_obj = [SELECT Account__c, Status_Formula__c FROM Contact_Role__c WHERE Type__c = 'Doctor-Employee' OR Type__c = 'Doctor-Owner' LIMIT 1];
System.assertEquals(true, cr_obj.size()>0);

NetworkRelationshipTriggerHandler obj01 = new NetworkRelationshipTriggerHandler();
NetworkRelationshipTriggerHandler.validate = false;
NetworkRelationshipTriggerHandler.applyActiveCostcoPIToNewDoctor_recursionX = false;
NetworkRelationshipTriggerHandler.applyActiveCostcoPIToNewDoctor(new set<id>());
test.stopTest();        
}
*/    
}