force/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Group_Sub_Type__c</fullName>
        <inlineHelpText>Buying Group - Takes financial responsibility for their members.
Alliance - Offers their members certain products at discounts.
Association - Individuals who join a group.
Educational Institution - School or College.
DOLP - Doctor Owned Lab Program.</inlineHelpText>
        <label>Account Group Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Buying Group</fullName>
                </value>
                <value>
                    <fullName>Alliance</fullName>
                </value>
                <value>
                    <fullName>Association</fullName>
                </value>
                <value>
                    <fullName>Educational Institution</fullName>
                </value>
                <value>
                    <fullName>DOLP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account_Type__c</fullName>
        <description>Is Account a Practice Account, Business Account or Account Group.</description>
        <inlineHelpText>Is Account a Practice Account, Business Account or Account Group.</inlineHelpText>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account Group</fullName>
                </value>
                <value>
                    <fullName>Business Account</fullName>
                </value>
                <value>
                    <fullName>Practice Account</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Altair_Exception__c</fullName>
        <label>Altair - Exception</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Altair_Field_Rep__c</fullName>
        <label>Altair - Field Rep</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Altair_Hybrid_Bebe__c</fullName>
        <label>Altair - Hybrid Bebe</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Altair_Key_Account__c</fullName>
        <label>Altair - Key Account</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Altair_Standard__c</fullName>
        <label>Altair Prospect Rep</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Eyefinity_Inside_Sales__c</fullName>
        <label>Eyefinity Inside Sales</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Eyefinity_Outside_Sales__c</fullName>
        <label>Eyefinity Outside Sales</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Global_Business_Development_Manager__c</fullName>
        <label>Global Business Development Manager</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Global_Business_Development_Partner__c</fullName>
        <label>Global Business Development Boundary</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marchon_Close_Out__c</fullName>
        <label>Marchon - Close Out</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marchon_Key_Account__c</fullName>
        <label>Marchon - Key Account</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marchon_Optical__c</fullName>
        <label>Marchon Prospect Rep</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marchon_Retail__c</fullName>
        <label>Marchon Retail</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ophthalmic_Business_Consultant__c</fullName>
        <label>Ophthalmic Business Consultant</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Optics_Contact_Lens_Consultant__c</fullName>
        <label>Optics Contact Lens Consultant</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Optics_Wholesale__c</fullName>
        <label>Optics Business Development Manager</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of Account.</description>
        <inlineHelpText>A = Active 
Inactive = Not a Current Customer of any LOB. 
Closed = Business has ceased operations 
New = In process of becoming an Active account</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Submit for Approval</fullName>
                </value>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Inactive Ownership Change</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
                <value>
                    <fullName>Marked for Deletion</fullName>
                </value>
                <value>
                    <fullName>Archive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tax_ID__c</fullName>
        <description>Account Tax ID.</description>
        <encrypted>true</encrypted>
        <inlineHelpText>Account Tax ID.</inlineHelpText>
        <label>Tax ID</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VC_EDS_NA__c</fullName>
        <label>Vision Care Network Administrator</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VC_Relationship_Manager__c</fullName>
        <defaultValue>&quot;PRMI0001&quot;</defaultValue>
        <label>Vision Care Relationship Manager</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Care_End_Date__c</fullName>
        <label>Vision Care End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Care_Location_Key__c</fullName>
        <encrypted>true</encrypted>
        <label>Vision Care Location Key</label>
        <length>125</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zipcode__c</fullName>
        <label>Zipcode</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <formula>HYPERLINK(&quot;/&quot; + Id, &quot;Contact Record&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Record</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Status of Contact.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vision_Care_End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Vision Care End Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

src/objects/Contact_Role__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Eye Care Professional</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <encryptionScheme>None</encryptionScheme>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accounting</fullName>
                </value>
                <value>
                    <fullName>Board Member/ Officer</fullName>
                </value>
                <value>
                    <fullName>Dean</fullName>
                </value>
                <value>
                    <fullName>Doctor-Employee</fullName>
                </value>
                <value>
                    <fullName>Doctor-Owner</fullName>
                </value>
                <value>
                    <fullName>Doctor-Unspecified</fullName>
                </value>
                <value>
                    <fullName>Group Administrator</fullName>
                </value>
                <value>
                    <fullName>Lab Technician</fullName>
                </value>
                <value>
                    <fullName>Member</fullName>
                </value>
                <value>
                    <fullName>Office Administration</fullName>
                </value>
                <value>
                    <fullName>Office Manager</fullName>
                </value>
                <value>
                    <fullName>Optical Buyer</fullName>
                </value>
                <value>
                    <fullName>Optical Manager</fullName>
                </value>
                <value>
                    <fullName>Optician</fullName>
                </value>
                <value>
                    <fullName>Optician-Owner</fullName>
                </value>
                <value>
                    <fullName>Owner</fullName>
                </value>
                <value>
                    <fullName>Student</fullName>
                </value>
                <value>
                    <fullName>Unspecified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/General_Table__c.object
<CustomObject>
    <fields>
        <fullName>Code_Description__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Code Description</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Table__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Table</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>General Table</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>General Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force/src/objects/Network_Relationship__c.object
<CustomObject>
    <description>Custom object to track Payment Relationships between doctors and offices.</description>
    <fields>
        <fullName>Contact_Role__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact Role</label>
        <referenceTo>Contact_Role__c</referenceTo>
        <relationshipName>Payment_Relationships</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vision_Care_Location_Key__c</fullName>
        <label>Vision Care Location Key</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Network Relationship</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Network Relationship Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Network Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/VSPR19_ChangeTaxIDCtrlTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class VSPR19_ChangeTaxIDCtrlTest {
  
  static testMethod void myUnitTest0() {
        // TO DO: implement unit test
        
        
        Account acc = new Account();
        acc.Name = 'Sample Account';
        acc.Status__c = 'New';
        acc.Altair_Standard__c = '001';
        acc.Altair_Field_Rep__c = '001'; 
        acc.Altair_Key_Account__c = '001';
        acc.Altair_Exception__c = '001'; 
        acc.Altair_Hybrid_Bebe__c = '001'; 
        acc.Ophthalmic_Business_Consultant__c = '001'; 
        acc.Optics_Contact_Lens_Consultant__c = '002'; 
        acc.Marchon_Key_Account__c = '001'; 
        acc.Marchon_Close_Out__c = '001'; 
        acc.Marchon_Optical__c = '001'; 
        acc.Marchon_Retail__c = '001';
        acc.VC_EDS_NA__c = '001'; 
        acc.Global_Business_Development_Manager__c = '001';
        acc.Global_Business_Development_Partner__c = '001';
        acc.VC_Relationship_Manager__c = '001'; // AMITSH 07/09/2015. Request # 1342. Added new field.
        acc.Optics_Wholesale__c = '001'; 
        acc.Eyefinity_Inside_Sales__c = '001'; 
        acc.Eyefinity_Outside_Sales__c = '002';
        insert acc;
        
        Id recordtype =[select Id from recordType where Name ='Business Account' and sObjectType ='Account' limit 1].Id;
        account acc1 = new account();
        acc1.name='test';
        acc1.recordTypeId = recordtype;
        acc1.email__c='abc@gmail.com';
        acc1.Tax_ID__c = '345433589';
        acc1.Fax = '223456';
        acc1.Phone = '96532';
        acc1.shippingStreet = '11US';
        acc1.Account_Type__c = 'Business Account';
        acc1.Zipcode__c= '01001' ;
        acc1.Account_Group_Sub_Type__c='ab';
        acc1.ParentId=acc.id;
        acc1.Vision_Care_Location_Key__c='371580129635 2';
        acc.Vision_Care_End_Date__c=date.today().adddays(-3);
        insert acc1;
        
       // Insert Contact
            Contact c = new Contact();
            c.FirstName = 'Rogers';
            c.LastName = 'Hornsby';
            c.AccountId = acc1.Id;
            insert c;

            Contact_Role__c cr = new Contact_Role__c();
            cr.Type__c = 'Doctor-Owner';
            cr.Start_Date__c = date.today().adddays(-2);
            cr.End_Date__c = date.today().adddays(30);
            cr.Account__c = acc1.Id;
            cr.Contact__c = c.Id;
            insert cr;

            
            General_Table__c gt = new General_Table__c();
            gt.Name = 'test5107';
            gt.Code_Description__c = 'test5107';
            gt.Table__c = 'PRSP';
            gt.Status__c = 'Active';
            insert gt;

            Network_Relationship__c nr = new Network_Relationship__c();
            nr.Contact_Role__c = cr.Id;
            nr.Account_Name__c = acc1.id;
            nr.Provider_Name__c = c.id;
            nr.Program_ID__c = gt.Id;
            nr.Program_Effective_Date__c = date.today().adddays(-2);
            nr.Program_End_Date__c = date.newInstance(2018,12,31);
            insert nr;
        
        
        PageReference pageRef = Page.VSPR19_ChangeTaxID;     
        
        pageRef.getParameters().put('id',acc.id);
        
        System.Test.setCurrentPage(pageRef); 
        //Instantiate and construct the controller class.     
        ApexPages.StandardController sc = new ApexPages.standardController(acc);
        // create an instance of the controller
        VSPR19_ChangeTaxIDCtrl controller = new VSPR19_ChangeTaxIDCtrl(sc);
        
        //controller.sapNumberSet.add(accRep.Sales_Rep__c);
        controller.validateVCEndDate();
        controller.createtaxId();
    }

    static testMethod void myUnitTest() {
        // TO DO: implement unit test
        
        
        Account acc = new Account();
        acc.Name = 'Sample Account';
        acc.Status__c = 'New';
        acc.Altair_Standard__c = '001';
        acc.Altair_Field_Rep__c = '001'; 
        acc.Altair_Key_Account__c = '001';
        acc.Altair_Exception__c = '001'; 
        acc.Altair_Hybrid_Bebe__c = '001'; 
        acc.Ophthalmic_Business_Consultant__c = '001'; 
        acc.Optics_Contact_Lens_Consultant__c = '002'; 
        acc.Marchon_Key_Account__c = '001'; 
        acc.Marchon_Close_Out__c = '001'; 
        acc.Marchon_Optical__c = '001'; 
        acc.Marchon_Retail__c = '001';
        acc.VC_EDS_NA__c = '001'; 
        acc.Global_Business_Development_Manager__c = '001';
        acc.Global_Business_Development_Partner__c = '001';
        acc.VC_Relationship_Manager__c = '001'; // AMITSH 07/09/2015. Request # 1342. Added new field.
        acc.Optics_Wholesale__c = '001'; 
        acc.Eyefinity_Inside_Sales__c = '001'; 
        acc.Eyefinity_Outside_Sales__c = '002';
        acc.Vision_Care_End_Date__c=date.today().adddays(-10);
        insert acc;
        
        Id recordtype =[select Id from recordType where Name ='Business Account' and sObjectType ='Account' limit 1].Id;
                account acc1 = new account();
                acc1.name='test';
                acc1.recordTypeId = recordtype;
                acc1.email__c='abc@gmail.com';
                acc1.Tax_ID__c = '345433589';
                acc1.Fax = '223456';
                acc1.Phone = '96532';
                acc1.shippingStreet = '11US';
                acc1.Account_Type__c = 'Business Account';
                acc1.Zipcode__c= '01001' ;
                acc1.Account_Group_Sub_Type__c='ab';
                acc1.ParentId=acc.id;
                acc1.Vision_Care_Location_Key__c='371580129635 2';
                acc1.Vision_Care_End_Date__c=date.today().adddays(-3);
                insert acc1;
        
       // Insert Contact
            Contact c = new Contact();
            c.FirstName = 'Rogers';
            c.LastName = 'Hornsby';
            c.AccountId = acc1.Id;
            insert c;

            Contact_Role__c cr = new Contact_Role__c();
            cr.Type__c = 'Doctor-Owner';
            cr.Start_Date__c = date.today().adddays(-2);
            cr.End_Date__c = date.today().adddays(30);
            cr.Account__c = acc1.Id;
            cr.Contact__c = c.Id;
            insert cr;

            
            General_Table__c gt = new General_Table__c();
            gt.Name = 'test5107';
            gt.Code_Description__c = 'test5107';
            gt.Table__c = 'PRSP';
            gt.Status__c = 'Active';
            insert gt;

            Network_Relationship__c nr = new Network_Relationship__c();
            nr.Contact_Role__c = cr.Id;
            nr.Account_Name__c = acc1.id;
            nr.Provider_Name__c = c.id;
            nr.Program_ID__c = gt.Id;
            nr.Program_Effective_Date__c = date.today().adddays(-2);
            nr.Program_End_Date__c = date.newInstance(2018,12,31);
            insert nr;
        
        
        PageReference pageRef = Page.VSPR19_ChangeTaxID;     
        
        pageRef.getParameters().put('id',acc.id);
        
        System.Test.setCurrentPage(pageRef); 
        //Instantiate and construct the controller class.     
        ApexPages.StandardController sc = new ApexPages.standardController(acc);
        // create an instance of the controller
        VSPR19_ChangeTaxIDCtrl controller = new VSPR19_ChangeTaxIDCtrl(sc);
        //controller.sapNumberSet.add(accRep.Sales_Rep__c);
        controller.createtaxId();
    }
    
    static testMethod void myUnitTest1() {
        // TO DO: implement unit test
        
        
        Account acc = new Account();
        acc.Name = 'Sample Account';
        acc.Status__c = 'New';
        acc.Altair_Standard__c = '001';
        acc.Altair_Field_Rep__c = '001'; 
        acc.Altair_Key_Account__c = '001';
        acc.Altair_Exception__c = '001'; 
        acc.Altair_Hybrid_Bebe__c = '001'; 
        acc.Ophthalmic_Business_Consultant__c = '001'; 
        acc.Optics_Contact_Lens_Consultant__c = '002'; 
        acc.Marchon_Key_Account__c = '001'; 
        acc.Marchon_Close_Out__c = '001'; 
        acc.Marchon_Optical__c = '001'; 
        acc.Marchon_Retail__c = '001';
        acc.VC_EDS_NA__c = '001'; 
        acc.Global_Business_Development_Manager__c = '001';
        acc.Global_Business_Development_Partner__c = '001';
        acc.VC_Relationship_Manager__c = '001'; // AMITSH 07/09/2015. Request # 1342. Added new field.
        acc.Optics_Wholesale__c = '001'; 
        acc.Eyefinity_Inside_Sales__c = '001'; 
        acc.Eyefinity_Outside_Sales__c = '002';
        acc.Vision_Care_End_Date__c=date.today().adddays(-10);
        acc.Vision_Care_Effective_Date__c = Date.today().adddays(-10);
        insert acc;
        
        Id recordtype =[select Id from recordType where Name ='Business Account' and sObjectType ='Account' limit 1].Id;
                account acc1 = new account();
                acc1.name='test';
                acc1.recordTypeId = recordtype;
                acc1.email__c='abc@gmail.com';
                acc1.Tax_ID__c = '345433589';
                acc1.Fax = '223456';
                acc1.Phone = '96532';
                acc1.shippingStreet = '11US';
                acc1.Account_Type__c = 'Business Account';
                acc1.Zipcode__c= '01001' ;
                acc1.Account_Group_Sub_Type__c='ab';
                acc1.ParentId=acc.id;
                acc1.Vision_Care_Location_Key__c='371580129635 2';
                acc1.Vision_Care_End_Date__c=date.today().adddays(-3);
                acc1.Vision_Care_Effective_Date__c = Date.today().adddays(-3);
                //acc1.Vision_Care_Effective_Date__c = date.today();
                insert acc1;
        
       // Insert Contact
            Contact c = new Contact();
            c.FirstName = 'Rogers';
            c.LastName = 'Hornsby';
            c.AccountId = acc1.Id;
            insert c;

            Contact_Role__c cr = new Contact_Role__c();
            cr.Type__c = 'Doctor-Owner';
            cr.Start_Date__c = date.today().adddays(-2);
            cr.End_Date__c = date.today().adddays(30);
            cr.Account__c = acc1.Id;
            cr.Contact__c = c.Id;
            insert cr;

            
            General_Table__c gt = new General_Table__c();
            gt.Name = 'ADVTG';
            gt.Code_Description__c = 'test5107';
            gt.Table__c = 'PRSP';
            gt.Status__c = 'Active';
            insert gt;

            Network_Relationship__c nr = new Network_Relationship__c();
            nr.Contact_Role__c = cr.Id;
            nr.Account_Name__c = acc1.id;
            nr.Provider_Name__c = c.id;
            nr.Program_ID__c = gt.Id;
            nr.Program_Effective_Date__c = date.today().adddays(-2);
            insert nr;
            
            NetworkRelTriggerForProgramIdHandler.applyActiveCostcoPIToNewDoctor(new set<id>{nr.id});
            NetworkRelationshipTriggerHandler.applyActiveCostcoPIToNewDoctor(new set<id>{nr.id});
        
        
        PageReference pageRef = Page.VSPR19_ChangeTaxID;     
        
        pageRef.getParameters().put('id',acc.id);
        
        System.Test.setCurrentPage(pageRef); 
        //Instantiate and construct the controller class.     
        ApexPages.StandardController sc = new ApexPages.standardController(acc);
        // create an instance of the controller
        VSPR19_ChangeTaxIDCtrl controller = new VSPR19_ChangeTaxIDCtrl(sc);
        
        //controller.sapNumberSet.add(accRep.Sales_Rep__c);
        
        controller.validateVCEndDate();
        controller.createtaxId();
        controller.doCancel();
    }
    
 /*   static testMethod void myUnitTest8() {
        // TO DO: implement unit test
        
        
        Account acc = new Account();
        acc.Name = 'Sample Account';
        acc.Status__c = 'New';
        acc.Altair_Standard__c = '001';
        acc.Altair_Field_Rep__c = '001'; 
        acc.Altair_Key_Account__c = '001';
        acc.Altair_Exception__c = '001'; 
        acc.Altair_Hybrid_Bebe__c = '001'; 
        acc.Optics_VSPOne__c = '001'; 
        acc.Optics_Brand__c = '002'; 
        acc.Marchon_Key_Account__c = '001'; 
        acc.Marchon_Close_Out__c = '001'; 
        acc.Marchon_Optical__c = '001'; 
        acc.Marchon_Retail__c = '001';
        acc.VC_EDS_NA__c = '001'; 
        acc.Global_Business_Development_Manager__c = '001';
        acc.Global_Business_Development_Partner__c = '001';
        acc.VC_Relationship_Manager__c = '001'; // AMITSH 07/09/2015. Request # 1342. Added new field.
        acc.Optics_Wholesale__c = '001'; 
        acc.Eyefinity_Inside_Sales__c = '001'; 
        acc.Eyefinity_Outside_Sales__c = '002';
        insert acc;
        
        Id recordtype =[select Id from recordType where Name ='Business Account' and sObjectType ='Account' limit 1].Id;
                account acc1 = new account();
                acc1.name='test';
                acc1.recordTypeId = recordtype;
                acc1.email__c='abc@gmail.com';
                acc1.Tax_ID__c = '345433589';
                acc1.Fax = '223456';
                acc1.Phone = '96532';
                acc1.shippingStreet = '11US';
                acc1.Account_Type__c = 'Business Account';
                acc1.Zipcode__c= '01001' ;
                acc1.Account_Group_Sub_Type__c='ab';
                acc1.ParentId=acc.id;
                acc1.Location_type__c='M - VSP Member Location';
                acc1.Vision_Care_Location_Key__c='371580129635 2';
                acc.Vision_Care_End_Date__c=date.today().adddays(-3);
                insert acc1;
        
       // Insert Contact
            Contact c = new Contact();
            c.FirstName = 'Rogers';
            c.LastName = 'Hornsby';
            c.AccountId = acc1.Id;
            c.doctor_type__c='M - VSP Member Doctor';
            insert c;

            Contact_Role__c cr = new Contact_Role__c();
            cr.Type__c = 'Doctor-Owner';
            cr.Start_Date__c = date.today().adddays(-2);
            cr.End_Date__c = date.today().adddays(30);
            cr.Account__c = acc1.Id;
            cr.Contact__c = c.Id;
            insert cr;

            
            General_Table__c gt = new General_Table__c();
            gt.Name = 'VSP';
            gt.Code_Description__c = 'test5107';
            gt.Table__c = 'PRSP';
            gt.Status__c = 'Active';
            insert gt;

            Network_Relationship__c nr = new Network_Relationship__c();
            nr.Contact_Role__c = cr.Id;
            nr.Account_Name__c = acc1.id;
            nr.Provider_Name__c = c.id;
            nr.Program_ID__c = gt.Id;
            nr.Program_Effective_Date__c = date.today().adddays(-2);
            insert nr;
            
            NetworkRelationshipsHandler obj=new NetworkRelationshipsHandler();
            obj.restrictOverlapNetworkRelationShip(new list<Network_Relationship__c>{nr});
            
    }*/
    
  /*  static testMethod void myUnitTest7() {
        // TO DO: implement unit test
        
        
        Account acc = new Account();
        acc.Name = 'Sample Account';
        acc.Status__c = 'New';
        acc.Altair_Standard__c = '001';
        acc.Altair_Field_Rep__c = '001'; 
        acc.Altair_Key_Account__c = '001';
        acc.Altair_Exception__c = '001'; 
        acc.Altair_Hybrid_Bebe__c = '001'; 
        acc.Optics_VSPOne__c = '001'; 
        acc.Optics_Brand__c = '002'; 
        acc.Marchon_Key_Account__c = '001'; 
        acc.Marchon_Close_Out__c = '001'; 
        acc.Marchon_Optical__c = '001'; 
        acc.Marchon_Retail__c = '001';
        acc.VC_EDS_NA__c = '001'; 
        acc.Global_Business_Development_Manager__c = '001';
        acc.Global_Business_Development_Partner__c = '001';
        acc.VC_Relationship_Manager__c = '001'; // AMITSH 07/09/2015. Request # 1342. Added new field.
        acc.Optics_Wholesale__c = '001'; 
        acc.Eyefinity_Inside_Sales__c = '001'; 
        acc.Eyefinity_Outside_Sales__c = '002';
        insert acc;
        
        Id recordtype =[select Id from recordType where Name ='Business Account' and sObjectType ='Account' limit 1].Id;
                account acc1 = new account();
                acc1.name='test';
                acc1.recordTypeId = recordtype;
                acc1.email__c='abc@gmail.com';
                acc1.Tax_ID__c = '345433589';
                acc1.Fax = '223456';
                acc1.Phone = '96532';
                acc1.shippingStreet = '11US';
                acc1.Account_Type__c = 'Business Account';
                acc1.Zipcode__c= '01001' ;
                acc1.Account_Group_Sub_Type__c='ab';
                acc1.ParentId=acc.id;
                acc1.Location_type__c='M - VSP Member Location';
                acc1.Vision_Care_Location_Key__c='371580129635 2';
                acc.Vision_Care_End_Date__c=date.today().adddays(-3);
          VSPUtility.stopAccountTrigger=true;
            
                insert acc1;
        
       // Insert Contact
            Contact c = new Contact();
            c.FirstName = 'Rogers';
            c.LastName = 'Hornsby';
            c.AccountId = acc1.Id;
            c.doctor_type__c='M - VSP Member Doctor';
            insert c;

            Contact_Role__c cr = new Contact_Role__c();
            cr.Type__c = 'Doctor-Owner';
            cr.Start_Date__c = date.today().adddays(-2);
            cr.End_Date__c = date.today().adddays(30);
            cr.Account__c = acc1.Id;
            cr.Contact__c = c.Id;
            insert cr;

            
            General_Table__c gt = new General_Table__c();
            gt.Name = 'COSTA';
            gt.Code_Description__c = 'test5107';
            gt.Table__c = 'PRSP';
            gt.Status__c = 'Active';
            insert gt;

            Network_Relationship__c nr = new Network_Relationship__c();
            nr.Contact_Role__c = cr.Id;
            nr.Account_Name__c = acc1.id;
            nr.Provider_Name__c = c.id;
            nr.Program_ID__c = gt.Id;
            nr.Program_Effective_Date__c = date.today().adddays(-2);
            insert nr;
            
            NetworkRelationshipsHandler obj=new NetworkRelationshipsHandler();
            obj.restrictOverlapNetworkRelationShip(new list<Network_Relationship__c>{nr});
            
    }*/
    
  /*  static testMethod void myUnitTest9() {
        // TO DO: implement unit test
        
        
        Account acc = new Account();
        acc.Name = 'Sample Account';
        acc.Status__c = 'New';
        acc.Altair_Standard__c = '001';
        acc.Altair_Field_Rep__c = '001'; 
        acc.Altair_Key_Account__c = '001';
        acc.Altair_Exception__c = '001'; 
        acc.Altair_Hybrid_Bebe__c = '001'; 
        acc.Optics_VSPOne__c = '001'; 
        acc.Optics_Brand__c = '002'; 
        acc.Marchon_Key_Account__c = '001'; 
        acc.Marchon_Close_Out__c = '001'; 
        acc.Marchon_Optical__c = '001'; 
        acc.Marchon_Retail__c = '001';
        acc.VC_EDS_NA__c = '001'; 
        acc.Global_Business_Development_Manager__c = '001';
        acc.Global_Business_Development_Partner__c = '001';
        acc.VC_Relationship_Manager__c = '001'; // AMITSH 07/09/2015. Request # 1342. Added new field.
        acc.Optics_Wholesale__c = '001'; 
        acc.Eyefinity_Inside_Sales__c = '001'; 
        acc.Eyefinity_Outside_Sales__c = '002';
        VSPUtility.stopAccountTrigger=true;
        insert acc;
        
        Id recordtype =[select Id from recordType where Name ='Business Account' and sObjectType ='Account' limit 1].Id;
                account acc1 = new account();
                acc1.name='test';
                acc1.recordTypeId = recordtype;
                acc1.email__c='abc@gmail.com';
                acc1.Tax_ID__c = '345433589';
                acc1.Fax = '223456';
                acc1.Phone = '96532';
                acc1.shippingStreet = '11US';
                acc1.Account_Type__c = 'Business Account';
                acc1.Zipcode__c= '01001' ;
                acc1.Account_Group_Sub_Type__c='ab';
                acc1.ParentId=acc.id;
                acc1.Location_type__c='M - VSP Member Location';
                acc1.Vision_Care_Location_Key__c='371580129635 2';
                acc.Vision_Care_End_Date__c=date.today().adddays(-3);
                insert acc1;
        
       // Insert Contact
            Contact c = new Contact();
            c.FirstName = 'Rogers';
            c.LastName = 'Hornsby';
            c.AccountId = acc1.Id;
            c.doctor_type__c='M - VSP Member Doctor';
            insert c;

            Contact_Role__c cr = new Contact_Role__c();
            cr.Type__c = 'Doctor-Owner';
            cr.Start_Date__c = date.today().adddays(-2);
            cr.End_Date__c = date.today().adddays(30);
            cr.Account__c = acc1.Id;
            cr.Contact__c = c.Id;
            insert cr;

            
            General_Table__c gt = new General_Table__c();
            gt.Name = 'VWRK';
            gt.Code_Description__c = 'test5107';
            gt.Table__c = 'PRSP';
            gt.Status__c = 'Active';
            insert gt;

            Network_Relationship__c nr = new Network_Relationship__c();
            nr.Contact_Role__c = cr.Id;
            nr.Account_Name__c = acc1.id;
            nr.Provider_Name__c = c.id;
            nr.Program_ID__c = gt.Id;
            nr.Program_Effective_Date__c = date.today().adddays(-2);
            insert nr;
            
            NetworkRelationshipsHandler obj=new NetworkRelationshipsHandler();
            obj.restrictOverlapNetworkRelationShip(new list<Network_Relationship__c>{nr});
            
    }*/

    static testMethod void myUnitTest10() {
        // TO DO: implement unit test
        
        
        Account acc = new Account();
        acc.Name = 'Sample Account';
        acc.Status__c = 'New';
        acc.Altair_Standard__c = '001';
        acc.Altair_Field_Rep__c = '001'; 
        acc.Altair_Key_Account__c = '001';
        acc.Altair_Exception__c = '001'; 
        acc.Altair_Hybrid_Bebe__c = '001'; 
        acc.Ophthalmic_Business_Consultant__c = '001'; 
        acc.Optics_Contact_Lens_Consultant__c = '002'; 
        acc.Marchon_Key_Account__c = '001'; 
        acc.Marchon_Close_Out__c = '001'; 
        acc.Marchon_Optical__c = '001'; 
        acc.Marchon_Retail__c = '001';
        acc.VC_EDS_NA__c = '001'; 
        acc.Global_Business_Development_Manager__c = '001';
        acc.Global_Business_Development_Partner__c = '001';
        acc.VC_Relationship_Manager__c = '001'; // AMITSH 07/09/2015. Request # 1342. Added new field.
        acc.Optics_Wholesale__c = '001'; 
        acc.Eyefinity_Inside_Sales__c = '001'; 
        acc.Eyefinity_Outside_Sales__c = '002';
        acc.Vision_Care_End_Date__c=date.today().adddays(-10);
        insert acc;
        
        Id recordtype =[select Id from recordType where Name ='Business Account' and sObjectType ='Account' limit 1].Id;
        account acc1 = new account();
        acc1.name='test';
        acc1.recordTypeId = recordtype;
        acc1.email__c='abc@gmail.com';
        acc1.Tax_ID__c = '345433589';
        acc1.Fax = '223456';
        acc1.Phone = '96532';
        acc1.shippingStreet = '11US';
        acc1.Account_Type__c = 'Business Account';
        acc1.Zipcode__c= '01001' ;
        acc1.Account_Group_Sub_Type__c='ab';
        acc1.ParentId=acc.id;
        acc1.Vision_Care_Location_Key__c='371580129635 2';
        acc1.Vision_Care_Effective_Date__c = Date.today().adddays(-1);
       // acc1.Vision_Care_End_Date__c=date.today().adddays(-1);
        insert acc1;
        
       // Insert Contact
            Contact c = new Contact();
            c.FirstName = 'Rogers';
            c.LastName = 'Hornsby';
            c.AccountId = acc1.Id;
            insert c;

            Contact_Role__c cr = new Contact_Role__c();
            cr.Type__c = 'Doctor-Owner';
            cr.Start_Date__c = date.today().adddays(-2);
            cr.End_Date__c = date.today().adddays(30);
            cr.Account__c = acc1.Id;
            cr.Contact__c = c.Id;
            insert cr;

            
            General_Table__c gt = new General_Table__c();
            gt.Name = 'ADVTG';
            gt.Code_Description__c = 'test5107';
            gt.Table__c = 'PRSP';
            gt.Status__c = 'Active';
            insert gt;

            Network_Relationship__c nr = new Network_Relationship__c();
            nr.Contact_Role__c = cr.Id;
            nr.Account_Name__c = acc1.id;
            nr.Provider_Name__c = c.id;
            nr.Program_ID__c = gt.Id;
            nr.Program_Effective_Date__c = date.today().adddays(-2);
            insert nr;
            
            NetworkRelTriggerForProgramIdHandler.applyActiveCostcoPIToNewDoctor(new set<id>{nr.id});
            NetworkRelationshipTriggerHandler.applyActiveCostcoPIToNewDoctor(new set<id>{nr.id});
        
        
        PageReference pageRef = Page.VSPR19_ChangeTaxID;     
        
        pageRef.getParameters().put('id',acc.id);
        
        System.Test.setCurrentPage(pageRef); 
        //Instantiate and construct the controller class.     
        ApexPages.StandardController sc = new ApexPages.standardController(acc);
        // create an instance of the controller
        VSPR19_ChangeTaxIDCtrl controller = new VSPR19_ChangeTaxIDCtrl(sc);
        
        //controller.sapNumberSet.add(accRep.Sales_Rep__c);
        
        controller.validateVCEndDate();
        controller.createtaxId();
        controller.doCancel();
    }
    
    static testMethod void myUnitTest110() {
        // TO DO: implement unit test
        
        
        Account acc = new Account();
        acc.Name = 'Sample Account';
        acc.Status__c = 'New';
        acc.Altair_Standard__c = '001';
        acc.Altair_Field_Rep__c = '001'; 
        acc.Altair_Key_Account__c = '001';
        acc.Altair_Exception__c = '001'; 
        acc.Altair_Hybrid_Bebe__c = '001'; 
        acc.Ophthalmic_Business_Consultant__c = '001'; 
        acc.Optics_Contact_Lens_Consultant__c = '002'; 
        acc.Marchon_Key_Account__c = '001'; 
        acc.Marchon_Close_Out__c = '001'; 
        acc.Marchon_Optical__c = '001'; 
        acc.Marchon_Retail__c = '001';
        acc.VC_EDS_NA__c = '001'; 
        acc.Global_Business_Development_Manager__c = '001';
        acc.Global_Business_Development_Partner__c = '001';
        acc.VC_Relationship_Manager__c = '001'; // AMITSH 07/09/2015. Request # 1342. Added new field.
        acc.Optics_Wholesale__c = '001'; 
        acc.Eyefinity_Inside_Sales__c = '001'; 
        acc.Eyefinity_Outside_Sales__c = '002';
        insert acc;
        
        Id recordtype =[select Id from recordType where Name ='Business Account' and sObjectType ='Account' limit 1].Id;
        account acc1 = new account();
        acc1.name='test';
        acc1.recordTypeId = recordtype;
        acc1.email__c='abc@gmail.com';
        acc1.Tax_ID__c = '345433589';
        acc1.Fax = '223456';
        acc1.Phone = '96532';
        acc1.shippingStreet = '11US';
        acc1.Account_Type__c = 'Business Account';
        acc1.Zipcode__c= '01001' ;
        acc1.Account_Group_Sub_Type__c='ab';
        acc1.ParentId=acc.id;
        acc1.Vision_Care_Location_Key__c='371580129635 2';
        acc1.Vision_Care_Effective_Date__c = Date.today().adddays(-1);
        //acc.Vision_Care_End_Date__c=date.today().adddays(-3);
        insert acc1;
        
       // Insert Contact
            Contact c = new Contact();
            c.FirstName = 'Rogers';
            c.LastName = 'Hornsby';
            c.AccountId = acc1.Id;
            insert c;

            Contact_Role__c cr = new Contact_Role__c();
            cr.Type__c = 'Doctor-Owner';
            cr.Start_Date__c = date.today().adddays(-2);
            cr.End_Date__c = date.today().adddays(30);
            cr.Account__c = acc1.Id;
            cr.Contact__c = c.Id;
            insert cr;

            
            General_Table__c gt = new General_Table__c();
            gt.Name = 'test5107';
            gt.Code_Description__c = 'test5107';
            gt.Table__c = 'PRSP';
            gt.Status__c = 'Active';
            insert gt;

            Network_Relationship__c nr = new Network_Relationship__c();
            nr.Contact_Role__c = cr.Id;
            nr.Account_Name__c = acc1.id;
            nr.Provider_Name__c = c.id;
            nr.Program_ID__c = gt.Id;
            nr.Program_Effective_Date__c = date.today().adddays(-2);
            nr.Program_End_Date__c = date.newInstance(2018,12,31);
            insert nr;
        
        DVIWebService__c dviWeb = new DVIWebService__c();
        dviWeb.EndPoint_Sandbox__c = 'https://api-staging.vspglobal.com==';
        dviWeb.Prod_Org_ID__c = '' ;
        dviWeb.Fee_Token_Header_Sandbox__c = 'EGVrgXfOYlVOm88C63xET6L3TxcxZ8PK9mxt3tzqVvVssgoh7pshfhR8k4YDCkiU';
        dviWeb.Name = 'Fee_Web';
        
        insert dviWeb;
        
        PageReference pageRef = Page.VSPR19_ChangeTaxID;     
        
        pageRef.getParameters().put('id',acc.id);
        
        System.Test.setCurrentPage(pageRef); 
        //Instantiate and construct the controller class.     
        ApexPages.StandardController sc = new ApexPages.standardController(acc);
        // create an instance of the controller
        VSPR19_ChangeTaxIDCtrl controller = new VSPR19_ChangeTaxIDCtrl(sc);
        
        //controller.sapNumberSet.add(accRep.Sales_Rep__c);
        controller.validateVCEndDate();
        controller.createtaxId();
        
     //   VSPR19_ChangeTaxIDCtrl.executeWebService(acc1.Id, String.valueOf(Date.today().adddays(-1)), String.valueOf(Date.today().adddays(-1)), String.valueOf(acc1.Id));
        
      //  Test.setMock(HttpCalloutMock.class, new VSPR16_consumerMockGen());
    }
}