force/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Location_Type__c</fullName>
        <label>Location Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>M - VSP Member Location</fullName>
                </value>
                <value>
                    <fullName>A - Affiliate Provider Location</fullName>
                </value>
                <value>
                    <fullName>F - Laser Vision Correction (LVC)</fullName>
                </value>
                <value>
                    <fullName>X - Client Authorized Location (GAP)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Contact_Role__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact Role</label>
        <referenceTo>Contact_Role__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <formula>HYPERLINK(&quot;/&quot; + Id, &quot;Contact Record&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Record</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Doctor_Type__c</fullName>
        <label>Doctor Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>M - VSP Member Doctor</fullName>
                </value>
                <value>
                    <fullName>A - Affiliate Provider</fullName>
                </value>
                <value>
                    <fullName>F - Laser Vision Correction (LVC)</fullName>
                </value>
                <value>
                    <fullName>S - School Faculty Provider</fullName>
                </value>
                <value>
                    <fullName>X - Client Authorized Provider (GAP)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Contact_Role__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Eye Care Professional</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status_Formula__c</fullName>
        <formula>IF( End_Date__c &lt; Today(),&quot;Inactive&quot;,&quot;Active&quot;)</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accounting</fullName>
                </value>
                <value>
                    <fullName>Board Member/ Officer</fullName>
                </value>
                <value>
                    <fullName>Dean</fullName>
                </value>
                <value>
                    <fullName>Doctor-Employee</fullName>
                </value>
                <value>
                    <fullName>Doctor-Owner</fullName>
                </value>
                <value>
                    <fullName>Doctor-Unspecified</fullName>
                </value>
                <value>
                    <fullName>Group Administrator</fullName>
                </value>
                <value>
                    <fullName>Lab Technician</fullName>
                </value>
                <value>
                    <fullName>Member</fullName>
                </value>
                <value>
                    <fullName>Office Administration</fullName>
                </value>
                <value>
                    <fullName>Office Manager</fullName>
                </value>
                <value>
                    <fullName>Optical Buyer</fullName>
                </value>
                <value>
                    <fullName>Optical Manager</fullName>
                </value>
                <value>
                    <fullName>Optician</fullName>
                </value>
                <value>
                    <fullName>Optician-Owner</fullName>
                </value>
                <value>
                    <fullName>Owner</fullName>
                </value>
                <value>
                    <fullName>Student</fullName>
                </value>
                <value>
                    <fullName>Unspecified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>VSP_Network_Provider__c</fullName>
        <defaultValue>false</defaultValue>
        <label>VSP Network Provider</label>
        <type>Checkbox</type>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/General_Table__c.object
<CustomObject>
    <label>General Table</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>General Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force/src/objects/Network_Relationship__c.object
<CustomObject>
    <description>Custom object to track Payment Relationships between doctors and offices.</description>
    <fields>
        <fullName>Contact_Role__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact Role</label>
        <referenceTo>Contact_Role__c</referenceTo>
        <relationshipName>Payment_Relationships</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Directory_Effective_Date__c</fullName>
        <label>Directory Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Directory_End_Date__c</fullName>
        <label>Directory End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Program_Effective_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Program Effective Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Program_End_Date__c</fullName>
        <label>Program End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Program_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup relationship field from Network Relationship to General Table object</description>
        <label>Program ID</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>General_Table__c.Table__c</field>
                <operation>equals</operation>
                <value>PRSP</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>General_Table__c</referenceTo>
        <relationshipLabel>Network Relationships</relationshipLabel>
        <relationshipName>Network_Relationships</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Network Relationship</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Network Relationship Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Network Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/NetworkRelTriggerForProgramIdHandler.cls
//Date: 28th March, 2017
//Description: Case Number: #00010929 - Ability to Systematically Replicate VSP Program IDs (VSP)
//             Handler class for trigger trgValidateMedicaidLicense on Network Relationship object.

public class NetworkRelTriggerForProgramIdHandler
{
    public static boolean validate=false;
    public static boolean applyActiveCostcoPIToNewDoctor_recursion = true;
    public static void applyActiveCostcoPIToNewDoctor(set<id> nwid)
    {
        if(applyActiveCostcoPIToNewDoctor_recursion){
         applyActiveCostcoPIToNewDoctor_recursion = false;

            List<Network_Relationship__c> finalNetworkRelationship = new List<Network_Relationship__c>();
            List<Network_Relationship__c> NetworkRelationship = new List<Network_Relationship__c>();
            NetworkRelationship =[select id, name,Program_Effective_Date__c,Program_End_Date__c,Contact_Role__c,Directory_Effective_Date__c,Directory_End_Date__c, program_id__r.name,Contact_Role__r.Type__c,Contact_Role__r.Account__c,Contact_Role__r.Contact__c,Contact_Role__r.Account__r.Location_Type__c,Contact_Role__r.Contact__r.Doctor_Type__c  from network_relationship__c where id in : nwId];
            Map<id,Network_Relationship__c> MapNetworkRelationship = new map<id,Network_Relationship__c>();
            set<id> RemoveNetwork=new set<id>();
            for(Network_Relationship__c nw:NetworkRelationship ){
            
                MapNetworkRelationship.put(nw.id,nw);
            }
            System.debug(MapNetworkRelationship+'New###############');
            Map<Id,Id> NetworlWithAccount = new Map<Id,Id>();
            mAP<ID,ID> ContactRoleWithAccount=new Map<id,id>();
            Map<id,id> NetworkIdContactRoleId=new map<id,id>();
            for(Network_Relationship__c NR : NetworkRelationship)
            {
                if((NR.Program_ID__r.Name == 'ADVTG' || NR.Program_ID__r.Name == 'CHOIC'|| NR.Program_ID__r.Name == 'SELCT' )&& (NR.Contact_Role__r.Contact__r.Doctor_Type__c == 'M - VSP Member Doctor') 
                    && (NR.Contact_Role__r.Account__r.Location_Type__c == 'M - VSP Member Location'))
                {
                  NetworlWithAccount.put(nr.id,nr.Contact_Role__r.Account__c);
                  ContactRoleWithAccount.put(nr.Contact_Role__c,nr.Contact_Role__r.Account__c);
                  NetworkIdContactRoleId.put(nr.id,nr.Contact_Role__c);
                }
            }
            System.debug(NetworlWithAccount+'New###############');
            System.debug(ContactRoleWithAccount+'New###############');
            System.debug(NetworkIdContactRoleId+'New###############');
            
            For(Contact_Role__c cr:[select id,Type__c,Account__c, Contact__r.Doctor_Type__c from Contact_Role__c where Account__c in :NetworlWithAccount.values() and Contact__r.Doctor_Type__c ='M - VSP Member Doctor' and (Type__c='Doctor-Employee' or Type__c='Doctor-Owner') and Status_Formula__c='Active' and VSP_Network_Provider__c =true]){
               system.debug(Cr+'$$$$New');
             
                  
                  system.debug('Network Realation ship found');
                  For(String NtrId : NetworlWithAccount.keyset()){
                  if(NetworlWithAccount.get(NtrId )==cr.Account__c && NetworkIdContactRoleId.get(NtrId)!=cr.id){
                  system.debug('Create network Realtion ship');
                   Network_Relationship__c nw=new Network_Relationship__c ();
                   nw.Contact_Role__c=cr.id;
                   nw.Directory_Effective_Date__c=MapNetworkRelationship.get(NtrId).Directory_Effective_Date__c;
                   nw.Directory_End_Date__c=MapNetworkRelationship.get(NtrId).Directory_End_Date__c;
                   nw.Program_Effective_Date__c=MapNetworkRelationship.get(NtrId).Program_Effective_Date__c;
                   nw.Program_End_Date__c=MapNetworkRelationship.get(NtrId).Program_End_Date__c;
                   nw.Program_ID__c=MapNetworkRelationship.get(NtrId).Program_ID__c;             
                   finalNetworkRelationship.add(nw);
                   RemoveNetwork.add(NtrId);
                   break;               
                   }
                  
                  }
                  
              
              }
               
                          
            if(finalNetworkRelationship.size()>0){
                validate=true;
                insert finalNetworkRelationship;
            }
        }
    }
     
     
}