force/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>IOF_Uncut_Pilot_Program__c</fullName>
        <inlineHelpText>When Yes or Exception, this office can process uncut lenses in their in-office lab</inlineHelpText>
        <label>IOF Uncut Pilot Program</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
                <value>
                    <fullName>Exception</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of Account.</description>
        <inlineHelpText>A = Active 
Inactive = Not a Current Customer of any LOB. 
Closed = Business has ceased operations 
New = In process of becoming an Active account</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Submit for Approval</fullName>
                </value>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Inactive Ownership Change</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
                <value>
                    <fullName>Marked for Deletion</fullName>
                </value>
                <value>
                    <fullName>Archive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force/src/objects/Account_Group__c.object
<CustomObject>
    <description>Account&apos;s relationship to an Account Group.</description>
    <fields>
        <fullName>Account_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Group</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Relationships (Account)</relationshipLabel>
        <relationshipName>Account_Relationships1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Relationships</relationshipLabel>
        <relationshipName>Account_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Optics_Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Doctor has chosen to receive Optics Group discounts through this Account Group.</inlineHelpText>
        <label>Optics Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(   OR( Start_Date__c  =  TODAY() , AND( Start_Date__c  &lt;  TODAY() , OR( End_Date__c   &gt;=  TODAY()  ,  ISBLANK( End_Date__c ) ) ) ) , &quot;Active&quot;,  IF( Start_Date__c  &gt;  TODAY() , &apos;Future&apos;, &apos;Inactive&apos;) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Account Relationship</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Salesforce_ID__mdt.object
<CustomObject>
    <description>To store IDs in the metadata component which will reduce our dependency to hard code record IDs in code.</description>
    <fields>
        <fullName>ID__c</fullName>
        <label>ID</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Salesforce ID</label>
    <pluralLabel>Salesforce IDs</pluralLabel>
</CustomObject>

src/classes/VSPR31_UncutPilotProgramBatch.cls
//Apex batch class to implement IOF Uncut Pilot Program to Business Accounts

global class VSPR31_UncutPilotProgramBatch implements Database.Batchable<sObject>, Database.Stateful {
	
	private static Id businessRecordTypeID = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
	private static Id accountGroupsRecordTypeID = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Account Groups').getRecordTypeId();
	global final String query = 'Select id, IOF_Uncut_Pilot_Program__c from Account where recordTypeId = \'' + businessRecordTypeID + '\' and IOF_Uncut_Pilot_Program__c != \'Exception\'';
	private final String s = 'Vision Trends';
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(query);
	}

   	global void execute(Database.BatchableContext BC, List<Account> scope) {

   		Set<Id> accountIds = new Set<Id>();
   		//Account acc = [Select id from Account where Name = 'Vision Trends' and recordTypeId = :accountGroupsRecordTypeID];
   		Salesforce_ID__mdt acc = [Select MasterLabel, ID__c from Salesforce_ID__mdt where MasterLabel = :s];
   		List<Account_Group__c> accRelationshipList = new List<Account_Group__c>();
   		Set<Id> idSet = new Set<Id>();
   		List<Account> accList = new List<Account>();
		Map<Id, String> accMap = new Map<Id, String>();

   		for(Account a: scope){
   			//accountIds.add(a.id);
			accMap.put(a.Id, a.IOF_Uncut_Pilot_Program__c);
   		}

   		//accRelationshipList = [Select id, Account__c from Account_Group__c where Account__c in :accountIds and Account_Group__c = :acc.id and End_Date__c = null and Optics_Primary__c = true];
		
		//The below was the original query   
   		//accRelationshipList = [Select id, Account__c from Account_Group__c where Account__c in :accountIds and Account_Group__c = :(Id)acc.ID__c and End_Date__c = null and Optics_Primary__c = true];

		//Querying it this way because the job will run at the end of the date. This way we will run the uncut part for A/C relationships having start date as tomorrow and end date of today. 
		//This will also cover for scenarios where end date might be yesterday or the relation got activated today, but the record failed to update.
		accRelationshipList = [Select id, Account__c, Status__c, End_Date__c, Start_Date__c from Account_Group__c where Account__c in :/*accountIds*/ accMap.keySet() and Account_Group__c = :(Id)acc.ID__c and (Status__c = 'Active' or Start_Date__c = TOMORROW) and Optics_Primary__c = true];

   		/*for(Account_Group__c a: accRelationshipList){
   			if(accountIds.contains(a.Account__c)){
   				if(!idSet.contains(a.Account__c)){
   					idSet.add(a.Account__c);
   				}
   			}
   		}*/

		
		//Updated logic statement.
		for(Account_Group__c a: accRelationshipList){
   			if(accMap.containsKey(a.Account__c)){
				if(a.End_Date__c != System.today()){
					idSet.add(a.Account__c);
				}
   			}
   		}

   		for(Account a: scope){
   			if(idSet.contains(a.id)){
   				a.IOF_Uncut_Pilot_Program__c = 'Yes';
   			}else{
   				a.IOF_Uncut_Pilot_Program__c = 'No';
   			}
   			//accList.add(a);
			if(a.IOF_Uncut_Pilot_Program__c != accMap.get(a.Id)){
				accList.add(a);
			}
   		}

   		update accList;
	
	}
	
	global void finish(Database.BatchableContext BC) {
		
	}
	
}