force/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Tax_ID__c</fullName>
        <description>Account Tax ID.</description>
        <encrypted>true</encrypted>
        <inlineHelpText>Account Tax ID.</inlineHelpText>
        <label>Tax ID</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force/src/objects/Practice_Report_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configurable parameters for Practice Report query.</description>
    <fields>
        <fullName>Posting_Date_From__c</fullName>
        <label>Posting Date (From)</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Posting_Date_To__c</fullName>
        <label>Posting Date (To)</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Quarter__c</fullName>
        <label>Quarter</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <length>4</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Practice Report Settings</label>
</CustomObject>

force/src/objects/RESTify_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Contains critical RESTify settings used by Apex client in RestifyClient.cls</description>
    <fields>
        <fullName>ACCESS_KEY__c</fullName>
        <label>ACCESS_KEY</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>END_POINT__c</fullName>
        <label>END_POINT</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HTTP_VERB__c</fullName>
        <label>HTTP_VERB</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PATH__c</fullName>
        <label>PATH</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SECRET_KEY__c</fullName>
        <label>SECRET_KEY</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>RESTify Settings</label>
</CustomObject>

force/src/classes/RestifyClient_v2_TEST.cls
/*
 * 2016 eightCloud + VSP
 *
 * Test class for Apex client to interact with RESTify API
 *
 * 
 */
@isTest
private class RestifyClient_v2_TEST {

    @testSetup static void init() {
        Account a = new Account(Name = 'Test Account', Tax_ID__c = '123456789');
        insert a;

        RESTify_Settings__c apiSettings = new RESTify_Settings__c();
        apiSettings.END_POINT__c = 'https://reports.vsp.com:443';
        apiSettings.PATH__c = '/ecm/query';
        apiSettings.HTTP_VERB__c = 'GET';
        apiSettings.ACCESS_KEY__c = 'access_key';
        apiSettings.SECRET_KEY__c = 'secret_key';
        insert apiSettings;
        
        Practice_Report_Settings__c query = new Practice_Report_Settings__c();
        query.Year__c = 'YYYY';
        query.Quarter__c = 'QX';
        query.Posting_Date_From__c = Date.newInstance(System.now().year(), System.now().month(), System.now().day());
        query.Posting_Date_To__c = Date.newInstance(System.now().year(), System.now().month()+3, System.now().day());
        insert query;
    }

    @isTest static void callout200() {
        Test.startTest();

        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('RESTify200');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json');
        
        Test.setMock(HttpCalloutMock.class, mock);
        String acctId = [SELECT Id FROM Account LIMIT 1].Id + 'Practice';
        String response = RestifyClient_v2.getReport(acctId);
        // Verify response received contains values returned by the mock response, which is based on the static resource payload example
        System.assertEquals('HTTP_STATUS_CODE200SFRUUF9TVEFUVVNfQ09ERTIwMGV5SmpiM1Z1ZENJNklqRWlMQ0p6ZEdGeWRDSTZJakFpTENKd1lXZGxJam9pTWpVaUxDSnBkR1Z0Y3lJNlczc2lVRkpCUTFSSlEwVkdJam9pTkRjeE1UazVPVEl5V1RJd01UWlJNU0o5WFgwPQ==', response);

        Test.stopTest();
    }

    @isTest static void callout500() {
        Test.startTest();

        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('RESTify500');
        mock.setStatusCode(500);
        mock.setHeader('Content-Type', 'application/json');
        
        Test.setMock(HttpCalloutMock.class, mock);
        String acctId = [SELECT Id FROM Account LIMIT 1].Id + 'Practice';
        String response = RestifyClient_v2.getReport(acctId);
        // Verify response received contains values returned by the mock response, which is based on the static resource payload example
        System.assertEquals('HTTP_STATUS_CODE500{"request": "RSrQ6boKyh","code": "500","message": "Document not found","trace": ""}', response);

        Test.stopTest();
    }

    @isTest static void callout403() {
        Test.startTest();

        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('RESTify403');
        mock.setStatusCode(403);
        mock.setHeader('Content-Type', 'application/json');
        
        Test.setMock(HttpCalloutMock.class, mock);
        String acctId = [SELECT Id FROM Account LIMIT 1].Id + 'Practice';
        String response = RestifyClient_v2.getReport(acctId);
        // Verify response received contains values returned by the mock response, which is based on the static resource payload example
        System.assertEquals('HTTP_STATUS_CODE403{"request": "e0rAGc4lDX","code": "403","message": "Invalid signature"}', response);

        Test.stopTest();
    }
    
}