force/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of Account.</description>
        <inlineHelpText>A = Active 
Inactive = Not a Current Customer of any LOB. 
Closed = Business has ceased operations 
New = In process of becoming an Active account</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Submit for Approval</fullName>
                </value>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Inactive Ownership Change</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
                <value>
                    <fullName>Marked for Deletion</fullName>
                </value>
                <value>
                    <fullName>Archive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vision_Care_Location_Key__c</fullName>
        <encrypted>true</encrypted>
        <label>Vision Care Location Key</label>
        <length>125</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <formula>HYPERLINK(&quot;/&quot; + Id, &quot;Contact Record&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Record</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Status of Contact.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force/src/objects/Contact_Role__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Active_or_Future_Vision_Care_Relationshi__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active or Future VC Relationship</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Eye Care Professional</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accounting</fullName>
                </value>
                <value>
                    <fullName>Board Member/ Officer</fullName>
                </value>
                <value>
                    <fullName>Dean</fullName>
                </value>
                <value>
                    <fullName>Doctor-Employee</fullName>
                </value>
                <value>
                    <fullName>Doctor-Owner</fullName>
                </value>
                <value>
                    <fullName>Doctor-Unspecified</fullName>
                </value>
                <value>
                    <fullName>Group Administrator</fullName>
                </value>
                <value>
                    <fullName>Lab Technician</fullName>
                </value>
                <value>
                    <fullName>Member</fullName>
                </value>
                <value>
                    <fullName>Office Administration</fullName>
                </value>
                <value>
                    <fullName>Office Manager</fullName>
                </value>
                <value>
                    <fullName>Optical Buyer</fullName>
                </value>
                <value>
                    <fullName>Optical Manager</fullName>
                </value>
                <value>
                    <fullName>Optician</fullName>
                </value>
                <value>
                    <fullName>Optician-Owner</fullName>
                </value>
                <value>
                    <fullName>Owner</fullName>
                </value>
                <value>
                    <fullName>Student</fullName>
                </value>
                <value>
                    <fullName>Unspecified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force/src/objects/QA_Review__c.object
<CustomObject>
    <description>Quality Assurance Reviews of Providers</description>
    <fields>
        <fullName>Contact_Role__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact Role</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact_Role__c.Type__c</field>
                <operation>equals</operation>
                <value>Doctor-Employee, Doctor-Owner</value>
            </filterItems>
            <filterItems>
                <field>Contact_Role__c.Active_or_Future_Vision_Care_Relationshi__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>You must select a Doctor-Owner or Doctor-Employee that is an Active Vision Care Provider.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact_Role__c</referenceTo>
        <relationshipLabel>QA Reviews</relationshipLabel>
        <relationshipName>QA_Reviews</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Original_DocuSign_Sent_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Original DocuSign Sent Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Provider_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Eye Care Professional</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>QA Reviews</relationshipLabel>
        <relationshipName>QA_Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QA_Review_Status__c</fullName>
        <label>QA Review Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress QA Admin</fullName>
                </value>
                <value>
                    <fullName>Submit for Claims</fullName>
                </value>
                <value>
                    <fullName>Re-Submit for Claims</fullName>
                </value>
                <value>
                    <fullName>Assigned to Clinical Auditor</fullName>
                </value>
                <value>
                    <fullName>In Progress Clinical Auditor</fullName>
                </value>
                <value>
                    <fullName>Clinical Auditor Complete</fullName>
                </value>
                <value>
                    <fullName>Completed Audit Pass</fullName>
                </value>
                <value>
                    <fullName>Completed Audit Failed</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed - Non-responder</fullName>
                </value>
                <value>
                    <fullName>Fail</fullName>
                    <isActive>false</isActive>
                    <label>Fail</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <isActive>false</isActive>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Pass</fullName>
                    <isActive>false</isActive>
                    <label>Pass</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Result_Letter_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Result Letter Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Review_Date_Scheduled__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Review Date Scheduled</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Review_Received_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Review/Received Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Care_Location_Key__c</fullName>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Vision Care Location Key</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>QA Review</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>QA Review Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QA Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force/src/classes/VSPR28_QA_Review_Status_Update_Sch_Test.cls
@isTest
public class VSPR28_QA_Review_Status_Update_Sch_Test {
    
    @TestSetup
    static void testData(){
        
        Id accRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Practice Account').getRecordTypeId();
        Id conRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Eye Care Professional').getRecordTypeId();
      
        Account pracAcc = new Account();
        pracAcc.RecordTypeId = accRecordTypeId;
        pracAcc.Name = 'Practice Account';
        insert pracAcc;
        
        Contact con = new Contact();
        con.RecordTypeId = conRecordTypeId;
        con.AccountId = pracAcc.Id;
        con.Status__c = 'Active';
        con.FirstName = 'FName';
        con.LastName = 'LName';
        insert con;
        
        Contact_Role__c	cr = new Contact_Role__c();
        cr.Account__c = pracAcc.Id;
        cr.Contact__c = con.Id;
        cr.Type__c = 'Doctor-Owner';
        cr.Status__c = 'Active';
        cr.Start_Date__c = Date.today();
        cr.Active_or_Future_Vision_Care_Relationshi__c = True;
        Test.startTest();
        insert cr;
        Test.stopTest();
        
        QA_Review__c qaReview = new QA_Review__c();
        qaReview.Contact_Role__c = cr.Id;
        qaReview.Provider_Name__c = con.Id;
        qaReview.Vision_Care_Location_Key__c = '123456789';
        qaReview.Review_Date_Scheduled__c = Date.today();
        qaReview.Review_Received_Date__c = Date.today();
        qaReview.Result_Letter_Date__c = Date.today();
        qaReview.QA_Review_Status__c = 'Completed Audit Pass';
        qaReview.Original_DocuSign_Sent_Date__c = Date.today().addDays(-46);
        insert qaReview;
       
    }
        
        static testmethod void runJob(){
            Test.startTest();
            
            String EXP = '0 0 23 * * ?';
            
            VSPR28_QA_Review_Status_Update_Schedule sch = new VSPR28_QA_Review_Status_Update_Schedule();
            
            system.Schedule('QA Review Status Update Test', EXP, sch);
            
            Test.stopTest();
        }
    }