force/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of Account.</description>
        <inlineHelpText>A = Active 
Inactive = Not a Current Customer of any LOB. 
Closed = Business has ceased operations 
New = In process of becoming an Active account</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Submit for Approval</fullName>
                </value>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Inactive Ownership Change</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
                <value>
                    <fullName>Marked for Deletion</fullName>
                </value>
                <value>
                    <fullName>Archive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Birthdate__c</fullName>
        <encrypted>true</encrypted>
        <label>Birthdate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <formula>HYPERLINK(&quot;/&quot; + Id, &quot;Contact Record&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Record</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marketing_Name__c</fullName>
        <inlineHelpText>The contact&apos;s name used for Marketing Campaigns.</inlineHelpText>
        <label>Marketing Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Status of Contact.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vision_Care_Network_Provider__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Provides services for Vision Care.</description>
        <inlineHelpText>Provides services for Vision Care.</inlineHelpText>
        <label>Vision Care Provider</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force/src/objects/Contact_Role__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Eye Care Professional</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accounting</fullName>
                </value>
                <value>
                    <fullName>Board Member/ Officer</fullName>
                </value>
                <value>
                    <fullName>Dean</fullName>
                </value>
                <value>
                    <fullName>Doctor-Employee</fullName>
                </value>
                <value>
                    <fullName>Doctor-Owner</fullName>
                </value>
                <value>
                    <fullName>Doctor-Unspecified</fullName>
                </value>
                <value>
                    <fullName>Group Administrator</fullName>
                </value>
                <value>
                    <fullName>Lab Technician</fullName>
                </value>
                <value>
                    <fullName>Member</fullName>
                </value>
                <value>
                    <fullName>Office Administration</fullName>
                </value>
                <value>
                    <fullName>Office Manager</fullName>
                </value>
                <value>
                    <fullName>Optical Buyer</fullName>
                </value>
                <value>
                    <fullName>Optical Manager</fullName>
                </value>
                <value>
                    <fullName>Optician</fullName>
                </value>
                <value>
                    <fullName>Optician-Owner</fullName>
                </value>
                <value>
                    <fullName>Owner</fullName>
                </value>
                <value>
                    <fullName>Student</fullName>
                </value>
                <value>
                    <fullName>Unspecified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force/src/classes/VSPR1_RelocateControllerTest.cls
/** 
     * Class Name: VSPR1_RelocateControllerTest
     * @author: Jinky M. N. Salvador
     * Date: 12.JUL.2013 
     * Requirement/Project Name: VSP 
     * @description: Test class for VSPR1_RelocateController class.  
     */

public class VSPR1_RelocateControllerTest {
    
    static testMethod void unitTest() {     
        
        List<Account> accList = new List<Account>();
        for(integer i=0;i<2;i++){
            Account acc = new Account();
            acc.Name = 'Sample Account';
            acc.Status__c = 'New';
            accList.add(acc);
        }
        
        insert accList;
        
        Contact cont = new Contact();
        cont.AccountId = accList[0].id;
        cont.LastName = 'Sample Contact';
        cont.Birthdate__c = system.today();
        cont.Vision_Care_Network_Provider__c = true;
        cont.Marketing_Name__c = 'Marketing Name';
        insert cont;
        
        Contact_Role__c cRole = new Contact_Role__c();
        cRole.Account__c = accList[0].id;
        cRole.Contact__c = cont.Id;
        cRole.Type__c = 'Accounting';
        cRole.Start_Date__c = system.today();
        insert cRole;
        
        Task task = new Task();
        task.WhoId = cont.id;
        task.Status = 'Not Started';
        task.Subject = 'Sample Subject';
        insert task;
        
        PageReference pageRef = Page.VSPR1_Relocate;      
        pageRef.getParameters().put('cid',cont.id);
        System.Test.setCurrentPage(pageRef); 
        //Instantiate and construct the controller class.     
        ApexPages.StandardController sc = new ApexPages.standardController(cRole);
        // create an instance of the controller
        VSPR1_RelocateController controller = new VSPR1_RelocateController(sc);
        controller.getcRole();
        /*
        controller.oContactRole.Contact__r.BirthDate = system.today();
        controller.oContactRole.Type__c = 'Doctor';
        controller.oContactRole.Start_Date__c = system.today();
        controller.oContactRole.End_Date__c = system.today();
        controller.oContactRole.Account__c = accList[1].id; 
        */       
        controller.DoSave();
        
        cont.Birthdate__c = null;
        cont.AccountId = accList[1].id;
        update cont;
        controller.getcRole();
        
        List<Contact> contList =  new List<Contact>();
        for(integer i=0;i<2;i++){
            Contact newCont = new Contact();
            newCont.AccountId = accList[0].id;
            newCont.LastName = 'Sample Contact';
            newCont.Birthdate__c = system.today();
            newCont.Marketing_Name__c = 'Marketing Name';
            newCont.Vision_Care_Network_Provider__c = true;
            contList.add(newCont);
        }
        insert contList;
        
        delete cont;       
    }
    
     static testMethod void unitTest2() {     
        
        List<Account> accList = new List<Account>();
        for(integer i=0;i<2;i++){
            Account acc = new Account();
            acc.Name = 'Sample Account';
            acc.Status__c = 'New';
            accList.add(acc);
        }
        
        insert accList;
        
        Contact cont = new Contact();
        cont.AccountId = accList[0].id;
        cont.LastName = 'Sample Contact';
        cont.Birthdate__c = system.today();
        cont.Vision_Care_Network_Provider__c = true;
        cont.Marketing_Name__c = 'Marketing Name';
        insert cont;
        
        Contact_Role__c cRole = new Contact_Role__c();
        cRole.Account__c = accList[0].id;
        cRole.Contact__c = cont.Id;
        cRole.Type__c = 'Accounting';
        cRole.Start_Date__c = system.today();
        cRole.End_Date__c = system.today() - 1;
         try{ 
              Test.startTest();
        insert cRole;
              Test.stopTest();
         }
         catch(DMLException e){
             System.debug('>>> ERROR ='+e);
             system.assert(e.getMessage().contains('Setting the “Contact Role End date” that precedes the “Contact Role Start Date” is not allowed'), 'message=' + e.getMessage());
         }
         
        Task task = new Task();
        task.WhoId = cont.id;
        task.Status = 'Not Started';
        task.Subject = 'Sample Subject';
        insert task;
        
        PageReference pageRef = Page.VSPR1_Relocate;      
        pageRef.getParameters().put('cid',cont.id);
        System.Test.setCurrentPage(pageRef); 
        //Instantiate and construct the controller class.     
        ApexPages.StandardController sc = new ApexPages.standardController(cRole);
        // create an instance of the controller
        VSPR1_RelocateController controller = new VSPR1_RelocateController(sc);
        controller.getcRole();
         controller.Roletype = 'Test';
         controller.curRoleEndDate = Date.today();
        /*
        controller.oContactRole.Contact__r.BirthDate = system.today();
        controller.oContactRole.Type__c = 'Doctor';
        controller.oContactRole.Start_Date__c = system.today();
        controller.oContactRole.End_Date__c = system.today();
        controller.oContactRole.Account__c = accList[1].id; 
        */  
          
             
        controller.DoSave();
             
         
        cont.Birthdate__c = null;
        cont.AccountId = accList[1].id;
        update cont;
        controller.getcRole();
        
        List<Contact> contList =  new List<Contact>();
        for(integer i=0;i<2;i++){
            Contact newCont = new Contact();
            newCont.AccountId = accList[0].id;
            newCont.LastName = 'Sample Contact';
            newCont.Birthdate__c = system.today();
            newCont.Marketing_Name__c = 'Marketing Name';
            newCont.Vision_Care_Network_Provider__c = true;
            contList.add(newCont);
        }
        insert contList;
        
        delete cont; 
       
         
    }
}