force/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Group_Sub_Type__c</fullName>
        <inlineHelpText>Buying Group - Takes financial responsibility for their members.
Alliance - Offers their members certain products at discounts.
Association - Individuals who join a group.
Educational Institution - School or College.
DOLP - Doctor Owned Lab Program.</inlineHelpText>
        <label>Account Group Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Buying Group</fullName>
                </value>
                <value>
                    <fullName>Alliance</fullName>
                </value>
                <value>
                    <fullName>Association</fullName>
                </value>
                <value>
                    <fullName>Educational Institution</fullName>
                </value>
                <value>
                    <fullName>DOLP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account_Type__c</fullName>
        <description>Is Account a Practice Account, Business Account or Account Group.</description>
        <inlineHelpText>Is Account a Practice Account, Business Account or Account Group.</inlineHelpText>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account Group</fullName>
                </value>
                <value>
                    <fullName>Business Account</fullName>
                </value>
                <value>
                    <fullName>Practice Account</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Location_Type__c</fullName>
        <label>Location Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>M - VSP Member Location</fullName>
                </value>
                <value>
                    <fullName>A - Affiliate Provider Location</fullName>
                </value>
                <value>
                    <fullName>F - Laser Vision Correction (LVC)</fullName>
                </value>
                <value>
                    <fullName>X - Client Authorized Location (GAP)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tax_ID__c</fullName>
        <description>Account Tax ID.</description>
        <encrypted>true</encrypted>
        <inlineHelpText>Account Tax ID.</inlineHelpText>
        <label>Tax ID</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VC__c</fullName>
        <formula>IF( Vision_Care_Effective_Date__c &lt;= TODAY()  &amp;&amp; (Vision_Care_End_Date__c &gt;=TODAY() ||  ISBLANK(Vision_Care_End_Date__c)) , TRUE, FALSE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>VC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vision_Care_Effective_Date__c</fullName>
        <label>Vision Care Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Care_End_Date__c</fullName>
        <label>Vision Care End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zipcode__c</fullName>
        <label>Zipcode</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Accommodates_Children_0_3_years__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Accommodates Children 0-3 years</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Accommodates_Children_3_5_years__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Accommodates Children 3-5 years</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Birthdate__c</fullName>
        <encrypted>true</encrypted>
        <label>Birthdate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CAQH_ID__c</fullName>
        <label>CAQH ID</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <formula>HYPERLINK(&quot;/&quot; + Id, &quot;Contact Record&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Record</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_of_CMS_Medicare_Application_Submiss__c</fullName>
        <inlineHelpText>Applied with the Center for Medicare Services to provide services to the Medicare population</inlineHelpText>
        <label>Date of CMS Application Submission</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Degree__c</fullName>
        <description>The educational degree of the Vision Care Doctor.</description>
        <inlineHelpText>The educational degree of the Vision Care Doctor.</inlineHelpText>
        <label>Degree</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>OD</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>DO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Doctor_Type__c</fullName>
        <label>Doctor Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>M - VSP Member Doctor</fullName>
                </value>
                <value>
                    <fullName>A - Affiliate Provider</fullName>
                </value>
                <value>
                    <fullName>F - Laser Vision Correction (LVC)</fullName>
                </value>
                <value>
                    <fullName>S - School Faculty Provider</fullName>
                </value>
                <value>
                    <fullName>X - Client Authorized Provider (GAP)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <label>Ethnicity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>American Indian or Alaskan Native</fullName>
                </value>
                <value>
                    <fullName>Asian/Pacific Islander</fullName>
                </value>
                <value>
                    <fullName>Black/African American</fullName>
                </value>
                <value>
                    <fullName>Caucasian</fullName>
                </value>
                <value>
                    <fullName>Hispanic or Latino</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Marketing_Name__c</fullName>
        <inlineHelpText>The contact&apos;s name used for Marketing Campaigns.</inlineHelpText>
        <label>Marketing Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Medicare_ID_Number__c</fullName>
        <label>Medicare ID Number</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NPI__c</fullName>
        <description>National Provider Indicator for a Vision Care Doctor.</description>
        <inlineHelpText>National Provider Indicator for a Vision Care Doctor.</inlineHelpText>
        <label>NPI</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Specializes_in_Hard_to_fit_Contacts__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Specializes in Hard-to-fit Contacts</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Specializes_in_Low_Vision__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Specializes in Low Vision</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Specializes_in_Vision_Therapy__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Specializes in Vision Therapy</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>VC__c</fullName>
        <description>Used to display Vision Care Providers in the Contact Search Results.</description>
        <formula>IF( Vision_Care_Effective_Date__c &lt;= TODAY() &amp;&amp; (Vision_Care_End_Date__c &gt;=TODAY() || ISBLANK(Vision_Care_End_Date__c)) , TRUE, FALSE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>VC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vision_Care_Effective_Date__c</fullName>
        <label>Vision Care Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Care_End_Date__c</fullName>
        <label>Vision Care End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Care_Relationship_Type_s__c</fullName>
        <inlineHelpText>Based on Active Location Relationships</inlineHelpText>
        <label>Vision Care Relationship Type(s)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force/src/objects/Contact_Role__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Eye Care Professional</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accounting</fullName>
                </value>
                <value>
                    <fullName>Board Member/ Officer</fullName>
                </value>
                <value>
                    <fullName>Dean</fullName>
                </value>
                <value>
                    <fullName>Doctor-Employee</fullName>
                </value>
                <value>
                    <fullName>Doctor-Owner</fullName>
                </value>
                <value>
                    <fullName>Doctor-Unspecified</fullName>
                </value>
                <value>
                    <fullName>Group Administrator</fullName>
                </value>
                <value>
                    <fullName>Lab Technician</fullName>
                </value>
                <value>
                    <fullName>Member</fullName>
                </value>
                <value>
                    <fullName>Office Administration</fullName>
                </value>
                <value>
                    <fullName>Office Manager</fullName>
                </value>
                <value>
                    <fullName>Optical Buyer</fullName>
                </value>
                <value>
                    <fullName>Optical Manager</fullName>
                </value>
                <value>
                    <fullName>Optician</fullName>
                </value>
                <value>
                    <fullName>Optician-Owner</fullName>
                </value>
                <value>
                    <fullName>Owner</fullName>
                </value>
                <value>
                    <fullName>Student</fullName>
                </value>
                <value>
                    <fullName>Unspecified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force/src/objects/Network_Recruitment__c.object
<CustomObject>
    <description>Custom object to track network recruiting activity.</description>
    <fields>
        <fullName>CAQH_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>CAQH ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Role__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact Role</label>
        <referenceTo>Contact_Role__c</referenceTo>
        <relationshipLabel>Network Recruitments</relationshipLabel>
        <relationshipName>Network_Recruitments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Degree__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Degree</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Email</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NPI__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>NPI</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <label>Network Recruitment</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Network Recruitment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Network Recruitments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force/src/classes/VSPR19b_RelationshipTypesConBatch1Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest(seealldata=false)
private class VSPR19b_RelationshipTypesConBatch1Test {

    static testMethod void myUnitTest() {
        /*uery = 'SELECT c.Id, c.Name, c.AccountId, c.Vision_Care_Relationship_Type_s__c, 
        
        c.Doctor_Type__c, c.Vision_Care_End_Date__c, c.Vision_Care_Effective_Date__c,
         c.VC__c, c.RecordType.Name FROM Contact c WHERE
          (c.Vision_Care_End_Date__c >=: todayDate OR c.Vision_Care_End_Date__c = NULL) 
          AND c.Vision_Care_Effective_Date__c <=: todayDate AND 
          c.AccountId IN  ORDER BY c.Name ASC'; 
          */ 

            list<account> lstAcnt = new list<account>();
                Id recordtype =[select Id from recordType where Name ='Business Account' and sObjectType ='Account' limit 1].Id;
                account acc = new account();
                acc.name='test';
                acc.recordTypeId = recordtype;
                acc.email__c='abc@gmail.com';
                acc.Tax_ID__c = '345433589';
                acc.Fax = '223456';
                acc.Phone = '96532';
                acc.shippingStreet = '11US';
                acc.Account_Type__c = 'Business Account';
                acc.Zipcode__c= '01001' ;
                acc.Account_Group_Sub_Type__c='ab';
                acc.Vision_Care_Effective_Date__c=date.today();
                acc.Vision_Care_End_Date__c=date.today().adddays(2);
                acc.Location_type__c='M - VSP Member Location';
                Test.StartTest();
                VSPUtility.stopAccountTrigger=true;
                insert acc;
               
                contact con = new contact();
                con.accountid=acc.id;
                con.lastname='xyz';
                con.firstname='rar';
                con.Marketing_Name__c='mat';
                con.npi__c='1851364921';
                con.Salutation = 'Dr.';
                con.Birthdate__c = Date.Parse('5/15/2015');
                con.Phone = '96532';
                con.Degree__c ='OD';
                con.CAQH_ID__c='9999';
                con.Doctor_Type__c='M - VSP Member Doctor';
                con.Email ='test@123.com';
                con.Vision_Care_Effective_Date__c=date.today();
                con.Vision_Care_End_Date__c=date.today().adddays(2);
                con.Date_of_CMS_Medicare_Application_Submiss__c = Date.Today();
                con.Ethnicity__c ='Other';
                con.Medicare_ID_Number__c ='Med11';
                con.Accommodates_Children_0_3_years__c = True;
                con.Accommodates_Children_3_5_years__c = True;
                con.Specializes_in_Hard_to_fit_Contacts__c = True;
                con.Specializes_in_Low_Vision__c = True;
                con.Specializes_in_Vision_Therapy__c = True;
                insert con;
                system.assertNotEquals(con.Email,'test@12345.com');
                
                Contact_Role__c role = new Contact_Role__c();
                role.Account__c = acc.id; 
                role.contact__c  = Con.id;
                role.Type__c  = 'Doctor-Employee';
                role.Start_Date__c = Date.Today();
                insert role;
                
                Network_Recruitment__c net = new Network_Recruitment__c();
                net.npi__c='1851364921';
                net.Recruitment_Type__c='Doctor Initiated';
                net.Recruitment_Status__c = 'New Lead';
                net.Doctor_id__c='12345';
                net.Additional_Office_Locations__c ='11234 Arizona Phoenix A38 11234';
                net.Contact_Role__c = role.id;
                net.ownerId = userInfo.getUserId();
                insert net;
                system.assertEquals(net.Recruitment_Status__c,'New Lead');
                system.assertEquals(net.Recruitment_Type__c,'Doctor Initiated');
                
                task t = new task();
                t.whatID =net.id;
                t.Subject ='Duplicate VSP  Doctor Request Submitted';
                t.Type ='Outbound Call';
                t.Status = 'Not Started';
                t.Priority ='Normal';
                t.ActivityDate =Date.Today() + 7; 
                t.ReminderDateTime =DateTime.Now().addHours(48);
                t.OwnerId  = net.ownerId;
                insert t;
                VSPUtility.stopAccountTrigger=true;
                update acc;
                
                
                VSPR9_AutoGenerateNetworkRecruitment autoGen = new VSPR9_AutoGenerateNetworkRecruitment();
                
                
                
                VSPR9_AutoGenerateNetworkRecruitment autoGenerateNw = new VSPR9_AutoGenerateNetworkRecruitment();
             VSPR19b_RelationshipTypesContactBatch activeNetRelsVC = new VSPR19b_RelationshipTypesContactBatch();
   			Database.ExecuteBatch(activeNetRelsVC,1); 
   			Test.StopTest();
         
        
    }
    
    static testMethod void myUnitTest2() {
        /*uery = 'SELECT c.Id, c.Name, c.AccountId, c.Vision_Care_Relationship_Type_s__c, 
        
        c.Doctor_Type__c, c.Vision_Care_End_Date__c, c.Vision_Care_Effective_Date__c,
         c.VC__c, c.RecordType.Name FROM Contact c WHERE
          (c.Vision_Care_End_Date__c >=: todayDate OR c.Vision_Care_End_Date__c = NULL) 
          AND c.Vision_Care_Effective_Date__c <=: todayDate AND 
          c.AccountId IN  ORDER BY c.Name ASC'; 
          */ 

            list<account> lstAcnt = new list<account>();
                Id recordtype =[select Id from recordType where Name ='Business Account' and sObjectType ='Account' limit 1].Id;
                account acc = new account();
                acc.name='test';
                acc.recordTypeId = recordtype;
                acc.email__c='abc@gmail.com';
                acc.Tax_ID__c = '345433589';
                acc.Fax = '223456';
                acc.Phone = '96532';
                acc.shippingStreet = '11US';
                acc.Account_Type__c = 'Business Account';
                acc.Zipcode__c= '01001' ;
                acc.Account_Group_Sub_Type__c='ab';
                acc.Vision_Care_Effective_Date__c=date.today();
                acc.Vision_Care_End_Date__c=date.today().adddays(2);
                acc.Location_type__c='M - VSP Member Location';
                Test.StartTest();
                VSPUtility.stopAccountTrigger=true;
                insert acc;
               
                contact con = new contact();
                con.accountid=acc.id;
                con.lastname='xyz';
                con.firstname='rar';
                con.Marketing_Name__c='mat';
                con.npi__c='1851364921';
                con.Salutation = 'Dr.';
                con.Birthdate__c = Date.Parse('5/15/2015');
                con.Phone = '96532';
                con.Degree__c ='OD';
                con.CAQH_ID__c='9999';
                con.Doctor_Type__c='S - School Faculty Provider';
                con.Email ='test@123.com';
                con.Vision_Care_Effective_Date__c=date.today();
                con.Vision_Care_End_Date__c=date.today().adddays(2);
                con.Date_of_CMS_Medicare_Application_Submiss__c = Date.Today();
                con.Ethnicity__c ='Other';
                con.Medicare_ID_Number__c ='Med11';
                con.Accommodates_Children_0_3_years__c = True;
                con.Accommodates_Children_3_5_years__c = True;
                con.Specializes_in_Hard_to_fit_Contacts__c = True;
                con.Specializes_in_Low_Vision__c = True;
                con.Specializes_in_Vision_Therapy__c = True;
                insert con;
                system.assertNotEquals(con.Email,'test@12345.com');
                
                Contact_Role__c role = new Contact_Role__c();
                role.Account__c = acc.id; 
                role.contact__c  = Con.id;
                role.Type__c  = 'Doctor-Employee';
                role.Start_Date__c = Date.Today();
                insert role;
                
                Network_Recruitment__c net = new Network_Recruitment__c();
                net.npi__c='1851364921';
                net.Recruitment_Type__c='Doctor Initiated';
                net.Recruitment_Status__c = 'New Lead';
                net.Doctor_id__c='12345';
                net.Additional_Office_Locations__c ='11234 Arizona Phoenix A38 11234';
                net.Contact_Role__c = role.id;
                net.ownerId = userInfo.getUserId();
                insert net;
                system.assertEquals(net.Recruitment_Status__c,'New Lead');
                system.assertEquals(net.Recruitment_Type__c,'Doctor Initiated');
                
                task t = new task();
                t.whatID =net.id;
                t.Subject ='Duplicate VSP  Doctor Request Submitted';
                t.Type ='Outbound Call';
                t.Status = 'Not Started';
                t.Priority ='Normal';
                t.ActivityDate =Date.Today() + 7; 
                t.ReminderDateTime =DateTime.Now().addHours(48);
                t.OwnerId  = net.ownerId;
                insert t;
                VSPUtility.stopAccountTrigger=true;
                update acc;
                
                DSSendtoBackend av=new DSSendtoBackend(userinfo.getuserid(),role.id,'23424',system.now());
                DSSendtoQueue.sobjectsListRequests sd=new DSSendtoQueue.sobjectsListRequests();
                sd.UID=userinfo.getuserid();
                sd.OBID=role.id;
                sd.phoneNum='23424';
                sd.callBackTime=system.now();
                DSSendtoQueue.DSSendtoQueue(new List<DSSendtoQueue.sobjectsListRequests>{sd});
                
                
                
                
                
                
   			VSPR19b_NetRelationshipsVisionCareBatch activeNetRelsVC1 = new VSPR19b_NetRelationshipsVisionCareBatch();
   			Database.ExecuteBatch(activeNetRelsVC1,1); 
   			Test.StopTest();
   			
   			VSPR2_UpdateContactRoleBatch hj=new VSPR2_UpdateContactRoleBatch();
   			Database.ExecuteBatch(hj,1); 
         
        
    }
}