force/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Bypass_VC_Validation_Rules__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass VC Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vision_Care_Location_Exception__c</fullName>
        <label>Vision Care Location Exception</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AGT - Agreement Non-Compliance</fullName>
                </value>
                <value>
                    <fullName>CTG - Group Agreement</fullName>
                </value>
                <value>
                    <fullName>DRS - Not all doctors are VSP Providers</fullName>
                </value>
                <value>
                    <fullName>DSP - Does not Dispense Glasses</fullName>
                </value>
                <value>
                    <fullName>FQH - FQHC Center</fullName>
                </value>
                <value>
                    <fullName>HRSA - Office Hours Exception</fullName>
                </value>
                <value>
                    <fullName>IHSC - Indian Health Clinic</fullName>
                </value>
                <value>
                    <fullName>SITE - On-site Clinic</fullName>
                </value>
                <value>
                    <fullName>COFR - Does not Maintain 200 Frames</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vision_Care_Practice_Exception__c</fullName>
        <label>Vision Care Practice Exception</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AOFF - Non-VSP Location</fullName>
                </value>
                <value>
                    <fullName>EFTX - No EFT</fullName>
                </value>
                <value>
                    <fullName>OFF - Does not own Dispensary</fullName>
                </value>
                <value>
                    <fullName>POWN - Non-Doctor Ownership</fullName>
                </value>
                <value>
                    <fullName>EQOW - Does not meet Equipment or Ownership Requirements</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/General_Table__c.object
<CustomObject>
    <label>General Table</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>General Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force/src/objects/Network_Relationship__c.object
<CustomObject>
    <description>Custom object to track Payment Relationships between doctors and offices.</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Network Relationships</relationshipLabel>
        <relationshipName>Network_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Bypass_VC_Validation_Rules__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass VC Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Exception_Reason_Calculation__c</fullName>
        <description>Calculates the Vision Care Exception Reasons from Practice Account, Business Account, Contact, and Contact Role and displays the exception if the Program ID = VSP</description>
        <formula>IF( Program_ID__r.Name  = &apos;VSP&apos; &amp;&amp; NOT(ISBLANK( TEXT(Account_Name__r.Parent.Vision_Care_Practice_Exception__c ))), TEXT(Account_Name__r.Parent.Vision_Care_Practice_Exception__c), 

IF(Program_ID__r.Name = &apos;VSP&apos; &amp;&amp; NOT(ISBLANK(TEXT( Account_Name__r.Vision_Care_Location_Exception__c ))), TEXT( Account_Name__r.Vision_Care_Location_Exception__c),

IF(Program_ID__r.Name = &apos;VSP&apos; &amp;&amp; NOT(ISBLANK(TEXT( Provider_Name__r.Vision_Care_Doctor_Exception__c ))), TEXT( Provider_Name__r.Vision_Care_Doctor_Exception__c), 

IF(Program_ID__r.Name = &apos;VSP&apos; &amp;&amp; NOT(ISBLANK(TEXT( Contact_Role__r.Vision_Care_Contact_Role_Exception__c ))), TEXT( Contact_Role__r.Vision_Care_Contact_Role_Exception__c), &quot;&quot;)
)
)
)</formula>
        <label>Exception Reason Calculation</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exception_Reason__c</fullName>
        <label>Exception Reason</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program_End_Date__c</fullName>
        <label>Program End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Program_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup relationship field from Network Relationship to General Table object</description>
        <label>Program ID</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>General_Table__c.Table__c</field>
                <operation>equals</operation>
                <value>PRSP</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>General_Table__c</referenceTo>
        <relationshipLabel>Network Relationships</relationshipLabel>
        <relationshipName>Network_Relationships</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Update__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Triggers an update on the record and sends outbound message for data integration</description>
        <label>Update</label>
        <type>Checkbox</type>
    </fields>
    <label>Network Relationship</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Network Relationship Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Network Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force/src/objects/Skip_Trigger__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Skip_Triggers__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Skip all PROS Decommission-related Triggers on Account, Contact, Contact Role, and Network Relationship objects.</description>
        <label>Skip Triggers</label>
        <type>Checkbox</type>
    </fields>
    <label>Skip Trigger</label>
</CustomObject>

src/classes/VSPR19b_AddExceptionToRelatedNRRecords.cls
/**
* Class Name: VSPR19b_AddExceptionToRelatedNRRecords
* Date: March 01, 2018
* Project: PROS Decommission
* @author: Shravani Chigullapally
* @description: Populates Update__c field with the value "True" on associated Network Relationship records when Vision_Care_Location_Exception__c field on Business or  Vision_Care_Practice_Exception__c field on Practice is changed.
*/

public with sharing class VSPR19b_AddExceptionToRelatedNRRecords{
    public static boolean VSPR19b_AddExceptionToRelatedNRRecords_recursion = true;
    //method holds logic of trigger VSPR19b_AddExceptionToRelatedNRRecords
    public void VSPR19b_AddExceptionToRelatedNRRecords(List<Account> newTrigger, Map<Id,Account> oldMap, Boolean isTrgUpdate){
        if(VSPR19b_AddExceptionToRelatedNRRecords_recursion){
            VSPR19b_AddExceptionToRelatedNRRecords_recursion = false;
            system.debug('***** entered VSPR19b_AddExceptionToRelatedNRRecords ***** ');
            Boolean isUpdate = false;
            Set<id> pracAccIDs = new set<id>();
            Set<id> busAccIDs = new set<id>();
            List<Network_Relationship__c> netRelList = new List<Network_Relationship__c>();
            String pracException, busException;
            String busAccRecordTypeId=[SELECT Id from RecordType where SObjectType = 'Account' and Name='Business Account'].Id;
            String pracAccRecordTypeId=[SELECT Id from RecordType where SObjectType = 'Account' and Name='Practice Account'].Id;
            Skip_Trigger__c skip = Skip_Trigger__c.getInstance();
            if(skip.Skip_Triggers__c) { 
                return;
            }
            for(Account acc : newTrigger){
                if(acc.RecordTypeId == pracAccRecordTypeId){
                    pracAccIDs.add(acc.id);
                }
                if(acc.RecordTypeId == busAccRecordTypeId){
                    busAccIDs.add(acc.id);
                }
                if(isTrgUpdate){
                    Account oldAcc = oldMap.get(acc.Id);
                    
                    system.debug('++++++++++++oldAcc.Vision_Care_Practice_Exception__c++++++++++++++++++++++++++' +oldAcc.Vision_Care_Practice_Exception__c);
                    system.debug('++++++++++++acc.Vision_Care_Practice_Exception__c++++++++++++++++++++++++++' +acc.Vision_Care_Practice_Exception__c);
                    
                    system.debug('++++++++++++acc.Vision_Care_Location_Exception__c++++++++++++++++++++++++++' +acc.Vision_Care_Location_Exception__c);
                    system.debug('++++++++++++oldAcc.Vision_Care_Location_Exception__c++++++++++++++++++++++++++' +oldAcc.Vision_Care_Location_Exception__c);
                    
                    if(oldAcc.Vision_Care_Practice_Exception__c == acc.Vision_Care_Practice_Exception__c && acc.RecordTypeId == pracAccRecordTypeId){
                        isUpdate = true;
                    }
                    if(oldAcc.Vision_Care_Location_Exception__c == acc.Vision_Care_Location_Exception__c && acc.RecordTypeId == busAccRecordTypeId){
                        isUpdate = true;
                    }
                }
            }

            system.debug('+++++++++++++++++++isUpdate++++++++++++++++++' +isUpdate);
            system.debug('+++++++++++++++++++busAccIDs++++++++++++++++++' +busAccIDs);
            system.debug('+++++++++++++++++++busAccIDs++++++++++++++++++' +busAccIDs.size());
            
            if(pracAccIDs.size() > 0 && isUpdate == false){
                List<Account> lstBusAcc = [Select Id from Account where RecordType.Name = 'Business Account' AND ParentId IN :pracAccIDs];
                for(Account a : lstBusAcc){
                    busAccIDs.add(a.id);
                }
            }
            
            
            if(busAccIDs.size() > 0 && isUpdate == false){
                list<Network_Relationship__c> busNetworkRelationshipList = [SELECT id, Exception_Reason__c, Exception_Reason_Calculation__c FROM Network_Relationship__c WHERE Account_Name__c in : busAccIDs AND Program_ID__r.name = 'VSP' AND (Program_End_Date__c >= TODAY OR Program_End_Date__c = NULL)];
                
                system.debug('+++++++++++++++++++busNetworkRelationshipList++++++++++++++++++' +busNetworkRelationshipList);
                
                if(busNetworkRelationshipList.size() >0){
                    for(Network_Relationship__c nr : busNetworkRelationshipList){
                        nr.Exception_Reason__c = nr.Exception_Reason_Calculation__c;
                        nr.Bypass_VC_Validation_Rules__c = true;
                        netRelList.add(nr);
                    }
                }
            }
            if(netRelList.size() > 0){
                update netRelList;
            }
            system.debug('***** exiting VSPR19b_AddExceptionToRelatedNRRecords ***** ');
        }
    }
}