force/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Eyefinity_Access__c</fullName>
        <label>Eyefinity Access</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>B - Basic</fullName>
                </value>
                <value>
                    <fullName>J - Participates in E-Claim</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fee_Calculation_Code__c</fullName>
        <label>Fee Calculation Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>O - Old Calculated Fee Schedule</fullName>
                </value>
                <value>
                    <fullName>N - New Calculated Fee Schedule</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Location_Type__c</fullName>
        <label>Location Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>M - VSP Member Location</fullName>
                </value>
                <value>
                    <fullName>A - Affiliate Provider Location</fullName>
                </value>
                <value>
                    <fullName>F - Laser Vision Correction (LVC)</fullName>
                </value>
                <value>
                    <fullName>X - Client Authorized Location (GAP)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Distribution__c</fullName>
        <description>Vision Care Practice receives one total payment or individual payments for each Business Account</description>
        <label>Payment Distribution</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Practice Account</fullName>
                </value>
                <value>
                    <fullName>Business Account(s)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <description>Practice Account Payment Method</description>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Check</fullName>
                </value>
                <value>
                    <fullName>Direct Deposit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Practice_Business_Type__c</fullName>
        <label>Practice Business Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>S - Sole Proprietor</fullName>
                </value>
                <value>
                    <fullName>C - Corporation</fullName>
                </value>
                <value>
                    <fullName>F - Laser Vision Correction</fullName>
                </value>
                <value>
                    <fullName>P - Partnership</fullName>
                </value>
                <value>
                    <fullName>U - Optometric School or University</fullName>
                </value>
                <value>
                    <fullName>V - Affiliate Provider</fullName>
                </value>
                <value>
                    <fullName>W - Applicant Doctor</fullName>
                </value>
                <value>
                    <fullName>X - Group Authorized Provider</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Products_and_Assets__c</fullName>
        <label>Products and Assets</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>L&amp;R Frame Lens Package</fullName>
                </value>
                <value>
                    <fullName>Level</fullName>
                </value>
                <value>
                    <fullName>RightEye</fullName>
                </value>
                <value>
                    <fullName>Shift Series</fullName>
                </value>
                <value>
                    <fullName>TRICARE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tax_ID__c</fullName>
        <description>Account Tax ID.</description>
        <encrypted>true</encrypted>
        <inlineHelpText>Account Tax ID.</inlineHelpText>
        <label>Tax ID</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Care_Effective_Date__c</fullName>
        <label>Vision Care Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Care_End_Date__c</fullName>
        <label>Vision Care End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Care_Location_Phone_Number__c</fullName>
        <label>Vision Care Location Phone Number</label>
        <type>Phone</type>
    </fields>
    <recordTypes>
        <fullName>Business_Account</fullName>
        <active>true</active>
        <description>A business entity doing business/providing a service or expressing an intent to do business/provide service with at least one VSP Global line of business.</description>
        <label>Business Account</label>
    </recordTypes>
    <recordTypes>
        <fullName>Practice_Account</fullName>
        <active>true</active>
        <description>A business entity representing the practice (identified by Tax ID) having a parent relationship over one or more Business Accounts.</description>
        <label>Practice Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/VSPR25_UpdatePracticeProdAssets_Test.cls
///Test Class for VSPR25_UpdatePracticeProdAssets
@isTest
public class VSPR25_UpdatePracticeProdAssets_Test {
 public static testmethod void testNewContactRole() { 
        
        String uniqueUserName = 'standarduser' + DateTime.now().getTime() + '@vsp.com';
        
        // This code runs as the system user
        Profile p = [SELECT Id FROM Profile WHERE Name='VSP Technical User'];
        User u = new User(Alias = 'standt', Email='standarduser@vsp.com',
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                          LocaleSidKey='en_US', ProfileId = p.Id,
                          TimeZoneSidKey='America/Los_Angeles',
                          UserName=uniqueUserName);
        
        System.runAs(u){
            
            test.starttest();
            Account acc= new Account();
            acc.Name='Practice Account Name';
            acc.Vision_Care_Effective_Date__c = Date.newInstance(2018, 07, 01);
            acc.Tax_ID__c = '123456789';
            acc.Phone = '1234567890';
            acc.ShippingStreet = '123 Test Street';
            acc.ShippingCity = 'Somewhere';
            acc.ShippingState = 'CA';
            acc.ShippingPostalCode = '90210';
            acc.ShippingCountry = 'USA';
            acc.Practice_Business_Type__c = 'S - Sole Proprietor';
            acc.Fee_Calculation_Code__c = 'N - New Calculated Fee Schedule';
            acc.Payment_Method__c = 'Direct Deposit';
            acc.Payment_Distribution__c = 'Practice Account';
            Id practiceRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Practice_Account').getRecordTypeId();
            
            acc.RecordTypeId =  practiceRecordTypeId;        
            insert acc;
            system.debug('++++++++++++++++++++++++++++  TestClassAccId  ++++++++++++++++++++++++++++++++++++++++++++++' + acc.Id);
            
            
            Account acc1= new Account();
            Id businessRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Business_Account').getRecordTypeId();
            acc1.Name='Business Account Name';       
            acc1.ParentId = acc.id;
            acc1.Fax = '123456789';
            acc1.ShippingStreet = '123 Test Street';
            acc1.ShippingCity = 'Somewhere';
            acc1.ShippingState = 'CA';
            acc1.ShippingPostalCode = '90210';
            acc1.ShippingCountry = 'USA';
            acc1.Vision_Care_Location_Phone_Number__c = '123456789';
            acc1.Eyefinity_Access__c = 'B - Basic';
            acc1.Location_Type__c = 'A - Affiliate Provider Location';
            acc1.Tax_ID__c = '123456789';
            acc1.Vision_Care_Effective_Date__c = Date.newInstance(2018, 07, 01);
            acc1.Vision_Care_End_Date__c = System.today() + 3;
            acc1.Products_and_Assets__c = 'Level';
            acc1.RecordTypeId =  businessRecordTypeId; 
            
            insert acc1;  
            
           
            acc1.Products_and_Assets__c = 'Level; RightEye';
            
            update acc1;
            delete acc1;
            
            
            Account acc2= new Account();  //null Parent Id for Bus Account
           
            acc2.Name='Business Account Name';       
          //  acc2.ParentId = acc.id;
            acc2.Fax = '123456789';
            acc2.ShippingStreet = '123 Test Street';
            acc2.ShippingCity = 'Somewhere';
            acc2.ShippingState = 'CA';
            acc2.ShippingPostalCode = '90210';
            acc2.ShippingCountry = 'USA';
            acc2.Vision_Care_Location_Phone_Number__c = '123456789';
            acc2.Eyefinity_Access__c = 'B - Basic';
            acc2.Location_Type__c = 'A - Affiliate Provider Location';
            acc2.Tax_ID__c = '123456789';
            acc2.Vision_Care_Effective_Date__c = Date.newInstance(2018, 07, 01);
            acc2.Vision_Care_End_Date__c = System.today() + 3;
            acc2.Products_and_Assets__c = 'Level';
            acc2.RecordTypeId =  businessRecordTypeId; 
            
            insert acc2;  
            
            test.stoptest();
            
            
        }
        
    }
}