force/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <description>Is Account a Practice Account, Business Account or Account Group.</description>
        <inlineHelpText>Is Account a Practice Account, Business Account or Account Group.</inlineHelpText>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account Group</fullName>
                </value>
                <value>
                    <fullName>Business Account</fullName>
                </value>
                <value>
                    <fullName>Practice Account</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Altair_Exception__c</fullName>
        <label>Altair - Exception</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Altair_Field_Rep__c</fullName>
        <label>Altair - Field Rep</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Altair_Hybrid_Bebe__c</fullName>
        <label>Altair - Hybrid Bebe</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Altair_Key_Account__c</fullName>
        <label>Altair - Key Account</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Altair_Standard__c</fullName>
        <label>Altair Prospect Rep</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Eyefinity_Inside_Sales__c</fullName>
        <label>Eyefinity Inside Sales</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Eyefinity_Outside_Sales__c</fullName>
        <label>Eyefinity Outside Sales</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Global_Business_Development_Manager__c</fullName>
        <label>Global Business Development Manager</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Global_Business_Development_Partner__c</fullName>
        <label>Global Business Development Boundary</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marchon_Close_Out__c</fullName>
        <label>Marchon - Close Out</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marchon_Key_Account__c</fullName>
        <label>Marchon - Key Account</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marchon_Optical__c</fullName>
        <label>Marchon Prospect Rep</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marchon_Retail__c</fullName>
        <label>Marchon Retail</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ophthalmic_Business_Consultant__c</fullName>
        <label>Ophthalmic Business Consultant</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Optics_Contact_Lens_Consultant__c</fullName>
        <label>Optics Contact Lens Consultant</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Optics_Wholesale__c</fullName>
        <label>Optics Business Development Manager</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of Account.</description>
        <inlineHelpText>A = Active 
Inactive = Not a Current Customer of any LOB. 
Closed = Business has ceased operations 
New = In process of becoming an Active account</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Submit for Approval</fullName>
                </value>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Inactive Ownership Change</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
                <value>
                    <fullName>Marked for Deletion</fullName>
                </value>
                <value>
                    <fullName>Archive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VC_EDS_NA__c</fullName>
        <label>Vision Care Network Administrator</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VC_Relationship_Manager__c</fullName>
        <defaultValue>&quot;PRMI0001&quot;</defaultValue>
        <label>Vision Care Relationship Manager</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force/src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Address_Type__c</fullName>
        <label>Address Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Physical</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Shipping</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <formula>Street__c &amp; &apos;, &apos; &amp; City__c &amp; &apos;, &apos; &amp; State__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force/src/objects/Address_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Address Relationships</relationshipLabel>
        <relationshipName>Address_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Address_Type__c</fullName>
        <label>Address Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Physical</fullName>
                </value>
                <value>
                    <fullName>Shipping</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Address Relationships</relationshipLabel>
        <relationshipName>Address_Relationships</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF( End_Date__c  &lt; TODAY(), &quot;Inactive&quot;, &quot;Active&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Address Relationship</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Address Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Address Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Birthdate__c</fullName>
        <encrypted>true</encrypted>
        <label>Birthdate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CAQH_ID__c</fullName>
        <label>CAQH ID</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <formula>HYPERLINK(&quot;/&quot; + Id, &quot;Contact Record&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Record</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Degree__c</fullName>
        <description>The educational degree of the Vision Care Doctor.</description>
        <inlineHelpText>The educational degree of the Vision Care Doctor.</inlineHelpText>
        <label>Degree</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>OD</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>DO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Marketing_Name__c</fullName>
        <inlineHelpText>The contact&apos;s name used for Marketing Campaigns.</inlineHelpText>
        <label>Marketing Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Status of Contact.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force/src/objects/Contact_Role__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accounting</fullName>
                </value>
                <value>
                    <fullName>Board Member/ Officer</fullName>
                </value>
                <value>
                    <fullName>Dean</fullName>
                </value>
                <value>
                    <fullName>Doctor-Employee</fullName>
                </value>
                <value>
                    <fullName>Doctor-Owner</fullName>
                </value>
                <value>
                    <fullName>Doctor-Unspecified</fullName>
                </value>
                <value>
                    <fullName>Group Administrator</fullName>
                </value>
                <value>
                    <fullName>Lab Technician</fullName>
                </value>
                <value>
                    <fullName>Member</fullName>
                </value>
                <value>
                    <fullName>Office Administration</fullName>
                </value>
                <value>
                    <fullName>Office Manager</fullName>
                </value>
                <value>
                    <fullName>Optical Buyer</fullName>
                </value>
                <value>
                    <fullName>Optical Manager</fullName>
                </value>
                <value>
                    <fullName>Optician</fullName>
                </value>
                <value>
                    <fullName>Optician-Owner</fullName>
                </value>
                <value>
                    <fullName>Owner</fullName>
                </value>
                <value>
                    <fullName>Student</fullName>
                </value>
                <value>
                    <fullName>Unspecified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force/src/classes/VSPR3_NetworkRecruitmentControllerTest.cls
/* 
* Class Name: VSPR3_NetworkRecruitmentControllerTest
* Created By: Amit Shinde, 09/15/2015
* Description: Test Class for VSPR3_NetworkRecruitmentController
* Updates:
*/

@isTest(SeeAllData = false)
public class VSPR3_NetworkRecruitmentControllerTest {
    static testMethod void unitTest(){   
        
        // Insert sample Account with email
        Account acc0 = new Account();
        acc0.Name = 'Sample Account 0';
        acc0.Status__c = 'New';
        acc0.Account_Type__c = 'Business Account';
        acc0.Email__c = 'vsp@vsp.com';
        acc0.Fax = '1112223333';
        acc0.Phone = '111223333';
        acc0.Altair_Standard__c = '001';
        acc0.Altair_Field_Rep__c = '001'; 
        acc0.Altair_Key_Account__c = '001';
        acc0.Altair_Exception__c = '001'; 
        acc0.Altair_Hybrid_Bebe__c = '001'; 
        acc0.Ophthalmic_Business_Consultant__c = '001'; 
        acc0.Optics_Contact_Lens_Consultant__c = '001'; 
        acc0.Marchon_Key_Account__c = '001'; 
        acc0.Marchon_Close_Out__c = '001'; 
        acc0.Marchon_Optical__c = '001'; 
        acc0.Marchon_Retail__c = '001';
        acc0.VC_EDS_NA__c = '001'; 
        acc0.Global_Business_Development_Manager__c = '001';
        acc0.Global_Business_Development_Partner__c = '001';
        acc0.VC_Relationship_Manager__c = '001'; 
        acc0.Optics_Wholesale__c = '001'; 
        acc0.Eyefinity_Inside_Sales__c = '001'; 
        acc0.Eyefinity_Outside_Sales__c = '002';
        insert acc0;
        
        // Insert sample Account without email
        Account acc1 = new Account();
        acc1.Name = 'Sample Account 0';
        acc1.Status__c = 'New';
        acc1.Account_Type__c = 'Business Account';
        acc1.Email__c = null;
        acc1.Altair_Standard__c = '001';
        acc1.Altair_Field_Rep__c = '001'; 
        acc1.Altair_Key_Account__c = '001';
        acc1.Altair_Exception__c = '001'; 
        acc1.Altair_Hybrid_Bebe__c = '001'; 
        acc1.Ophthalmic_Business_Consultant__c = '001'; 
        acc1.Optics_Contact_Lens_Consultant__c = '001'; 
        acc1.Marchon_Key_Account__c = '001'; 
        acc1.Marchon_Close_Out__c = '001'; 
        acc1.Marchon_Optical__c = '001'; 
        acc1.Marchon_Retail__c = '001';
        acc1.VC_EDS_NA__c = '001'; 
        acc1.Global_Business_Development_Manager__c = '001';
        acc1.Global_Business_Development_Partner__c = '001';
        acc1.VC_Relationship_Manager__c = '001'; 
        acc1.Optics_Wholesale__c = '001'; 
        acc1.Eyefinity_Inside_Sales__c = '001'; 
        acc1.Eyefinity_Outside_Sales__c = '002';
        insert acc1;
        
        //Insert Sample address
        Address__c address = new Address__c();
        address.Street__c = '111 Sample St';
        address.City__c = 'Rancho Cordova';
        address.State__c = 'CA';
        address.Zip__c = '95670';
        address.Country__c = 'USA';
        insert address;
        
        //Associate account with address 
        Address_Relationship__c accaddressrel = new Address_Relationship__c();
        accaddressrel.Account__c = acc0.id;
        accaddressrel.Address__c = address.Id;
        accaddressrel.Address_Type__c = 'Physical';
        insert accaddressrel;
        
        //Contact where CAQH_ID__c is not null
        Contact con0 = new Contact();
        con0.LastName = 'Text0000';
        con0.FirstName = 'Sample0000';
        con0.CAQH_ID__c = '000';
        con0.Marketing_Name__c = '000';
        con0.AccountId = acc0.id;
        con0.Birthdate__c = date.newInstance(1979, 3, 21);
        con0.Degree__c = 'MD';
        insert con0;
        
        //Contact where CAQH_ID__c is null
        Contact con1 = new Contact();
        con1.LastName = 'Text00001';
        con1.FirstName = 'Sample00001';
        con1.Marketing_Name__c = '001';
        con1.AccountId = acc0.id;
        con1.Birthdate__c = date.newInstance(1979, 3, 21);
        insert con1;
        
        //Contact where CAQH_ID__c is null and date of birth is null
        Contact con2 = new Contact();
        con2.LastName = 'Text00002';
        con2.FirstName = 'Sample00002';
        con2.Marketing_Name__c = '002';
        con2.AccountId = acc0.id;
        con2.Birthdate__c = null;
        insert con2;
        
        // Contact Role with account, contact with CAQH_ID__c
        Contact_Role__c conrole0 = New Contact_Role__c();
        conrole0.Account__c = acc0.Id;
        conrole0.Contact__c = con0.Id;
        conrole0.Type__c = 'Accounting';
        insert conrole0;
        
        // Contact Role with account, contact without CAQH_ID__c
        Contact_Role__c conrole1 = New Contact_Role__c();
        conrole1.Account__c = acc0.Id;
        conrole1.Contact__c = con1.Id;
        conrole1.Type__c = 'Accounting';
        insert conrole1;
        
        // Contact Role with account with no email, contact without CAQH_ID__c
        Contact_Role__c conrole2 = New Contact_Role__c();
        conrole2.Account__c = acc1.Id;
        conrole2.Contact__c = con1.Id;
        conrole2.Type__c = 'Accounting';
        insert conrole2;
        
        // Contact Role with account with no email, contact without CAQH_ID__c and DOB
        Contact_Role__c conrole3 = New Contact_Role__c();
        conrole3.Account__c = acc0.Id;
        conrole3.Contact__c = con2.Id;
        conrole3.Type__c = 'Accounting';
        insert conrole3;
        
        // Contact Role with account, contact with CAQH_ID__c
        PageReference pageRef0 = Page.VSPR3_NetworkRecruitment;   
        pageRef0.getParameters().put('cRoleid',conrole0.Id);    
        pageRef0.getParameters().put('dob',con0.Birthdate__c.format());
        System.Test.setCurrentPage(pageRef0); 
        ApexPages.StandardController sc0 = new ApexPages.standardController(conrole0);
        VSPR3_NetworkRecruitmentController controller0 = new VSPR3_NetworkRecruitmentController(sc0);
        controller0.getRawDetails();
        
        // Contact Role with account with email, contact without CAQH_ID__c
        PageReference pageRef1 = Page.VSPR3_NetworkRecruitment;   
        pageRef1.getParameters().put('cRoleid',conrole1.Id);    
        pageRef1.getParameters().put('dob',con1.Birthdate__c.format());
        System.Test.setCurrentPage(pageRef1); 
        ApexPages.StandardController sc1 = new ApexPages.standardController(conrole1);
        VSPR3_NetworkRecruitmentController controller1 = new VSPR3_NetworkRecruitmentController(sc1);
        controller1.getRawDetails();
        
        // Contact ROle with Account without email, without CAQH_ID__c
        PageReference pageRef2 = Page.VSPR3_NetworkRecruitment;   
        pageRef2.getParameters().put('cRoleid',conrole2.Id);    
        pageRef2.getParameters().put('dob','');
        System.Test.setCurrentPage(pageRef2); 
        ApexPages.StandardController sc2 = new ApexPages.standardController(conrole2);
        VSPR3_NetworkRecruitmentController controller2 = new VSPR3_NetworkRecruitmentController(sc2);
        controller2.getRawDetails();
        
    }
}