force/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <description>For Practice and Business accounts so that the data can be populated for use in premier tier calculation.
Population on Business account will be manual or through data loader.</description>
        <inlineHelpText>Identifies the location&apos;s relationship with VSP for Premier Tiering</inlineHelpText>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Affiliate</fullName>
                </value>
                <value>
                    <fullName>AOP</fullName>
                </value>
                <value>
                    <fullName>CAT2</fullName>
                </value>
                <value>
                    <fullName>Conflict</fullName>
                </value>
                <value>
                    <fullName>GAP</fullName>
                </value>
                <value>
                    <fullName>Independent</fullName>
                </value>
                <value>
                    <fullName>LVC</fullName>
                </value>
                <value>
                    <fullName>Near Site</fullName>
                </value>
                <value>
                    <fullName>Net Dev Excluded</fullName>
                </value>
                <value>
                    <fullName>Net Dev Purchasing Requirement</fullName>
                </value>
                <value>
                    <fullName>Not Supported</fullName>
                </value>
                <value>
                    <fullName>Onsite</fullName>
                </value>
                <value>
                    <fullName>Pearle Vision CO</fullName>
                </value>
                <value>
                    <fullName>Pearle Vision LO</fullName>
                </value>
                <value>
                    <fullName>Pop Up</fullName>
                </value>
                <value>
                    <fullName>Rollup</fullName>
                </value>
                <value>
                    <fullName>School</fullName>
                </value>
                <value>
                    <fullName>VSP Retail</fullName>
                </value>
                <value>
                    <fullName>VSP Ventures</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Location_Type__c</fullName>
        <label>Location Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>M - VSP Member Location</fullName>
                </value>
                <value>
                    <fullName>A - Affiliate Provider Location</fullName>
                </value>
                <value>
                    <fullName>F - Laser Vision Correction (LVC)</fullName>
                </value>
                <value>
                    <fullName>X - Client Authorized Location (GAP)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_Company__c</fullName>
        <label>Parent Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AEHG- Acuity Eyecare Holding Group</fullName>
                </value>
                <value>
                    <fullName>CLRK - Clarkson Eyecare Location</fullName>
                </value>
                <value>
                    <fullName>COHN - Cohen&apos;s Fashion Optical</fullName>
                </value>
                <value>
                    <fullName>COST - Costco Location</fullName>
                </value>
                <value>
                    <fullName>CVS - CVS Location</fullName>
                </value>
                <value>
                    <fullName>ECCA - ECCA or Visionworks Location</fullName>
                </value>
                <value>
                    <fullName>FEGV - For Eyes Grand Vision</fullName>
                </value>
                <value>
                    <fullName>GRRA - Grand Rapids Ophthalmology</fullName>
                </value>
                <value>
                    <fullName>INTL - International Eyecare Center Location</fullName>
                </value>
                <value>
                    <fullName>JVNTR - Joint Ventures</fullName>
                </value>
                <value>
                    <fullName>MEDR - MyEyeDr. Location</fullName>
                </value>
                <value>
                    <fullName>OCNB - Near-site Clinic Location, VSP</fullName>
                </value>
                <value>
                    <fullName>OCSI - Onsite Clinic Location, VSP</fullName>
                </value>
                <value>
                    <fullName>OPTX - Optyx Location</fullName>
                </value>
                <value>
                    <fullName>PERL - Pearle Vision Location</fullName>
                </value>
                <value>
                    <fullName>POP - Pop-Up Clinic Location, VSP</fullName>
                </value>
                <value>
                    <fullName>PRIT - Pritchett Eye Care Location</fullName>
                </value>
                <value>
                    <fullName>RXOP - Rx Optical Location</fullName>
                </value>
                <value>
                    <fullName>SHOP - Shopko Location</fullName>
                </value>
                <value>
                    <fullName>TECP - Total Eyecare Partners</fullName>
                </value>
                <value>
                    <fullName>TOTV - Total Vision Inc</fullName>
                </value>
                <value>
                    <fullName>VNTR - VSP Ventures</fullName>
                </value>
                <value>
                    <fullName>WALM - Walmart Location</fullName>
                </value>
                <value>
                    <fullName>WVIS - Wisconsin Vision Location</fullName>
                </value>
                <value>
                    <fullName>OCCV - CVS Location, VSP</fullName>
                    <isActive>false</isActive>
                    <label>OCCV - CVS Location, VSP</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Premier_Tax_ID_Roll_Up_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Indicates whether an Account is being evaluated for Premier qualification in conjunction with other accounts with different Tax ID&apos;s.</inlineHelpText>
        <label>Tax ID Roll Up Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Provider_Category__c</fullName>
        <label>Provider Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AOP - Approved OON Provider</fullName>
                </value>
                <value>
                    <fullName>CAT2 - Non-Standard Ownership Model</fullName>
                </value>
                <value>
                    <fullName>CNTRC - Contract Provider</fullName>
                </value>
                <value>
                    <fullName>OFPCS - Pearle Vision Corp Sublease Holder</fullName>
                </value>
                <value>
                    <fullName>OFPLS - Pearle Vision L.O Sublease Holder</fullName>
                </value>
                <value>
                    <fullName>PEARL - License Operator Pearle Vision</fullName>
                </value>
                <value>
                    <fullName>PVCO - Corp Managed Pearle Vision</fullName>
                </value>
                <value>
                    <fullName>RETL - VSP Retail</fullName>
                </value>
                <value>
                    <fullName>SCHLS - Optometric School or University</fullName>
                </value>
                <value>
                    <fullName>VNTR - VSP Ventures</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vision_Care_Effective_Date__c</fullName>
        <label>Vision Care Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Care_Good_Standing__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is account in good standing with Vision Care.</description>
        <inlineHelpText>Is account in good standing with Vision Care.</inlineHelpText>
        <label>Vision Care Good Standing</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Exception_handler_Email__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Exception Handler Email</label>
</CustomObject>

force/src/classes/VSPR31_PracticeContractTypeBatch_Test.cls
@isTest public class VSPR31_PracticeContractTypeBatch_Test {

	private static Id businessRecordTypeID = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
	private static Id practiceRecordTypeID = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Practice Account').getRecordTypeId();

	//Testing for scenario where the practice account is not in good standing. 
	public static testmethod void testMethod1(){

		//List<Account> accountList = new List<Account>();

		Account a1 = new Account();
		a1.Name = 'Practice Account Test';
		a1.recordTypeId = practiceRecordTypeID;
		a1.Premier_Tax_ID_Roll_Up_Account__c = true;
		insert a1;

		Account a2 = new Account();
		a2.Name = 'Testing Account';
		a2.Location_Type__c = 'X - Client Authorized Location (GAP)';
		a2.Vision_Care_Good_Standing__c = true;
		a2.Provider_Category__c = 'PVCO - Corp Managed Pearle Vision';
		a2.Parent_Company__c = 'PERL - Pearle Vision Location';
		a2.recordTypeID = businessRecordTypeID;
		a2.ParentId = a1.id;
		insert a2;

		Exception_handler_Email__c toAddress = new Exception_handler_Email__c();
        toAddress.Name = 'test@vsp.com';
        insert toAddress;

		VSPR31_PracticeContractTypeBatch job = new VSPR31_PracticeContractTypeBatch();

		Test.startTest();
		Id jobId = Database.executeBatch(job);
		Test.stopTest();

		Account a3 = [Select id, Contract_Type__c from Account where Name = 'Practice Account Test'];
		System.assertEquals(a3.Contract_Type__c, null);

	}


	//Testing for scenario where the practice account is a tax id rollup.
	public static testmethod void testMethod2(){

		List<Account> accountList = new List<Account>();

		Account acc = new Account();
		acc.Name = 'Practice Account Test';
		acc.recordTypeId = practiceRecordTypeID;
		acc.Premier_Tax_ID_Roll_Up_Account__c = true;
		acc.Vision_Care_Good_Standing__c = true;
		insert acc;

		Account a1 = new Account();
		a1.Name = 'Business Test Account 1';
		a1.Location_Type__c = 'F - Laser Vision Correction (LVC)';
		a1.recordTypeId = businessRecordTypeID;
		a1.Vision_Care_Good_Standing__c = true;
		a1.Provider_Category__c = 'PVCO - Corp Managed Pearle Vision';
		a1.ParentId = acc.id;
		a1.Vision_Care_Effective_Date__c = System.today().addDays(-1);
		accountList.add(a1);

		Account a2 = new Account();
		a2.Name = 'Testing Account';
		a2.Location_Type__c = 'X - Client Authorized Location (GAP)';
		a2.Vision_Care_Good_Standing__c = true;
		a2.Provider_Category__c = 'PVCO - Corp Managed Pearle Vision';
		a2.Parent_Company__c = 'PERL - Pearle Vision Location';
		a2.recordTypeID = businessRecordTypeID;
		a2.ParentId = acc.id;
		a2.Vision_Care_Effective_Date__c = System.today().addDays(-1);
		accountList.add(a2);

		insert accountList;

		Exception_handler_Email__c toAddress = new Exception_handler_Email__c();
        toAddress.Name = 'test@vsp.com';
        insert toAddress;

		VSPR31_PracticeContractTypeBatch job = new VSPR31_PracticeContractTypeBatch();

		Test.startTest();
		Id jobId1 = Database.executeBatch(job);
		Test.stopTest();

		Account acc1 = [Select id, Contract_Type__c from Account where Name = 'Practice Account Test'];
		System.assertEquals(acc1.Contract_Type__c, 'Rollup');

	}


	//testing for scenario when the account is in good standing but not a tax id rollup.
	//The business accounts have a different contract types.
	public static testmethod void testMethod3(){
		List<Account> accountList = new List<Account>();

		Account acc = new Account();
		acc.Name = 'Practice Account Test';
		acc.recordTypeId = practiceRecordTypeID;
		acc.Vision_Care_Good_Standing__c = true;
		insert acc;

		Account a1 = new Account();
		a1.Name = 'Business Test Account 1';
		a1.Location_Type__c = 'F - Laser Vision Correction (LVC)';
		a1.recordTypeId = businessRecordTypeID;
		a1.Vision_Care_Good_Standing__c = true;
		a1.Provider_Category__c = 'PVCO - Corp Managed Pearle Vision';
		a1.ParentId = acc.id;
		a1.Vision_Care_Effective_Date__c = System.today().addDays(-1);
		accountList.add(a1);

		Account a2 = new Account();
		a2.Name = 'Testing Account';
		a2.Location_Type__c = 'X - Client Authorized Location (GAP)';
		a2.Vision_Care_Effective_Date__c = System.today().addDays(-1);
		a2.Vision_Care_Good_Standing__c = true;
		a2.Provider_Category__c = 'PVCO - Corp Managed Pearle Vision';
		a2.Parent_Company__c = 'PERL - Pearle Vision Location';
		a2.recordTypeID = businessRecordTypeID;
		a2.ParentId = acc.id;
		accountList.add(a2);

		Exception_handler_Email__c toAddress = new Exception_handler_Email__c();
        toAddress.Name = 'test@vsp.com';
        insert toAddress;

		insert accountList;

		VSPR31_PracticeContractTypeBatch job = new VSPR31_PracticeContractTypeBatch();

		Test.startTest();
		Id jobId1 = Database.executeBatch(job);
		Test.stopTest();

		Account acc1 = [Select id, Contract_Type__c from Account where Name = 'Practice Account Test'];
		System.assertEquals(acc1.Contract_Type__c, 'Conflict');
	}

	//testing for scenario when the account is in good standing but not a tax id rollup.
	//The business accounts have a same contract types.
	public static testmethod void testMethod4(){
		List<Account> accountList = new List<Account>();

		Account acc = new Account();
		acc.Name = 'Practice Account Test';
		acc.recordTypeId = practiceRecordTypeID;
		acc.Vision_Care_Good_Standing__c = true;
		insert acc;

		Account a1 = new Account();
		a1.Name = 'Testing Account 1';
		a1.Location_Type__c = 'X - Client Authorized Location (GAP)';
		a1.Vision_Care_Good_Standing__c = true;
		a1.Provider_Category__c = 'PVCO - Corp Managed Pearle Vision';
		a1.Parent_Company__c = 'PERL - Pearle Vision Location';
		a1.recordTypeID = businessRecordTypeID;
		a1.ParentId = acc.id;
		a1.Vision_Care_Effective_Date__c = System.today().addDays(-1);
		accountList.add(a1);

		Account a2 = new Account();
		a2.Name = 'Testing Account';
		a2.Vision_Care_Effective_Date__c = System.today().addDays(-1);
		a2.Location_Type__c = 'X - Client Authorized Location (GAP)';
		a2.Vision_Care_Good_Standing__c = true;
		a2.Provider_Category__c = 'PVCO - Corp Managed Pearle Vision';
		a2.Parent_Company__c = 'PERL - Pearle Vision Location';
		a2.recordTypeID = businessRecordTypeID;
		a2.ParentId = acc.id;
		accountList.add(a2);

		insert accountList;

		Exception_handler_Email__c toAddress = new Exception_handler_Email__c();
        toAddress.Name = 'test@vsp.com';
        insert toAddress;

		VSPR31_PracticeContractTypeBatch job = new VSPR31_PracticeContractTypeBatch();

		Test.startTest();
		Id jobId1 = Database.executeBatch(job);
		Test.stopTest();

		Account acc1 = [Select id, Contract_Type__c from Account where Name = 'Practice Account Test'];
		System.assertEquals(acc1.Contract_Type__c, 'GAP');
	}

	//testing for scenario when the account is in good standing but not a tax id rollup.
	//The business accounts have contract types equals to null.
	public static testmethod void testMethod5(){
		List<Account> accountList = new List<Account>();

		Account acc = new Account();
		acc.Name = 'Practice Account Test';
		acc.recordTypeId = practiceRecordTypeID;
		acc.Vision_Care_Good_Standing__c = true;
		insert acc;

		Account a1 = new Account();
		a1.Name = 'Testing Account 1';
		a1.Location_Type__c = 'X - Client Authorized Location (GAP)';
		//a1.Vision_Care_Good_Standing__c = true;
		a1.Provider_Category__c = 'PVCO - Corp Managed Pearle Vision';
		a1.Parent_Company__c = 'PERL - Pearle Vision Location';
		a1.recordTypeID = businessRecordTypeID;
		a1.ParentId = acc.id;
		accountList.add(a1);

		Account a2 = new Account();
		a2.Name = 'Testing Account';
		a2.Location_Type__c = 'X - Client Authorized Location (GAP)';
		//a2.Vision_Care_Good_Standing__c = true;
		a2.Provider_Category__c = 'PVCO - Corp Managed Pearle Vision';
		a2.Parent_Company__c = 'PERL - Pearle Vision Location';
		a2.recordTypeID = businessRecordTypeID;
		a2.ParentId = acc.id;
		accountList.add(a2);

		insert accountList;

		Exception_handler_Email__c toAddress = new Exception_handler_Email__c();
        toAddress.Name = 'test@vsp.com';
        insert toAddress;

		VSPR31_PracticeContractTypeBatch job = new VSPR31_PracticeContractTypeBatch();

		Test.startTest();
		Id jobId1 = Database.executeBatch(job);
		Test.stopTest();

		Account acc1 = [Select id, Contract_Type__c from Account where Name = 'Practice Account Test'];
		System.assertEquals(acc1.Contract_Type__c, null);
	}
	
}