force/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <label>Line of Business</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Vision Benefits</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>D2C</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Auto_Assign__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Un-check to maintain ownership of this Case when it is created.</inlineHelpText>
        <label>Automatically Assign Case</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Classification__c</fullName>
        <inlineHelpText>The relevant category for the Issue or Request.</inlineHelpText>
        <label>Classification</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account/Contact Maintenance</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Claims</fullName>
                </value>
                <value>
                    <fullName>Credentialing/Recruiting</fullName>
                </value>
                <value>
                    <fullName>Product</fullName>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Shipping</fullName>
                </value>
                <value>
                    <fullName>Status</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <inlineHelpText>The Line of Business responsible for working the Case.</inlineHelpText>
        <label>Line of Business</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Altair</fullName>
                    <color>#0B6FCE</color>
                    <label>Altair</label>
                </value>
                <value>
                    <fullName>Eyefinity</fullName>
                    <color>#78C953</color>
                    <label>Eyefinity</label>
                </value>
                <value>
                    <fullName>Global Customer Care</fullName>
                </value>
                <value>
                    <fullName>Marchon</fullName>
                    <color>#E27001</color>
                    <label>Marchon</label>
                </value>
                <value>
                    <fullName>Optics Group</fullName>
                    <color>#A845DC</color>
                    <label>Optics Group</label>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Vision Care</fullName>
                    <color>#F3D904</color>
                    <label>Vision Care</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Quick-reference notes pertaining to the Case.</inlineHelpText>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Topic</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Line_of_Business__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Inventory</fullName>
                </value>
                <value>
                    <fullName>Special Order Request</fullName>
                </value>
                <value>
                    <fullName>Stock Order Status</fullName>
                </value>
                <value>
                    <fullName>Product Mapping</fullName>
                </value>
                <value>
                    <fullName>System</fullName>
                </value>
                <value>
                    <fullName>2020 Source (Affiliate)</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Cash Receipts</fullName>
                </value>
                <value>
                    <fullName>Data Entry</fullName>
                </value>
                <value>
                    <fullName>EDI Membership</fullName>
                </value>
                <value>
                    <fullName>Email Update</fullName>
                </value>
                <value>
                    <fullName>Explanation of Payment (EOP)</fullName>
                </value>
                <value>
                    <fullName>Eyeconic Ops</fullName>
                </value>
                <value>
                    <fullName>Eyeconic USC</fullName>
                </value>
                <value>
                    <fullName>Eye Health Management (EHM)</fullName>
                </value>
                <value>
                    <fullName>Lab Opt Out</fullName>
                </value>
                <value>
                    <fullName>Level</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>HP Plan Admin</fullName>
                </value>
                <value>
                    <fullName>HP Billing</fullName>
                </value>
                <value>
                    <fullName>Membership</fullName>
                </value>
                <value>
                    <fullName>MetLife</fullName>
                </value>
                <value>
                    <fullName>Molina</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>Office Hours Update</fullName>
                </value>
                <value>
                    <fullName>otto</fullName>
                </value>
                <value>
                    <fullName>Practice Report</fullName>
                </value>
                <value>
                    <fullName>Premier</fullName>
                </value>
                <value>
                    <fullName>Regence</fullName>
                </value>
                <value>
                    <fullName>Reimbursement Fees</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Severity__c</fullName>
        <inlineHelpText>Systematic Escalation of the Case is driven by the value in this field.</inlineHelpText>
        <label>Severity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Critical</fullName>
                </value>
                <value>
                    <fullName>Major</fullName>
                </value>
                <value>
                    <fullName>Minor</fullName>
                    <default>true</default>
                    <label>Minor</label>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Eyeconic</fullName>
        <active>true</active>
        <businessProcess>VSP Global</businessProcess>
        <description>Used to track Eyeconic cases</description>
        <label>Eyeconic</label>
    </recordTypes>
</CustomObject>

force/src/objects/CaseRecordType__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Id__c</fullName>
        <label>Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Case Record Type</label>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Marketing_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>The contact&apos;s name used for Marketing Campaigns.</inlineHelpText>
        <label>Marketing Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <label>Client</label>
    </recordTypes>
    <recordTypes>
        <fullName>Consumer</fullName>
        <active>true</active>
        <label>Consumer</label>
    </recordTypes>
</CustomObject>

force/src/objects/DVIWebService__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Setting for the DVI Web Service URL and token header</description>
    <label>DVI Web Service</label>
</CustomObject>

src/classes/VSPR13_ContactAndCaseControllerTest.cls
/* Modified Date : 21st June 2016
Related Case : #9251.
Description : Increase Code coverage to 90 %.
*/

@isTest(seeAllData=false)
public class VSPR13_ContactAndCaseControllerTest{
    
    @TestSetup
    static void testData(){
        Test.startTest();
        Id contactRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Consumer').getRecordTypeId();
        Id personRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId(); 
        DVIWebService__c dviWeb = new DVIWebService__c();
        
        dviWeb.Name = 'DVI Values';
        
        insert dviWeb;
        //Create Account
        Account ac = new Account (name='VSP Consumer');
        ac.Name = 'VSP Consumer';
        ac.Email__c = 'francisbenzon@gmail.com';
        ac.Phone = '3634582';
        ac.Fax = '123456';
        ac.Website = 'www.google.com';
        insert ac;
        
        
        Contact c = new Contact();
        c.Salutation = 'Mr.';
        c.LastName = 'Test1';
        c.FirstName = 'Test';
        c.Marketing_Name__c = 'Test';
        c.AccountId = ac.id;
        c.RecordTypeId =  contactRecordTypeId;
        insert c;
        //c.RecordTypeId = '012P00000000S0NIAU';
        
        Contact c2 = new Contact();
        c2.Salutation = 'Mr.';
        c2.LastName = 'Test2';
        c2.FirstName = 'Test';
        c2.Marketing_Name__c = 'Test';
        c2.AccountId = ac.id;
        c2.RecordTypeId =  contactRecordTypeId;
        insert c2;
        //c2.RecordTypeId = '012P00000000S0S';
        
        Contact c3 = new Contact();
        c3.Salutation = 'Mr.';
        c3.Marketing_Name__c = 'Test';
        c3.LastName = 'Test3';
        c3.FirstName = 'Test';
        c3.AccountId = ac.id;
        c3.RecordTypeId =  contactRecordTypeId;
        insert c3;
        //c3.RecordTypeId = '012P00000000S0N';

        /*
        Contact c4 = new Contact();
        c4.Salutation = 'Mr.';
        c4.Marketing_Name__c = 'Test';
        c4.LastName = 'Test4';
        c4.FirstName = 'Test';
        c4.AccountId = ac.id;
        c4.RecordTypeId =  contactRecordTypeId;
        insert c4;
        //c3.RecordTypeId = '012P00000000S0N';
        */
        
        Id personAccountId = TestDataFactory.createPersonAccount('lname');
        Id personContactId = [SELECT PersonContactId FROM Account WHERE Id=: personAccountId].PersonContactId;
        
        
        Case cs1 = new Case();
        cs1.Subject = 'Test';
        cs1.Notes__c = 'Test';
        cs1.Severity__c = 'Minor';
        cs1.Origin = 'Email';
        cs1.Line_of_Business__c = 'Retail';
        cs1.Description = 'Test';
        cs1.Status = 'New';
        cs1.Type = 'Issue';
        cs1.Classification__c = 'Training';
        cs1.Product__c = 'Premier';
        cs1.Auto_Assign__c = false;
        cs1.ContactId = c.Id;
        insert cs1;
        
        Case cs2 = new Case();
        cs2.Subject = 'Test';
        cs2.Notes__c = 'Test';
        cs2.Severity__c = 'Minor';
        cs2.Origin = 'Email';
        cs2.Line_of_Business__c = 'Retail';
        cs2.Description = 'Test';
        cs2.Status = 'New';
        cs2.Type = 'Issue';
        cs2.Classification__c = 'Training';
        cs2.Product__c = 'Premier';
        cs2.ContactId = c2.Id;
        insert cs2;
        
        Case cs3 = new Case();
        cs3.Subject = 'Test';
        cs3.Notes__c = 'Test';
        cs3.Severity__c = 'Minor';
        cs3.Origin = 'Email';
        cs3.Line_of_Business__c = 'Retail';
        cs3.Description = 'Test';
        cs3.Status = 'New';
        cs3.Type = 'Issue';
        cs3.Classification__c = 'Training';
        cs3.Product__c = 'Premier';
        cs3.ContactId = c3.Id;
        insert cs3;
        
        Id caseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Eyeconic').getRecordTypeId();
        Case cs5 = new Case();
        cs5.Subject = 'Test';
        cs5.Notes__c = 'Test';
        cs5.Severity__c = 'Minor';
        cs5.Origin = 'Email';
        cs5.Line_of_Business__c = 'Retail';
        cs5.Description = 'Test';
        cs5.Status = 'New';
        cs5.Type = 'Issue';
        cs5.Classification__c = 'Training';
        cs5.Product__c = 'Premier';
        cs5.RecordTypeId = caseRecordTypeId;
        //cs5.ContactId = c4.Id;
        cs5.ContactId = personContactId;
        cs5.SuppliedEmail = 'test@test.net';
        cs5.SuppliedName = 'Test Contact';
        insert cs5; 
        Test.stopTest();
    }
    static testMethod void VSPR13_ContactAndCaseControllerTest()
    {
        CaseRecordType__c caseRecType = new CaseRecordType__c();
        caseRecType.Name = 'Eyeconic';
        caseRecType.Id__c = '0120B000000t8xa';
        insert caseRecType;
        //Test converage for the myPage visualforce page
        PageReference pageRef = Page.VSPR13_ContactAndCaseVFP;
        Test.setCurrentPageReference(pageRef);
        
        
        Contact c = [SELECT Id FROM Contact WHERE LastName = 'Test1' LIMIT 1];
        Contact c2 = [SELECT Id FROM Contact WHERE LastName = 'Test2' LIMIT 1];
        Contact c3 = [SELECT Id FROM Contact WHERE LastName = 'Test3' LIMIT 1];
        //Contact c4 = [SELECT Id FROM Contact WHERE LastName = 'Test4' LIMIT 1];
        Contact c4 = [SELECT Id FROM Contact WHERE LastName = 'lname' LIMIT 1];
        
        ApexPages.StandardController sc = new ApexPages.standardController(c);

        // create an instance of the controller
        
        VSPR13_ContactAndCaseExtensionController ExtensionControllerTest = new VSPR13_ContactAndCaseExtensionController(sc);
        ExtensionControllerTest.selectedrecordType = 'Client';
        //ExtensionControllerTest.ContactID = c.Id;            
        
        ApexPages.StandardController sc2 = new ApexPages.standardController(c2);
        // create an instance of the controller
        VSPR13_ContactAndCaseExtensionController ExtensionControllerTest2 = new VSPR13_ContactAndCaseExtensionController(sc2); 
        ExtensionControllerTest2.selectedrecordType = 'Consumer';
        //ExtensionControllerTest2.ContactID = c2.Id;
        
        ApexPages.StandardController sc3 = new ApexPages.standardController(c3);
        // create an instance of the controller
        VSPR13_ContactAndCaseExtensionController ExtensionControllerTest4 = new VSPR13_ContactAndCaseExtensionController(sc3);       
        ExtensionControllerTest4.selectedrecordType = 'Client';  
        //ExtensionControllerTest4.ContactId = c3.ID;
        //ExtensionControllerTest4.acc = ac.Id;
        
        ApexPages.StandardController sc5 = new ApexPages.standardController(c4);
        // create an instance of the controller
        VSPR13_ContactAndCaseExtensionController ExtensionControllerTest6 = new VSPR13_ContactAndCaseExtensionController(sc5);       
        ExtensionControllerTest6.selectedrecordType = 'Client';  
        ExtensionControllerTest6.acc = '';
        ExtensionControllerTest6.contactid = '';
        ExtensionControllerTest6.caseSelectedRecordType = 'Eyeconic';
        //ExtensionControllerTest4.ContactId = c3.ID;
        //ExtensionControllerTest4.acc = ac.Id;
        
        Test.startTest();
        Test.setCurrentPage(Page.VSPR13_ContactAndCaseVFP);
        
        PageReference pagereferenceTest = ExtensionControllerTest2.save();
        PageReference pagereferenceTest2 = ExtensionControllerTest.cancel(); 
        PageReference pagereferenceTest3 = ExtensionControllerTest.doSaveAndNew();
        PageReference pagereferenceTest5 = ExtensionControllerTest2.doSaveAndNew();
        PageReference pagereferenceTest4 = ExtensionControllerTest4.save();
        PageReference pagereferenceTest6 = ExtensionControllerTest6.save();
        
        try{
            ApexPages.StandardController sc4 = new ApexPages.standardController(new Contact());
            // create an instance of the controller
            VSPR13_ContactAndCaseExtensionController ExtensionControllerTest5 = new VSPR13_ContactAndCaseExtensionController(sc4); 
            ExtensionControllerTest5.save();
        }catch(System.DMLException e){
            
        }
        
        System.assert(true);
        Test.stopTest();
        
    }
    
}