force/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Client_Id__c</fullName>
        <label>Client Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ConsumerID__c</fullName>
        <label>ConsumerID</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Classification__c</fullName>
        <inlineHelpText>The relevant category for the Issue or Request.</inlineHelpText>
        <label>Classification</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account/Contact Maintenance</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Claims</fullName>
                </value>
                <value>
                    <fullName>Credentialing/Recruiting</fullName>
                </value>
                <value>
                    <fullName>Product</fullName>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Shipping</fullName>
                </value>
                <value>
                    <fullName>Status</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Client_Id__c</fullName>
        <inlineHelpText>Main client Id field. All other collection fields will pipe to this field. All logic will be based upon this field for client Id.</inlineHelpText>
        <label>Client Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consumer_ID__c</fullName>
        <inlineHelpText>Main consumer Id field. All other collection fields will pipe to this field. All logic will be based upon this field for consumer Id.</inlineHelpText>
        <label>Consumer ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Member_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member Plan</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.ContactId</field>
                <operation>equals</operation>
                <valueField>$Source.ContactId</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>MemberPlan</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PersonAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PersonAccount</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.IsPersonAccount</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (PersonAccount)</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PrimaryMemberConsumerId__c</fullName>
        <label>PrimaryMemberConsumerId</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force/src/objects/CC_Portal__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>CC Portal</label>
</CustomObject>

force/src/objects/Consumer_Search_Web_Service__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Consumer_Search_Web_Service__c</fullName>
        <label>Consumer Search Web Service</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Consumer Search Web Service</label>
</CustomObject>

force/src/objects/DVIWebService__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Setting for the DVI Web Service URL and token header</description>
    <label>DVI Web Service</label>
</CustomObject>

force/src/objects/MemberPlan.object
<CustomObject>
    <fields>
        <fullName>Client_ID__c</fullName>
        <label>Client ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ConsumerId__c</fullName>
        <label>ConsumerId</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division_ID__c</fullName>
        <label>Division ID</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>primaryMemberConsumerId__c</fullName>
        <label>Primary Member ConsumerId</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Propensity_Score_Management__mdt.object
<CustomObject>
    <fields>
        <fullName>Channel__c</fullName>
        <label>Channel</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>States__c</fullName>
        <label>States</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Time_Span_Begin__c</fullName>
        <label>Time Span Begin</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Time_Span_End__c</fullName>
        <label>Time Span End</label>
        <type>Date</type>
    </fields>
    <label>Propensity Score Management</label>
    <pluralLabel>Propensity Score Management</pluralLabel>
</CustomObject>

force/src/objects/PropensityScores__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>PropensityScores</relationshipLabel>
        <relationshipName>PropensityScores</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Phone</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Chat</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Classification__c</fullName>
        <label>Classification</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ConsumerId__c</fullName>
        <label>ConsumerId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Offer_To__c</fullName>
        <label>Offer To</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Vision Benefits Members &amp; Dependents</fullName>
                </value>
                <value>
                    <fullName>MetLife Vision Members &amp; Dependents</fullName>
                </value>
                <value>
                    <fullName>CignaVision Members &amp; Dependents</fullName>
                </value>
                <value>
                    <fullName>VSP Providers</fullName>
                </value>
                <value>
                    <fullName>VSP Premiere Providers</fullName>
                </value>
                <value>
                    <fullName>Eyeconic Customers</fullName>
                </value>
                <value>
                    <fullName>Dragon Customers</fullName>
                </value>
                <value>
                    <fullName>Nike Customers</fullName>
                </value>
                <value>
                    <fullName>Level Customers</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PersonAccount__c</fullName>
        <label>PersonAccount</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>PropensityScores</relationshipLabel>
        <relationshipName>PropensityScores</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>States__c</fullName>
        <label>States</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Time_Span_Begin__c</fullName>
        <description>Sets the Expected Effective date to this field</description>
        <label>Time Span Begin</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Time_Span_End__c</fullName>
        <label>Time Span End</label>
        <type>Date</type>
    </fields>
    <label>PropensityScores</label>
    <nameField>
        <displayFormat>PS-{0}</displayFormat>
        <label>PropensityScores Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PropensityScores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force/src/classes/VSPR2_GetPropensityScores_Test.cls
@isTest
public class VSPR2_GetPropensityScores_Test {
    @isTest 
    public static void getScoresWithCallout(){  
        DVIWebService__c dviCustSetting = testDataFactory.setDVISettings();
        Consumer_Search_Web_Service__c CSCustSetting = testDataFactory.setCSSettings();
        CC_Portal__c ccPortalSettings = testDataFactory.setCCPortalSettings();        
        Test.setMock(HttpCalloutMock.Class, new VSPR2_GetPropensityCalloutMock());
        
        Account acc = new Account();
        Id rt = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        acc.FirstName = 'TestDummy';
        acc.LastName = 'TheThird';
        acc.RecordTypeId = rt;
        insert acc; 
        
        MemberPlan mp = New MemberPlan();
        mp.ConsumerId__c = '306032315';
        mp.Division_ID__c = '0001';
        mp.Client_ID__c = '12006950';
        mp.primaryMemberConsumerId__c= '306032315';
        mp.Name = 'MP-100';
        mp.MemberId = acc.Id;
        insert mp;
        
        case caseobj = new case(); 
        Id rtId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Vision Benefits').getRecordTypeId();
        caseObj.accountId = acc.Id;
        caseObj.Member_Plan__c = mp.Id;
        caseObj.Consumer_ID__c = mp.ConsumerId__c;
        caseObj.Client_Id__c = mp.Client_ID__c;
        caseobj.recordtypeId = rtId;
        insert caseobj;  
        
        String requestsId = caseobj.Id;
        VSPR2_GetPropensityScores props = new VSPR2_GetPropensityScores();
        List<VSPR2_GetPropensityScores.Requests> requests = new List<VSPR2_GetPropensityScores.Requests>(); 
        VSPR2_GetPropensityScores.Requests request = new VSPR2_GetPropensityScores.Requests();
        
        request.caseIdSB = requestsId;
        requests.add(request);
        Test.startTest();
        VSPR2_GetPropensityScores.getPropensityScores(requests);
        Test.stopTest();
        
        List<Propensity_Score_Management__mdt> IPpsm = [SELECT Channel__c,Customer__c,Priority__c,States__c,Time_Span_Begin__c,Time_Span_End__c FROM Propensity_Score_Management__mdt WHERE DeveloperName = 'IP' LIMIT 1];
        //List<Propensity_Score_Management__mdt> OONpsm = [SELECT Channel__c,Customer__c,Priority__c,States__c,Time_Span_Begin__c,Time_Span_End__c FROM Propensity_Score_Management__mdt WHERE DeveloperName = 'OON' LIMIT 1];
        
        PropensityScores__c IPScores = new PropensityScores__c();
        PropensityScores__c OONScores = new PropensityScores__c();
        
        IPScores = [SELECT Offer_To__c,Channel__c,Time_Span_Begin__c FROM PropensityScores__c WHERE Case__c =: requestsId AND Code__c = 'IP'];
        //OONScores = [SELECT Offer_To__c,Channel__c,Time_Span_Begin__c FROM PropensityScores__c WHERE Case__c =: requestsId AND Code__c = 'OON'];
        
        system.assertEquals(IPpsm[0].Customer__c, IPScores.Offer_To__c);
        system.assertEquals(IPpsm[0].Channel__c, IPScores.Channel__c);
        system.assertEquals(IPpsm[0].Time_Span_Begin__c, IPScores.Time_Span_Begin__c);
        
        //system.assertEquals(OONpsm[0].Customer__c, OONScores.Offer_To__c);
        //system.assertEquals(OONpsm[0].Channel__c, OONScores.Channel__c);
        //system.assertEquals(OONpsm[0].Time_Span_Begin__c, OONScores.Time_Span_Begin__c);
    } 

    @isTest
    public static void getScoresOnCase(){
        DVIWebService__c dviCustSetting = testDataFactory.setDVISettings();
        Consumer_Search_Web_Service__c CSCustSetting = testDataFactory.setCSSettings();
        CC_Portal__c ccPortalSettings = testDataFactory.setCCPortalSettings();
        List<Propensity_Score_Management__mdt> IPpsm = [SELECT Channel__c,Customer__c,Priority__c,States__c,Time_Span_Begin__c,Time_Span_End__c FROM Propensity_Score_Management__mdt WHERE DeveloperName = 'IP' LIMIT 1];
        List<Propensity_Score_Management__mdt> OONpsm = [SELECT Channel__c,Customer__c,Priority__c,States__c,Time_Span_Begin__c,Time_Span_End__c FROM Propensity_Score_Management__mdt WHERE DeveloperName = 'OON' LIMIT 1];
        
        Account acc = new Account();
        Id rt = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        acc.FirstName = 'TestDummy';
        acc.LastName = 'TheThird';
        acc.RecordTypeId = rt;
        insert acc;
        
        MemberPlan mp = New MemberPlan();
        mp.ConsumerId__c = '3060323333';
        mp.Division_ID__c = '0001';
        mp.Client_ID__c = '12006950';
        mp.primaryMemberConsumerId__c= '3060323333';
        mp.Name = 'MP-100';
        mp.MemberId = acc.Id;
        insert mp;
        
        case caseobj = new case(); 
        Id rtId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Vision Benefits').getRecordTypeId();
        caseObj.accountId = acc.Id;
        caseObj.Member_Plan__c = mp.Id;
        caseObj.Consumer_ID__c = mp.ConsumerId__c;
        caseObj.Client_Id__c = mp.Client_ID__c;
        caseobj.recordtypeId = rtId;
        insert caseobj;  
        
        PropensityScores__c ps = new PropensityScores__c();
        ps.Case__c = caseobj.Id;
        ps.ConsumerId__c = mp.ConsumerId__c;
        ps.Classification__c = 'N';
        ps.Code__c = 'IP';
        ps.PersonAccount__c = acc.Id;
        ps.States__c = IPpsm[0].States__c;
        ps.Channel__c = IPpsm[0].Channel__c;
        ps.Time_Span_Begin__c = IPpsm[0].Time_Span_Begin__c;
        ps.Offer_To__c = IPpsm[0].Customer__c;
        insert ps;
        /*
        PropensityScores__c ps2 = new PropensityScores__c();
        ps2.Case__c = caseobj.Id;
        ps2.ConsumerId__c = mp.ConsumerId__c;
        ps2.Classification__c = 'N';
        ps2.Code__c = 'OON';
        ps2.PersonAccount__c = acc.Id;
        ps2.States__c = OONpsm[0].States__c;
        ps2.Channel__c = OONpsm[0].Channel__c;
        ps2.Time_Span_Begin__c = OONpsm[0].Time_Span_Begin__c;
        ps2.Offer_To__c = OONpsm[0].Customer__c;
        insert ps2;
		*/
            
        String requestsId = caseobj.Id;
        VSPR2_GetPropensityScores props = new VSPR2_GetPropensityScores();
        List<VSPR2_GetPropensityScores.Requests> requests = new List<VSPR2_GetPropensityScores.Requests>(); 
        VSPR2_GetPropensityScores.Requests request = new VSPR2_GetPropensityScores.Requests();
        request.caseIdSB = requestsId;
        requests.add(request);
        
        Test.startTest();
        VSPR2_GetPropensityScores.getPropensityScores(requests); 
        Test.stopTest();
        
        PropensityScores__c IPScores = new PropensityScores__c();
        IPScores = [SELECT Offer_To__c,Channel__c,Time_Span_Begin__c FROM PropensityScores__c WHERE Case__c =: requestsId AND Code__c = 'IP'];
        PropensityScores__c OONscores = new PropensityScores__c();
        //OONscores = [SELECT Offer_To__c,Channel__c,Time_Span_Begin__c FROM PropensityScores__c WHERE Case__c =: requestsId AND Code__c = 'OON'];
        
        system.assertEquals(IPpsm[0].Customer__c, IPScores.Offer_To__c);
        system.assertEquals(IPpsm[0].Channel__c, IPScores.Channel__c);
        system.assertEquals(IPpsm[0].Time_Span_Begin__c, IPScores.Time_Span_Begin__c);
        
        //system.assertEquals(OONpsm[0].Customer__c, OONscores.Offer_To__c);
        //system.assertEquals(OONpsm[0].Channel__c, OONscores.Channel__c);
        //system.assertEquals(OONpsm[0].Time_Span_Begin__c, OONscores.Time_Span_Begin__c);
    }
    
    @isTest
    public static void CalloutWithNoScores(){
        Test.setMock(HttpCalloutMock.Class, new VSPR2_GetPropensityCalloutNoScoresMock());
        DVIWebService__c dviCustSetting = testDataFactory.setDVISettings();
        Consumer_Search_Web_Service__c CSCustSetting = testDataFactory.setCSSettings();
        CC_Portal__c ccPortalSettings = testDataFactory.setCCPortalSettings();
        
        Account acc = new Account();
        Id rt = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        acc.FirstName = 'TestDummy';
        acc.LastName = 'TheThird';
        acc.RecordTypeId = rt;
        insert acc;
        
        MemberPlan mp = New MemberPlan();
        mp.ConsumerId__c = '3060323333';
        mp.Division_ID__c = '0001';
        mp.Client_ID__c = '12006950';
        mp.primaryMemberConsumerId__c= '3060323333';
        mp.Name = 'MP-100';
        mp.MemberId = acc.Id;
        insert mp;
        
        case caseobj = new case(); 
        Id rtId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Vision Benefits').getRecordTypeId();
        caseObj.accountId = acc.Id;
        caseObj.Member_Plan__c = mp.Id;
        caseObj.Consumer_ID__c = mp.ConsumerId__c;
        caseObj.Client_Id__c = mp.Client_ID__c;
        caseobj.recordtypeId = rtId;
        insert caseobj;  
        
        String requestsId = caseobj.Id;
        VSPR2_GetPropensityScores props = new VSPR2_GetPropensityScores();
        List<VSPR2_GetPropensityScores.Requests> requests = new List<VSPR2_GetPropensityScores.Requests>(); 
        VSPR2_GetPropensityScores.Requests request = new VSPR2_GetPropensityScores.Requests();
        
        request.caseIdSB = requestsId;
        requests.add(request); 
        
        Test.startTest();
        List<VSPR2_GetPropensityScores.Results> resultsList = VSPR2_GetPropensityScores.getPropensityScores(requests);
        Test.stopTest();
        
        List<PropensityScores__c> updatedScores = new List<PropensityScores__c>();
        updatedScores = [SELECT Id,Offer_To__c,Channel__c,Time_Span_Begin__c FROM PropensityScores__c WHERE Case__c =: requestsId];
        
        system.assertEquals(0, updatedScores.size());
        system.assertEquals('No Offer', resultsList[0].propensityScoreFieldIP); 
    }
}