force/src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Address_Type__c</fullName>
        <label>Address Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Physical</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Shipping</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <formula>Street__c &amp; &apos;, &apos; &amp; City__c &amp; &apos;, &apos; &amp; State__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Address</label>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force/src/objects/Address_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Address Relationships</relationshipLabel>
        <relationshipName>Address_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Address_Type__c</fullName>
        <label>Address Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Physical</fullName>
                </value>
                <value>
                    <fullName>Shipping</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Address Relationships</relationshipLabel>
        <relationshipName>Address_Relationships</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF( End_Date__c  &lt; TODAY(), &quot;Inactive&quot;, &quot;Active&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Address Relationship</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Address Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Address Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force/src/classes/VSPR1_AddressRelationshipDML.cls
/**
 * Class Name: VSPR1_AddressRelationshipDML
 * @author: Marvin B. Gatchalian
 * Date: 18.JUNE.2013
 * Requirement/Project Name: VSP
 * @description: Handles all DML for the Address Relationship Custom object.
 */

public class VSPR1_AddressRelationshipDML { 
    
    public static List<Address_Relationship__c> getAddressRelationDetails(Set<Id> addressIds){
       system.debug('>>> Enter getAddressRelationDetails');
        List<Address_Relationship__c> AddressesR = [Select Account__c, address__c, createdDate, status__c from 
                                                    Address_Relationship__c where address__c IN: addressIds order by address__c desc];
        return AddressesR;      
    }
    
    public static List<Address_Relationship__c> getAddressRelationbyAccount(Set<Id> accountIds){
        system.debug('>>> Enter getAddressRelationbyAccount');
       List<Address_Relationship__c> AddressesR = [Select Account__c, address__c, Address_Type__c, LastModifiedDate, status__c from 
                                                  Address_Relationship__c where Status__c = 'Active' and Address_Type__c = 'Physical'
                                                   and Account__c IN: accountIds order by LastModifiedDate desc];
               
        return AddressesR;      
    } 
   

    
}