force/src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <formula>Street__c &amp; &apos;, &apos; &amp; City__c &amp; &apos;, &apos; &amp; State__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Address</label>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force/src/objects/Address_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Address Relationships</relationshipLabel>
        <relationshipName>Address_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Address Relationships</relationshipLabel>
        <relationshipName>Address_Relationships</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Address Relationship</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Address Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Address Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force/src/classes/VSPR1_AddressRelationshipBL.cls
/**
 * Class Name: VSPR1_AddressRelationshipBL
 * @author: Marvin B. Gatchalian
 * Date: 18.JUNE.2013
 * Requirement/Project Name: VSP
 * @description: Handles all Business Logic for the Address Relationship Custom object.
 */

public with sharing class VSPR1_AddressRelationshipBL { 

	//Map<id,Address__c> AddressMap = new Map<id,Address__c>();		
	Set<Id> addressIds = new Set<ID>();
	Set<Id> accountIds = new Set<ID>();
	
		public VSPR1_AddressRelationshipBL(List<Address_Relationship__c> newTrigger, List<Address_Relationship__c> oldTrigger, Map<id,Address_Relationship__c> TriggerMap, Boolean isDelete, Boolean isInsert){
			
			//AddressMap = TriggerMap;
			if (isDelete) {
				for(Address_Relationship__c Address : oldTrigger){
					addressIds.add(Address.address__c);
					accountIds.add(Address.Account__c);
 				}
			}
			else if (!isDelete) {
				for(Address_Relationship__c Address : newTrigger){
					addressIds.add(Address.address__c);
					accountIds.add(Address.Account__c);
 				}
 				
			}
			//system.assertEquals(accountIds, null);
 			VSPR1_FindCorrectAddress.findAddress(accountIds);		

		} 
		
	
}