force/src/objects/Article_Feedback__c.object
<CustomObject>
    <description>Container for user feedback</description>
    <fields>
        <fullName>Article_ID__c</fullName>
        <description>Populate with KnowledgeArticle.ID</description>
        <label>Article ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Article_Title__c</fullName>
        <label>Article Title</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Reason</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Broken Link</fullName>
                </value>
                <value>
                    <fullName>Page Unclear</fullName>
                </value>
                <value>
                    <fullName>Missing Information</fullName>
                </value>
                <value>
                    <fullName>Hard to Find Page</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Article Feedback</label>
    <nameField>
        <displayFormat>Feedback-{000}</displayFormat>
        <label>Article Feedback ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Article Feedback</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ArticleFeedbackTrigger_TestClass.cls
@isTest
private class ArticleFeedbackTrigger_TestClass {
/* Jesten Hayle
    static testmethod void testTrigger(){ 
        Core_Benefit__kav cb = new Core_Benefit__kav();
        cb.Title = 'ArticleFeedbackTriggerTest';
        cb.urlname = 'ArticleFeedbackTriggerTest';
        insert cb;
        Core_Benefit__kav insertedTestcb = [Select KnowledgeArticleId from Core_Benefit__kav where ID = :cb.Id];
        KbManagement.PublishingService.publishArticle(insertedTestcb.KnowledgeArticleId, true);
                
        Article_Feedback__c af =new Article_Feedback__c();
        af.Comments__c='Testing';
        af.Article_ID__c=insertedTestcb.KnowledgeArticleId;
        system.debug('=================15======'+af.Article_ID__c);
        af.Reason__c='Other';
        af.Article_Title__c=cb.Title;
        insert af;
        //Core_Benefit__Feed cbfeed=[SELECT Body,ParentId,Title,Type FROM Core_Benefit__Feed WHERE ParentId = :cb.KnowledgeArticleId LIMIT 1];
        //List<FeedItem> lstFeeds = new List<FeedItem>();
        FeedItem fi = new FeedItem();
        fi.Type = 'TextPost';
        fi.Title= 'test article';
        fi.ParentId = af.Article_ID__c;
        fi.Body = af.Comments__c;       
        insert fi;
    }
Jesten Hayle */
}