force/src/objects/Article_Feedback__c.object
<CustomObject>
    <description>Container for user feedback</description>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Reason</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Broken Link</fullName>
                </value>
                <value>
                    <fullName>Page Unclear</fullName>
                </value>
                <value>
                    <fullName>Missing Information</fullName>
                </value>
                <value>
                    <fullName>Hard to Find Page</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Article Feedback</label>
    <nameField>
        <displayFormat>Feedback-{000}</displayFormat>
        <label>Article Feedback ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Article Feedback</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Knowledge__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <page>Knowledge_VFP</page>
            <template>Page</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <fields>
        <fullName>Additional_Benefits__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Additional Benefits</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Additional_Information__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Additional Information</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Article_Details__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Article Details</label>
        <length>41000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Article_Record_Type_Name__c</fullName>
        <description>Created to capture the record type name which is used in apex classes and visualforce pages to serve-up knowledge articles in Quest.</description>
        <formula>RecordType.DeveloperName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Article Record Type Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Benefit_Effective_Data__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Date that enrolled benifits become effective</inlineHelpText>
        <label>Benefit Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Benefit__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Client-specific benefits</inlineHelpText>
        <label>Benefit</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Change_Cancel__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Change/Cancel</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Confirmation__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Confirmation</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Contacts__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Contacts</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Details__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Details</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Doctor_Network__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Doctor Network</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Eligibility__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>client requirements for eligibility</inlineHelpText>
        <label>Eligibility</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Enrollment_End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Date that open enrollments closes for members</inlineHelpText>
        <label>Enrollment End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Enrollment_Start_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Date that enrollment opens up for members</inlineHelpText>
        <label>Enrollment Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Exam__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Exam</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Frame__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Frame</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>General_Description__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>General Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>How_To_Enroll__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>How To Enroll</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Information__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Information</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Keyword__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Keyword</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Keywords__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Keywords</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Lab__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Lab</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Lens_Enhancements__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Lens Enhancements</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Lens__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Lens</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Links__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Links</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Premiums_and_Billing__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Premiums and Billing</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Procedure__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Procedure</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Reason_Details__c</fullName>
        <label>Reason Details</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Reason__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Full Service Plans</fullName>
                </value>
                <value>
                    <fullName>Partial Service Plans</fullName>
                </value>
                <value>
                    <fullName>Savings</fullName>
                </value>
                <value>
                    <fullName>LVC</fullName>
                </value>
                <value>
                    <fullName>Medically Related</fullName>
                </value>
                <value>
                    <fullName>NCL</fullName>
                </value>
                <value>
                    <fullName>Occupational</fullName>
                </value>
                <value>
                    <fullName>Remaining contact lens allowance</fullName>
                </value>
                <value>
                    <fullName>Glasses Related</fullName>
                </value>
                <value>
                    <fullName>Promotions &amp; Offers</fullName>
                </value>
                <value>
                    <fullName>CS Letters</fullName>
                </value>
                <value>
                    <fullName>First Time Redo</fullName>
                </value>
                <value>
                    <fullName>Guarantees</fullName>
                </value>
                <value>
                    <fullName>Natural Disaster</fullName>
                </value>
                <value>
                    <fullName>Patient Paid Privately</fullName>
                </value>
                <value>
                    <fullName>COB</fullName>
                </value>
                <value>
                    <fullName>Benefits</fullName>
                </value>
                <value>
                    <fullName>Claims</fullName>
                </value>
                <value>
                    <fullName>Register</fullName>
                </value>
                <value>
                    <fullName>Password Reset</fullName>
                </value>
                <value>
                    <fullName>Update Account</fullName>
                </value>
                <value>
                    <fullName>Issues / Security</fullName>
                </value>
                <value>
                    <fullName>Find a Doctor</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Verbal or Mail</fullName>
                </value>
                <value>
                    <fullName>Prospective/Member Not Active</fullName>
                </value>
                <value>
                    <fullName>LVC Facilities</fullName>
                </value>
                <value>
                    <fullName>Doctor Access</fullName>
                </value>
                <value>
                    <fullName>Disclosure of Information</fullName>
                </value>
                <value>
                    <fullName>Protected Health Information (PHI)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Caller_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Benefits</fullName>
                </value>
                <value>
                    <fullName>Website_Assistance</fullName>
                    <label>Website Assistance</label>
                </value>
                <value>
                    <fullName>Doctor_Referral</fullName>
                    <label>Doctor Referral</label>
                </value>
                <value>
                    <fullName>Confidentiality</fullName>
                </value>
                <value>
                    <fullName>AOB/OON Provider</fullName>
                </value>
                <value>
                    <fullName>Member Experience</fullName>
                </value>
                <value>
                    <fullName>Complaint</fullName>
                </value>
                <value>
                    <fullName>Authorization</fullName>
                </value>
                <value>
                    <fullName>Eligibility</fullName>
                </value>
                <value>
                    <fullName>Client Exceptions</fullName>
                </value>
                <value>
                    <fullName>Potential Members</fullName>
                </value>
                <value>
                    <fullName>Out of Network Claims</fullName>
                </value>
                <value>
                    <fullName>Updates</fullName>
                </value>
                <value>
                    <fullName>Claims Adjustment</fullName>
                </value>
                <value>
                    <fullName>Eyefinity Assistance</fullName>
                </value>
                <value>
                    <fullName>Claim Payment</fullName>
                </value>
                <value>
                    <fullName>Provider/Office Update</fullName>
                </value>
                <value>
                    <fullName>Provider Confidentiality</fullName>
                </value>
                <value>
                    <fullName>Member Confidentiality</fullName>
                </value>
                <value>
                    <fullName>Client Confidentiality</fullName>
                </value>
                <value>
                    <fullName>Provider Authorization</fullName>
                </value>
                <value>
                    <fullName>Member Authorization</fullName>
                </value>
                <value>
                    <fullName>Provider Benefits</fullName>
                </value>
                <value>
                    <fullName>Member Benefits</fullName>
                </value>
                <value>
                    <fullName>Member Website Assistance</fullName>
                </value>
                <value>
                    <fullName>Client Website Assistance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Review_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Review Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Support_Queue_Steps__c</fullName>
        <description>Restrict visibility by Profile - visible to all users across the company EXCEPT Processors, CSR&apos;s, Hybrid CSR&apos;s and CART</description>
        <encryptionScheme>None</encryptionScheme>
        <label>SQ/QQ Steps</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Topic_Links__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Topic Links</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Version_Comments__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Version Comments</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
    <recordTypes>
        <fullName>Additional_Benefits</fullName>
        <active>true</active>
        <label>Additional Benefits</label>
    </recordTypes>
    <recordTypes>
        <fullName>C_G_Article</fullName>
        <active>true</active>
        <label>C&amp;G Article</label>
    </recordTypes>
    <recordTypes>
        <fullName>Category_Tab_Link</fullName>
        <active>true</active>
        <label>Category Tab Link</label>
    </recordTypes>
    <recordTypes>
        <fullName>Core_Benefit</fullName>
        <active>true</active>
        <label>Core Benefit</label>
    </recordTypes>
    <recordTypes>
        <fullName>External_Publication</fullName>
        <active>true</active>
        <label>External Publication</label>
    </recordTypes>
    <recordTypes>
        <fullName>General_Article_Template</fullName>
        <active>true</active>
        <label>General Article Template</label>
    </recordTypes>
    <recordTypes>
        <fullName>Multi_Topic_Details</fullName>
        <active>true</active>
        <label>Multi Topic Details</label>
    </recordTypes>
    <recordTypes>
        <fullName>Open_Enrollment</fullName>
        <active>true</active>
        <label>Open Enrollment</label>
    </recordTypes>
    <recordTypes>
        <fullName>Procedure</fullName>
        <active>true</active>
        <label>Procedure</label>
    </recordTypes>
    <recordTypes>
        <fullName>Provider_Solutions_Community</fullName>
        <active>true</active>
        <label>Provider Solutions Community</label>
    </recordTypes>
    <recordTypes>
        <fullName>Support_Queue</fullName>
        <active>true</active>
        <label>Support Queue</label>
    </recordTypes>
    <recordTypes>
        <fullName>Universal_Service</fullName>
        <active>true</active>
        <label>Universal Service</label>
    </recordTypes>
</CustomObject>

src/classes/MultiTopic_FeedbackctrlLEX.cls
public class MultiTopic_FeedbackctrlLEX {
    
    public Article_Feedback__c ArticleFeedbackObj = new Article_Feedback__c();
    Public string Comments {get;set;}      
    String[] reasons = new String[]{};
    Public Knowledge__kav filterid;
    public string cbkId {get; set;}
    public Knowledge__kav mtpf{get;set;}
    public String sfUrl = URL.getSalesforceBaseUrl().getHost();   
    public List<Knowledge__DataCategorySelection> CatDetails;  
    public Knowledge__kav cbk {get; set;}
    public Boolean hiddenvaluesflag {get;set;} 
    public Boolean toolbarflag {get;set;}      
    public string ID = apexpages.currentpage(). getParameters().get('id');
    public Boolean highlightVersionComments{get;set;} 
    public Boolean checkIfDraft{get;set;}
    
    public MultiTopic_FeedbackctrlLEX(ApexPages.KnowledgeArticleVersionStandardController controller) {
        hiddenvaluesflag=false;
        toolbarflag = true;
        mtpf=(Knowledge__kav)controller.getRecord();   
        cbkId = apexpages.currentpage(). getParameters().get('id');                             
        cbk = new Knowledge__kav();
        if(cbkId != null && cbkId != '') {
            //Querying Data from ArticleType            
            cbk = [Select Id, LastPublishedDate,Version_Comments__c,Support_Queue_Steps__c, Title,Article_Record_Type_Name__c,
            	   Topic_Links__c, PublishStatus, Article_Details__c,Keyword__c, UrlName, ArticleNumber, CreatedById, OwnerId,Procedure__c,
                   Additional_Information__c, Keywords__c, Review_Date__c, Details__c, Information__c,
                   Benefit_Effective_Data__c, Reason_Details__c, Reason__c, Exam__c, Lens__c, Lens_Enhancements__c, Enrollment_Start_Date__c, Enrollment_End_Date__c,
                   General_Description__c, Benefit__c, Eligibility__c, How_To_Enroll__c, Premiums_and_Billing__c, Confirmation__c, Change_Cancel__c, Links__c,
                   Frame__c, Contacts__c, Doctor_Network__c, lab__c, Additional_Benefits__c, Chat_Answer__c
                   from Knowledge__kav where id=:mtpf.id  AND KnowledgeArticleId =: cbkId];           
            filterid=[SELECT Id,UrlName FROM Knowledge__kav WHERE ArticleNumber =: cbk.ArticleNumber AND id=:mtpf.id ];                
            CatDetails= [Select DataCategoryName,DataCategoryGroupName from Knowledge__DataCategorySelection where ParentId =:filterid.Id];   
        } 
        
        if(cbk.LastPublishedDate != null){
            if((cbk.LastPublishedDate.date().addDays(30))  < DateTime.now().date()){
                highlightVersionComments = false;
            }
            else{
                highlightVersionComments = true;
            } 
        }  
        
        if(cbk.PublishStatus == 'Draft'){
            checkIfDraft = true;
        }
    } 
    
    public MultiTopic_FeedbackctrlLEX(){
        
    }
    
    //Multi-Picklist values for Reasons
    public List<SelectOption> getItems() {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('Broken Link','Broken Link'));
        options.add(new SelectOption('Page Unclear','Page Unclear'));
        options.add(new SelectOption('Missing Information','Missing Information'));
        options.add(new SelectOption('Hard to Find Page','Hard to Find Page'));
        options.add(new SelectOption('Other','Other'));
        return options;
    }
    
    public String[] getReasons() {
       	return reasons;
    }
            
    public void setreasons(String[] reasons) {
        this.reasons = reasons;
    }   
       
    public void setCatDetails(List<Knowledge__DataCategorySelection> catDetailsList) {
        this.CatDetails = catDetailsList;
    } 
    
    public String getart() {
        return ID;      
    }
    
    public String getsfurll() {
        return sfURL;      
    }
    
    public Article_Feedback__c getArticleFeedbackObj(){
      return ArticleFeedbackObj;
    }
    
    public void setArticleFeedbackObj(Article_Feedback__c ArticleFeedbackObj){
      this.ArticleFeedbackObj = ArticleFeedbackObj;
    }
    
    public String getReturnid() {
        return cbkId;
    }

    public List<Knowledge__DataCategorySelection> getCategory() {
        return CatDetails;
    }
  
    // Creating an Article FeedBack from ArticleFeedback tab in VFP
    public PageReference saveclick() {
        ArticleFeedbackObj = new Article_Feedback__c();           
        ArticleFeedbackObj.Article_ID__c=ID;
        ArticleFeedbackObj.Article_Title__c=cbk.Title;
        ArticleFeedbackObj.Article_Type__c = cbk.Article_Record_Type_Name__c;
        ArticleFeedbackObj.Article_URL__c=sfURL+'/'+ID;       
        ArticleFeedbackObj.Comments__c=Comments;
        if(ArticleFeedbackObj.Comments__c == '' || ArticleFeedbackObj.Comments__c == null){
           ApexPages.addMessage(new ApexPages.Message ( ApexPages.Severity.ERROR, 'Article Feedback Error: You must enter Comments and select at least one Reason'));
           toolbarflag = false;
           return null;
        }

        ArticleFeedbackObj.Data_Category__c = '';

        if(CatDetails != null && !CatDetails.isEmpty()) {
             for(Integer i=0; i < CatDetails.size(); i++) {
                if(ArticleFeedbackObj.Data_Category__c != '')
                ArticleFeedbackObj.Data_Category__c = ArticleFeedbackObj.Data_Category__c + ';';
                ArticleFeedbackObj.Data_Category__c = ArticleFeedbackObj.Data_Category__c+CatDetails[i].DataCategoryName;
                ArticleFeedbackObj.Data_Category_Group__c=CatDetails[i].DataCategoryGroupName;
            }
        }
 
        ArticleFeedbackObj.Reason__c = '';
        if(reasons != null && !reasons.isEmpty()) {
            for(Integer i=0; i < reasons.size(); i++) {
                ArticleFeedbackObj.Reason__c = ArticleFeedbackObj.Reason__c+';'+reasons[i];
            }        
        }
        if(ArticleFeedbackObj.Reason__c == '' || ArticleFeedbackObj.Reason__c == null){
           ApexPages.addMessage(new ApexPages.Message ( ApexPages.Severity.ERROR, 'Article Feedback Error: You must select at least one Reason'));
           toolbarflag = false;
           return null;
        }
        insert ArticleFeedbackObj;
        reasons = new List<String>();
        comments = '';
        ApexPages.addMessage(new ApexPages.Message ( ApexPages.Severity.INFO, 'Successfully Inserted.'));
        toolbarflag = true;
        return null;    
	}   
    
    public PageReference redirect(){
        id currentRecordId =  ApexPages.CurrentPage().getparameters().get('id');
        List<Knowledge__Kav> curArt = new List<Knowledge__Kav>();
        String recTypeName;
        
		curArt = [Select knowledgearticleid,Article_Record_Type_Name__c,Title,PublishStatus from Knowledge__Kav where knowledgearticleid = :currentRecordId and PublishStatus='online'];

        if(curArt.size()<1){
            curArt = [Select knowledgearticleid,Article_Record_Type_Name__c,Title from Knowledge__Kav where knowledgearticleid = :currentRecordId and PublishStatus='draft'];
        } 
        recTypeName = curArt.get(0).Article_Record_Type_Name__c;
      
            
        if(recTypeName == 'Procedure'){
            PageReference nonQuest = new PageReference('/apex/Procedure_VFP?Id='+ currentRecordId);
            nonQuest.setRedirect(false);   

            return nonQuest; 
        } 
        else if(recTypeName == 'General_Article_Template'){
            string rUrl = apexpages.currentPage().getParameters().get('search');
            system.debug('search = '+rUrl);
            PageReference nonQuest = new PageReference('/apex/General_Article_VFP?Id='+ currentRecordId);
            nonQuest.setRedirect(false);   
                
            return nonQuest;
        } else if(recTypeName =='Provider_Solutions_Community'){
            PageReference nonQuest = new PageReference('/apex/Provider_Solutions_Community_VFP?Id='+ currentRecordId);            
            nonQuest.setRedirect(false); 
                
            return nonQuest;
        } else if(recTypeName == 'External_Publication'){
            PageReference nonQuest = new PageReference('/apex/External_Publication_VFP?Id='+ currentRecordId);
            nonQuest.setRedirect(false);   
                
            return nonQuest;
        } else if(recTypeName == 'Open_Enrollment'){
            PageReference questPage = new PageReference('/apex/Open_Enrollment_VFP?Id='+ currentRecordId);
            questPage.setRedirect(false);   
                
            return questPage;
        } else if(recTypeName == 'Core_Benefit'){
            PageReference questPage = new PageReference('/apex/Core_Benefit_VFP?Id='+ currentRecordId);
            questPage.setRedirect(false);   
                
            return questPage;
        } else if(recTypeName == 'Additional_Benefits'){
            PageReference questPage = new PageReference('/apex/Additional_Benefits_VFP?Id='+ currentRecordId);
            questPage.setRedirect(false);   
                
            return questPage;
        } else if(recTypeName == 'C_G_Article'){
            PageReference questPage = new PageReference('/apex/CG_VFP?Id='+ currentRecordId);
            questPage.setRedirect(false);   
                
            return questPage;
        } else if(recTypeName == 'Category_Tab_Link'){
            PageReference questPage = new PageReference('/apex/Category_Tab_Link_VFP?Id='+ currentRecordId);
            questPage.setRedirect(false);   
                
            return questPage;
        } else if(recTypeName == 'Multi_Topic_Details'){
            PageReference questPage = new PageReference('/apex/MTD_VFP?Id='+ currentRecordId);
            questPage.setRedirect(false);   
                
            return questPage;
        } else if(recTypeName == 'Support_Queue'){
            PageReference questPage = new PageReference('/apex/Support_Queue_VFP?Id='+ currentRecordId);
            questPage.setRedirect(false);   
                
            return questPage;
        } else if(recTypeName == 'Universal_Service'){
            PageReference questPage = new PageReference('/apex/USC_VFP?Id='+ currentRecordId);
            questPage.setRedirect(false);   
                
            return questPage;
        }
        else { //multiTopic/SingleTopic
            return null;
        }    

    }
}