force/src/objects/Article_Feedback__c.object
<CustomObject>
    <description>Container for user feedback</description>
    <fields>
        <fullName>Article_ID__c</fullName>
        <description>Populate with KnowledgeArticle.ID</description>
        <label>Article ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Article_Title__c</fullName>
        <label>Article Title</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Article_Type__c</fullName>
        <label>Article Type</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Article_URL__c</fullName>
        <label>Article URL</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Data_Category_Group__c</fullName>
        <label>Data Category Group</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Data_Category__c</fullName>
        <label>Data Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Reason</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Broken Link</fullName>
                </value>
                <value>
                    <fullName>Page Unclear</fullName>
                </value>
                <value>
                    <fullName>Missing Information</fullName>
                </value>
                <value>
                    <fullName>Hard to Find Page</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Article Feedback</label>
    <nameField>
        <displayFormat>Feedback-{000}</displayFormat>
        <label>Article Feedback ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Article Feedback</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force/src/objects/Knowledge__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <page>Knowledge_VFP</page>
            <template>Page</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <fields>
        <fullName>Article_Details__c</fullName>
        <label>Article Details</label>
        <length>41000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Article_Record_Type_Name__c</fullName>
        <description>Created to capture the record type name which is used in apex classes and visualforce pages to serve-up knowledge articles in Quest.</description>
        <formula>RecordType.DeveloperName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Article Record Type Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Keyword__c</fullName>
        <label>Keyword</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Caller_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Benefits</fullName>
                </value>
                <value>
                    <fullName>Website_Assistance</fullName>
                    <label>Website Assistance</label>
                </value>
                <value>
                    <fullName>Doctor_Referral</fullName>
                    <label>Doctor Referral</label>
                </value>
                <value>
                    <fullName>Confidentiality</fullName>
                </value>
                <value>
                    <fullName>AOB/OON Provider</fullName>
                </value>
                <value>
                    <fullName>Member Experience</fullName>
                </value>
                <value>
                    <fullName>Complaint</fullName>
                </value>
                <value>
                    <fullName>Authorization</fullName>
                </value>
                <value>
                    <fullName>Eligibility</fullName>
                </value>
                <value>
                    <fullName>Client Exceptions</fullName>
                </value>
                <value>
                    <fullName>Potential Members</fullName>
                </value>
                <value>
                    <fullName>Out of Network Claims</fullName>
                </value>
                <value>
                    <fullName>Updates</fullName>
                </value>
                <value>
                    <fullName>Claims Adjustment</fullName>
                </value>
                <value>
                    <fullName>Eyefinity Assistance</fullName>
                </value>
                <value>
                    <fullName>Claim Payment</fullName>
                </value>
                <value>
                    <fullName>Provider/Office Update</fullName>
                </value>
                <value>
                    <fullName>Provider Confidentiality</fullName>
                </value>
                <value>
                    <fullName>Member Confidentiality</fullName>
                </value>
                <value>
                    <fullName>Client Confidentiality</fullName>
                </value>
                <value>
                    <fullName>Provider Authorization</fullName>
                </value>
                <value>
                    <fullName>Member Authorization</fullName>
                </value>
                <value>
                    <fullName>Provider Benefits</fullName>
                </value>
                <value>
                    <fullName>Member Benefits</fullName>
                </value>
                <value>
                    <fullName>Member Website Assistance</fullName>
                </value>
                <value>
                    <fullName>Client Website Assistance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Support_Queue_Steps__c</fullName>
        <description>Restrict visibility by Profile - visible to all users across the company EXCEPT Processors, CSR&apos;s, Hybrid CSR&apos;s and CART</description>
        <label>SQ/QQ Steps</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Topic_Links__c</fullName>
        <label>Topic Links</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Version_Comments__c</fullName>
        <label>Version Comments</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
    <recordTypes>
        <fullName>Multi_Topic</fullName>
        <active>true</active>
        <label>Multi Topic</label>
    </recordTypes>
</CustomObject>

force/src/classes/MultiTopic_Feedbackctrl.cls
public class MultiTopic_Feedbackctrl {
    /*
    public Article_Feedback__c ArticleFeedbackObj = new Article_Feedback__c();
    Public string Comments {get;set;}      
    String[] reasons = new String[]{};
    Public Knowledge__kav filterid;
    public string cbkId {get; set;}
    public Knowledge__kav mtpf{get;set;}
    public String sfUrl=URL.getSalesforceBaseUrl().getHost();   
    public List<Knowledge__DataCategorySelection> CatDetails;  
    public Knowledge__kav cbk {get; set;}
    public Boolean hiddenvaluesflag {get;set;} 
    public Boolean toolbarflag {get;set;}      
    public string ID=apexpages.currentpage(). getParameters().get('id');
    //public boolean x;
    public Boolean highlightVersionComments{get;set;} 
    public Boolean checkIfDraft{get;set;}
    
    public MultiTopic_Feedbackctrl(ApexPages.KnowledgeArticleVersionStandardController controller) {
        hiddenvaluesflag=false;
        toolbarflag = true;
        mtpf=(Knowledge__kav)controller.getRecord();           
        //Getting the Article ID 
        cbkId = apexpages.currentpage(). getParameters().get('id');                             
        cbk = new Knowledge__kav();
        if(cbkId != null && cbkId != '') {
            //Querying Data from ArticleType            
            cbk = [Select Id, LastPublishedDate,Version_Comments__c,Support_Queue_Steps__c, Title,Article_Record_Type_Name__c,
            Topic_Links__c, PublishStatus, Article_Details__c,Keyword__c, UrlName, ArticleNumber, CreatedById, OwnerId from Knowledge__kav where id=:mtpf.id  AND KnowledgeArticleId =: cbkId];           
            filterid=[SELECT Id,UrlName FROM Knowledge__kav WHERE ArticleNumber =: cbk.ArticleNumber AND id=:mtpf.id ];                
            CatDetails= [Select DataCategoryName,DataCategoryGroupName from Knowledge__DataCategorySelection where ParentId =:filterid.Id];          
        } 
        
        if(cbk.LastPublishedDate != null){
            if((cbk.LastPublishedDate.date().addDays(30))  < DateTime.now().date()){
                highlightVersionComments = false;
            }
            else{
                highlightVersionComments = true;
            } 
        }  
        
        if(cbk.PublishStatus == 'Draft'){
            checkIfDraft = true;
        }
            
    }
    
    //Multi-Picklist values for Reasons
    public List<SelectOption> getItems() {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('Broken Link','Broken Link'));
        options.add(new SelectOption('Page Unclear','Page Unclear'));
        options.add(new SelectOption('Missing Information','Missing Information'));
        options.add(new SelectOption('Hard to Find Page','Hard to Find Page'));
        options.add(new SelectOption('Other','Other'));
        return options;
    }
    
    public String[] getReasons() {
            return reasons;
        }
            
    public void setreasons(String[] reasons) {
            this.reasons = reasons;
        }   
       
    public void setCatDetails(List<Knowledge__DataCategorySelection> catDetailsList) {
        this.CatDetails = catDetailsList;
    } 
    
    public String getart() {
        return ID;      
    }
    
    public String getsfurll() {
        return sfURL;      
    }
    
    public Article_Feedback__c getArticleFeedbackObj(){
      return ArticleFeedbackObj;
    }
    
    public void setArticleFeedbackObj(Article_Feedback__c ArticleFeedbackObj){
      this.ArticleFeedbackObj = ArticleFeedbackObj;
    }
    
    public String getReturnid() {
        return cbkId;
    }

    public List<Knowledge__DataCategorySelection> getCategory() {
        return CatDetails;
    }
  
    // Creating an Article FeedBack from ArticleFeedback tab in VFP
    public PageReference saveclick() {
        ArticleFeedbackObj = new Article_Feedback__c();           
        ArticleFeedbackObj.Article_ID__c=ID;
        ArticleFeedbackObj.Article_Title__c=cbk.Title;
        //ArticleFeedbackObj.Article_Type__c='Multi_Topic';//cbk.Open_Enrollment_MJ_Record_Type__c;        
        ArticleFeedbackObj.Article_Type__c = cbk.Article_Record_Type_Name__c;
        ArticleFeedbackObj.Article_URL__c=sfURL+'/'+ID;//cbk.UrlName;       
        ArticleFeedbackObj.Comments__c=Comments;
        if(ArticleFeedbackObj.Comments__c == '' || ArticleFeedbackObj.Comments__c == null){
           ApexPages.addMessage(new ApexPages.Message ( ApexPages.Severity.ERROR, 'Article Feedback Error: You must enter Comments and select at least one Reason'));
           toolbarflag = false;
           return null;
        }

        ArticleFeedbackObj.Data_Category__c = '';

        if(CatDetails != null && !CatDetails.isEmpty()) {
             for(Integer i=0; i < CatDetails.size(); i++) {
                if(ArticleFeedbackObj.Data_Category__c != '')
                ArticleFeedbackObj.Data_Category__c = ArticleFeedbackObj.Data_Category__c + ';';
                ArticleFeedbackObj.Data_Category__c = ArticleFeedbackObj.Data_Category__c+CatDetails[i].DataCategoryName;
                ArticleFeedbackObj.Data_Category_Group__c=CatDetails[i].DataCategoryGroupName;
            }
        }
 
        ArticleFeedbackObj.Reason__c = '';
        if(reasons != null && !reasons.isEmpty()) {
            for(Integer i=0; i < reasons.size(); i++) {
                ArticleFeedbackObj.Reason__c = ArticleFeedbackObj.Reason__c+';'+reasons[i];
            }        
        }
        if(ArticleFeedbackObj.Reason__c == '' || ArticleFeedbackObj.Reason__c == null){
           ApexPages.addMessage(new ApexPages.Message ( ApexPages.Severity.ERROR, 'Article Feedback Error: You must select at least one Reason'));
           toolbarflag = false;
           return null;
        }
        insert ArticleFeedbackObj;
        reasons = new List<String>();
        comments = '';
        ApexPages.addMessage(new ApexPages.Message ( ApexPages.Severity.INFO, 'Successfully Inserted.'));
        toolbarflag = true;
        return null;    
        }   
	*/
}