force/src/objects/Article_Feedback__c.object
<CustomObject>
    <description>Container for user feedback</description>
    <label>Article Feedback</label>
    <nameField>
        <displayFormat>Feedback-{000}</displayFormat>
        <label>Article Feedback ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Article Feedback</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Knowledge__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <page>Knowledge_VFP</page>
            <template>Page</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <fields>
        <fullName>Article_Details__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Article Details</label>
        <length>41000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Keyword__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Keyword</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Support_Queue_Steps__c</fullName>
        <description>Restrict visibility by Profile - visible to all users across the company EXCEPT Processors, CSR&apos;s, Hybrid CSR&apos;s and CART</description>
        <encryptionScheme>None</encryptionScheme>
        <label>SQ/QQ Steps</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Topic_Links__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Topic Links</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Version_Comments__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Version Comments</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
</CustomObject>

src/classes/EligibilityPDFController.cls
public class EligibilityPDFController{
	
    public String param1 { get; set; }

    public string cbkId {get; set;}
    public String sfURL=URL.getSalesforceBaseUrl().getHost();   
    public knowledge__kav cbk {get; set;}
    public string ID=apexpages.currentpage(). getParameters().get('id');
    //public boolean x;
    public Boolean highlightVersionComments{get;set;} 
    public Boolean checkIfDraft{get;set;}
     public Article_Feedback__c ArticleFeedbackObj = new Article_Feedback__c();
              
    public String getart() {
        return ID;      
    }
    
    public String getsfurll() {
        //sfURL='https://vsp--knowledge.cs96.my.salesforce.com/';
        return sfURL;      
    }
          
    public String getReturnid() {
        return cbkId;
    }
        
    public PageReference setParams()
    {
    
        String sidetitle = 'Sidebar '+param1;
    system.debug('1'+param1);  

   // hiddenvaluesflag=false;
     //   toolbarflag = true;
        //mtpf=(Multi_Topic__kav)controller.getRecord();           
        //Getting the Article ID
        /* 
        switch on param1 {
        when 'Eligibility' {cbkId = 'kaH1g0000004ChREAU';} //apexpages.currentpage(). getParameters().get('id');  
        when 'Benefits' {cbkId = 'kaH1g0000004ELTEA2';}
        when 'Authorization' {cbkId = 'kaH1g0000004CrEEAU';}
        when 'COB' {cbkId = 'kaH1g0000004ChCEAU';}
        when 'Adjustments' {cbkId = 'kaH1g0000004ChVEAU';}
        when 'Determining' {cbkId = 'kaH1g0000004Cr9EAE';}
        when 'Client Exceptions' {cbkId = 'kaH1g0000004EFjEAM';}
        when 'Doctor Info' {cbkId = 'kaH1g0000004CqmEAE';}
        when 'Processing' {cbkId = 'kaH1g0000004Cr3EAE';}
        when 'Submit' {cbkId = 'kaH1g0000004CqoEAE';}
        when 'Compliance' {cbkId = 'kaH1g0000004EFTEA2';}
        when'Phone' {cbkId = 'kaH1g0000004ChbEAE';}
        }
       */
      //system.debug('param1'+param1);                                    
            cbk = [Select Id, Keyword__c,Article_Details__c, LastPublishedDate, Title, UrlName, ArticleNumber, 
            CreatedById, OwnerId,Version_Comments__c, Topic_Links__c,
            Support_Queue_Steps__c, VersionNumber from knowledge__kav where Title=:param1];                   
        return null;
    }   
     
    public EligibilityPDFController() {
    String strX = ApexPages.currentPage().getParameters().get('param1');       
    system.debug('strX'+strX); 
    }

    public String getcbkId() {
    system.debug(cbkId);        
            return cbkId;      
    }
  
    public Knowledge__kav getcbk() {
        return cbk;      
    }
	
}