force/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <label>Line of Business</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>VSP Global</fullName>
                </value>
                <value>
                    <fullName>Optics</fullName>
                </value>
                <value>
                    <fullName>Altair</fullName>
                </value>
                <value>
                    <fullName>Eyefinity</fullName>
                </value>
                <value>
                    <fullName>Vision Care</fullName>
                </value>
                <value>
                    <fullName>Marchon</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <formula>HYPERLINK(&quot;/&quot; + Id, &quot;Contact Record&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Record</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force/src/objects/Contact_Role__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Eye Care Professional</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force/src/classes/VSPR27_CampaignRelatedListExt.cls
/***************************************************
Displays Campaigns Related list on the Contact Role
that shows all open Altair Campaigns in the last 90 days 
****************************************************/


public class VSPR27_CampaignRelatedListExt {
    Public List<CampaignMember> camps{get;set;}
    private Contact_Role__c currentContactRole;
    ApexPages.StandardController controller;
    
    public VSPR27_CampaignRelatedListExt(ApexPages.StandardController controller){
        this.controller = controller;
        ID contactRoleId = ApexPages.currentPage().getParameters().get('Id');
        currentContactRole = [SELECT ID, Account__c, Contact__c FROM Contact_Role__c WHERE id=:ContactRoleID];
        camps = [SELECT Status, ContactId, Campaign.Name, Campaign.Description, Campaign.StartDate, Campaign.EndDate FROM CampaignMember WHERE ContactId =:currentContactRole.Contact__c  
                 AND Campaign.Line_of_Business__c IN ('Altair', 'Marchon') AND (Campaign.StartDate = LAST_N_DAYS:90 OR Campaign.StartDate >= TODAY)];        
    }
    
    
//    public PageReference queueRecords(){
//        String queue = '';
//        System.debug('queue string is: ' + queue);
//        update contactRoles; //needed?
//        return null;
//    }

    
}