force/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <label>Line of Business</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>VSP Global</fullName>
                </value>
                <value>
                    <fullName>Optics</fullName>
                </value>
                <value>
                    <fullName>Altair</fullName>
                </value>
                <value>
                    <fullName>Eyefinity</fullName>
                </value>
                <value>
                    <fullName>Vision Care</fullName>
                </value>
                <value>
                    <fullName>Marchon</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <formula>HYPERLINK(&quot;/&quot; + Id, &quot;Contact Record&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Record</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force/src/objects/Contact_Role__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Altair_Campaigns__c</fullName>
        <label>Altair Campaigns</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Altair_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to identify Altair Contacts on reports and call lists for DialSource.</description>
        <label>Altair Contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact_Role_Phone__c</fullName>
        <label>Role Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Contact_Role_Type__c</fullName>
        <formula>HYPERLINK(&quot;javascript:if(typeof(srcUp)!=&apos;function&apos;) {(window.parent.location.href=&apos;/&quot; &amp; Id &amp; &quot;&apos;);}&quot;+ &quot; else {srcUp(&apos;/&quot; &amp; Id &amp; &quot;?isdtp=vw&apos;)}&quot;, TEXT(Type__c), &quot;_parent&quot; )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Role Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Eye Care Professional</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force/src/classes/DS_ContactRoleRelatedListExt.cls
public class DS_ContactRoleRelatedListExt {
    Public List<Contact_Role__c> contactRoles{get;set;}
    ApexPages.StandardController controller;    
    
    public DS_ContactRoleRelatedListExt(ApexPages.StandardController controller){
        this.controller = controller;
        ID ContactRoleID = ApexPages.currentPage().getParameters().get('Id');
        Contact_Role__c c = [SELECT Account__c,id FROM Contact_Role__c WHERE id=:ContactRoleID];
        contactRoles = [SELECT Name, id, Contact__c , Contact__r.Email,Contact_Role_Phone__c,Contact_Role_Type__c,Account__c, Altair_Contact__c, Altair_Campaigns__c FROM Contact_Role__c WHERE Account__c =: c.Account__c AND id !=: c.id];
        
        Map<String, Integer> campaignsByContactIdMap = new Map<String, Integer>();
        for(Contact_Role__c cr : contactRoles){
            campaignsByContactIdMap.put(cr.Contact__c, getCampainsByContactId(cr.Contact__c).size());
            cr.Altair_Campaigns__c = campaignsByContactIdMap.get(cr.Contact__c);
        }
        
    }
    
    public List<Campaign> getCampainsByContactId(String contactId)
    {
        List<Campaign> campaignList = new List<Campaign>();
        List<CampaignMember> campaignMemberList = new List<CampaignMember>();
        List<Campaign> campaignListFiltered = new List<Campaign>();
        
        campaignMemberList = [Select Id, Title, Campaign.Id From CampaignMember where Contact.Id = :contactId];     
        
        for(CampaignMember cm : campaignMemberList){
            campaignList.add(cm.Campaign);
        }
        
        //Date dt = Date.TODAY()-90;
        campaignListFiltered = [Select Id From Campaign where Id IN :campaignList AND Line_of_Business__c IN ('Altair', 'Marchon') AND (StartDate >= TODAY OR StartDate = LAST_N_DAYS:90)];
        
        /*
        for(Campaign cmp : campaignList){
            if(cmp.Line_of_Business__c == 'Altair' && (cmp.StartDate >= Date.TODAY() || cmp.StartDate < Date.TODAY()-90)){
                campaignListFiltered.add(cmp);
            }
        }
        */
        
        return campaignListFiltered;
    }
    
    public PageReference queueRecords(){
        //may need to update contactRoles list for checkbox value to save
        String queue = '';
        System.debug('contact role before for loop: ' + contactRoles);
        System.debug('queue string is: ' + queue);
        //SubmitCallBackListFuture(String sfdcUserId, String sfdcObjectType, String DSCallBackListIds, Boolean isGlobal, String phoneType)
        //DSPriorityQueue.SubmitCallBackListFuture(UserInfo.getUserId(),'Contact_Role__c',queue,False,'Contact_Role_Phone__c');
        update contactRoles; //needed?
        return null;
    }
}