force/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Classification__c</fullName>
        <inlineHelpText>The relevant category for the Issue or Request.</inlineHelpText>
        <label>Classification</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account/Contact Maintenance</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Claims</fullName>
                </value>
                <value>
                    <fullName>Credentialing/Recruiting</fullName>
                </value>
                <value>
                    <fullName>Product</fullName>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Shipping</fullName>
                </value>
                <value>
                    <fullName>Status</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Client_Id__c</fullName>
        <inlineHelpText>Main client Id field. All other collection fields will pipe to this field. All logic will be based upon this field for client Id.</inlineHelpText>
        <label>Client Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consumer_ID__c</fullName>
        <inlineHelpText>Main consumer Id field. All other collection fields will pipe to this field. All logic will be based upon this field for consumer Id.</inlineHelpText>
        <label>Consumer ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Member_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member Plan</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.ContactId</field>
                <operation>equals</operation>
                <valueField>$Source.ContactId</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>MemberPlan</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PersonAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PersonAccount</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.IsPersonAccount</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (PersonAccount)</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PrimaryMemberConsumerId__c</fullName>
        <label>PrimaryMemberConsumerId</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CallerType__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Customer Service</fullName>
                </value>
                <value>
                    <fullName>Delays</fullName>
                </value>
                <value>
                    <fullName>Frame</fullName>
                </value>
                <value>
                    <fullName>Quality</fullName>
                </value>
                <value>
                    <fullName>Shipping</fullName>
                </value>
                <value>
                    <fullName>Injury</fullName>
                </value>
                <value>
                    <fullName>Benefits</fullName>
                </value>
                <value>
                    <fullName>Website Assistance</fullName>
                </value>
                <value>
                    <fullName>Doctor Referral</fullName>
                </value>
                <value>
                    <fullName>Confidentiality</fullName>
                </value>
                <value>
                    <fullName>AOB/OON Provider</fullName>
                </value>
                <value>
                    <fullName>Member Experience</fullName>
                </value>
                <value>
                    <fullName>Complaint</fullName>
                </value>
                <value>
                    <fullName>Authorization</fullName>
                </value>
                <value>
                    <fullName>Eligibility</fullName>
                </value>
                <value>
                    <fullName>Client Exceptions</fullName>
                </value>
                <value>
                    <fullName>Potential Members</fullName>
                </value>
                <value>
                    <fullName>Out of Network Claims</fullName>
                </value>
                <value>
                    <fullName>Updates</fullName>
                </value>
                <value>
                    <fullName>Claims Adjustment</fullName>
                </value>
                <value>
                    <fullName>Eyefinity Assistance</fullName>
                </value>
                <value>
                    <fullName>Claim Payment</fullName>
                </value>
                <value>
                    <fullName>Provider/Office Update</fullName>
                </value>
                <value>
                    <fullName>Provider Confidentiality</fullName>
                </value>
                <value>
                    <fullName>Member Confidentiality</fullName>
                </value>
                <value>
                    <fullName>Client Confidentiality</fullName>
                </value>
                <value>
                    <fullName>Provider Authorization</fullName>
                </value>
                <value>
                    <fullName>Member Authorization</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force/src/objects/ConsumerSeachResults__c.object
<CustomObject>
    <description>Used to store results from ConsumerdB so they can be displayed and sorted using Lightning dtaaTable.  After CreateCase is called- need to delete these records.</description>
    <fields>
        <fullName>Client_Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Client Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ConsumerId__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>ConsumerId</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consumer_Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>COnsumer Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimaryMemberConsumerId__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>PrimaryMemberConsumerId</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>ConsumerSeachResults</label>
    <nameField>
        <displayFormat>CS-{000}</displayFormat>
        <label>ConsumerSeachResults Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ConsumerSeachResults</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force/src/objects/MemberPlan.object
<CustomObject>
    <fields>
        <fullName>Client_ID__c</fullName>
        <label>Client ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ConsumerId__c</fullName>
        <label>ConsumerId</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division_ID__c</fullName>
        <label>Division ID</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>primaryMemberConsumerId__c</fullName>
        <label>Primary Member ConsumerId</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Propensity_Score_Management__mdt.object
<CustomObject>
    <fields>
        <fullName>Channel__c</fullName>
        <label>Channel</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>States__c</fullName>
        <label>States</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Time_Span_Begin__c</fullName>
        <label>Time Span Begin</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Time_Span_End__c</fullName>
        <label>Time Span End</label>
        <type>Date</type>
    </fields>
    <label>Propensity Score Management</label>
    <pluralLabel>Propensity Score Management</pluralLabel>
</CustomObject>

force/src/objects/PropensityScores__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>PropensityScores</relationshipLabel>
        <relationshipName>PropensityScores</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Phone</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Chat</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Classification__c</fullName>
        <label>Classification</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Confidence__c</fullName>
        <label>Confidence</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ConsumerId__c</fullName>
        <label>ConsumerId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Offer_To__c</fullName>
        <label>Offer To</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Vision Benefits Members &amp; Dependents</fullName>
                </value>
                <value>
                    <fullName>MetLife Vision Members &amp; Dependents</fullName>
                </value>
                <value>
                    <fullName>CignaVision Members &amp; Dependents</fullName>
                </value>
                <value>
                    <fullName>VSP Providers</fullName>
                </value>
                <value>
                    <fullName>VSP Premiere Providers</fullName>
                </value>
                <value>
                    <fullName>Eyeconic Customers</fullName>
                </value>
                <value>
                    <fullName>Dragon Customers</fullName>
                </value>
                <value>
                    <fullName>Nike Customers</fullName>
                </value>
                <value>
                    <fullName>Level Customers</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PersonAccount__c</fullName>
        <label>PersonAccount</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>PropensityScores</relationshipLabel>
        <relationshipName>PropensityScores</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Propensity_Priority__c</fullName>
        <description>Used for Priority field on Propensity</description>
        <label>Propensity Priority</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Reason</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>States__c</fullName>
        <label>States</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Time_Span_Begin__c</fullName>
        <description>Sets the Expected Effective date to this field</description>
        <label>Time Span Begin</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Time_Span_End__c</fullName>
        <label>Time Span End</label>
        <type>Date</type>
    </fields>
    <label>PropensityScores</label>
    <nameField>
        <displayFormat>PS-{0}</displayFormat>
        <label>PropensityScores Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PropensityScores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force/src/classes/VSPR2_GetPropensityScores.cls
global class VSPR2_GetPropensityScores{
    @InvocableMethod
    public static List<Results> getPropensityScores(List<Requests> requests){
        Results curResult = new Results();
        List<Results> resultsList = new List<Results>();
        
        List<PropensityScores__c> pScores = [SELECT Id, Case__c, Classification__c, Code__c, Confidence__c, ConsumerId__c, Name, PersonAccount__c, Priority__c, Reason__c,Time_Span_Begin__c,Time_Span_End__c
                                            FROM PropensityScores__c WHERE Case__c =: requests[0].caseIdSB];
        
        List<Propensity_Score_Management__mdt> IPpsm = [SELECT Channel__c,Customer__c,Priority__c,States__c,Time_Span_Begin__c,Time_Span_End__c FROM Propensity_Score_Management__mdt WHERE DeveloperName = 'IP' LIMIT 1];
        
        if(pScores.isEmpty()){ //if there are no scores associated to this case, call out to Consumer db and get scores
            Case caseRec = [SELECT id, accountId, member_Plan__c, consumer_Id__c, ContactId
                            FROM Case WHERE id =: requests[0].caseIdSB]; 
    
            MemberPlan mp = [SELECT ID, ConsumerId__c, Division_Id__c, Client_Id__c, PrimarymemberConsumerId__c
                             FROM MemberPlan WHERE id =: caseRec.member_Plan__c];
        
            ID personAcctId = caseRec.accountId;
            String jsonString='{"consumerId":"'+caseRec.consumer_ID__c+'","primaryMemberConsumerId":"'+mp.primaryMemberConsumerId__c+'","divIds":"'+mp.division_id__c+'","clientIds":"'+ mp.client_Id__c+'"}';
            
            HTTPResponse memResp = new HttpResponse();
            memResp = VSPR2_GetPropensityCallOut.getConsumerAPIResponse(jsonString);
            
            List<PropensityScores__c> propList = new List<PropensityScores__c>();
            
            if (memResp.getStatusCode() == 200){   
                Map<String,Object> entities = (Map<String,Object>)JSON.deserializeUntyped(memResp.getbody());
                Map<String,Object> entityResults = (Map<String,Object>)entities.get('entity');     
                List<Object>consumerResults = (List<Object>)entityResults.get('consumers');
                
                if(consumerResults != null){
                	Integer i=0;
                    Map<String,Object> subscriber;
                    
                    List<ConsumerSeachResults__c> csResultsList = new List<ConsumerSeachResults__c>();  //This is where we save the Search results from API
                    ConsumerSeachResults__c csResult;
                    
                    for(Object consumer:consumerResults){
                        subscriber = (Map<String,Object>)consumer;
                        
                        if(subscriber.keyset().contains('propensityScores')){
                            List<Object> propListAPI = (List<Object>)subscriber.get('propensityScores');                  
                            PropensityScores__c propRec = new PropensityScores__c();
                            Map<String,Object> propMap = new Map<String,Object>();
                            for(object p:propListAPI){  
                                propMap = (Map<String,Object>)p;
                                propRec = new PropensityScores__c();
                                propRec.consumerId__c = ''+ propMap.get('consumerId');
                                propRec.code__c = (String)propMap.get('code');
                                propRec.priority__c = ''+ propMap.get('priority');
                                propRec.classification__c = (String)propMap.get('classification');
                                propRec.confidence__c = (String)propMap.get('confidence');
                                propRec.reason__c = (String)propMap.get('reason');
                                propRec.PersonAccount__c = personAcctId;
                                propRec.Case__c = requests[0].caseIdSB;
                                propList.add(propRec);
                            }
                        }
                    }
                    
                    if(propList != null && propList.size() >0){
                        insert propList;
                        
                        List<PropensityScores__c> propSearch = [SELECT Case__c,Channel__c,Classification__c,Code__c,Confidence__c,ConsumerId__c,Id,Name,Offer_To__c,
                                                                PersonAccount__c,Priority__c,Propensity_Priority__c,Reason__c,Time_Span_Begin__c,Time_Span_End__c
                                                                FROM PropensityScores__c WHERE Case__c =: requests[0].caseIdSB];
                        
                        if(!propSearch.isEmpty()){
                            for(PropensityScores__c pss: propSearch){ 
                                if(pss.Code__c == 'IP' && IPpsm.size()>0){
                                    if(pss.Priority__c == '1'){
                                    	pss.Propensity_Priority__c = 'High';
                                    }else if(pss.Priority__c == '2')
                                        pss.Propensity_Priority__c = 'Medium';
                                    else{
                                        pss.Propensity_Priority__c = 'Low';
                                    }
                                    pss.Offer_To__c = IPpsm[0].Customer__c;
                                    pss.Channel__c = IPpsm[0].Channel__c;
                                    pss.Time_Span_Begin__c = IPpsm[0].Time_Span_Begin__c;
                                    pss.Time_Span_End__c = IPpsm[0].Time_Span_End__c;
                                    curResult.IPCode = 'IP';
                                    curResult.IPClassification = pss.Classification__c;
                                    curResult.IPConfidence = pss.Confidence__c;
                                    curResult.IPReason = pss.Reason__c;
                                }
                            }
                            update propSearch;
                        }
                        
                        if(!string.isEmpty(curResult.IPCode)){
                            resultsList.add(curResult);
                        }
                    }
                }
            }
        }
        else{ //scores exist on the case
            Boolean pScoreUpdate = false;
            for(PropensityScores__c pScore:pScores){
                if(pScore.Code__c == 'IP'){
                    curResult.IPCode = 'IP';
                    curResult.IPClassification = pScore.Classification__c;
                    curResult.IPConfidence = pScore.Confidence__c;
                    curResult.IPReason = pScore.Reason__c;
                    pScore.Offer_To__c = IPpsm[0].Customer__c;
                    pScore.Channel__c = IPpsm[0].Channel__c;
                    pScore.Time_Span_Begin__c = IPpsm[0].Time_Span_Begin__c;
                    pScore.Time_Span_End__c = IPpsm[0].Time_Span_End__c;
                    pScoreUpdate = true;
                }
            }  
            
            if(pScoreUpdate){
                update pScores;
            }
            
			if(!string.isEmpty(curResult.IPCode)){
            	resultsList.add(curResult);
            }
        }
        
        if(!resultsList.isEmpty()){
            return resultsList;
        }
        else{
            curResult.propensityScoreFieldIP = 'No Offer';
            resultsList.add(curResult);
            return resultsList;
        }
    }
    
    global class Requests{
        @InvocableVariable
        global String caseIdSB;
    }
    
    global class Results{
        @InvocableVariable
        global String propensityScoreFieldIP;
        @InvocableVariable
        global String IPCode;
        @InvocableVariable
        global String IPClassification;
        @InvocableVariable
        global String IPConfidence;
        @InvocableVariable
        global String IPReason;
    }
}