force/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Auto_Assign__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Un-check to maintain ownership of this Case when it is created.</inlineHelpText>
        <label>Automatically Assign Case</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Case_Priority__c</fullName>
        <description>Used for Customer Care record type, page layout, workflow, escalation and assignment rules.</description>
        <label>Case Priority</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                    <default>true</default>
                    <label>Medium</label>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IVR_Caller_Intent__c</fullName>
        <label>IVR Caller Intent</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IVR_Contact_ID__c</fullName>
        <inlineHelpText>Used to store the unique Contact ID written from IVR to the comm service and passed to Salesforce to use to pop CC Portal.</inlineHelpText>
        <label>IVR Contact ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IVR_DNIS__c</fullName>
        <label>IVR DNIS</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <inlineHelpText>The Line of Business responsible for working the Case.</inlineHelpText>
        <label>Line of Business</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Altair</fullName>
                    <color>#0B6FCE</color>
                    <label>Altair</label>
                </value>
                <value>
                    <fullName>Eyefinity</fullName>
                    <color>#78C953</color>
                    <label>Eyefinity</label>
                </value>
                <value>
                    <fullName>Global Customer Care</fullName>
                </value>
                <value>
                    <fullName>Marchon</fullName>
                    <color>#E27001</color>
                    <label>Marchon</label>
                </value>
                <value>
                    <fullName>Optics Group</fullName>
                    <color>#A845DC</color>
                    <label>Optics Group</label>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Vision Care</fullName>
                    <color>#F3D904</color>
                    <label>Vision Care</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Topic</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Line_of_Business__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Inventory</fullName>
                </value>
                <value>
                    <fullName>Special Order Request</fullName>
                </value>
                <value>
                    <fullName>Stock Order Status</fullName>
                </value>
                <value>
                    <fullName>Product Mapping</fullName>
                </value>
                <value>
                    <fullName>System</fullName>
                </value>
                <value>
                    <fullName>2020 Source (Affiliate)</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Cash Receipts</fullName>
                </value>
                <value>
                    <fullName>Data Entry</fullName>
                </value>
                <value>
                    <fullName>EDI Membership</fullName>
                </value>
                <value>
                    <fullName>Email Update</fullName>
                </value>
                <value>
                    <fullName>Explanation of Payment (EOP)</fullName>
                </value>
                <value>
                    <fullName>Eyeconic Ops</fullName>
                </value>
                <value>
                    <fullName>Eyeconic USC</fullName>
                </value>
                <value>
                    <fullName>Eye Health Management (EHM)</fullName>
                </value>
                <value>
                    <fullName>Lab Opt Out</fullName>
                </value>
                <value>
                    <fullName>Level</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>HP Plan Admin</fullName>
                </value>
                <value>
                    <fullName>HP Billing</fullName>
                </value>
                <value>
                    <fullName>Membership</fullName>
                </value>
                <value>
                    <fullName>MetLife</fullName>
                </value>
                <value>
                    <fullName>Molina</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>Office Hours Update</fullName>
                </value>
                <value>
                    <fullName>otto</fullName>
                </value>
                <value>
                    <fullName>Practice Report</fullName>
                </value>
                <value>
                    <fullName>Premier</fullName>
                </value>
                <value>
                    <fullName>Regence</fullName>
                </value>
                <value>
                    <fullName>Reimbursement Fees</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Eyeconic</fullName>
        <active>true</active>
        <businessProcess>VSP Global</businessProcess>
        <description>Used to track Eyeconic cases</description>
        <label>Eyeconic</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Eyeconic_Primary_Phone__c</fullName>
        <label>Eyeconic Primary Phone</label>
        <type>Phone</type>
    </fields>
    <recordTypes>
        <fullName>Consumer</fullName>
        <active>true</active>
        <label>Consumer</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force/src/classes/VSP_CTI_Controller.cls
public class VSP_CTI_Controller {
    
    
    public String conIdValue{get; set;}
    public String Call_Intent{get; set;}
    public String caseId{get; set;}
    public String caseNum{get; set;}
    public String IVRDNIS{get; set;}
    public String IVRConId{get; set;}
    public List<String> Arraylist{get;set;}
    public String conIdList{get;set;}
    public String senderNum {get;set;}
    public List<Contact> conLst {get;set;}
    public List<Contact> conLstNonEye {get;set;}
    public String processNum {get;set;}
    public String conFirstLast {get;set;}
    
    
    
    public void VSP_CTI_Controller(){
        //  conIdValue = 'TestId';
        //  String conIdValue = Apexpages.currentPage().getParameters().get('conIdValue');
        if (conIdList != null){
            Arraylist = conIdList.split(';');
        }
        system.debug('FIND THIS conIdList ' + conIdList);
        system.debug('FIND THIS Arraylist ' + Arraylist);
        ///New Case Create///
        if(conIdList != null && conIdList != ''){
            try{
                String caseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Eyeconic').getRecordTypeId();
                String conRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Consumer').getRecordTypeId();
                conLstNonEye = [SELECT Id, Eyeconic_Primary_Phone__c, FirstName, LastName FROM Contact WHERE Id IN :Arraylist AND RecordTypeId = :conRecordTypeId ORDER BY LastModifiedDate DESC];
                conLst = [SELECT Id, Eyeconic_Primary_Phone__c, FirstName, LastName FROM Contact WHERE Id IN :Arraylist AND Eyeconic_Primary_Phone__c != null AND RecordTypeId = :conRecordTypeId ORDER BY LastModifiedDate DESC];
                system.debug('conLst ' + conLst);
                if(conLst.size() == 1){
                    
                    if(Arraylist.size() == 1){
                        
                        for(Contact cLst :conLst){
                            String tphone = cLst.Eyeconic_Primary_Phone__c.replaceAll('\\D','');
                            system.debug('tphone ' + tphone);
                            system.debug('senderNum ' + senderNum);
                            if(tphone == senderNum){
                                
                               
                                // String[] Fields = Call_Intent.split(';');
                                //Integer LastValue = Fields.size() - 1;
                                Case newCase = new Case(
                                    RecordTypeId = caseRecordTypeId,
                                    Subject = 'Eyeconic phone call',
                                    Description = 'Eyeconic phone call',
                                    Line_of_Business__c = 'Retail',
                                    Case_Priority__c = 'Medium',
                                    Origin = 'Phone',
                                    Type = 'Issue',
                                    Status = 'New',
                                    Product__c = 'Eyeconic USC',
                                    Auto_Assign__c = false,
                                    IVR_DNIS__c = IVRDNIS,
                                    IVR_Contact_ID__c = IVRConId,
                                    //  IVR_Caller_Intent__c = Fields[LastValue],
                                    ContactId = cLst.Id);
                                insert newCase; 
                                caseId = newCase.Id;
                                conIdValue = cLst.Id;
                                newCase = [select Id, CaseNumber from Case where Id = :caseId];
                                caseNum = newCase.CaseNumber;
                                conFirstLast = cLst.FirstName + ' ' + cLst.LastName;
                                processNum = 'found1EyeconCaseOutFocus';
                                system.debug('ProcessNum ' + processNum + ' ConId ' + conIdValue);
                                return;
                                //   system.debug('FIND THIS ' + conIdValue +' Call_Intent '+ Call_Intent + ' Case Num ' + caseNum + ' Array Size' + LastValue );
                            }
                            else{
                                
                                // String[] Fields = Call_Intent.split(';');
                                //Integer LastValue = Fields.size() - 1;
                                Case newCase = new Case(
                                    RecordTypeId = caseRecordTypeId,
                                    Subject = 'Eyeconic phone call',
                                    Description = 'Eyeconic phone call',
                                    Line_of_Business__c = 'Retail',
                                    Case_Priority__c = 'Medium',
                                    Origin = 'Phone',
                                    Type = 'Issue',
                                    Status = 'New',
                                    Product__c = 'Eyeconic USC',
                                    Auto_Assign__c = false,
                                    IVR_DNIS__c = IVRDNIS,
                                    IVR_Contact_ID__c = IVRConId);
                                //  IVR_Caller_Intent__c = Fields[LastValue],
                                // ContactId = cLst.Id);
                                insert newCase; 
                                caseId = newCase.Id;
                                conIdValue = cLst.Id;
                                newCase = [select Id, CaseNumber from Case where Id = :caseId];
                                caseNum = newCase.CaseNumber;
                                conFirstLast = cLst.FirstName + ' ' + cLst.LastName;
                                processNum = 'found1EyeconCaseOutFocus';
                                system.debug('ProcessNum ' + processNum + ' ConId ' + conIdValue);                            
                                return;
                                
                            }
                        }
                    }
                    else if(Arraylist.size() > 1){
                        
                        for(Contact cLst :conLst){
                            String tphone = cLst.Eyeconic_Primary_Phone__c.replaceAll('\\D','');
                            system.debug('tphone ' + tphone);
                            system.debug('senderNum ' + senderNum);
                            if(tphone == senderNum){
                                
                                // String[] Fields = Call_Intent.split(';');
                                //Integer LastValue = Fields.size() - 1;
                                Case newCase = new Case(
                                    RecordTypeId = caseRecordTypeId,
                                    Subject = 'Eyeconic phone call',
                                    Description = 'Eyeconic phone call',
                                    Line_of_Business__c = 'Retail',
                                    Case_Priority__c = 'Medium',
                                    Origin = 'Phone',
                                    Type = 'Issue',
                                    Status = 'New',
                                    Product__c = 'Eyeconic USC',
                                    Auto_Assign__c = false,
                                    IVR_DNIS__c = IVRDNIS,
                                    IVR_Contact_ID__c = IVRConId,
                                    //  IVR_Caller_Intent__c = Fields[LastValue],
                                    ContactId = cLst.Id);
                                insert newCase; 
                                caseId = newCase.Id;
                                conIdValue = cLst.Id;
                                newCase = [select Id, CaseNumber from Case where Id = :caseId];
                                caseNum = newCase.CaseNumber;
                                conFirstLast = cLst.FirstName + ' ' + cLst.LastName;
                                processNum = 'Multifound1EyeconCaseOutFocus';
                                system.debug('ProcessNum ' + processNum + ' ConId ' + conIdValue);
                                return;
                                //   system.debug('FIND THIS ' + conIdValue +' Call_Intent '+ Call_Intent + ' Case Num ' + caseNum + ' Array Size' + LastValue );
                            }
                            else{
                                
                                // String[] Fields = Call_Intent.split(';');
                                //Integer LastValue = Fields.size() - 1;
                                Case newCase = new Case(
                                    RecordTypeId = caseRecordTypeId,
                                    Subject = 'Eyeconic phone call',
                                    Description = 'Eyeconic phone call',
                                    Line_of_Business__c = 'Retail',
                                    Case_Priority__c = 'Medium',
                                    Origin = 'Phone',
                                    Type = 'Issue',
                                    Status = 'New',
                                    Product__c = 'Eyeconic USC',
                                    Auto_Assign__c = false,
                                    IVR_DNIS__c = IVRDNIS,
                                    IVR_Contact_ID__c = IVRConId);
                                //  IVR_Caller_Intent__c = Fields[LastValue],
                                // ContactId = cLst.Id);
                                insert newCase; 
                                caseId = newCase.Id;
                                conIdValue = cLst.Id;
                                newCase = [select Id, CaseNumber from Case where Id = :caseId];
                                caseNum = newCase.CaseNumber;
                                conFirstLast = cLst.FirstName + ' ' + cLst.LastName;
                                processNum = 'Multifound1EyeconCaseOutFocus';
                                system.debug('ProcessNum ' + processNum + ' ConId ' + conIdValue);                            
                                return;
                                
                            }
                        }
                        
                    }
                }
                else if(conLst.size() > 1){
                    
                    // String[] Fields = Call_Intent.split(';');
                    //Integer LastValue = Fields.size() - 1;
                    Case newCase = new Case(
                        RecordTypeId = caseRecordTypeId,
                        Subject = 'Eyeconic phone call',
                        Description = 'Eyeconic phone call',
                        Line_of_Business__c = 'Retail',
                        Case_Priority__c = 'Medium',
                        Origin = 'Phone',
                        Type = 'Issue',
                        Status = 'New',
                        Product__c = 'Eyeconic USC',
                        Auto_Assign__c = false,
                        IVR_DNIS__c = IVRDNIS,
                        IVR_Contact_ID__c = IVRConId);
                    //  IVR_Caller_Intent__c = Fields[LastValue],
                    // ContactId = cLst.Id);
                    insert newCase; 
                    caseId = newCase.Id;
                    //  conIdValue = cLst.Id;
                    newCase = [select Id, CaseNumber from Case where Id = :caseId];
                    caseNum = newCase.CaseNumber;
                    // conFirstLast = cLst.FirstName + ' ' + cLst.LastName;
                    processNum = 'MultifoundMultiEyeconCaseOutFocus';
                    system.debug('ProcessNum ' + processNum + ' ConId ' + conIdValue + 'ConLst size '+ conLst.size() + ' Array size ' + Arraylist.size());                            
                    return;
                    
                }
                
                
                else if(conLst.isEmpty()){///count is 0
                    if(Arraylist.size() == 1){
                        
                        for(Contact cLst :conLstNonEye){

                            // String[] Fields = Call_Intent.split(';');
                            //Integer LastValue = Fields.size() - 1;
                            Case newCase = new Case(
                                RecordTypeId = caseRecordTypeId,
                                Subject = 'Eyeconic phone call',
                                Description = 'Eyeconic phone call',
                                Line_of_Business__c = 'Retail',
                                Case_Priority__c = 'Medium',
                                Origin = 'Phone',
                                Type = 'Issue',
                                Status = 'New',
                                Product__c = 'Eyeconic USC',
                                Auto_Assign__c = false,
                                IVR_DNIS__c = IVRDNIS,
                                IVR_Contact_ID__c = IVRConId);
                            //  IVR_Caller_Intent__c = Fields[LastValue],
                            // ContactId = cLst.Id);
                            insert newCase; 
                            caseId = newCase.Id;
                            conIdValue = cLst.Id;
                            newCase = [select Id, CaseNumber from Case where Id = :caseId];
                            caseNum = newCase.CaseNumber;
                            conFirstLast = cLst.FirstName + ' ' + cLst.LastName;
                            processNum = 'found1conCaseOutFocus';
                            system.debug('ProcessNum ' + processNum + ' ConId ' + conIdValue + 'ConLst size '+ conLst.size() + ' Array size ' + Arraylist.size());                            
                            return;
                        }
                    }
                    else{
                        
                        // String[] Fields = Call_Intent.split(';');
                        //Integer LastValue = Fields.size() - 1;
                        Case newCase = new Case(
                            RecordTypeId = caseRecordTypeId,
                            Subject = 'Eyeconic phone call',
                            Description = 'Eyeconic phone call',
                            Line_of_Business__c = 'Retail',
                            Case_Priority__c = 'Medium',
                            Origin = 'Phone',
                            Type = 'Issue',
                            Status = 'New',
                            Product__c = 'Eyeconic USC',
                            Auto_Assign__c = false,
                            IVR_DNIS__c = IVRDNIS,
                            IVR_Contact_ID__c = IVRConId);
                        //  IVR_Caller_Intent__c = Fields[LastValue],
                        // ContactId = cLst.Id);
                        insert newCase; 
                        caseId = newCase.Id;
                        // conIdValue = cLst.Id;
                        newCase = [select Id, CaseNumber from Case where Id = :caseId];
                        caseNum = newCase.CaseNumber;
                        // conFirstLast = cLst.FirstName + ' ' + cLst.LastName;
                        processNum = 'foundMulticonCaseInFocus';  ///multiple contacts no eye phone numbers
                        system.debug('ProcessNum ' + processNum + 'ConLst size '+ conLst.size() + ' Array size ' + Arraylist.size());                            
                        return;
                    }
                }
            }///end Try
            catch(Exception e){
                System.debug('ERROR:' + e); 
            }
        }
        else{////array size is 0
            try{
                
                String caseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Eyeconic').getRecordTypeId();
                // String[] Fields = Call_Intent.split(';');
                //Integer LastValue = Fields.size() - 1;
                Case newCase = new Case(
                    RecordTypeId = caseRecordTypeId,
                    Subject = 'Eyeconic phone call',
                    Description = 'Eyeconic phone call',
                    Line_of_Business__c = 'Retail',
                    Case_Priority__c = 'Medium',
                    Origin = 'Phone',
                    Type = 'Issue',
                    Status = 'New',
                    Product__c = 'Eyeconic USC',
                    Auto_Assign__c = false,
                    IVR_DNIS__c = IVRDNIS,
                    IVR_Contact_ID__c = IVRConId);
                //  IVR_Caller_Intent__c = Fields[LastValue],
                // ContactId = cLst.Id);
                insert newCase; 
                caseId = newCase.Id;
                // conIdValue = cLst.Id;
                newCase = [select Id, CaseNumber from Case where Id = :caseId];
                caseNum = newCase.CaseNumber;
                // conFirstLast = cLst.FirstName + ' ' + cLst.LastName;
                processNum = 'found0conCaseInFocus';  ///no contacts
                system.debug('ProcessNum ' + processNum + 'No Contacts found');                            
                return;                
            }
            catch(Exception e){
                System.debug('ERROR:' + e); 
            }
        }
    }
    
}