force/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <label>Topic</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Line_of_Business__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Inventory</fullName>
                </value>
                <value>
                    <fullName>Special Order Request</fullName>
                </value>
                <value>
                    <fullName>Stock Order Status</fullName>
                </value>
                <value>
                    <fullName>Product Mapping</fullName>
                </value>
                <value>
                    <fullName>System</fullName>
                </value>
                <value>
                    <fullName>2020 Source (Affiliate)</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Cash Receipts</fullName>
                </value>
                <value>
                    <fullName>Data Entry</fullName>
                </value>
                <value>
                    <fullName>EDI Membership</fullName>
                </value>
                <value>
                    <fullName>Email Update</fullName>
                </value>
                <value>
                    <fullName>Explanation of Payment (EOP)</fullName>
                </value>
                <value>
                    <fullName>Eyeconic Ops</fullName>
                </value>
                <value>
                    <fullName>Eyeconic USC</fullName>
                </value>
                <value>
                    <fullName>Eye Health Management (EHM)</fullName>
                </value>
                <value>
                    <fullName>Lab Opt Out</fullName>
                </value>
                <value>
                    <fullName>Level</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>HP Plan Admin</fullName>
                </value>
                <value>
                    <fullName>HP Billing</fullName>
                </value>
                <value>
                    <fullName>Membership</fullName>
                </value>
                <value>
                    <fullName>MetLife</fullName>
                </value>
                <value>
                    <fullName>Molina</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>Office Hours Update</fullName>
                </value>
                <value>
                    <fullName>otto</fullName>
                </value>
                <value>
                    <fullName>Practice Report</fullName>
                </value>
                <value>
                    <fullName>Premier</fullName>
                </value>
                <value>
                    <fullName>Regence</fullName>
                </value>
                <value>
                    <fullName>Reimbursement Fees</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reason_for_Contact__c</fullName>
        <label>Reason for Contact</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Product__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Account/Contact Maintenance</fullName>
                </value>
                <value>
                    <fullName>Adjustments</fullName>
                </value>
                <value>
                    <fullName>Authorization</fullName>
                </value>
                <value>
                    <fullName>Benefits - In-Network</fullName>
                </value>
                <value>
                    <fullName>Benefits - Insurance</fullName>
                </value>
                <value>
                    <fullName>Benefits - Out-Of-Network</fullName>
                </value>
                <value>
                    <fullName>Billing/Charges</fullName>
                </value>
                <value>
                    <fullName>Claims</fullName>
                </value>
                <value>
                    <fullName>COB</fullName>
                </value>
                <value>
                    <fullName>Cobra/Enrollment</fullName>
                </value>
                <value>
                    <fullName>Cost</fullName>
                </value>
                <value>
                    <fullName>Dr List</fullName>
                </value>
                <value>
                    <fullName>Eligibility</fullName>
                </value>
                <value>
                    <fullName>Exchange/Refund</fullName>
                </value>
                <value>
                    <fullName>General Inquiry</fullName>
                </value>
                <value>
                    <fullName>ID Card Requests</fullName>
                </value>
                <value>
                    <fullName>Individual Plans</fullName>
                </value>
                <value>
                    <fullName>Level App</fullName>
                </value>
                <value>
                    <fullName>Level Frame - Charging</fullName>
                </value>
                <value>
                    <fullName>Level Frame - Tech</fullName>
                </value>
                <value>
                    <fullName>Level Tech Support</fullName>
                </value>
                <value>
                    <fullName>Level Troubleshooting</fullName>
                </value>
                <value>
                    <fullName>Material - Contacts</fullName>
                </value>
                <value>
                    <fullName>Material - Frames Only</fullName>
                </value>
                <value>
                    <fullName>Material - Glasses</fullName>
                </value>
                <value>
                    <fullName>Material - Lenses Only</fullName>
                </value>
                <value>
                    <fullName>Member ID Inquiry</fullName>
                </value>
                <value>
                    <fullName>Member Info Not Found</fullName>
                </value>
                <value>
                    <fullName>My Account</fullName>
                </value>
                <value>
                    <fullName>No Response</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Resolution_of_Contact__c</fullName>
        <label>Resolution of Contact</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Provided Authorization Services for Customer</fullName>
                </value>
                <value>
                    <fullName>Provided Insurance Benefits Information for Customer</fullName>
                </value>
                <value>
                    <fullName>Provided In-Network Benefits Information for Customer</fullName>
                </value>
                <value>
                    <fullName>Provided Out-Of-Network Benefits Information for Customer</fullName>
                </value>
                <value>
                    <fullName>Provided Eyeconic Billing Information for Customer</fullName>
                </value>
                <value>
                    <fullName>Provided Claim(s) Information for Customer</fullName>
                </value>
                <value>
                    <fullName>Provided Coverage/Claims Coordination of Benefits Information with Customer</fullName>
                </value>
                <value>
                    <fullName>Provided Benefits Information for Customer regarding Cobra or Open Enrollment Coverage</fullName>
                </value>
                <value>
                    <fullName>Provided Dr List for Customer</fullName>
                </value>
                <value>
                    <fullName>Provided Eligibility Information for Customer</fullName>
                </value>
                <value>
                    <fullName>Assisted Customer with ID Card Request</fullName>
                </value>
                <value>
                    <fullName>Provided Individual Plan Information for Customer</fullName>
                </value>
                <value>
                    <fullName>Provided Level Application Information to Customer</fullName>
                </value>
                <value>
                    <fullName>Provided Level Frame Tech Information for Customer</fullName>
                </value>
                <value>
                    <fullName>Provided Level Frame Charging Information for Customer</fullName>
                </value>
                <value>
                    <fullName>Provided Level Tech Support for Customer</fullName>
                </value>
                <value>
                    <fullName>Provided Level Troubleshooting Information for Customer</fullName>
                </value>
                <value>
                    <fullName>Assisted Customer with Contact Lens Material Inquiry</fullName>
                </value>
                <value>
                    <fullName>Assisted Customer with Glasses Material Inquiry</fullName>
                </value>
                <value>
                    <fullName>Assisted Customer with Frames Only Material Inquiry</fullName>
                </value>
                <value>
                    <fullName>Assisted Customer with Spectacle Lenses Only Material Inquiry</fullName>
                </value>
                <value>
                    <fullName>Assisted Customer with Member ID Inquiry</fullName>
                </value>
                <value>
                    <fullName>Provided Member Info to Customer</fullName>
                </value>
                <value>
                    <fullName>Assisted Customer with Eyeconic My Account Issues</fullName>
                </value>
                <value>
                    <fullName>Provided Eyeconic Order Status Information for customer</fullName>
                </value>
                <value>
                    <fullName>Assisted Customer with new Eyeconic Order</fullName>
                </value>
                <value>
                    <fullName>Assisted Customer with Cancellation of their Eyeconic Order</fullName>
                </value>
                <value>
                    <fullName>Assisted Customer with existing Eyeconic Order</fullName>
                </value>
                <value>
                    <fullName>Assisted Customer with Eyeconic Order</fullName>
                </value>
                <value>
                    <fullName>Provided Eyeconic Prescription Information for Customer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Customer_Care</fullName>
        <active>true</active>
        <businessProcess>VSP Global</businessProcess>
        <description>Used for VSP Global Customer Care Cases</description>
        <label>Customer Care</label>
    </recordTypes>
    <recordTypes>
        <fullName>Eyeconic</fullName>
        <active>true</active>
        <businessProcess>VSP Global</businessProcess>
        <description>Used to track Eyeconic cases</description>
        <label>Eyeconic</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force/src/objects/Case_Resolution__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Reason_for_Contact__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Reason for Contact</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Resolution_of_Contact__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Resolution of Contact</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Topic__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Topic</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Case Resolution</label>
</CustomObject>

force/src/classes/VSPR26_PopulateResolutionContact.cls
public class VSPR26_PopulateResolutionContact {
    
    public static boolean VSPR26_PopulateResolutionContact_recursion = true;
    public void setResolution(List<Case> newCaselst,Map<Id,Case> mpOldCase) {
        
        if(VSPR26_PopulateResolutionContact_recursion){
            VSPR26_PopulateResolutionContact_recursion = false;
            system.debug('***** VSPR26_PopulateResolutionContact ***** ');
            Id eyeconicRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Eyeconic').getRecordTypeId();
            Id customerCaseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Customer_Care').getRecordTypeId();
            Set<id> caseId=new Set<Id>();
            Set<String> setTopic = new Set<String>();
            Set<String> setReason = new Set<String>();
            Map<id, Case> mapCase = new Map<Id, Case>();
            for(Case cs : newCaselst){
                
                if(mpOldCase !=null && (cs.RecordTypeId == eyeconicRecordTypeId || cs.RecordTypeId == customerCaseRecordTypeId)){
                    if(cs.Reason_for_Contact__c != mpOldCase.get(cs.Id).Reason_for_Contact__c
                       ||mpOldCase.get(cs.Id).Reason_for_Contact__c == null && cs.Reason_for_Contact__c !=null
                       ||mpOldCase.get(cs.Id).Reason_for_Contact__c != null && cs.Reason_for_Contact__c ==null){
                           caseId.add(cs.Id);
                           mapCase.put(cs.Id,cs);
                           setTopic.add(cs.Product__c);
                           if(cs.Reason_for_Contact__c ==null){
                               
                           }
                           else{
                               List<String> lstString = cs.Reason_for_Contact__c.split(';');
                               for(String t: lstString){
                                   setReason.add(t);
                               }
                           }
                           //  setReason.add(cs.Reason_for_Contact__c);
                       }
                }
                else{
                    if(cs.Reason_for_Contact__c != null && (cs.RecordTypeId == eyeconicRecordTypeId || cs.RecordTypeId == customerCaseRecordTypeId)){
                        caseId.add(cs.Id);
                        mapCase.put(cs.Id,cs);
                        setTopic.add(cs.Product__c);
                        List<String> lstString = cs.Reason_for_Contact__c.split(';');
                        for(String t: lstString){
                            setReason.add(t);
                        }
                    }
                }
            }
            
            if(!caseId.isEmpty()){
                system.debug('***** caseId set ***** ' + caseId);
                system.debug('***** mapCase map ***** ' + mapCase);
                system.debug('***** setTopic ***** ' + setTopic);
                system.debug('***** setReason ***** ' + setReason);
                
                List<Case_Resolution__c> resList = [SELECT Id, Name, Topic__c, Reason_for_Contact__c, Resolution_of_Contact__c 
                                                    FROM Case_Resolution__c
                                                    WHERE Topic__c in :setTopic
                                                    AND Reason_for_Contact__c in :setReason];
                
                
                system.debug('***** resList List ***** ' + resList);
                
                if(!resList.isEmpty() && resList != null){
                    Set<String> resolutionSet = new set<String>();
                    String resolutionString = '';
                    map<Id, String> caseUpd = new map<Id, String>();
                    for(Case updCase: mapCase.values()){
                        for(Case_Resolution__c cr: resList){
                            if(cr.Resolution_of_Contact__c != null
                               && cr.Topic__c == updCase.Product__c 
                               && updCase.Reason_for_Contact__c.contains(cr.Reason_for_Contact__c)){
                                   
                                   resolutionSet.add(cr.Resolution_of_Contact__c);
                               }
                        }
                    }
                    
                    system.debug('***** resolutionSet ***** ' + resolutionSet);
                    
                    for(String s:resolutionSet){
                        System.debug('TESTING++++++ s' + s);
                        if(resolutionString == ''){
                            resolutionString = s;
                        }
                        else{
                            resolutionString = resolutionString + ';' + s;
                        }
                        
                    }
                    
                    
                    for(Case setResolution : mapCase.values()){
                        
                        setResolution.Resolution_of_Contact__c = resolutionString;
                    }
                    
                    
                }
                else{
                    for(Case setResolution :mapCase.values()){
                        setResolution.Resolution_of_Contact__c = null;
                    }
                }
                
            }
            
        }
        
    }
    
    
}