force/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Contact_Role__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact Role</label>
        <referenceTo>Contact_Role__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force/src/objects/Contact_Role__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Eye Care Professional</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force/src/objects/General_Table__c.object
<CustomObject>
    <label>General Table</label>
    <nameField>
        <label>Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>General Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force/src/objects/License__c.object
<CustomObject>
    <description>Object to manage a Vision Care Doctor&apos;s Licenses</description>
    <fields>
        <fullName>License_Type_Description__c</fullName>
        <label>License Type Description</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>State Controlled Substances</fullName>
                </value>
                <value>
                    <fullName>Federal Controlled Substances</fullName>
                </value>
                <value>
                    <fullName>Standard State License</fullName>
                </value>
                <value>
                    <fullName>Medicaid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <label>Provider</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Licenses</relationshipLabel>
        <relationshipName>Licenses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>NH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>License</label>
    <nameField>
        <displayFormat>LICENSE-{000000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force/src/objects/Network_Relationship__c.object
<CustomObject>
    <description>Custom object to track Payment Relationships between doctors and offices.</description>
    <fields>
        <fullName>Claims_Priced__c</fullName>
        <label>Claims Priced</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Y</fullName>
                </value>
                <value>
                    <fullName>N</fullName>
                    <default>true</default>
                    <label>N</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact_Role__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact Role</label>
        <referenceTo>Contact_Role__c</referenceTo>
        <relationshipName>Payment_Relationships</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup relationship field from Network Relationship to General Table object</description>
        <label>Program ID</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>General_Table__c.Table__c</field>
                <operation>equals</operation>
                <value>PRSP</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>General_Table__c</referenceTo>
        <relationshipLabel>Network Relationships</relationshipLabel>
        <relationshipName>Network_Relationships</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Provider Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Network Relationships</relationshipLabel>
        <relationshipName>Network_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Network Relationship</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Network Relationship Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Network Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force/src/objects/Skip_Trigger__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Skip_Triggers__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Skip all PROS Decommission-related Triggers on Account, Contact, Contact Role, and Network Relationship objects.</description>
        <label>Skip Triggers</label>
        <type>Checkbox</type>
    </fields>
    <label>Skip Trigger</label>
</CustomObject>

force/src/classes/VSPR25b_ValidateMedicaidLicense.cls
public class VSPR25b_ValidateMedicaidLicense {
    
    public static boolean VSPR19B_ValidateMedicaidLicenseMethod_recursion = true;
    public void VSPR19B_ValidateMedicaidLicenseMethod(List<Network_Relationship__c> newRecs,List<Network_Relationship__c> oldRecs,Map<Id,Network_Relationship__c> newRecsMap,Map<Id,Network_Relationship__c> oldRecsMap){
        
        if(VSPR19B_ValidateMedicaidLicenseMethod_recursion){
            VSPR19B_ValidateMedicaidLicenseMethod_recursion = false;
            
            system.debug('***** entered VSPR19B_ValidateMedicaidLicenseMethod ***** ');
            
            list<License__c> listLicense = new list<License__c>();
            list<Contact_Role__c> listContactRole = new list<Contact_Role__c>();
            Set<Id> DoctorIds = new Set<Id>();
            Set<Id> ContactRoleIds = new Set<Id>();
            String stateMedicaId;
            String programIdBeginswith;
            Id currentUserId = userInfo.getUserId();
            Id profileId = userinfo.getProfileId();
            String profileName = [Select Id, Name from Profile where Id = :profileId].Name;
            Skip_Trigger__c skip = Skip_Trigger__c.getInstance();
            if(skip.Skip_Triggers__c) { return;}    
            
            
            
            if(( profileName != 'System Administrator' && 
                profileName != 'VSP Technical User' && 
                profileName != 'VSP Integration User' ) || test.isrunningtest()){
                    if(Trigger.IsInsert && Trigger.IsBefore){
                        map<String,General_Table__c> mpProgramId = new map<String,General_Table__c>(); 
                        for(Network_Relationship__c nw : newRecs){
                            if(nw.Program_ID__c != NULL) {
                                mpProgramId.put(nw.Program_ID__c,NULL);
                            }
                        }
                        mpProgramId = new map<String,General_Table__c>([SELECT Id,Name FROM General_Table__c WHERE Id IN :mpProgramId.keySet()]);
                        for(Network_Relationship__c nw : newRecs){
                            system.debug('============CRole'+nw.Contact_Role__c);
                            system.debug('============Provider'+nw.Provider_Name__c);
                            //system.debug('============Program'+nw.Program_ID__r.name);
                            //DoctorIds.add(nw.Provider_Name__c);
                            ContactRoleIds.add(nw.Contact_Role__c);
                            
                            stateMedicaId = mpProgramId.containsKey(nw.Program_ID__c) ? mpProgramId.get(nw.Program_ID__c).Name.right(2) : null; //((String.valueof(nw.Program_ID__r.Name)).right(2));
                            system.debug('------------'+stateMedicaId); 
                            programIdBeginswith = mpProgramId.containsKey(nw.Program_ID__c) ? mpProgramId.get(nw.Program_ID__c).Name.left(3) : null; //(String.valueof(nw.Program_ID__r.Name).left(3));
                            system.debug('------------ '+programIdBeginswith); 
                        }
                        
                        listContactRole = [select Id, Contact__c from Contact_Role__c where Id IN:ContactRoleIds];
                        for(Contact_Role__c cr :listContactRole ){
                            DoctorIds.add(cr.Contact__c);
                        }
                        if(programIdBeginswith == 'MCD'){
                            listLicense = [SELECT Id, License_Type_Description__c, State__c 
                                           FROM License__c 
                                           WHERE Provider__c IN :DoctorIds 
                                           AND License_Type_Description__c ='Medicaid' 
                                           AND State__c=:stateMedicaId];
                            system.debug('=============ListLicense'+listLicense+'Size'+ ListLicense.size());
                            for(Network_Relationship__c nw : newRecs){
                                if(programIdBeginswith == 'MCD' && listLicense.size()>0)
                                    system.debug('Match Ok');
                                else
                                    nw.addError('To add this Program ID, the doctor must have an associated Medicaid License for that state.');
                            }
                        }
                    }
                    
                    
                    //Case Number: 00010881
                    //Date: 17th March, 2017
                    if (trigger.IsInsert && trigger.isAfter)
                    {
                        system.debug('#### in handler');
                        
                        if(NetworkRelTriggerForProgramIdHandler.validate==false){
                            system.debug('############# Insert in Handler');
                            NetworkRelTriggerForProgramIdHandler.applyActiveCostcoPIToNewDoctor(newRecsMap.keyset());
                        }
                        
                    }
                    if (( (trigger.IsInsert && trigger.isAfter)|| (trigger.IsUpdate && trigger.isAfter) ) || test.isrunningtest())
                    {
                        system.debug('#### in handler updation');
                        //call to handler class
                        //NetworkRelationshipTriggerHandler.applyActiveCostcoPIToNewDoctor(trigger.new);
                        
                        if(NetworkRelationshipTriggerHandler.validate==false && (trigger.IsInsert && trigger.isAfter)){
                            system.debug('############# Insert in Handler');
                            NetworkRelationshipTriggerHandler.applyActiveCostcoPIToNewDoctor(newRecsMap.keyset());
                        }
                        else if(NetworkRelationshipTriggerHandler.validate==false && (trigger.IsUpdate && trigger.isAfter)){
                            system.debug('updated&&&&&&');
                            set<id> newId=new set<id>();
                            for(Network_Relationship__c nw:newRecs){
                                // system.debug(nw.Program_ID__c+'%%%%%%%%'+Trigger.oldMap.get(nw.id).Program_ID__c);
                                if(nw.Program_ID__c!=oldRecsMap.get(nw.id).Program_ID__c)
                                    newId.add(nw.id);
                            }
                            if(newId.size()>0)
                                NetworkRelationshipTriggerHandler.applyActiveCostcoPIToNewDoctor(newId);
                            
                        }
                        
                        
                    }
                    
                    If(Trigger.isdelete){
                        for(Network_Relationship__c nw:oldRecs){
                            
                            if(nw.Claims_Priced__c=='Y'){
                                nw.Claims_Priced__c.addError(' A claim has been priced against this Network Relationship. It cannot be deleted.');
                                
                            }
                            
                        }
                        
                    }
                } 
        }
    }  
    
}