force/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <label>Topic</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Line_of_Business__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Inventory</fullName>
                </value>
                <value>
                    <fullName>Special Order Request</fullName>
                </value>
                <value>
                    <fullName>Stock Order Status</fullName>
                </value>
                <value>
                    <fullName>Product Mapping</fullName>
                </value>
                <value>
                    <fullName>System</fullName>
                </value>
                <value>
                    <fullName>2020 Source (Affiliate)</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Cash Receipts</fullName>
                </value>
                <value>
                    <fullName>Data Entry</fullName>
                </value>
                <value>
                    <fullName>EDI Membership</fullName>
                </value>
                <value>
                    <fullName>Email Update</fullName>
                </value>
                <value>
                    <fullName>Explanation of Payment (EOP)</fullName>
                </value>
                <value>
                    <fullName>Eyeconic Ops</fullName>
                </value>
                <value>
                    <fullName>Eyeconic USC</fullName>
                </value>
                <value>
                    <fullName>Eye Health Management (EHM)</fullName>
                </value>
                <value>
                    <fullName>Lab Opt Out</fullName>
                </value>
                <value>
                    <fullName>Level</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>HP Plan Admin</fullName>
                </value>
                <value>
                    <fullName>HP Billing</fullName>
                </value>
                <value>
                    <fullName>Membership</fullName>
                </value>
                <value>
                    <fullName>MetLife</fullName>
                </value>
                <value>
                    <fullName>Molina</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>Office Hours Update</fullName>
                </value>
                <value>
                    <fullName>otto</fullName>
                </value>
                <value>
                    <fullName>Practice Report</fullName>
                </value>
                <value>
                    <fullName>Premier</fullName>
                </value>
                <value>
                    <fullName>Regence</fullName>
                </value>
                <value>
                    <fullName>Reimbursement Fees</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reason_for_Contact__c</fullName>
        <label>Reason for Contact</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Product__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Account/Contact Maintenance</fullName>
                </value>
                <value>
                    <fullName>Adjustments</fullName>
                </value>
                <value>
                    <fullName>Authorization</fullName>
                </value>
                <value>
                    <fullName>Benefits - In-Network</fullName>
                </value>
                <value>
                    <fullName>Benefits - Insurance</fullName>
                </value>
                <value>
                    <fullName>Benefits - Out-Of-Network</fullName>
                </value>
                <value>
                    <fullName>Billing/Charges</fullName>
                </value>
                <value>
                    <fullName>Claims</fullName>
                </value>
                <value>
                    <fullName>COB</fullName>
                </value>
                <value>
                    <fullName>Cobra/Enrollment</fullName>
                </value>
                <value>
                    <fullName>Cost</fullName>
                </value>
                <value>
                    <fullName>Dr List</fullName>
                </value>
                <value>
                    <fullName>Eligibility</fullName>
                </value>
                <value>
                    <fullName>Exchange/Refund</fullName>
                </value>
                <value>
                    <fullName>General Inquiry</fullName>
                </value>
                <value>
                    <fullName>ID Card Requests</fullName>
                </value>
                <value>
                    <fullName>Individual Plans</fullName>
                </value>
                <value>
                    <fullName>Level App</fullName>
                </value>
                <value>
                    <fullName>Level Frame - Charging</fullName>
                </value>
                <value>
                    <fullName>Level Frame - Tech</fullName>
                </value>
                <value>
                    <fullName>Level Tech Support</fullName>
                </value>
                <value>
                    <fullName>Level Troubleshooting</fullName>
                </value>
                <value>
                    <fullName>Material - Contacts</fullName>
                </value>
                <value>
                    <fullName>Material - Frames Only</fullName>
                </value>
                <value>
                    <fullName>Material - Glasses</fullName>
                </value>
                <value>
                    <fullName>Material - Lenses Only</fullName>
                </value>
                <value>
                    <fullName>Member ID Inquiry</fullName>
                </value>
                <value>
                    <fullName>Member Info Not Found</fullName>
                </value>
                <value>
                    <fullName>My Account</fullName>
                </value>
                <value>
                    <fullName>No Response</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Resolution_of_Contact__c</fullName>
        <label>Resolution of Contact</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Provided Authorization Services for Customer</fullName>
                </value>
                <value>
                    <fullName>Provided Insurance Benefits Information for Customer</fullName>
                </value>
                <value>
                    <fullName>Provided In-Network Benefits Information for Customer</fullName>
                </value>
                <value>
                    <fullName>Provided Out-Of-Network Benefits Information for Customer</fullName>
                </value>
                <value>
                    <fullName>Provided Eyeconic Billing Information for Customer</fullName>
                </value>
                <value>
                    <fullName>Provided Claim(s) Information for Customer</fullName>
                </value>
                <value>
                    <fullName>Provided Coverage/Claims Coordination of Benefits Information with Customer</fullName>
                </value>
                <value>
                    <fullName>Provided Benefits Information for Customer regarding Cobra or Open Enrollment Coverage</fullName>
                </value>
                <value>
                    <fullName>Provided Dr List for Customer</fullName>
                </value>
                <value>
                    <fullName>Provided Eligibility Information for Customer</fullName>
                </value>
                <value>
                    <fullName>Assisted Customer with ID Card Request</fullName>
                </value>
                <value>
                    <fullName>Provided Individual Plan Information for Customer</fullName>
                </value>
                <value>
                    <fullName>Provided Level Application Information to Customer</fullName>
                </value>
                <value>
                    <fullName>Provided Level Frame Tech Information for Customer</fullName>
                </value>
                <value>
                    <fullName>Provided Level Frame Charging Information for Customer</fullName>
                </value>
                <value>
                    <fullName>Provided Level Tech Support for Customer</fullName>
                </value>
                <value>
                    <fullName>Provided Level Troubleshooting Information for Customer</fullName>
                </value>
                <value>
                    <fullName>Assisted Customer with Contact Lens Material Inquiry</fullName>
                </value>
                <value>
                    <fullName>Assisted Customer with Glasses Material Inquiry</fullName>
                </value>
                <value>
                    <fullName>Assisted Customer with Frames Only Material Inquiry</fullName>
                </value>
                <value>
                    <fullName>Assisted Customer with Spectacle Lenses Only Material Inquiry</fullName>
                </value>
                <value>
                    <fullName>Assisted Customer with Member ID Inquiry</fullName>
                </value>
                <value>
                    <fullName>Provided Member Info to Customer</fullName>
                </value>
                <value>
                    <fullName>Assisted Customer with Eyeconic My Account Issues</fullName>
                </value>
                <value>
                    <fullName>Provided Eyeconic Order Status Information for customer</fullName>
                </value>
                <value>
                    <fullName>Assisted Customer with new Eyeconic Order</fullName>
                </value>
                <value>
                    <fullName>Assisted Customer with Cancellation of their Eyeconic Order</fullName>
                </value>
                <value>
                    <fullName>Assisted Customer with existing Eyeconic Order</fullName>
                </value>
                <value>
                    <fullName>Assisted Customer with Eyeconic Order</fullName>
                </value>
                <value>
                    <fullName>Provided Eyeconic Prescription Information for Customer</fullName>
                </value>
                <value>
                    <fullName>Provided cost of Glasses information for Customer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Customer_Care</fullName>
        <active>true</active>
        <businessProcess>VSP Global</businessProcess>
        <description>Used for VSP Global Customer Care Cases</description>
        <label>Customer Care</label>
    </recordTypes>
    <recordTypes>
        <fullName>Eyeconic</fullName>
        <active>true</active>
        <businessProcess>VSP Global</businessProcess>
        <description>Used to track Eyeconic cases</description>
        <label>Eyeconic</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force/src/objects/Case_Resolution__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Reason_for_Contact__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Reason for Contact</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Resolution_of_Contact__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Resolution of Contact</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Topic__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Topic</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Case Resolution</label>
</CustomObject>

force/src/objects/DVIWebService__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Setting for the DVI Web Service URL and token header</description>
    <label>DVI Web Service</label>
</CustomObject>

force/src/classes/VSPR26_PopulateResolutionContact_Test.cls
///Test Class for VSPR26_PopulateResolutionContact
@isTest
public class VSPR26_PopulateResolutionContact_Test {
    
    @TestSetup
    public static void testNewCase(){
        
        String uniqueUserName = 'standarduser' + DateTime.now().getTime() + '@vsp.com';
        
        // This code runs as the system user
        Profile p = [SELECT Id FROM Profile WHERE Name='VSP Technical User'];
        User u = new User(Alias = 'standt', Email='standarduser@vsp.com',
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                          LocaleSidKey='en_US', ProfileId = p.Id,
                          TimeZoneSidKey='America/Los_Angeles',
                          UserName=uniqueUserName);
        
        System.runAs(u){
            
            test.starttest();
            insert new Case_Resolution__c(Name = 'Level - Claims', Topic__c = 'Level', Reason_for_Contact__c = 'Claims', Resolution_of_Contact__c = 'Provided Claim(s) Information for Customer');
            insert new Case_Resolution__c(Name = 'Level - COB', Topic__c = 'Level', Reason_for_Contact__c = 'COB', Resolution_of_Contact__c = 'Provided Coverage/Claims Coordination of Benefits Information with Customer');
            insert new Case_Resolution__c(Name = 'Level - Cost', Topic__c = 'Level', Reason_for_Contact__c = 'Cost', Resolution_of_Contact__c = 'Provided cost of Glasses information for Customer');    
            insert new Case_Resolution__c(Name = 'Level - Dr List', Topic__c = 'Level', Reason_for_Contact__c = 'Dr List', Resolution_of_Contact__c = 'Provided Dr List for Customer');    
            
            DVIWebService__c dviWeb = new DVIWebService__c(); 
            dviWeb.Name = 'DVI Values';
            insert dviWeb;
            
            
            Id eyeconicRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Eyeconic').getRecordTypeId();
            Id customerCaseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Customer_Care').getRecordTypeId();
            //      List<Case> lstCase = new List<Case>();
            Case custCase = new Case();
            custCase.RecordTypeId = customerCaseRecordTypeId;
            custCase.Subject = 'Test Customer Case';
            custCase.Description = 'Test Customer Description';
            custCase.Type = 'Issue';
            custCase.Product__c = 'Level';
            custCase.Reason_for_Contact__c = 'Claims;COB;Cost';
            custCase.Origin = 'Phone';
            
            //   lstCase.add(custCase);
            
            insert custCase;
            
            test.stoptest();
        }
    }
    public static testmethod void testUpdateCustCase() {
        Case custCase = [SELECT Id from Case WHERE Subject = 'Test Customer Case' AND Type = 'Issue' AND Product__c = 'Level'];
        
        custCase.Reason_for_Contact__c = 'Claims;COB;Cost;Dr List';
        update custCase;
    }
    
}