force/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Contact_Role__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact Role</label>
        <referenceTo>Contact_Role__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User_Role__c</fullName>
        <label>User Role</label>
        <length>125</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force/src/objects/Contact_Role__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Eye Care Professional</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force/src/classes/VSPR3_CaseBL.cls
/**
 * Class Name: VSPR3_CaseBL
 * @author: karl.wilson.l.tan
 * Date: 08.OCT.2013
 * Requirement/Project Name: VSP
 * @description: Handles all Business Logic for the Case object.
 */
 
public class VSPR3_CaseBL{
 
    public void CaseBeforeTriggerMethod(List<Case> newTrigger){ 
 
     Set<ID> setCaseIds = new Set<ID>();

     for(Case cases : newTrigger){
        setCaseIds.add(cases.OwnerId);
     //system.debug('-------------------------------- Case ID : ' + setCaseIds);
    }
    
      
     MAP<ID , User> mapUser = new MAP<ID , User>([Select Id, UserRole.Name from User where id in: setCaseIds]);
     //system.debug('--------------------------------MAP  : ' +mapUser);

     for(Case cases : newTrigger){

            User u = mapUser.get(cases.ownerId);
            //system.debug('--------------------------------Case Owner : ' + cases.ownerId);
            
            if(u != null){
            
                cases.User_Role__c = u.UserRole.Name;
            }
            else if(u == null){
            
                cases.User_Role__c ='';
            }
            

       }
    }
    
        public void cRoleCasesBeforeTriggerMethod(List<Case> newTrigger){ 
 
     Set<ID> setCIds = new Set<ID>();
     for(Case cases : newTrigger){
        if(cases.Contact_Role__c != null)
        setCIds.add(cases.Contact_Role__c);
    }
     


     MAP<ID , Contact_Role__c> mapConRoltoCase = new MAP<ID , Contact_Role__c>([Select Id, Account__c, Contact__c from Contact_Role__c where id in: setCIds]);
     

     for(Case cases : newTrigger)
       {
        if(cases.Contact_Role__c != null)
            {
            Contact_Role__c c = mapConRoltoCase.get(cases.Contact_Role__c);
            
            
            cases.AccountId = c.Account__c;
            cases.ContactId = c.Contact__c;

            
            }
       }
    }

}