force/src/objects/CatTabDefault__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Default setting for tabs in the Quest Landing Page framework</description>
    <fields>
        <fullName>Category_Links__c</fullName>
        <description>URL to article that contains sidebar links for the Category</description>
        <label>Category Links</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Quest Category Tab Defaults</label>
</CustomObject>

force/src/objects/Knowledge__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <page>Knowledge_VFP</page>
            <template>Page</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <fields>
        <fullName>Links__c</fullName>
        <label>Links</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
</CustomObject>

force/src/classes/QuestController2.cls
public class QuestController2{

    public CatTabDefault__c QuestTab {get; set;}
    public list<CatTabDefault__c> catset {get; set;}
    
    
    public String Sidebarlinks  {get; set;}
         //Constructor with no arguments 
    public QuestController2() {
        
        catset = CatTabDefault__c.getAll().values();
        QuestTab = CatTabDefault__c.getInstance('Benefits');           
        //SOQL to search articles filtered by Data-Categories
        
        //SOQL to retrieve data from categoryTabLinkk article Type
        Sidebarlinks= [SELECT Links__c FROM Knowledge__kav 
        WHERE PublishStatus = 'online' AND Language = 'en_US' AND UrlName =: QuestTab.Category_Links__c].Links__c;      
         }         
    
           
    public String getSidebarlinks() {
        return Sidebarlinks;      
    }
    
    
}