force/src/objects/CatTabDefault__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Default setting for tabs in the Quest Landing Page framework</description>
    <fields>
        <fullName>Category_Links__c</fullName>
        <description>URL to article that contains sidebar links for the Category</description>
        <label>Category Links</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Quest Category Tab Defaults</label>
</CustomObject>

src/classes/SubmitTabController.cls
public class SubmitTabController{
   /*
    public CatTabDefault__c SubmitTab {get; set;}    
    public list<CatTabDefault__c> catset {get; set;}
           
    public String links;
    
     //Constructor with no arguments 
    public SubmitTabController() {
        
        catset = CatTabDefault__c.getAll().values();       
        SubmitTab = CatTabDefault__c.getInstance('Submit');
        //SOQL to retrieve data from
        
        //links= [SELECT Links__c FROM Category_Tab_Link__kav WHERE PublishStatus = 'online' AND Language = 'en_US' AND UrlName =: SubmitTab.Category_Links__c].Links__c;
              
         }         
      
       
     public String getSubcatlinks() {
        return links;      
    }
    */
}