force/src/objects/CatTabDefault__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Default setting for tabs in the Quest Landing Page framework</description>
    <fields>
        <fullName>Category_Links__c</fullName>
        <description>URL to article that contains sidebar links for the Category</description>
        <label>Category Links</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Quest Category Tab Defaults</label>
</CustomObject>

force/src/classes/COBTabController.cls
public class COBTabController{
	/*
    public CatTabDefault__c COBTab {get; set;}
    public list<CatTabDefault__c> catset {get; set;}
    
    
    public String links;
    
     //Constructor with no arguments 
    public COBTabController() {
        
        catset = CatTabDefault__c.getAll().values();
        COBTab = CatTabDefault__c.getInstance('COB');
        //SOQL to search articles filtered by Data-Categories
        //SOQL to retrieve data from
        
        //links= [SELECT Links__c FROM Category_Tab_Link__kav WHERE PublishStatus = 'online' AND Language = 'en_US' AND UrlName =: COBTab.Category_Links__c].Links__c;
             
         }         
    
    public String getCOBcatlinks() {
        return links;      
    }
   	*/
}