force/src/objects/CatTabDefault__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Default setting for tabs in the Quest Landing Page framework</description>
    <fields>
        <fullName>Category_Links__c</fullName>
        <description>URL to article that contains sidebar links for the Category</description>
        <label>Category Links</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Quest Category Tab Defaults</label>
</CustomObject>

src/classes/ComplianceTabController.cls
public class ComplianceTabController{
    /*
    public CatTabDefault__c ComplianceTab {get; set;}     
    public list<CatTabDefault__c> catset {get; set;}    
    public String links;  
    //Constructor with no arguments 
    public ComplianceTabController() {
        
        catset = CatTabDefault__c.getAll().values();
        ComplianceTab = CatTabDefault__c.getInstance('Compliance');
              
        //SOQL to retrieve data from
        
        //links= [SELECT Links__c FROM Category_Tab_Link__kav WHERE PublishStatus = 'online' AND Language = 'en_US' AND UrlName =: ComplianceTab.Category_Links__c].Links__c;
           
         }         
      
    
        public String getComcatlinks() {
        return links;      
    }
    */
}