force/src/objects/CatTabDefault__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Default setting for tabs in the Quest Landing Page framework</description>
    <fields>
        <fullName>Category_Links__c</fullName>
        <description>URL to article that contains sidebar links for the Category</description>
        <label>Category Links</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Quest Category Tab Defaults</label>
</CustomObject>

src/objects/Knowledge__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <page>Knowledge_VFP</page>
            <template>Page</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <fields>
        <fullName>Links__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Links</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
</CustomObject>

src/classes/QNewsTabControllerLEX.cls
public class QNewsTabControllerLEX{   

    public CatTabDefault__c QNewsTab{get; set;}     
    public list<CatTabDefault__c> catset {get; set;}
    public String links;    
    
//Constructor with no arguments 
    public QNewsTabControllerLEX() {       
        catset = CatTabDefault__c.getAll().values();            
        QNewsTab = CatTabDefault__c.getInstance('QNews');  
        
        //SOQL to retrieve data from    
        if(QNewsTab.Category_Links__c != null && QNewsTab.Category_Links__c != '') {
        links = [SELECT Links__c FROM knowledge__kav where title ='Sidebar-QNews' AND PublishStatus='OnLine' AND Language='en_US' Limit 1].Links__c;

            //links= [SELECT Links__c FROM Category_Tab_Link__kav WHERE PublishStatus = 'online' AND Language = 'en_US' AND UrlName =: QNewsTab.Category_Links__c].Links__c;            
        }                       
    }                        
    public String getQNewscatlinks() {
        return links;      
    }

}