force/src/objects/CatTabDefault__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Default setting for tabs in the Quest Landing Page framework</description>
    <fields>
        <fullName>Category_Links__c</fullName>
        <description>URL to article that contains sidebar links for the Category</description>
        <label>Category Links</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Quest Category Tab Defaults</label>
</CustomObject>

src/classes/DrInfoTabController.cls
public class DrInfoTabController{
   	/*
    public CatTabDefault__c Dr_InfoTab {get; set;}    
    public list<CatTabDefault__c> catset {get; set;}
    public String links;
    
    //Constructor with no arguments 
    public DrInfoTabController() {
       catset = CatTabDefault__c.getAll().values();
       Dr_InfoTab = CatTabDefault__c.getInstance('Dr Info');
       //SOQL to search articles filtered by Data-Categories      
       //links= [SELECT Links__c FROM Category_Tab_Link__kav WHERE PublishStatus = 'online' AND Language = 'en_US' AND UrlName =: Dr_InfoTab.Category_Links__c].Links__c;           
         }                
    public String getDrinfocatlinks() {
        return links;      
    }    
	*/
}