force/src/objects/CatTabDefault__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Default setting for tabs in the Quest Landing Page framework</description>
    <label>Quest Category Tab Defaults</label>
</CustomObject>

src/objects/Knowledge__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <page>Knowledge_VFP</page>
            <template>Page</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <fields>
        <fullName>Links__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Links</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Topic_Links__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Topic Links</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
</CustomObject>

src/classes/BenefitsTabController.cls
public class BenefitsTabController{
	/*
    public CatTabDefault__c BenefitsTab {get; set;}   
    public list<CatTabDefault__c> catset {get; set;}
    public String defaultlink {get; set;}   
    public String sidebarlink {get; set;}    
    public String links;   
         //Constructor with no arguments 
    public BenefitsTabController() {
        
        catset = CatTabDefault__c.getAll().values();
        
        //BenefitsTab = CatTabDefault__c.getInstance('Benefits');       
        
        //SOQL to search articles filtered by Data-Categories
        
        //SOQL to retrieve data from
        defaultlink= [SELECT Topic_Links__c FROM Knowledge__kav WHERE PublishStatus = 'online' AND Language = 'en_US' AND Title ='Benefits'].Topic_Links__c;
        sidebarlink= [SELECT Links__c FROM Knowledge__kav WHERE PublishStatus = 'online' AND Language = 'en_US' AND Title ='Sidebar Benefits'].Links__c;
        
         }         
          
    public String getBenefitscatlinks() {
        return links;      
    }
    
    public String getdefaultlink() {
        return defaultlink;      
    }
    
    public String getsidebarlink() {
        return sidebarlink;      
    }
	*/
}