force/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <formula>HYPERLINK(&quot;/&quot; + Id, &quot;Contact Record&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Record</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <label>Client</label>
    </recordTypes>
    <recordTypes>
        <fullName>Consumer</fullName>
        <active>true</active>
        <label>Consumer</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force/src/objects/Contact_Role__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Eye Care Professional</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force/src/objects/New_Contact_and_ContactRole__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>New Contact and Contact Role</label>
</CustomObject>

force/src/classes/VSPR5_ContactExtensionController.cls
public class VSPR5_ContactExtensionController
{
    public Contact_Role__c objCrole {get;set;}
    public Contact objcontact {get;set;}
    public String contactid{get;set;}
    public String acc{get;set;}
    public Boolean renderFlagVisionCareDetails {get; set;}
    
    public String clientRecordTypeId{get;set;}
    public String consumerRecordTypeId{get;set;}
    public String ECPRecordTypeId{get;set;}
    

    public VSPR5_ContactExtensionController(ApexPages.StandardController controller) {
         renderFlagVisionCareDetails = false;
         objCrole = new Contact_Role__c();
         this.objcontact = new Contact();
         this.objcontact = (Contact)controller.getrecord();  
         String AccountId = ApexPages.currentPage().getParameters().get('accid'); 
         objcontact.AccountId = (Id)AccountId;   
         clientRecordTypeId = New_Contact_and_ContactRole__c.getInstance('Client').Id__c;
         consumerRecordTypeId = New_Contact_and_ContactRole__c.getInstance('Consumer').Id__c;
         ECPRecordTypeId = New_Contact_and_ContactRole__c.getInstance('ECP').Id__c;
         
         Id profileId = userinfo.getProfileId();
         String profileName = [Select Id, Name from Profile where Id = :profileId].Name;
         Id userId = userInfo.getUserId();
         
         List<PermissionSetAssignment> listPSA = [SELECT id, PermissionSetId
                                        FROM PermissionSetAssignment
                                        WHERE AssigneeId = :userId];
        Set<Id> ids = new set<Id>();
        for (PermissionSetAssignment PSA : listPSA) {
            ids.add(PSA.PermissionSetId);
        }

        List<PermissionSet> listPS = [Select name from PermissionSet where id in :ids];
        System.debug('#### listPS: ' + listPS);
        boolean permissionSetFound = false;
        for (PermissionSet PS: listPS) {
            if (PS.Name == 'Credentialing_Data_Manager')                permissionSetFound = true;
        }
        
        System.debug('#### permissionSetFound ' + permissionSetFound);
         
        if (profileName == 'VSP Network Recruitment User' || profileName == 'VSP Network Recruitment Management User' || profileName == 'System Administrator' || permissionSetFound == true)
            renderFlagVisionCareDetails = true;
    }

          
   
    public PageReference save()
    {    
       try
       {          
          Insert objcontact;
          
          objCrole.Contact__c = objcontact.Id;
          objCrole.Account__c = objcontact.AccountId;
          
          if((objcontact.RecordTypeId != clientRecordTypeId ) && (objcontact.RecordTypeId != consumerRecordTypeId)){    
              Insert objCrole; 
          }            
          
          PageReference pageRef = new pageReference('/apex/VSPR5_ContactRenameTab?id=' + objcontact.Id 
                                                      + '&salutation=' + objcontact.Salutation
                                                      + '&fname=' + objcontact.FirstName
                                                      + '&lname=' + objcontact.LastName);
          pageRef.setRedirect(true);
          return pageRef; 
       }
           
      catch(DmlException ex){
          ApexPages.addmessages(ex);
          return null;
       }
    }
   public PageReference cancel(){
       PageReference pageRef = new pageReference('/003/o');
       pageRef.setRedirect(true);
       return pageRef;        
   }
        
        
   public PageReference doSaveAndNew(){
    try
    {    
        Insert objcontact;
        
        objCrole.Contact__c = objcontact.Id;
        objCrole.Account__c = objcontact.AccountId;
        
        if((objcontact.RecordTypeId != clientRecordTypeId ) && (objcontact.RecordTypeId != consumerRecordTypeId)){   
              Insert objCrole; 
          }
           
        
        PageReference pageRef = new pageReference('/apex/VSPR5_ContactVFP?accid='+objcontact.AccountId+'&retURL=%2F003K000000pBTKt&save_newsfdc.override=1');
        pageRef.setRedirect(true);       
        return pageRef;
   }catch(DmlException ex){
      ApexPages.addmessages(ex);
      return null;
   }
   /*
    //Contact and Contact Role values are reset and 'Common Account Name' field is prepopulated with AccountId upon clicking save&new button 
    Id acctId = objcontact.AccountId;
    objcontact = new Contact();
    objcontact.AccountId = acctId ;    
    objCrole = new Contact_Role__c();
    objCrole.Start_Date__c = date.today();
    return null;
   */
   }
     
  }