force/src/objects/Contact_Role__c.object
<CustomObject>
    <fields>
        <fullName>Fee_Code__c</fullName>
        <label>Fee Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force/src/objects/General_Table__c.object
<CustomObject>
    <label>General Table</label>
    <nameField>
        <label>Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>General Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force/src/objects/Network_Relationship__c.object
<CustomObject>
    <description>Custom object to track Payment Relationships between doctors and offices.</description>
    <fields>
        <fullName>Claims_Priced__c</fullName>
        <label>Claims Priced</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Y</fullName>
                </value>
                <value>
                    <fullName>N</fullName>
                    <default>true</default>
                    <label>N</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact_Role__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact Role</label>
        <referenceTo>Contact_Role__c</referenceTo>
        <relationshipName>Payment_Relationships</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fee_Code__c</fullName>
        <defaultValue>&quot;NF&quot;</defaultValue>
        <label>Fee Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup relationship field from Network Relationship to General Table object</description>
        <label>Program ID</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>General_Table__c.Table__c</field>
                <operation>equals</operation>
                <value>PRSP</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>General_Table__c</referenceTo>
        <relationshipLabel>Network Relationships</relationshipLabel>
        <relationshipName>Network_Relationships</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Network Relationship</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Network Relationship Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Network Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force/src/classes/VSP_NetworkRelationshipTriggerHandler.cls
/*
* Updates Network relationship fee code
*/
public class VSP_NetworkRelationshipTriggerHandler {
//Contact Role is required on the Network Relationship object. SFDC-9054
/*
    public static boolean poulateFreeCodeFromCntRole_recursion = true;
    public static void poulateFreeCodeFromCntRole(list<Network_Relationship__c> lstNR) {
        
        if(poulateFreeCodeFromCntRole_recursion){
        poulateFreeCodeFromCntRole_recursion = false;

            map<String,Contact_Role__c> mpContactRole = new map<String,Contact_Role__c>(); 

            for(Network_Relationship__c nr : lstNR) {
                if(nr.Contact_Role__c == NULL ) {
                    mpContactRole.put(nr.Contact_Role__c,null);
                }
            }
            if(mpContactRole.isEmpty()) {
                return;
            }

            mpContactRole = new map<String,Contact_Role__c>([SELECT id,Fee_Code__c FROM Contact_Role__c WHERE id IN :mpContactRole.keySet()]);

            map<Id,General_Table__c> mpPrograms = new map<Id,General_Table__c>([SELECT Id FROM General_Table__c WHERE Name = 'VSP' OR Name = 'CHOIC']); 

            Set<Network_Relationship__c> nrSet = new Set<Network_Relationship__c>();
            for(Network_Relationship__c nr : lstNR) {
                if(nr.Contact_Role__c == NULL || !mpPrograms.containsKey(nr.Program_ID__c) || nr.Claims_Priced__c != 'N') {
                  continue;
                }
                Network_Relationship__c x = new Network_Relationship__c(Id = nr.Id);
                nr.Fee_Code__c = mpContactRole.get(nr.Contact_Role__c).Fee_Code__c;
                nrSet.add(x);
            }
            
            List<Network_Relationship__c> nrList = new List<Network_Relationship__c>(nrSet);
            if(!nrList.isEmpty()){
                update nrList;
            }
        }
    }  */
}