force/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>High_Profile_Count__c</fullName>
        <formula>IF( High_Profile__c , 1, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>High Profile Count</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>VSP_Network_Provider_Count__c</fullName>
        <formula>IF(Vision_Care_Network_Provider__c, 1, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>VSP Network Provider Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force/src/classes/VSPR1_ContactDML.cls
/**
 * Class Name: VSPR1_ContactDML
 * @author: Jinky M.N. Salvador
 * Date: 27.MAY.2013
 * Requirement/Project Name: VSP
 * @description: Handles all DML for the Contact object.
 */

public class VSPR1_ContactDML { 

	public static List<Contact> getContactDetails(Set<Id> ids){
		
		List<Contact> contacts = [Select AccountId,VSP_Network_Provider_Count__c,High_Profile_Count__c from Contact where AccountId IN: ids];
		return contacts;		
	} 
}