force/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Bypass_VC_Validation_Rules__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass VC Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vision_Care_Doctor_Exception__c</fullName>
        <label>Vision Care Doctor Exception</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ABO - Not ABO Certified</fullName>
                </value>
                <value>
                    <fullName>AWP - Willing Provider State</fullName>
                </value>
                <value>
                    <fullName>CAD1 - Consent Agreement - NM</fullName>
                </value>
                <value>
                    <fullName>CAD2 - Consent Agreement - A&amp;H</fullName>
                </value>
                <value>
                    <fullName>CAD3 - Consent Agreement - SIU</fullName>
                </value>
                <value>
                    <fullName>CAD4 - Consent Agreement - promo</fullName>
                </value>
                <value>
                    <fullName>CED1 - Legal Approved - 2002</fullName>
                </value>
                <value>
                    <fullName>CED2 - Legal Approved - 2006</fullName>
                </value>
                <value>
                    <fullName>CED3 - Legal Approved - 2009</fullName>
                </value>
                <value>
                    <fullName>DEC - Covering for Deceased Owner Dr.</fullName>
                </value>
                <value>
                    <fullName>GAP - GAP eClaim Capability</fullName>
                </value>
                <value>
                    <fullName>GRF - Grandfather</fullName>
                </value>
                <value>
                    <fullName>LEV - Maternity Leave/Sabbatical</fullName>
                </value>
                <value>
                    <fullName>INS - Insufficient Insurance Coverage</fullName>
                </value>
                <value>
                    <fullName>LFU - Not Fully DPA/TPA Licensed</fullName>
                </value>
                <value>
                    <fullName>TFH - Alleged contract violation/investigation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force/src/objects/General_Table__c.object
<CustomObject>
    <label>General Table</label>
    <nameField>
        <label>Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>General Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force/src/objects/Network_Relationship__c.object
<CustomObject>
    <description>Custom object to track Payment Relationships between doctors and offices.</description>
    <fields>
        <fullName>Bypass_VC_Validation_Rules__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass VC Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Exception_Reason_Calculation__c</fullName>
        <description>Calculates the Vision Care Exception Reasons from Practice Account, Business Account, Contact, and Contact Role and displays the exception if the Program ID = VSP</description>
        <formula>IF( Program_ID__r.Name  = &apos;VSP&apos; &amp;&amp; NOT(ISBLANK( TEXT(Account_Name__r.Parent.Vision_Care_Practice_Exception__c ))), TEXT(Account_Name__r.Parent.Vision_Care_Practice_Exception__c), 

IF(Program_ID__r.Name = &apos;VSP&apos; &amp;&amp; NOT(ISBLANK(TEXT( Account_Name__r.Vision_Care_Location_Exception__c ))), TEXT( Account_Name__r.Vision_Care_Location_Exception__c),

IF(Program_ID__r.Name = &apos;VSP&apos; &amp;&amp; NOT(ISBLANK(TEXT( Provider_Name__r.Vision_Care_Doctor_Exception__c ))), TEXT( Provider_Name__r.Vision_Care_Doctor_Exception__c), 

IF(Program_ID__r.Name = &apos;VSP&apos; &amp;&amp; NOT(ISBLANK(TEXT( Contact_Role__r.Vision_Care_Contact_Role_Exception__c ))), TEXT( Contact_Role__r.Vision_Care_Contact_Role_Exception__c), &quot;&quot;)
)
)
)</formula>
        <label>Exception Reason Calculation</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exception_Reason__c</fullName>
        <label>Exception Reason</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program_End_Date__c</fullName>
        <label>Program End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Program_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup relationship field from Network Relationship to General Table object</description>
        <label>Program ID</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>General_Table__c.Table__c</field>
                <operation>equals</operation>
                <value>PRSP</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>General_Table__c</referenceTo>
        <relationshipLabel>Network Relationships</relationshipLabel>
        <relationshipName>Network_Relationships</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Provider Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Network Relationships</relationshipLabel>
        <relationshipName>Network_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Network Relationship</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Network Relationship Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Network Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force/src/objects/Skip_Trigger__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Skip_Triggers__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Skip all PROS Decommission-related Triggers on Account, Contact, Contact Role, and Network Relationship objects.</description>
        <label>Skip Triggers</label>
        <type>Checkbox</type>
    </fields>
    <label>Skip Trigger</label>
</CustomObject>

force/src/classes/VSPR19b_AddContactExctoRelatedNetRels.cls
/**
* Class Name:  VSPR19b_AddContactExctoRelatedNetRels
* Date: March 27, 2018
* Project: PROS Decommission
* @author: Katherine
* @description: When the Vision Care Doctor Exception changes on the Contact record, populate the Exception_Reason__c field 
                on the associated Active or Future VSP Network Relationship records. 
*/

public with sharing class VSPR19b_AddContactExctoRelatedNetRels {
    public static boolean VSPR19b_AddContactExctoRelatedNetRels_recursion = true;
    public void VSPR19b_AddContactExctoRelatedNetRels(List<Contact> newTrigger, Map<Id,Contact> oldMap, Boolean isTrgUpdate){
        if(VSPR19b_AddContactExctoRelatedNetRels_recursion){
            VSPR19b_AddContactExctoRelatedNetRels_recursion = false;
            system.debug('***********entered VSPR19b_AddContactExctoRelatedNetRels ********');
            Boolean isUpdate = false;
            Set<id> conIDs = new set<id>();
            List<Network_Relationship__c> netRelList = new List<Network_Relationship__c>();
            String conRecordTypeId=[SELECT Id from RecordType WHERE sObjectType = 'Contact' and Name = 'Eye Care Professional'].Id;
            Skip_Trigger__c skip = Skip_Trigger__c.getInstance();
            if(skip.Skip_Triggers__c){
                return;
            }
            for(Contact con : NewTrigger){
                if(con.RecordTypeId == conRecordTypeId){
                    conIDs.add(con.Id);
                }
                if(isTrgUpdate){
                    Contact oldCon = oldMap.get(con.Id);
                    
                    system.debug('++++++++++++oldCon.Vision_Care_Doctor_Exception__c++++++++++++++++++++++++++' +oldCon.Vision_Care_Doctor_Exception__c);
                    system.debug('++++++++++++con.Vision_Care_Doctor_Exception__c++++++++++++++++++++++++++' +con.Vision_Care_Doctor_Exception__c);
                     
                    if(oldCon.Vision_Care_Doctor_Exception__c != con.Vision_Care_Doctor_Exception__c){
                        isUpdate=true;
                    }
                }    
            }
            
            system.debug('+++++++++++isUpdate++++++++++ ' +isUpdate);
            system.debug('+++++++++++conIDs++++++++++++ ' +conIDs);
            system.debug('+++++++++++conIDsSize++++++++ ' +conIDs.size());
            
            if(conIDs.size()>0 && isUpdate == true){
                list<Network_Relationship__c> conNetRelList = [SELECT Id, Exception_Reason__c, Exception_Reason_Calculation__c 
                                                              FROM Network_Relationship__c WHERE Provider_Name__c in : conIDs 
                                                               AND Program_ID__r.Name = 'VSP' AND (Program_End_Date__c >=TODAY OR Program_End_Date__c = NULL)];
                
                system.debug('+++++++++++++conNetRelList+++++++++++ '+conNetRelList);
                
                if(conNetRelList.size()>0){
                    for(Network_Relationship__c nr : conNetRelList){
                        nr.Exception_Reason__c = nr.Exception_Reason_Calculation__c;
                        nr.Bypass_VC_Validation_Rules__c = true;
                        netRelList.add(nr);
                 
                    }
                }
                
            } 
            
            if(netRelList.size()>0){
                update netRelList;
            }
            system.debug('************exiting VSPR19b_AddContactExctoRelatedNetRels***********');
                        
        }
    }
}