force/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <formula>HYPERLINK(&quot;/&quot; + Id, &quot;Contact Record&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Record</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force/src/objects/Contact_Role__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Eye Care Professional</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DS_Conversation_Count__c</fullName>
        <description>Tracks the number of conversations conducted through DialSource.</description>
        <label>DS Conversation Count Last 30 Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DS_Pending_Task_Date__c</fullName>
        <label>DS Pending Task Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DS_VM_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Tracks the number of voicemails left through DialSource in the last 30 Days</description>
        <inlineHelpText>Tracks the number of voicemails left through DialSource in the last 30 Days</inlineHelpText>
        <label>DS VM Count Last 30 Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accounting</fullName>
                </value>
                <value>
                    <fullName>Board Member/ Officer</fullName>
                </value>
                <value>
                    <fullName>Dean</fullName>
                </value>
                <value>
                    <fullName>Doctor-Employee</fullName>
                </value>
                <value>
                    <fullName>Doctor-Owner</fullName>
                </value>
                <value>
                    <fullName>Doctor-Unspecified</fullName>
                </value>
                <value>
                    <fullName>Group Administrator</fullName>
                </value>
                <value>
                    <fullName>Lab Technician</fullName>
                </value>
                <value>
                    <fullName>Member</fullName>
                </value>
                <value>
                    <fullName>Office Administration</fullName>
                </value>
                <value>
                    <fullName>Office Manager</fullName>
                </value>
                <value>
                    <fullName>Optical Buyer</fullName>
                </value>
                <value>
                    <fullName>Optical Manager</fullName>
                </value>
                <value>
                    <fullName>Optician</fullName>
                </value>
                <value>
                    <fullName>Optician-Owner</fullName>
                </value>
                <value>
                    <fullName>Owner</fullName>
                </value>
                <value>
                    <fullName>Student</fullName>
                </value>
                <value>
                    <fullName>Unspecified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force/src/classes/DSUpdateVMConvoCountV3_Test.cls
@isTest
private class DSUpdateVMConvoCountV3_Test 
{	
	@isTest 
	static void testAccuracy() {
		Account testAcct = new Account(
            Name = 'Test Account'
        ); 
            
        insert testAcct; 
        
        Contact testContact = new Contact(
        	LastName = 'Test',
            Account = testAcct
        );
        
        insert testContact; 
        
        Contact_Role__c testContactRole = new Contact_Role__c (
            Account__c = testAcct.Id, 
            Contact__c = testContact.Id, 
            Type__c	= 'Student',
            Start_Date__c = Date.newInstance(2016, 12, 9),
            DS_Pending_Task_Date__c = Date.newInstance(2016, 12, 10)
        );
        
        insert testContactRole; 
        
        //Insert a logged call
        Task loggedCall = new Task(
        	Subject = 'Call',
            Type__c = 'Outbound Call',
            Status = 'Completed',
            WhatId = testContactRole.Id,
            DialSource__Call_Disposition_DS__c = 'Voicemail'
        );
        
        insert loggedCall;

        //Insert a logged call
        Task loggedCall2 = new Task(
        	Subject = 'Call',
            Type__c = 'Outbound Call',
            Status = 'Completed',
            WhatId = testContactRole.Id,
            DialSource__Call_Disposition_DS__c = 'Convo'
        );
        
        insert loggedCall2;

        //Start test
        Test.startTest();
        DSUpdateVMConvoCountV3 batchJob = new DSUpdateVMConvoCountV3();
        database.executebatch(batchJob, 200);
        Test.stopTest();

        //Query for the inserted Contact Role
        Contact_Role__c updatedContactRole = [SELECT Id, DS_Conversation_Count__c, DS_VM_Count__c FROM Contact_Role__c WHERE Id = :testContactRole.Id LIMIT 1]; 

        System.assertEquals(1, updatedContactRole.DS_Conversation_Count__c, 'The Conversation Count for the last 30 days is incorrect.');
        System.assertEquals(1, updatedContactRole.DS_VM_Count__c, 'The Voicemail Count for the last 30 days is incorrect.');
	}
	
}