force/src/objects/DVIWebService__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Setting for the DVI Web Service URL and token header</description>
    <fields>
        <fullName>DVI_Token_Header__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>DVI Token Header</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DVI_Web_Service__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>DVI Web Service</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DVI Web Service</label>
</CustomObject>

force/src/classes/TestPPPCalculator.cls
@isTest
public class TestPPPCalculator {
    
    private static testmethod void TestCopyToCase()
    {
        DVIWebService__c dviCustSetting = new DVIWebService__c();
        dviCustSetting.name = 'DVI Values';
        dviCustSetting.DVI_Web_Service__c = 'webserviceURL'; 
        dviCustSetting.DVI_Token_Header__c = 'tokenheader';
        insert dviCustSetting;
        
		case caseobj = new case(); 
       	Id rtId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Vision Benefits').getRecordTypeId();
       	caseobj.recordtypeId = rtId;
       	insert caseobj;  

       	String result = PPPCalcController.getcopytocase('2', '2', '200', caseobj.Id);
		System.assertEquals('Success', result);        
    }
}