force/src/objects/Global_Rewards_Group__c.object
<CustomObject>
    <description>Parent object in a relationship that groups multiple Business/Practice Accounts under one Global Rewards Program (child object is Global Rewards Group Relationship)</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF( OR( Start_Date__c = TODAY() , AND( Start_Date__c &lt; TODAY() , OR( End_Date__c &gt;= TODAY() , ISBLANK( End_Date__c ) ) ) ) , &quot;Active&quot;, &apos;Inactive&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Global Rewards Group</label>
    <nameField>
        <label>Global Rewards Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Global Rewards Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force/src/objects/Global_Rewards_Group_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>Date the child record was ended its relationship with the Parent Roll up account.</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Global_Rewards_Group__c</fullName>
        <label>Global Rewards Group</label>
        <referenceTo>Global_Rewards_Group__c</referenceTo>
        <relationshipLabel>Global Rewards Group Relationships</relationshipLabel>
        <relationshipName>Global_Rewards_Group</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Date the child record was added to the Parent Roll up account.</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF((Start_Date__c &lt;= TODAY() &amp;&amp; (ISBLANK(End_Date__c) ||  End_Date__c &gt;= TODAY())), &apos;Active&apos;, 
IF((Start_Date__c &gt; Today()), &apos;Future&apos;, &apos;Inactive&apos;))</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Global Rewards Group Relationship</label>
    <nameField>
        <displayFormat>PREMIER-{0000}</displayFormat>
        <label>Global Rewards Group Relationship ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Global Rewards Group Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force/src/classes/VSPR31_Update_GRG_End_Date.cls
public class VSPR31_Update_GRG_End_Date {
    
    public static boolean VSPR31_Update_GRG_End_Date_recursion = true;
    public void VSPR31_Update_GRG_End_Date(List<Global_Rewards_Group_Relationship__c> newTrigger,Map<Id,Global_Rewards_Group_Relationship__c> oldRecs){
        
        if(VSPR31_Update_GRG_End_Date_recursion){
            VSPR31_Update_GRG_End_Date_recursion = false;
            
            system.debug('***** entered VSPR31_Update_GRG_End_Date ***** ');
            Set<id> grgIdSet = new Set<Id>();

            for(Global_Rewards_Group_Relationship__c grgR: newTrigger){
                
                if(oldRecs !=null){
                    system.debug('GRG Record Type' + grgR.Global_Rewards_Group__r.RecordType.Name );
                    if(grgR.End_Date__c != oldRecs.get(grgR.Id).End_Date__c && grgR.Start_Date__c != Null){
                        grgIdSet.add(grgR.Global_Rewards_Group__c);
                    }
                }
                else{
                    if(grgR.Start_Date__c != Null){
                        grgIdSet.add(grgR.Global_Rewards_Group__c);
                    }
                }
            }
            
            
            if(!grgIdSet.isEmpty()){
                
                List<Global_Rewards_Group__c> grgToUpd = new List<Global_Rewards_Group__c>();
                
                List<Global_Rewards_Group__c> grgLst = [SELECT Id, Status__c, End_Date__c,
                                                        (SELECT End_Date__c FROM Global_Rewards_Group__r ORDER BY End_Date__c DESC NULLS FIRST LIMIT 1)
                                                        FROM Global_Rewards_Group__c 
                                                        WHERE Id IN :grgIdSet AND RecordType.Name != 'Tax ID Rollup'];
                
                
                for(Global_Rewards_Group__c grg :grgLst){
                    for(Global_Rewards_Group_Relationship__c grgR :grg.Global_Rewards_Group__r){
						grg.End_Date__c = grgR.End_Date__c;                        
                        grgToUpd.add(grg);
                        break;
                    }
                }
                
                system.debug('grgToUpd ' + grgToUpd);
                if(!grgToUpd.isEmpty()){
                    List<String> exception_List = new List<String>();
                    Database.SaveResult[] SaveResultList = Database.update(grgToUpd,false); 
                    
                    for(integer i =0; i<SaveResultList.size();i++){
                        String msg='';
                        If(!SaveResultList[i].isSuccess()){
                            
                            msg += 'Group Reward Group Record Id: ' + grgToUpd.get(i).id + '\n'+'Error: "';        
                            for(Database.Error err: SaveResultList[i].getErrors()){  
                                msg += err.getmessage()+'"\n\n';
                            } 
                        }
                        if(msg!= '')
                            exception_List.add(msg);
                    } 
                    
                }
            }
        }
    }
}