force/src/objects/MPM4_BASE__Milestone1_Project__c.object
<CustomObject>
    <description>Passage Technology - Milestones PM+ Free Edition - A project can have many milestones.</description>
    <fields>
        <fullName>MPM4_BASE__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force/src/objects/MPM4_BASE__Milestone1_Task__c.object
<CustomObject>
    <description>Passage Technology - Milestones PM+ Free Edition - An activity that has hours, budget, and is assigned to a User.</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MPM4_BASE__ProjectId__c</fullName>
        <formula>MPM4_BASE__Project_Milestone__r.MPM4_BASE__Project__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ProjectId</label>
        <type>Text</type>
    </fields>
    <label>Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force/src/classes/MPM_Plus_Task_Customization.cls
public class MPM_Plus_Task_Customization {
    
    public static void pullAccountToTask(List<MPM4_BASE__Milestone1_Task__c> triggeredTasks) {
        Id projectId = triggeredTasks[0].MPM4_BASE__ProjectId__c;
        
        MPM4_BASE__Milestone1_Project__c accountId = [SELECT MPM4_BASE__Account__c FROM MPM4_BASE__Milestone1_Project__c WHERE Id = :projectId LIMIT 1][0];
        
        for(MPM4_BASE__Milestone1_Task__c triggeredTask : triggeredTasks) {
            triggeredTask.Account_Name__c = accountId.MPM4_BASE__Account__c;
        }
        
    }
    
    public static void pullAccountToTaskFromProjectAccountAdded(List<MPM4_BASE__Milestone1_Project__c> triggeredProjects) {
        Id projectId = triggeredProjects[0].Id;
        
        String truncatedProjectId = String.valueOf(projectId).substring(0, 15);
        system.debug(truncatedProjectId);
        List<MPM4_BASE__Milestone1_Task__c> tasksToUpdate = [SELECT Id, Account_Name__c FROM MPM4_BASE__Milestone1_Task__c WHERE MPM4_BASE__ProjectId__c = :truncatedProjectId];
        
        for(MPM4_BASE__Milestone1_Task__c taskToUpdate : tasksToUpdate) {
            taskToUpdate.Account_Name__c = triggeredProjects[0].MPM4_BASE__Account__c;
        }
        
        upsert tasksToUpdate;
    }
}