force/src/objects/Network_Relationship__c.object
<CustomObject>
    <description>Custom object to track Payment Relationships between doctors and offices.</description>
    <fields>
        <fullName>Claims_Priced__c</fullName>
        <label>Claims Priced</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Y</fullName>
                </value>
                <value>
                    <fullName>N</fullName>
                    <default>true</default>
                    <label>N</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Network Relationship</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Network Relationship Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Network Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force/src/objects/Skip_Trigger__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Allow_Network_Relationships_Delete__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allows user to bypass the restriction of being able to delete a Network Relationship Record when Claims Priced = Y</description>
        <inlineHelpText>Allows user to bypass the restriction of being able to delete a Network Relationship Record when Claims Priced = Y</inlineHelpText>
        <label>Allow Network Relationships Delete</label>
        <type>Checkbox</type>
    </fields>
    <label>Skip Trigger</label>
</CustomObject>

force/src/classes/VSPR25b_ValidateClaimsPriced.cls
public class VSPR25b_ValidateClaimsPriced {
    
    //Restrict users from deleting a Network Relationship if Claims Priced = Y
    public static boolean validateClaimsPriced_recursion = true;
    public void validateClaimsPriced(List<Network_Relationship__c> lstNetRels){
        
        if (validateClaimsPriced_recursion){
            validateClaimsPriced_recursion = false;
            
            system.debug('***** entered validateClaimsPriced ***** ');
            Skip_Trigger__c skip = Skip_Trigger__c.getInstance();
            if(skip.Allow_Network_Relationships_Delete__c) { 
                return; 
            }
            
            for(Network_Relationship__c nr : lstNetRels) {
                if(nr.Claims_Priced__c == 'Y'){
                    nr.addError('A claim has been priced against this Network Relationship. It cannot be deleted.');
                    return;
                }
            }
        }
    }
    
}