force/src/objects/Premier_Tier__c.object
<CustomObject>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <description>A criteria in Premier Admin Tiering so that I differentiate tiers by contract.</description>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Affiliate</fullName>
                </value>
                <value>
                    <fullName>AOP</fullName>
                </value>
                <value>
                    <fullName>CAT2</fullName>
                </value>
                <value>
                    <fullName>Conflict</fullName>
                </value>
                <value>
                    <fullName>GAP</fullName>
                </value>
                <value>
                    <fullName>Independent</fullName>
                </value>
                <value>
                    <fullName>LVC</fullName>
                </value>
                <value>
                    <fullName>Near Site</fullName>
                </value>
                <value>
                    <fullName>Net Dev Excluded</fullName>
                </value>
                <value>
                    <fullName>Net Dev Purchasing Requirement</fullName>
                </value>
                <value>
                    <fullName>Not Supported</fullName>
                </value>
                <value>
                    <fullName>Onsite</fullName>
                </value>
                <value>
                    <fullName>Pearle Vision CO</fullName>
                </value>
                <value>
                    <fullName>Pearle Vision LO</fullName>
                </value>
                <value>
                    <fullName>Pop Up</fullName>
                </value>
                <value>
                    <fullName>Rollup</fullName>
                </value>
                <value>
                    <fullName>School</fullName>
                </value>
                <value>
                    <fullName>VSP Retail</fullName>
                </value>
                <value>
                    <fullName>VSP Ventures</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <inlineHelpText>Blank Date = No end date.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hierarchy_Action__c</fullName>
        <inlineHelpText>The selection of &quot;&lt;&quot; below or &quot;Top Tier&quot;, will determine the hierarchy location of where the new or edited tier needs to go in the list of existing tiers.</inlineHelpText>
        <label>Hierarchy Action</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>&lt;</fullName>
                </value>
                <value>
                    <fullName>Top_Tier</fullName>
                    <label>Top Tier</label>
                </value>
                <value>
                    <fullName>&gt;</fullName>
                    <isActive>false</isActive>
                    <label>&gt;</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Hierarchy_Selection__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If Hierarchy Action = Top Tier, Hierarchy Selection must be blank.</inlineHelpText>
        <label>Hierarchy Selection</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>The selected Hierarchy Selection Tier has a status of Inactive.</errorMessage>
            <filterItems>
                <field>Premier_Tier__c.Status__c</field>
                <operation>notEqual</operation>
                <value>Inactive</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>System Administrator, VSP Technical User</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Premier_Tier__c</referenceTo>
        <relationshipLabel>Premier Tiers</relationshipLabel>
        <relationshipName>Tiers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Future</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Premier Tier</label>
    <nameField>
        <label>Tier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Premier Tiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force/src/classes/VSP_Premier_Status_Hierarchy_Test.cls
@isTest
public class VSP_Premier_Status_Hierarchy_Test {
    
    @TestSetup
    static void testData(){
        
        Premier_Tier__c FirstT = new Premier_Tier__c();
        FirstT.Name = 'First';
        FirstT.Description__c = 'First Description';
        FirstT.Effective_Date__c = system.today();
        FirstT.Hierarchy_Action__c = 'Top_Tier';
        FirstT.Status__c = 'Active';
        FirstT.Contract_Type__c = 'Contract Top Tier Test1';
        
        insert FirstT;
        
        Premier_Tier__c SecondT = new Premier_Tier__c();
        SecondT.Name = 'Second';
        SecondT.Description__c = 'Second Description';
        SecondT.Effective_Date__c = system.today();
        SecondT.Hierarchy_Action__c = '<';
        SecondT.Hierarchy_Selection__c = FirstT.Id;
        SecondT.Status__c = 'Active';
        SecondT.Contract_Type__c = 'Contract 2';
        
        insert SecondT;
        
        Premier_Tier__c ThirdT = new Premier_Tier__c();  
        ThirdT.Name = 'Third';
        ThirdT.Description__c = 'Third Description';
        ThirdT.Effective_Date__c = system.today() - 2;
        ThirdT.End_Date__c = system.today() + 3;
        ThirdT.Hierarchy_Action__c = '<';
        ThirdT.Hierarchy_Selection__c = SecondT.Id;
        ThirdT.Status__c = 'Active';
        ThirdT.Contract_Type__c = 'Contract 3';
        
        insert ThirdT;
    }
    
    static testmethod void updateRecords(){    
        //  Premier_Tier__c second = [Select Id FROM Premier_Tier__c WHERE Name = 'Second'];      
        Premier_Tier__c third = [Select Id, Status__c FROM Premier_Tier__c WHERE Name = 'Third']; 
        //   second.Effective_Date__c = Date.today() - 1;
        third.End_Date__c = system.today() - 1;
        Test.startTest();
        //   update second;
        update third;
        //   system.assertEquals('Inactive', third.Status__c);
        Test.stopTest();      
    }
    
    static testmethod void updateRecords2(){
        
        Premier_Tier__c first = [Select Id, Status__c FROM Premier_Tier__c WHERE Name = 'First']; 
        first.End_Date__c = system.today() - 1;
        
        Test.startTest();
        update first;
        Test.stopTest();      
    }
    
    static testmethod void insertNew(){
        
        Premier_Tier__c third = [Select Id, Status__c FROM Premier_Tier__c WHERE Name = 'Third'];
        Premier_Tier__c forth = new Premier_Tier__c();  
        forth.Name = 'Forth';
        forth.Description__c = 'Forth Description';
        forth.Effective_Date__c = system.today() - 5;
        forth.Hierarchy_Action__c = '<';
        forth.Hierarchy_Selection__c = third.Id;
        forth.Status__c = 'Inactive';
        forth.Contract_Type__c = 'Contract 4';
        
        Test.startTest();
        insert forth;
        Test.stopTest();
    }
    
    static testmethod void insertNew2(){
        
        Premier_Tier__c third = [Select Id, Status__c FROM Premier_Tier__c WHERE Name = 'Third'];
        Premier_Tier__c forth = new Premier_Tier__c();  
        forth.Name = 'Forth';
        forth.Description__c = 'Forth Description';
        forth.Effective_Date__c = system.today() - 5;
        forth.Hierarchy_Action__c = 'Top_Tier';
        forth.Status__c = 'Inactive';
        forth.Contract_Type__c = 'Contract 4';
        
        Test.startTest();
        insert forth;
        Test.stopTest();
    }
    
}