force/src/objects/Premier_Benefit__c.object
<CustomObject>
    <fields>
        <fullName>Benefit_Amount__c</fullName>
        <label>Benefit Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Benefit_Type__c</fullName>
        <label>Benefit Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Currency</fullName>
                </value>
                <value>
                    <fullName>Discount</fullName>
                </value>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Premier Benefit</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Benefit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Premier Benefits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force/src/classes/VSP_Premier_Benefit_Dupe_Validation_Test.cls
@isTest
public class VSP_Premier_Benefit_Dupe_Validation_Test {
    
    @TestSetup
    static void testData(){
        
        Premier_Benefit__c firstBenefit = new Premier_Benefit__c();
        firstBenefit.Name = 'First Benefit';
        firstBenefit.Benefit_Type__c = 'Currency';
        firstBenefit.Benefit_Amount__c = 10;
        
        insert firstBenefit;
    } 
    static testmethod void insertDup(){
        try{
            Test.startTest();
            Premier_Benefit__c dupFirstBenefit = new Premier_Benefit__c();
            dupFirstBenefit.Name = 'First Benefit';
            dupFirstBenefit.Benefit_Type__c = 'Currency';
            dupFirstBenefit.Benefit_Amount__c = 10;
            
            insert dupFirstBenefit;
            
            Test.stopTest();
        }
        catch(Exception e){
            system.assert(e.getMessage().contains('This benefit already exists'));
        }
    }
    
}