force/src/objects/Premier_Tier__c.object
<CustomObject>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <inlineHelpText>Blank Date = No end date.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hierarchy_Action__c</fullName>
        <inlineHelpText>The selection of &quot;&lt;&quot; below or &quot;Top Tier&quot;, will determine the hierarchy location of where the new or edited tier needs to go in the list of existing tiers.</inlineHelpText>
        <label>Hierarchy Action</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>&lt;</fullName>
                </value>
                <value>
                    <fullName>Top_Tier</fullName>
                    <label>Top Tier</label>
                </value>
                <value>
                    <fullName>&gt;</fullName>
                    <isActive>false</isActive>
                    <label>&gt;</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Hierarchy_Selection__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If Hierarchy Action = Top Tier, Hierarchy Selection must be blank.</inlineHelpText>
        <label>Hierarchy Selection</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>The selected Hierarchy Selection Tier has a status of Inactive.</errorMessage>
            <filterItems>
                <field>Premier_Tier__c.Status__c</field>
                <operation>notEqual</operation>
                <value>Inactive</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>System Administrator, VSP Technical User</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Premier_Tier__c</referenceTo>
        <relationshipLabel>Premier Tiers</relationshipLabel>
        <relationshipName>Tiers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Future</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Premier Tier</label>
    <nameField>
        <label>Tier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Premier Tiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force/src/classes/VSP_Premier_Tier_Status_Update.cls
public class VSP_Premier_Tier_Status_Update {
    
    public static boolean VSP_Premier_Tier_Status_Update_recursion = true;
    public void VSP_Premier_Tier_Status_Update(List<Premier_Tier__c> newTrigger, Map<Id,Premier_Tier__c> oldRecs){
        
        if(VSP_Premier_Tier_Status_Update_recursion){
            VSP_Premier_Tier_Status_Update_recursion = false;
            system.debug('*****entered VSP_Premier_Tier_Status_Update ****');
            
            Set<Id> TierStatusUpdate = new Set<Id>();
            
            for(Premier_Tier__c nT: newTrigger){
                
                system.debug('***** oldRecs ***** ' + oldRecs);
                
                if(oldRecs != null){
                    if(nT.Effective_Date__c != oldRecs.get(nT.Id).Effective_Date__c ||
                       nT.End_Date__c != oldRecs.get(nT.Id).End_Date__c){
                           
                           TierStatusUpdate.add(nT.Id);
                           
                       }
                    
                }
                
                else{
                    
                    TierStatusUpdate.add(nT.Id);
                }
            }
            
            
            if(!TierStatusUpdate.isEmpty()){
                
                List<Premier_Tier__c> TierToUpdate = new List<Premier_Tier__c>();
                List<Premier_Tier__c> allTiers = [SELECT Id, Hierarchy_Action__c, Hierarchy_Selection__c, Effective_Date__c, End_Date__c, Status__c FROM Premier_Tier__c Where Id in :TierStatusUpdate];
                
                for(Premier_Tier__c updTier :allTiers){
                    
                    if(updTier.Effective_Date__c > Date.today()){
                        updTier.Status__c = 'Future';
                    }
                    else if(updTier.Effective_Date__c <= Date.today() && (updTier.End_Date__c >= Date.today() || updTier.End_Date__c == NULL)){
                        updTier.Status__c = 'Active';
                    }
                    else{
                        updTier.Status__c = 'Inactive';
                    }
                    TierToUpdate.add(updTier);
                }
                 system.debug('TierToUpdate List '+ TierToUpdate);
                if(!TierToUpdate.isEmpty()){
                    update TierToUpdate;
                }
            
            }
        }
        
    }
    
}