force/src/objects/QA_Review__c.object
<CustomObject>
    <description>Quality Assurance Reviews of Providers</description>
    <fields>
        <fullName>QA_Review_Status__c</fullName>
        <label>QA Review Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress QA Admin</fullName>
                </value>
                <value>
                    <fullName>Submit for Claims</fullName>
                </value>
                <value>
                    <fullName>Re-Submit for Claims</fullName>
                </value>
                <value>
                    <fullName>Assigned to Clinical Auditor</fullName>
                </value>
                <value>
                    <fullName>In Progress Clinical Auditor</fullName>
                </value>
                <value>
                    <fullName>Clinical Auditor Complete</fullName>
                </value>
                <value>
                    <fullName>Completed Audit Pass</fullName>
                </value>
                <value>
                    <fullName>Completed Audit Failed</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed - Non-responder</fullName>
                </value>
                <value>
                    <fullName>Fail</fullName>
                    <isActive>false</isActive>
                    <label>Fail</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <isActive>false</isActive>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Pass</fullName>
                    <isActive>false</isActive>
                    <label>Pass</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>QA Review</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>QA Review Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QA Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/VSPR28_QA_Review_Status_Update_Batchable.cls
global class VSPR28_QA_Review_Status_Update_Batchable implements Database.Batchable<sObject>,Database.AllowsCallouts{

     global final String Query;
    
    global VSPR28_QA_Review_Status_Update_Batchable(String q){
        Query =q;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }
    
    
    global void execute(Database.BatchableContext BC, List<sObject> scope){
        
        Set<Id> qaRec = new Set<Id>();
        
        for(sobject s : scope){
            QA_Review__c T = (QA_Review__c)s;
            qaRec.add(T.Id);
        }
        
        if(!qaRec.isEmpty()){
            List<QA_Review__c> qaRectoUpd = new List<QA_Review__c>();
            List<QA_Review__c> allQARec = [Select Id, QA_Review_Status__c from QA_Review__c Where Id IN :qaRec];
            
            for(QA_Review__c updList :allQARec){
                updList.QA_Review_Status__c = 'Closed - Non-responder';
                qaRectoUpd.add(updList);
            }
            
            if(!qaRectoUpd.isEmpty()){
                update qaRectoUpd;
            }
            
        }
        
    }
    
    
    
    global void finish(Database.BatchableContext BC){
        
    }
}