force/src/objects/QA_Review__c.object
<CustomObject>
    <description>Quality Assurance Reviews of Providers</description>
    <fields>
        <fullName>QA_Review_Status__c</fullName>
        <label>QA Review Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress QA Admin</fullName>
                </value>
                <value>
                    <fullName>Submit for Claims</fullName>
                </value>
                <value>
                    <fullName>Re-Submit for Claims</fullName>
                </value>
                <value>
                    <fullName>Assigned to Clinical Auditor</fullName>
                </value>
                <value>
                    <fullName>In Progress Clinical Auditor</fullName>
                </value>
                <value>
                    <fullName>Clinical Auditor Complete</fullName>
                </value>
                <value>
                    <fullName>Completed Audit Pass</fullName>
                </value>
                <value>
                    <fullName>Completed Audit Failed</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed - Non-responder</fullName>
                </value>
                <value>
                    <fullName>Fail</fullName>
                    <isActive>false</isActive>
                    <label>Fail</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <isActive>false</isActive>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Pass</fullName>
                    <isActive>false</isActive>
                    <label>Pass</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Result_Letter_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Result Letter Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Review_Date_Scheduled__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Review Date Scheduled</label>
        <type>Date</type>
    </fields>
    <label>QA Review</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>QA Review Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QA Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/VSPR28_QA_Review_Purge_Schedule.cls
global class VSPR28_QA_Review_Purge_Schedule implements Schedulable {
    
    global void execute(SchedulableContext sc){
        
        String Query;
        Date tDate = Date.today().addMonths(-126);   ///Date 10 years and 6 months ago
        String sDate = String.valueOf(tDate);
        sDate = sDate.removeEnd(' 00:00:00');        /// remove the time from the date
        Query = 'Select Id FROM QA_Review__c WHERE Review_Date_Scheduled__c < ' + sDate + ' OR (QA_Review_Status__c IN (\'Completed Audit Pass\',\'Completed Audit Failed\') AND Result_Letter_Date__c < ' + sDate + ')';
        //Query = 'Select Id FROM QA_Review__c';
        system.debug('Query= '+Query);
        system.debug('testDate= '+tDate);
        system.debug('testDate= '+sDate);
        
        
        VSPR28_QA_Review_Purge_Batchable batch = new VSPR28_QA_Review_Purge_Batchable(Query);
        database.executeBatch(batch,100);
    }
}