force/src/objects/QA_Review__c.object
<CustomObject>
    <description>Quality Assurance Reviews of Providers</description>
    <fields>
        <fullName>DocuSign_Completion_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>DocuSign Completion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Original_DocuSign_Sent_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Original DocuSign Sent Date</label>
        <type>Date</type>
    </fields>
    <label>QA Review</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>QA Review Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QA Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force/src/classes/VSPR28_QA_Review_Status_Update_Schedule.cls
global class VSPR28_QA_Review_Status_Update_Schedule implements Schedulable {

    global void execute(SchedulableContext sc){
        
        String Query;
        Date tDate = Date.today().addDays(-45);   ///Date 45 days ago
        String sDate = String.valueOf(tDate);
        sDate = sDate.removeEnd(' 00:00:00');        /// remove the time from the date
        Query = 'Select Id FROM QA_Review__c WHERE DocuSign_Completion_Date__c = null AND Original_DocuSign_Sent_Date__c < ' + sDate + ')';
        //Query = 'Select Id FROM QA_Review__c';
        system.debug('Query= '+Query);
        system.debug('testDate= '+tDate);
        system.debug('testDate= '+sDate);
        
        
       // VSPR28_QA_Review_Purge_Batchable batch = new VSPR28_QA_Review_Purge_Batchable(Query);
       // database.executeBatch(batch,100);
    }
}