force/src/objects/Release__c.object
<CustomObject>
    <description>TOOLKIT - An object that represents a specific instance of the product and all of the related components that make up the specific instance.</description>
    <fields>
        <fullName>Release__c</fullName>
        <label>Release #</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force/src/objects/Request__c.object
<CustomObject>
    <description>TOOLKIT - An object that represents a set of features that provides the ability to handle a capability.</description>
    <fields>
        <fullName>Nudge__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Nudge</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Release__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The release in which the request will actually be deployed. If the requirement has not been approved for a release, there should not be a value in this field.</inlineHelpText>
        <label>Planned Release</label>
        <referenceTo>Release__c</referenceTo>
        <relationshipLabel>Requests (Planned Release)</relationshipLabel>
        <relationshipName>Requirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request_Title__c</fullName>
        <description>Captures the requirement title</description>
        <inlineHelpText>Captures the requirement title</inlineHelpText>
        <label>Request Statement</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Request</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force/src/classes/UpdateReleaseLOEOnRequestChangeTest.cls
@isTest
private class UpdateReleaseLOEOnRequestChangeTest{

    static testMethod void test_UseCase1(){
        test.startTest();
        
        Release__c release_Obj = new Release__c(Name = 'Name438');
        Insert release_Obj; 
        
        Request__c request_Obj = new Request__c(Nudge__c = false);
        request_Obj.Request_Title__c='UseCase11-1';

        request_Obj.Release__c = release_Obj.id;
        Insert request_Obj; 
        Delete request_Obj;
        test.stopTest();
    }
}