force/src/objects/vsphighlights__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is used to define the &quot;What to Know&quot; highlights - max 5 lines displayed on the right side of the VSPGlobalSales community page..</description>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>displaytext__c</fullName>
        <label>displaytext</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>vsphighlights</label>
</CustomObject>

force/src/classes/Testvsphighlights.cls
/**
* Class Name: Testvsphighlights
* @author: Eagle Creek    
* Date: 25.OCT.2018
* Requirement/Project Name: VSPGlobalSales
* @description: Test class for the retrievel of custom settings value for vsphighlights.
*/
@isTest
public class Testvsphighlights {
   static testmethod void Testvsphighlights()
    {
   /* vsphighlights__c vsphighlights = new vsphighlights__c();         
    vsphighlights.Name = 'FourthLine';        
    vsphighlights.displaytext__c = '4th Highlights';   
	vsphighlights.URL__c = 'Highlight4';  
    insert vsphighlights;
	
	Map<String, vsphighlights__c> whattoknow = vsphighlights__c.getall();
    vsphighlights__c highllightURL = whattoknow.get('FourthLine');          
	String distext = highllightURL.displaytext__c;
	string URLval  = highllightURL.URL__c;
    System.debug(distext);	*/
        
      vsphighlights vs = new vsphighlights();
      System.debug(vs.vspheadln);
     
    }

}