src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Address_Type__c</fullName>
        <label>Address Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Physical</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Shipping</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <formula>Street__c &amp; &apos;, &apos; &amp; City__c &amp; &apos;, &apos; &amp; State__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>City</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Country</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>County</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LM_MASTER_SKEY__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>MDM Location Key</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>State</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Street</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Zip</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/VSPR1_AddressDML.cls
/**
 * Class Name: VSPR1_AddressDML
 * @author: Marvin B. Gatchalian
 * Date: 18.JUNE.2013
 * Requirement/Project Name: VSP
 * @description: Handles all DML for the Address Custom object.
 */

public class VSPR1_AddressDML { 

    //public static List<Address__c> getAddressDetails(Set<Id> ids){
     //system.debug('>>> Enter getAddressDetails');
      //List<Address__c> Addresses = [Select id from Address__c where id IN: ids];
      //return Addresses;        
   // }
    
    public static List<Address__c> getAddressPhysicalOnly(Set<Id> ids){
        system.debug('>>> Enter getAddressPhysicalOnly');
        List<Address__c> Addresses = [Select a.Zip__c, a.SystemModstamp, 
                                             a.Street__c, a.State__c, a.OwnerId,
                                             a.Name, a.LastModifiedDate, a.LastModifiedById, 
                                             a.LM_MASTER_SKEY__c, a.IsDeleted, a.Id, 
                                             a.CreatedDate, a.CreatedById, a.Country__c, 
                                             a.City__c, a.County__c
                                             From Address__c a where id IN: ids order by a.CreatedDate desc];
       
       // Below query is a backup before address type field is move to address relationship object 
       // List<Address__c> Addresses = [Select a.Zip__c, a.SystemModstamp, 
       //                                      a.Street__c, a.State__c, a.OwnerId,
       //                                      a.Name, a.LastModifiedDate, a.LastModifiedById, 
       //                                      a.LM_MASTER_SKEY__c, a.IsDeleted, a.Id, 
       //                                      a.CreatedDate, a.CreatedById, a.Country__c, 
       //                                      a.City__c, a.Address_Type__c 
       //                                      From Address__c a where Address_Type__c = 'Physical' 
       //                                      and id IN: ids order by a.CreatedDate desc];
        return Addresses;       
    }
}