src/objects/Article_Permission__c.object
<CustomObject>
    <fields>
        <fullName>Article_Type__c</fullName>
        <label>Article Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Article_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Group_Email__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>If the email needs to go to a Group and not a user</inlineHelpText>
        <label>Group Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Article_Permission</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Article Permission</label>
    <nameField>
        <displayFormat>AP-{0}</displayFormat>
        <label>Article Permission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Article Permission</pluralLabel>
    <recordTypes>
        <fullName>Editors</fullName>
        <active>true</active>
        <description>The users who can Edit/Delete Articles without generating an email  - based on Article Type</description>
        <label>Editors</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CC_Portal__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Base_URL__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Base URL</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>CC Portal</label>
</CustomObject>

src/objects/Consumer_Search_Web_Service__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Consumer_Search_Token_Header__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Consumer Search Token Header</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consumer_Search_Web_Service__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Consumer Search Web Service</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Consumer Search Web Service</label>
</CustomObject>

force/src/objects/DVIWebService__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Setting for the DVI Web Service URL and token header</description>
    <fields>
        <fullName>DVI_Token_Header__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>DVI Token Header</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DVI_Web_Service__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>DVI Web Service</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DVI Web Service</label>
</CustomObject>

src/objects/Knowledge__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <page>Knowledge_VFP</page>
            <template>Page</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
</CustomObject>

src/globalValueSets/Article_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Additional_Benefits</fullName>
        <label>Additional Benefits</label>
    </customValue>
    <customValue>
        <fullName>C_G_Article</fullName>
        <label>C G Article</label>
    </customValue>
    <customValue>
        <fullName>Core_Benefit</fullName>
        <label>Core Benefit</label>
    </customValue>
    <customValue>
        <fullName>External_Publication</fullName>
        <label>External Publication</label>
    </customValue>
    <customValue>
        <fullName>General_Article_Template</fullName>
        <label>General Article Template</label>
    </customValue>
    <customValue>
        <fullName>Multi_Topic</fullName>
        <label>Multi Topic</label>
    </customValue>
    <customValue>
        <fullName>Multi_Topic_Details</fullName>
        <label>Multi Topic Details</label>
    </customValue>
    <customValue>
        <fullName>Open_Enrollment</fullName>
        <label>Open Enrollment</label>
    </customValue>
    <customValue>
        <fullName>Procedure</fullName>
    </customValue>
    <customValue>
        <fullName>Provider_Solutions_Community</fullName>
        <label>Provider Solutions Community</label>
    </customValue>
    <customValue>
        <fullName>Single_Topic</fullName>
        <label>Single Topic</label>
    </customValue>
    <customValue>
        <fullName>Support_Queue</fullName>
        <label>Support Queue</label>
    </customValue>
    <customValue>
        <fullName>Universal_Service</fullName>
        <label>Universal Service</label>
    </customValue>
    <description>DO NOT EDIT these names - they are he Record Type Names stored.  If you change they will not match.</description>
    <masterLabel>Article Types</masterLabel>
</GlobalValueSet>

src/classes/TestDataFactory.cls
@isTest
public class TestDataFactory {

    public static Id createAccount(String name){
        Account account = new Account(Name = name);
        insert account;
        return account.id;
    }
     public static Id createPersonAccount(String name){
        Account account = new Account(lastName = name);
        RecordType personAccountRecordType =  [SELECT Id FROM RecordType WHERE Name = 'Person Account' and SObjectType = 'Account'];
        account.Recordtypeid = personAccountRecordType.id;
        insert account;
        return account.id;
    }
    public static MemberPlan createMemberPlan(id aid, String name){
        MemberPlan mp = new MemberPlan(Name = name, MemberId = aid);
        insert mp;
        return mp;
    }
    
    public static Id createArticleEditors(String aType, User u){
        Id rtId = Schema.SObjectType.Article_Permission__c.getRecordTypeInfosByName().get('Editors').getRecordTypeId();
        Article_Permission__c aPerm = new Article_Permission__c(User__c = u.id,Article_Type__c = aType );
        insert aPerm;
        aPerm.RecordTypeId = rtId;
        update aPerm;
        return aPerm.id;
    }
    
    public static Id createGroupArticleOwners(String aType,String gpEmail){
        Id rtId = Schema.SObjectType.Article_Permission__c.getRecordTypeInfosByName().get('Article Owners').getRecordTypeId();
        Article_Permission__c aPerm = new Article_Permission__c(Article_Type__c = aType ,Group_Email__c = gpEmail, RecordTypeId = rtId);
        insert aPerm;
        return aPerm.id;
    }
    
    public static Id createUserArticleOwners(String aType,User u){
        Id rtId = Schema.SObjectType.Article_Permission__c.getRecordTypeInfosByName().get('Article Owners').getRecordTypeId();
        Article_Permission__c aPerm = new Article_Permission__c(Article_Type__c = aType ,User__c = u.id, RecordTypeId = rtId);
        insert aPerm;
        return aPerm.id;
    }
    public static Knowledge__kav createKnowledge(string RTName){
        Id rtId = Schema.SObjectType.Knowledge__kav.getRecordTypeInfosByName().get(RTName).getRecordTypeId();
        
        Knowledge__kav article = new Knowledge__kav(
            Title=System.now().millisecond() + 'test',
            summary=System.now().millisecond() + 'xyz',
            urlname=System.now().millisecond() + 'xyz');
        article.recordtypeId = rtId;
        insert article;
        return article;    
    }
    
   public static User createUser(String first, String last){
        
         //Create user
         Profile VSPProfile = [SELECT Id FROM Profile WHERE Name LIKE '%VSP%' Limit 1];
         User user1 = new User(
         Username = System.now().millisecond() + First+ 'test12345@test.com',
         ProfileId = VSPProfile.Id,
         Alias = 'tst1'+first.left(4),
         Email = last+'test12345@test.com',
         EmailEncodingKey = 'UTF-8',
         LastName = last,
         CommunityNickname = last+'12345',
         TimeZoneSidKey = 'America/Los_Angeles',
         LocaleSidKey = 'en_US',
         LanguageLocaleKey = 'en_US'
         ); 
         insert user1;
         return user1;
    }  
   public static DVIWebService__c setDVISettings(){
        DVIWebService__c dviCustSetting = new DVIWebService__c();
        dviCustSetting.name = 'DVI Values';
        dviCustSetting.DVI_Web_Service__c = 'webserviceURL'; 
        dviCustSetting.DVI_Token_Header__c = 'tokenheader';
        insert dviCustSetting;
        return dviCustSetting;
        }
 
   public static CC_Portal__c setCCPortalSettings(){
        CC_Portal__c ccCustSetting = new CC_Portal__c();
        ccCustSetting.name = 'Environment';
        ccCustSetting.Base_URL__c = 'https://ccp-test.vsp.com'; 
        insert ccCustSetting;
        return ccCustSetting;
        } 
    public static Consumer_Search_Web_Service__c setCSSettings(){
        Consumer_Search_Web_Service__c CSCustSetting = new Consumer_Search_Web_Service__c();
        CSCustSetting.Name = 'Consumer Search Values';
        CSCustSetting.Consumer_Search_Web_Service__c = 'https://api-staging.vspglobal.com'; 
        CSCustSetting.Consumer_Search_Token_Header__c = 'tokenheader';
        insert CSCustSetting;
        return CSCustSetting;
    }
   
}