src/objects/Article_Permission__c.object
<CustomObject>
    <fields>
        <fullName>Article_Type__c</fullName>
        <label>Article Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Article_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>OwnerName__c</fullName>
        <formula>If(ISBLANK(Group_Email__c), User__r.FirstName ,Group_Email__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>OwnerName</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserEmail__c</fullName>
        <description>If they enter both a User and a Group Email put the Group Email in the UserEmail field - that is the email that gets the message.</description>
        <formula>If(ISBLANK(Group_Email__c), User__r.Email ,Group_Email__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>UserEmail</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Article_Permission</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Article Permission</label>
    <nameField>
        <displayFormat>AP-{0}</displayFormat>
        <label>Article Permission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Article Permission</pluralLabel>
    <recordTypes>
        <fullName>Editors</fullName>
        <active>true</active>
        <description>The users who can Edit/Delete Articles without generating an email  - based on Article Type</description>
        <label>Editors</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Knowledge__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <page>Knowledge_VFP</page>
            <template>Page</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <fields>
        <fullName>Article_Record_Type_Name__c</fullName>
        <description>Created to capture the record type name which is used in apex classes and visualforce pages to serve-up knowledge articles in Quest.</description>
        <formula>RecordType.DeveloperName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Article Record Type Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Feedback_Submitted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Feedback Submitted</label>
        <type>Checkbox</type>
    </fields>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
</CustomObject>

src/globalValueSets/Article_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Additional_Benefits</fullName>
        <label>Additional Benefits</label>
    </customValue>
    <customValue>
        <fullName>C_G_Article</fullName>
        <label>C G Article</label>
    </customValue>
    <customValue>
        <fullName>Core_Benefit</fullName>
        <label>Core Benefit</label>
    </customValue>
    <customValue>
        <fullName>External_Publication</fullName>
        <label>External Publication</label>
    </customValue>
    <customValue>
        <fullName>General_Article_Template</fullName>
        <label>General Article Template</label>
    </customValue>
    <customValue>
        <fullName>Multi_Topic</fullName>
        <label>Multi Topic</label>
    </customValue>
    <customValue>
        <fullName>Multi_Topic_Details</fullName>
        <label>Multi Topic Details</label>
    </customValue>
    <customValue>
        <fullName>Open_Enrollment</fullName>
        <label>Open Enrollment</label>
    </customValue>
    <customValue>
        <fullName>Procedure</fullName>
    </customValue>
    <customValue>
        <fullName>Provider_Solutions_Community</fullName>
        <label>Provider Solutions Community</label>
    </customValue>
    <customValue>
        <fullName>Single_Topic</fullName>
        <label>Single Topic</label>
    </customValue>
    <customValue>
        <fullName>Support_Queue</fullName>
        <label>Support Queue</label>
    </customValue>
    <customValue>
        <fullName>Universal_Service</fullName>
        <label>Universal Service</label>
    </customValue>
    <description>DO NOT EDIT these names - they are he Record Type Names stored.  If you change they will not match.</description>
    <masterLabel>Article Types</masterLabel>
</GlobalValueSet>

src/classes/VSPR1_KnowledgeTriggerHandler.cls
public with sharing class VSPR1_KnowledgeTriggerHandler { 
/*Created by: Elly Bockley - Eagle Creek Software Services
  Date: April 2019
  Description: This handles the Updates/Deletes to an Article
               If a person is not allowed to edit/delete and email is sent to the owner
               Whether a person can edit or delete is defined in Article_Permissions__c
               The person(s) who receive the email are also defined there. 
               The Record Type Name exists on teh Knowledge Article
               This trigger will not run in batch updates - only sends email once
			   Need to send separate emails in case there are multiple Owners - in order to fillin the Owner field	
*/

    public void onBefore(List<Knowledge__kav> newArticles) { 
        
         String userPermissions = setPermissions(); 
        
         String trigger_type = 'modification';
         Knowledge__kav newArticle;
         
         for(Knowledge__kav kav:newArticles){
             newArticle = kav; 
         }
          
        List<String> recipients = getEmailRecipients(newArticle.Article_Record_Type_Name__c); 
        List<String> ownerNames = getOwnerNames(newArticle.Article_Record_Type_Name__c); 
            
             if(trigger.isDelete){
                 trigger_type = 'deletion';
             }       
             
            
             //Now see if the current user has this permission
                 if(userPermissions == null || !userPermissions.contains(newArticle.Article_Record_Type_Name__c)){
                    
                     if(recipients.size() >0){
                         for(Integer i = 0; i < recipients.size(); i++){
                      	   SendEmail(trigger_type, recipients[i], ownerNames[i], newArticle); 
                     }
                     }   
                 }
         
    }
    public String setPermissions(){
    //Get the list of permissions for current user
    Id rtId = Schema.SObjectType.Article_Permission__c.getRecordTypeInfosByName().get('Editors').getRecordTypeId();
     
     List<Article_Permission__c> permList = new List<Article_Permission__c>(
         [SELECT id, User__c, Article_Type__c 
          FROM Article_Permission__c
          WHERE RecordtypeId =: rtId
          AND User__c =: UserInfo.getUserId()
           ]);
     String permissionList='';
     
     if(permList.size() >0){
         permissionList = permList[0].Article_Type__c;
     }
      
     return permissionList;
    }
   
    public List<String> getEmailRecipients(String aType){
    //Get the list of recipients for the current Record Type
   
     Id rtId = Schema.SObjectType.Article_Permission__c.getRecordTypeInfosByName().get('Article Owners').getRecordTypeId();
    
     List<Article_Permission__c> emailList = new List<Article_Permission__c>(
         [SELECT id, Article_Type__c, UserEmail__c
          FROM Article_Permission__c
          WHERE RecordtypeId =: rtId
           ]);
    
     List<String> recipients = new List<String>();
 
     //There can be multiple recipients per Knowledge Record Type
         for(Article_Permission__c a:emailList){
         
             if(a.Article_Type__c.contains(aType)){
                     recipients.add(a.UserEmail__c);                    
       
             }
         }
    System.debug('### size of recipients = ' + recipients.size() );
     return recipients;
    }
    
    public List<String> getOwnerNames(String aType){
    //Get the list of recipients for the current Record Type
   
     Id rtId = Schema.SObjectType.Article_Permission__c.getRecordTypeInfosByName().get('Article Owners').getRecordTypeId();
    
     List<Article_Permission__c> emailList = new List<Article_Permission__c>(
         [SELECT id, Article_Type__c, OwnerName__c
          FROM Article_Permission__c
          WHERE RecordtypeId =: rtId
           ]);
    
     List<String> ownerNames = new List<String>();
 
     //There can be multiple recipients per Knowledge Record Type - if groupemail, use that email as the OwnerName
        for(Article_Permission__c a:emailList){
         
             if(a.Article_Type__c.contains(aType)){         
     	        ownerNames.add(a.OwnerName__c);                    
             }
		}
     return ownerNames;
    }
   
    public void sendEmail(string updatetype, String recipient, String ownerName, Knowledge__kav kArticle ){
      
        Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
        List<String> recipients = new List<String>(); //need to pass List
        recipients.add(recipient);
        message.setToAddresses(recipients);
        message.Subject = 'Article Modification Notification';
        
        String Body = 'Dear '+ ownerName +'</p>';
        Body =  Body + 'There has recently been a ' +updatetype+ ' to an article you own. </p>';
        Body = Body+'Modified By: '+ userInfo.getName()+'</p>Date/Time of Change: '+ kArticle.lastModifiedDate;
        Body = Body + '<p/>Article Title: '+ kArticle.Title + '</p>Article Number: '+ kArticle.ArticleNumber;
        Body = Body + '<p/>Please review the article content and contact the modifier if appropriate.';
        message.setHTMLBODY(Body);
               
        Messaging.SingleEmailMessage[] messages = new List<Messaging.SingleEmailMessage>{message};
        
        Messaging.SendEmailResult[] results = Messaging.sendEmail(messages);
        if(results[0].success){
            System.debug('###Message sent');
        }
        else{
            System.debug('###Email failed to send'+results[0].errors[0].message);
        }
       
    }
    public void chatterPost(List<Knowledge__kav> newArticles){
		for(integer i = 0; i<newArticles.size(); i++ ){
        	if(newArticles.get(i).Feedback_Submitted__c == true && newArticles.get(i).isLatestVersion == true){			
            	ConnectApi.FeedElement feedElement = ConnectApi.ChatterFeeds.postFeedElement(Network.getNetworkId(), newArticles.get(i).id, ConnectApi.FeedElementType.FeedItem, 'Feedback was submitted on this article');
        	}
    	} 
    }
}