src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Auto_Assign__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Un-check to maintain ownership of this Case when it is created.</inlineHelpText>
        <label>Automatically Assign Case</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Case_Age_2__c</fullName>
        <defaultValue>0</defaultValue>
        <label>SLA Case Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Classification__c</fullName>
        <inlineHelpText>The relevant category for the Issue or Request.</inlineHelpText>
        <label>Classification</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account/Contact Maintenance</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Claims</fullName>
                </value>
                <value>
                    <fullName>Credentialing/Recruiting</fullName>
                </value>
                <value>
                    <fullName>Product</fullName>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Shipping</fullName>
                </value>
                <value>
                    <fullName>Status</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>In_Danger_of_Missing_for_High_Priority__c</fullName>
        <defaultValue>false</defaultValue>
        <label>In Danger of Missing for High Priority</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <inlineHelpText>The Line of Business responsible for working the Case.</inlineHelpText>
        <label>Line of Business</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Altair</fullName>
                    <color>#0B6FCE</color>
                    <label>Altair</label>
                </value>
                <value>
                    <fullName>Eyefinity</fullName>
                    <color>#78C953</color>
                    <label>Eyefinity</label>
                </value>
                <value>
                    <fullName>Global Customer Care</fullName>
                </value>
                <value>
                    <fullName>Marchon</fullName>
                    <color>#E27001</color>
                    <label>Marchon</label>
                </value>
                <value>
                    <fullName>Optics Group</fullName>
                    <color>#A845DC</color>
                    <label>Optics Group</label>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Vision Care</fullName>
                    <color>#F3D904</color>
                    <label>Vision Care</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Topic</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Line_of_Business__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Inventory</fullName>
                </value>
                <value>
                    <fullName>Special Order Request</fullName>
                </value>
                <value>
                    <fullName>Stock Order Status</fullName>
                </value>
                <value>
                    <fullName>Product Mapping</fullName>
                </value>
                <value>
                    <fullName>System</fullName>
                </value>
                <value>
                    <fullName>2020 Source (Affiliate)</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Cash Receipts</fullName>
                </value>
                <value>
                    <fullName>Data Entry</fullName>
                </value>
                <value>
                    <fullName>EDI Membership</fullName>
                </value>
                <value>
                    <fullName>Email Update</fullName>
                </value>
                <value>
                    <fullName>Explanation of Payment (EOP)</fullName>
                </value>
                <value>
                    <fullName>Eyeconic Ops</fullName>
                </value>
                <value>
                    <fullName>Eyeconic USC</fullName>
                </value>
                <value>
                    <fullName>Eye Health Management (EHM)</fullName>
                </value>
                <value>
                    <fullName>Lab Opt Out</fullName>
                </value>
                <value>
                    <fullName>Level</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>HP Plan Admin</fullName>
                </value>
                <value>
                    <fullName>HP Billing</fullName>
                </value>
                <value>
                    <fullName>Membership</fullName>
                </value>
                <value>
                    <fullName>MetLife</fullName>
                </value>
                <value>
                    <fullName>Molina</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>Office Hours Update</fullName>
                </value>
                <value>
                    <fullName>otto</fullName>
                </value>
                <value>
                    <fullName>Practice Report</fullName>
                </value>
                <value>
                    <fullName>Premier</fullName>
                </value>
                <value>
                    <fullName>Regence</fullName>
                </value>
                <value>
                    <fullName>Reimbursement Fees</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Severity__c</fullName>
        <inlineHelpText>Systematic Escalation of the Case is driven by the value in this field.</inlineHelpText>
        <label>Severity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Critical</fullName>
                </value>
                <value>
                    <fullName>Major</fullName>
                </value>
                <value>
                    <fullName>Minor</fullName>
                    <default>true</default>
                    <label>Minor</label>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force/src/objects/CaseRecordType__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Id__c</fullName>
        <label>Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Case Record Type</label>
</CustomObject>

force/src/objects/DVIWebService__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Setting for the DVI Web Service URL and token header</description>
    <fields>
        <fullName>DVI_Token_Header__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>DVI Token Header</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DVI_Web_Service__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>DVI Web Service</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DVI Web Service</label>
</CustomObject>

src/objects/Escalated_Queue_Name__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Escalated_Q_Name__c</fullName>
        <defaultValue>&apos;Escalated Queue&apos;</defaultValue>
        <encryptionScheme>None</encryptionScheme>
        <label>Escalated Q Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Escalated Queue Name</label>
</CustomObject>

src/classes/trgCaseAgeCalculationTest.cls
/*
   Writen Date : 27th May 2016.
   Related Object : Case.
   Related Case : Case 9044.
   Description :Test class for  trgCaseAgeCalculation Trigger and CaseAgeCalculationHandler Apex Class
*/
@isTest
public class trgCaseAgeCalculationTest{
    public static testmethod void trgEmailAlertandCaseAgeCalculationMethod(){
         DVIWebService__c di = new DVIWebService__c(Name='DVI Values',DVI_Web_Service__c='Test',DVI_Token_Header__c='test');
        insert di;
        
        List<case> CaseList=new List<case>();
        List<case> UpdatedCaseList=new List<case>();
        List<CaseRecordType__c> CaseRecordTypeList=new List<CaseRecordType__c>();
                
        RecordType rt = new RecordType();
        rt = [Select id,name from RecordType where name = 'Customer Care' and sobjectType = 'Case' LIMIT 1];
        Id RecordTypeID = [Select id,name from RecordType where name != 'Customer Care' and sobjectType = 'Case' LIMIT 1].id;
        CaseRecordType__c CaseRecordType=new CaseRecordType__c();
        CaseRecordType.Id__c= rt.id;
        CaseRecordType.name='VSP Global Full Id';
        
        CaseRecordTypeList.add(CaseRecordType);
        //insert CaseRecordType;
        
        CaseRecordType__c CaseRecordType1=new CaseRecordType__c();
        CaseRecordType1.Id__c= rt.id;
        CaseRecordType1.name='Customer Care';
        
        CaseRecordTypeList.add(CaseRecordType1);
        //insert CaseRecordType1;
        
        insert CaseRecordTypeList;
        system.assertEquals(CaseRecordTypeList.size(),2);
       
       system.assertNotEquals(CaseRecordType.id,null);
       
       Escalated_Queue_Name__c Escalated_Queue_Name=new Escalated_Queue_Name__c();
       Escalated_Queue_Name.name='Error Queue';
       Escalated_Queue_Name.Escalated_Q_Name__c='Error Queue';
       insert Escalated_Queue_Name;
       system.assertNotEquals(Escalated_Queue_Name.id,null); 
       
        for(integer i=0;i<10;i++)
        {
            Case c=new Case();
            c.Origin='Web';
            c.Subject='test';
            c.Description='test';
            c.Line_of_Business__c='Altair';
            c.status='New';
            c.Severity__c='Minor';
            c.Type='Request';
            c.Product__c='Premier';
            c.In_Danger_of_Missing_for_High_Priority__c = false;
            c.Auto_Assign__c = false;
            c.Classification__c='Billing';
            CaseList.add(c);
        }
        
        Test.StartTest();
            insert CaseList;
            for(Case c:CaseList){
                c.status='Closed';
                c.Origin='Email';
                c.Case_Age_2__c = 21.00;
                c.In_Danger_of_Missing_for_High_Priority__c = true;
                UpdatedCaseList.add(c);
            }
            update UpdatedCaseList;
            update UpdatedCaseList;
        Test.StopTest();
    }
}