src/objects/CC_Portal__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Base_URL__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Base URL</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>CC Portal</label>
</CustomObject>

src/classes/VSPR2_CCPortal_Controller_Test.cls
@isTest
public class VSPR2_CCPortal_Controller_Test {
	@isTest
    public static void getCCPUrl(){
        CC_Portal__c ccCustSetting = new CC_Portal__c();
        ccCustSetting.name = 'Environment';
        ccCustSetting.Base_URL__c = 'https://ccp-test.vsp.com'; 
        insert ccCustSetting;

        VSPR2_CCPortal_Controller ccController = new VSPR2_CCPortal_Controller();
		ccController.VSPR2_CCPortal_Controller();
		String ccp = ccController.ccpURL;
        
        system.assertEquals('https://ccp-test.vsp.com/csrportal/ctiEvent/ready?reset=true',ccp);
    }
}