src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <formula>HYPERLINK(&quot;/&quot; + Id, &quot;Contact Record&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Record</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Contact_Role__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Eye Care Professional</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DS_Last_Disposition__c</fullName>
        <description>DialSource V3 &quot;Last Disposition&quot; field for the Contact Role custom object</description>
        <encryptionScheme>None</encryptionScheme>
        <label>DS Last Disposition</label>
        <length>140</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DS_Pending_Event_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>DS Pending Event Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DS_Pending_Task_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>DS Pending Task Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <encryptionScheme>None</encryptionScheme>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accounting</fullName>
                </value>
                <value>
                    <fullName>Board Member/ Officer</fullName>
                </value>
                <value>
                    <fullName>Dean</fullName>
                </value>
                <value>
                    <fullName>Doctor-Employee</fullName>
                </value>
                <value>
                    <fullName>Doctor-Owner</fullName>
                </value>
                <value>
                    <fullName>Doctor-Unspecified</fullName>
                </value>
                <value>
                    <fullName>Group Administrator</fullName>
                </value>
                <value>
                    <fullName>Lab Technician</fullName>
                </value>
                <value>
                    <fullName>Member</fullName>
                </value>
                <value>
                    <fullName>Office Administration</fullName>
                </value>
                <value>
                    <fullName>Office Manager</fullName>
                </value>
                <value>
                    <fullName>Optical Buyer</fullName>
                </value>
                <value>
                    <fullName>Optical Manager</fullName>
                </value>
                <value>
                    <fullName>Optician</fullName>
                </value>
                <value>
                    <fullName>Optician-Owner</fullName>
                </value>
                <value>
                    <fullName>Owner</fullName>
                </value>
                <value>
                    <fullName>Student</fullName>
                </value>
                <value>
                    <fullName>Unspecified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DSTaskDueDatePB_Test.cls
@isTest
public class DSTaskDueDatePB_Test {

    @isTest
    static void pendingTask()
    {
        User u = [SELECT Id, IsActive FROM User WHERE IsActive = TRUE LIMIT 1];
        
        List<DSTaskDueDatePB.DSTaskDueDatePB_Request> testRequestList = new List<DSTaskDueDatePB.DSTaskDueDatePB_Request>();
        DSTaskDueDatePB.DSTaskDueDatePB_Request testRequest = new DSTaskDueDatePB.DSTaskDueDatePB_Request();
        
        testRequest.contactRoleID = instantiateDBTask('', 'Task').Id; 
        testRequest.dueDate = 10;
        testRequest.subject = 'Test';
        testRequest.assignedTo = u.Id; 
        testRequest.status = 'Test';
        testRequest.taskType = 'Test'; 
        testRequest.priority = 'Test';
        
        testRequestList.add(testRequest);
        
        Test.startTest(); 
        DSTaskDueDatePB.createFollowUpTasks(testRequestList);
        Test.stopTest();
    }
    
    @isTest
    static void pendingEvent()
    {
        User u = [SELECT Id, IsActive FROM User WHERE IsActive = TRUE LIMIT 1];
        
        List<DSTaskDueDatePB.DSTaskDueDatePB_Request> testRequestList = new List<DSTaskDueDatePB.DSTaskDueDatePB_Request>();
        DSTaskDueDatePB.DSTaskDueDatePB_Request testRequest = new DSTaskDueDatePB.DSTaskDueDatePB_Request();
        
        testRequest.contactRoleID = instantiateDBTask('','Event').Id; 
        testRequest.dueDate = 10;
        testRequest.subject = 'Test';
        testRequest.assignedTo = u.Id; 
        testRequest.status = 'Test';
        testRequest.taskType = 'Test'; 
        testRequest.priority = 'Test';
        
        testRequestList.add(testRequest);
        
        Test.startTest(); 
        DSTaskDueDatePB.createFollowUpTasks(testRequestList);
        Test.stopTest();
    }

    @isTest 
    static void normalDays()
    {
        User u = [SELECT Id, IsActive FROM User WHERE IsActive = TRUE LIMIT 1];
        
        List<DSTaskDueDatePB.DSTaskDueDatePB_Request> testRequestList = new List<DSTaskDueDatePB.DSTaskDueDatePB_Request>();
        DSTaskDueDatePB.DSTaskDueDatePB_Request testRequest = new DSTaskDueDatePB.DSTaskDueDatePB_Request();
        
        testRequest.contactRoleID = instantiateDBTask('','').Id; 
        testRequest.dueDate = 11;
        testRequest.subject = 'Test';
        testRequest.assignedTo = u.Id; 
        testRequest.status = 'Test';
        testRequest.taskType = 'Test'; 
        testRequest.priority = 'Test';
        testRequest.businessDaysOption = false; 
        testRequest.dateToday = Date.newInstance(2016, 12, 5);
        
        testRequestList.add(testRequest);
        
        Test.startTest(); 
        DSTaskDueDatePB.createFollowUpTasks(testRequestList);
        Test.stopTest();
    }
    
    @isTest 
    static void defaultTask1DayMonday()
    {
        User u = [SELECT Id, IsActive FROM User WHERE IsActive = TRUE LIMIT 1];
        
        List<DSTaskDueDatePB.DSTaskDueDatePB_Request> testRequestList = new List<DSTaskDueDatePB.DSTaskDueDatePB_Request>();
        DSTaskDueDatePB.DSTaskDueDatePB_Request testRequest = new DSTaskDueDatePB.DSTaskDueDatePB_Request();
        
        testRequest.contactRoleID = instantiateDBTask('','').Id; 
        testRequest.dueDate = 11;
        testRequest.subject = 'Test';
        testRequest.assignedTo = u.Id; 
        testRequest.status = 'Test';
        testRequest.taskType = 'Test'; 
        testRequest.priority = 'Test';
        testRequest.businessDaysOption = true; 
        testRequest.dateToday = Date.newInstance(2016, 12, 5);
        
        testRequestList.add(testRequest);
        
        Test.startTest(); 
        DSTaskDueDatePB.createFollowUpTasks(testRequestList);
        Test.stopTest();
    }
    
    @isTest 
    static void defaultTask1DayFriday()
    {
        User u = [SELECT Id, IsActive FROM User WHERE IsActive = TRUE LIMIT 1];
        
        List<DSTaskDueDatePB.DSTaskDueDatePB_Request> testRequestList = new List<DSTaskDueDatePB.DSTaskDueDatePB_Request>();
        DSTaskDueDatePB.DSTaskDueDatePB_Request testRequest = new DSTaskDueDatePB.DSTaskDueDatePB_Request();
        
        testRequest.contactRoleID = instantiateDBTask('','').Id; 
        testRequest.dueDate = 11;
        testRequest.subject = 'Test';
        testRequest.assignedTo = u.Id; 
        testRequest.status = 'Test';
        testRequest.taskType = 'Test'; 
        testRequest.priority = 'Test';
        testRequest.businessDaysOption = true; 
        testRequest.dateToday = Date.newInstance(2016, 12, 9);
        
        testRequestList.add(testRequest);
        
        Test.startTest(); 
        DSTaskDueDatePB.createFollowUpTasks(testRequestList);
        Test.stopTest();
    }
    
    @isTest 
    static void defaultTask1DaySaturday()
    {
        User u = [SELECT Id, IsActive FROM User WHERE IsActive = TRUE LIMIT 1];
        
        List<DSTaskDueDatePB.DSTaskDueDatePB_Request> testRequestList = new List<DSTaskDueDatePB.DSTaskDueDatePB_Request>();
        DSTaskDueDatePB.DSTaskDueDatePB_Request testRequest = new DSTaskDueDatePB.DSTaskDueDatePB_Request();
        
        testRequest.contactRoleID = instantiateDBTask('','').Id; 
        testRequest.dueDate = 11;
        testRequest.subject = 'Test';
        testRequest.assignedTo = u.Id; 
        testRequest.status = 'Test';
        testRequest.taskType = 'Test'; 
        testRequest.priority = 'Test';
        testRequest.businessDaysOption = true; 
        testRequest.dateToday = Date.newInstance(2016, 12, 10);
        
        testRequestList.add(testRequest);
        
        Test.startTest(); 
        DSTaskDueDatePB.createFollowUpTasks(testRequestList);
        Test.stopTest();
    }
    
    @isTest 
    static void defaultTask1DaySunday()
    {
        User u = [SELECT Id, IsActive FROM User WHERE IsActive = TRUE LIMIT 1];
        
        List<DSTaskDueDatePB.DSTaskDueDatePB_Request> testRequestList = new List<DSTaskDueDatePB.DSTaskDueDatePB_Request>();
        DSTaskDueDatePB.DSTaskDueDatePB_Request testRequest = new DSTaskDueDatePB.DSTaskDueDatePB_Request();
        
        testRequest.contactRoleID = instantiateDBTask('','').Id; 
        testRequest.dueDate = 11;
        testRequest.subject = 'Test';
        testRequest.assignedTo = u.Id; 
        testRequest.status = 'Test';
        testRequest.taskType = 'Test'; 
        testRequest.priority = 'Test';
        testRequest.businessDaysOption = true; 
        testRequest.dateToday = Date.newInstance(2016, 12, 11);
        
        testRequestList.add(testRequest);
        
        Test.startTest(); 
        DSTaskDueDatePB.createFollowUpTasks(testRequestList);
        Test.stopTest();
    }
    
    @isTest 
    static void defaultTask2DaysMonday()
    {
        User u = [SELECT Id, IsActive FROM User WHERE IsActive = TRUE LIMIT 1];
        
        List<DSTaskDueDatePB.DSTaskDueDatePB_Request> testRequestList = new List<DSTaskDueDatePB.DSTaskDueDatePB_Request>();
        DSTaskDueDatePB.DSTaskDueDatePB_Request testRequest = new DSTaskDueDatePB.DSTaskDueDatePB_Request();
        
        testRequest.contactRoleID = instantiateDBTask('','').Id; 
        testRequest.dueDate = 12;
        testRequest.subject = 'Test';
        testRequest.assignedTo = u.Id; 
        testRequest.status = 'Test';
        testRequest.taskType = 'Test'; 
        testRequest.priority = 'Test';
		testRequest.businessDaysOption = true; 
        testRequest.dateToday = Date.newInstance(2016, 12, 5);
        
        testRequestList.add(testRequest);
        
        Test.startTest(); 
        DSTaskDueDatePB.createFollowUpTasks(testRequestList);
        Test.stopTest();
    }
    
    @isTest 
    static void defaultTask2DaysThursday()
    {
        User u = [SELECT Id, IsActive FROM User WHERE IsActive = TRUE LIMIT 1];
        
        List<DSTaskDueDatePB.DSTaskDueDatePB_Request> testRequestList = new List<DSTaskDueDatePB.DSTaskDueDatePB_Request>();
        DSTaskDueDatePB.DSTaskDueDatePB_Request testRequest = new DSTaskDueDatePB.DSTaskDueDatePB_Request();
        
        testRequest.contactRoleID = instantiateDBTask('','').Id; 
        testRequest.dueDate = 12;
        testRequest.subject = 'Test';
        testRequest.assignedTo = u.Id; 
        testRequest.status = 'Test';
        testRequest.taskType = 'Test'; 
        testRequest.priority = 'Test';
		testRequest.businessDaysOption = true; 
        testRequest.dateToday = Date.newInstance(2016, 12, 8);
        
        testRequestList.add(testRequest);
        
        Test.startTest(); 
        DSTaskDueDatePB.createFollowUpTasks(testRequestList);
        Test.stopTest();
    }
    
    @isTest 
    static void defaultTask2DaysSaturday()
    {
        User u = [SELECT Id, IsActive FROM User WHERE IsActive = TRUE LIMIT 1];
        
        List<DSTaskDueDatePB.DSTaskDueDatePB_Request> testRequestList = new List<DSTaskDueDatePB.DSTaskDueDatePB_Request>();
        DSTaskDueDatePB.DSTaskDueDatePB_Request testRequest = new DSTaskDueDatePB.DSTaskDueDatePB_Request();
        
        testRequest.contactRoleID = instantiateDBTask('','').Id; 
        testRequest.dueDate = 12;
        testRequest.subject = 'Test';
        testRequest.assignedTo = u.Id; 
        testRequest.status = 'Test';
        testRequest.taskType = 'Test'; 
        testRequest.priority = 'Test';
		testRequest.businessDaysOption = true; 
        testRequest.dateToday = Date.newInstance(2016, 12, 10);
        
        testRequestList.add(testRequest);
        
        Test.startTest(); 
        DSTaskDueDatePB.createFollowUpTasks(testRequestList);
        Test.stopTest();
    }
    
    @isTest 
    static void defaultTask2DaysSunday()
    {
        User u = [SELECT Id, IsActive FROM User WHERE IsActive = TRUE LIMIT 1];
        
        List<DSTaskDueDatePB.DSTaskDueDatePB_Request> testRequestList = new List<DSTaskDueDatePB.DSTaskDueDatePB_Request>();
        DSTaskDueDatePB.DSTaskDueDatePB_Request testRequest = new DSTaskDueDatePB.DSTaskDueDatePB_Request();
        
        testRequest.contactRoleID = instantiateDBTask('','').Id; 
        testRequest.dueDate = 12;
        testRequest.subject = 'Test';
        testRequest.assignedTo = u.Id; 
        testRequest.status = 'Test';
        testRequest.taskType = 'Test'; 
        testRequest.priority = 'Test';
		testRequest.businessDaysOption = true; 
        testRequest.dateToday = Date.newInstance(2016, 12, 11);
        
        testRequestList.add(testRequest);
        
        Test.startTest(); 
        DSTaskDueDatePB.createFollowUpTasks(testRequestList);
        Test.stopTest();
    }
    
    @isTest 
    static void defaultTask3DaysMonday()
    {
        User u = [SELECT Id, IsActive FROM User WHERE IsActive = TRUE LIMIT 1];
        
        List<DSTaskDueDatePB.DSTaskDueDatePB_Request> testRequestList = new List<DSTaskDueDatePB.DSTaskDueDatePB_Request>();
        DSTaskDueDatePB.DSTaskDueDatePB_Request testRequest = new DSTaskDueDatePB.DSTaskDueDatePB_Request();
        
        testRequest.contactRoleID = instantiateDBTask('','').Id; 
        testRequest.dueDate = 13;
        testRequest.subject = 'Test';
        testRequest.assignedTo = u.Id; 
        testRequest.status = 'Test';
        testRequest.taskType = 'Test'; 
        testRequest.priority = 'Test';
        testRequest.businessDaysOption = true; 
        testRequest.dateToday = Date.newInstance(2016, 12, 5);
        
        testRequestList.add(testRequest);
        
        Test.startTest(); 
        DSTaskDueDatePB.createFollowUpTasks(testRequestList);
        Test.stopTest();
    }
    
    @isTest 
    static void defaultTask3DaysWednesday()
    {
        User u = [SELECT Id, IsActive FROM User WHERE IsActive = TRUE LIMIT 1];
        
        List<DSTaskDueDatePB.DSTaskDueDatePB_Request> testRequestList = new List<DSTaskDueDatePB.DSTaskDueDatePB_Request>();
        DSTaskDueDatePB.DSTaskDueDatePB_Request testRequest = new DSTaskDueDatePB.DSTaskDueDatePB_Request();
        
        testRequest.contactRoleID = instantiateDBTask('','').Id; 
        testRequest.dueDate = 13;
        testRequest.subject = 'Test';
        testRequest.assignedTo = u.Id; 
        testRequest.status = 'Test';
        testRequest.taskType = 'Test'; 
        testRequest.priority = 'Test';
        testRequest.businessDaysOption = true; 
        testRequest.dateToday = Date.newInstance(2016, 12, 7);
        
        testRequestList.add(testRequest);
        
        Test.startTest(); 
        DSTaskDueDatePB.createFollowUpTasks(testRequestList);
        Test.stopTest();
    }
    
    @isTest 
    static void defaultTask3DaysSaturday()
    {
        User u = [SELECT Id, IsActive FROM User WHERE IsActive = TRUE LIMIT 1];
        
        List<DSTaskDueDatePB.DSTaskDueDatePB_Request> testRequestList = new List<DSTaskDueDatePB.DSTaskDueDatePB_Request>();
        DSTaskDueDatePB.DSTaskDueDatePB_Request testRequest = new DSTaskDueDatePB.DSTaskDueDatePB_Request();
        
        testRequest.contactRoleID = instantiateDBTask('','').Id; 
        testRequest.dueDate = 13;
        testRequest.subject = 'Test';
        testRequest.assignedTo = u.Id; 
        testRequest.status = 'Test';
        testRequest.taskType = 'Test'; 
        testRequest.priority = 'Test';
        testRequest.businessDaysOption = true; 
        testRequest.dateToday = Date.newInstance(2016, 12, 10);
        
        testRequestList.add(testRequest);
        
        Test.startTest(); 
        DSTaskDueDatePB.createFollowUpTasks(testRequestList);
        Test.stopTest();
    }
    
    @isTest 
    static void defaultTask3DaysSunday()
    {
        User u = [SELECT Id, IsActive FROM User WHERE IsActive = TRUE LIMIT 1];
        
        List<DSTaskDueDatePB.DSTaskDueDatePB_Request> testRequestList = new List<DSTaskDueDatePB.DSTaskDueDatePB_Request>();
        DSTaskDueDatePB.DSTaskDueDatePB_Request testRequest = new DSTaskDueDatePB.DSTaskDueDatePB_Request();
        
        testRequest.contactRoleID = instantiateDBTask('','').Id; 
        testRequest.dueDate = 13;
        testRequest.subject = 'Test';
        testRequest.assignedTo = u.Id; 
        testRequest.status = 'Test';
        testRequest.taskType = 'Test'; 
        testRequest.priority = 'Test';
        testRequest.businessDaysOption = true; 
        testRequest.dateToday = Date.newInstance(2016, 12, 11);
        
        testRequestList.add(testRequest);
        
        Test.startTest(); 
        DSTaskDueDatePB.createFollowUpTasks(testRequestList);
        Test.stopTest();
    }
    
    @isTest 
    static void defaultTask4DaysMonday()
    {
        User u = [SELECT Id, IsActive FROM User WHERE IsActive = TRUE LIMIT 1];
        
        List<DSTaskDueDatePB.DSTaskDueDatePB_Request> testRequestList = new List<DSTaskDueDatePB.DSTaskDueDatePB_Request>();
        DSTaskDueDatePB.DSTaskDueDatePB_Request testRequest = new DSTaskDueDatePB.DSTaskDueDatePB_Request();
        
        testRequest.contactRoleID = instantiateDBTask('','').Id; 
        testRequest.dueDate = 14;
        testRequest.subject = 'Test';
        testRequest.assignedTo = u.Id; 
        testRequest.status = 'Test';
        testRequest.taskType = 'Test'; 
        testRequest.priority = 'Test';
        testRequest.businessDaysOption = true; 
        testRequest.dateToday = Date.newInstance(2016, 12, 5);
        
        testRequestList.add(testRequest);
        
        Test.startTest(); 
        DSTaskDueDatePB.createFollowUpTasks(testRequestList);
        Test.stopTest();
    }
    
    @isTest 
    static void defaultTask4DaysTuesday()
    {
        User u = [SELECT Id, IsActive FROM User WHERE IsActive = TRUE LIMIT 1];
        
        List<DSTaskDueDatePB.DSTaskDueDatePB_Request> testRequestList = new List<DSTaskDueDatePB.DSTaskDueDatePB_Request>();
        DSTaskDueDatePB.DSTaskDueDatePB_Request testRequest = new DSTaskDueDatePB.DSTaskDueDatePB_Request();
        
        testRequest.contactRoleID = instantiateDBTask('','').Id; 
        testRequest.dueDate = 14;
        testRequest.subject = 'Test';
        testRequest.assignedTo = u.Id; 
        testRequest.status = 'Test';
        testRequest.taskType = 'Test'; 
        testRequest.priority = 'Test';
        testRequest.businessDaysOption = true; 
        testRequest.dateToday = Date.newInstance(2016, 12, 6);
        
        testRequestList.add(testRequest);
        
        Test.startTest(); 
        DSTaskDueDatePB.createFollowUpTasks(testRequestList);
        Test.stopTest();
    }
    
    @isTest
    static void defaultTask4DaysSaturday()
    {
        User u = [SELECT Id, IsActive FROM User WHERE IsActive = TRUE LIMIT 1];
        
        List<DSTaskDueDatePB.DSTaskDueDatePB_Request> testRequestList = new List<DSTaskDueDatePB.DSTaskDueDatePB_Request>();
        DSTaskDueDatePB.DSTaskDueDatePB_Request testRequest = new DSTaskDueDatePB.DSTaskDueDatePB_Request();
        
        testRequest.contactRoleID = instantiateDBTask('','').Id; 
        testRequest.dueDate = 14;
        testRequest.subject = 'Test';
        testRequest.assignedTo = u.Id; 
        testRequest.status = 'Test';
        testRequest.taskType = 'Test'; 
        testRequest.priority = 'Test';
        testRequest.businessDaysOption = true; 
        testRequest.dateToday = Date.newInstance(2016, 12, 10);
        
        testRequestList.add(testRequest);
        
        Test.startTest(); 
        DSTaskDueDatePB.createFollowUpTasks(testRequestList);
        Test.stopTest();
    }
    
    @isTest
    static void defaultTask4DaysSunday()
    {
        User u = [SELECT Id, IsActive FROM User WHERE IsActive = TRUE LIMIT 1];
        
        List<DSTaskDueDatePB.DSTaskDueDatePB_Request> testRequestList = new List<DSTaskDueDatePB.DSTaskDueDatePB_Request>();
        DSTaskDueDatePB.DSTaskDueDatePB_Request testRequest = new DSTaskDueDatePB.DSTaskDueDatePB_Request();
        
        testRequest.contactRoleID = instantiateDBTask('','').Id; 
        testRequest.dueDate = 14;
        testRequest.subject = 'Test';
        testRequest.assignedTo = u.Id; 
        testRequest.status = 'Test';
        testRequest.taskType = 'Test'; 
        testRequest.priority = 'Test';
        testRequest.businessDaysOption = true; 
        testRequest.dateToday = Date.newInstance(2016, 12, 11);
        
        testRequestList.add(testRequest);
        
        Test.startTest(); 
        DSTaskDueDatePB.createFollowUpTasks(testRequestList);
        Test.stopTest();
    }
    
    @isTest 
    static void defaultTask5DaysMonday()
    {
        User u = [SELECT Id, IsActive FROM User WHERE IsActive = TRUE LIMIT 1];
        
        List<DSTaskDueDatePB.DSTaskDueDatePB_Request> testRequestList = new List<DSTaskDueDatePB.DSTaskDueDatePB_Request>();
        DSTaskDueDatePB.DSTaskDueDatePB_Request testRequest = new DSTaskDueDatePB.DSTaskDueDatePB_Request();
        
        testRequest.contactRoleID = instantiateDBTask('','').Id; 
        testRequest.dueDate = 15;
        testRequest.subject = 'Test';
        testRequest.assignedTo = u.Id; 
        testRequest.status = 'Test';
        testRequest.taskType = 'Test'; 
        testRequest.priority = 'Test';
        testRequest.businessDaysOption = true; 
        testRequest.dateToday = Date.newInstance(2016, 12, 5);
        
        testRequestList.add(testRequest);
        
        Test.startTest(); 
        DSTaskDueDatePB.createFollowUpTasks(testRequestList);
        Test.stopTest();
    }
    
    @isTest 
    static void defaultTask5DaysSaturday()
    {
        User u = [SELECT Id, IsActive FROM User WHERE IsActive = TRUE LIMIT 1];
        
        List<DSTaskDueDatePB.DSTaskDueDatePB_Request> testRequestList = new List<DSTaskDueDatePB.DSTaskDueDatePB_Request>();
        DSTaskDueDatePB.DSTaskDueDatePB_Request testRequest = new DSTaskDueDatePB.DSTaskDueDatePB_Request();
        
        testRequest.contactRoleID = instantiateDBTask('','').Id; 
        testRequest.dueDate = 15;
        testRequest.subject = 'Test';
        testRequest.assignedTo = u.Id; 
        testRequest.status = 'Test';
        testRequest.taskType = 'Test'; 
        testRequest.priority = 'Test';
        testRequest.businessDaysOption = true; 
        testRequest.dateToday = Date.newInstance(2016, 12, 24);
        
        testRequestList.add(testRequest);
        
        Test.startTest(); 
        DSTaskDueDatePB.createFollowUpTasks(testRequestList);
        Test.stopTest();
    }
    
    @isTest 
    static void defaultTask5DaysSunday()
    {
        User u = [SELECT Id, IsActive FROM User WHERE IsActive = TRUE LIMIT 1];
        
        List<DSTaskDueDatePB.DSTaskDueDatePB_Request> testRequestList = new List<DSTaskDueDatePB.DSTaskDueDatePB_Request>();
        DSTaskDueDatePB.DSTaskDueDatePB_Request testRequest = new DSTaskDueDatePB.DSTaskDueDatePB_Request();
        
        testRequest.contactRoleID = instantiateDBTask('','').Id; 
        testRequest.dueDate = 15;
        testRequest.subject = 'Test';
        testRequest.assignedTo = u.Id; 
        testRequest.status = 'Test';
        testRequest.taskType = 'Test'; 
        testRequest.priority = 'Test';
        testRequest.businessDaysOption = true; 
        testRequest.dateToday = Date.newInstance(2016, 12, 25);
        
        testRequestList.add(testRequest);
        
        Test.startTest(); 
        DSTaskDueDatePB.createFollowUpTasks(testRequestList);
        Test.stopTest();
    }
    
    @isTest 
    static void defaultTaskOppInterested()
    {
        User u = [SELECT Id, IsActive FROM User WHERE IsActive = TRUE LIMIT 1];
        
        List<DSTaskDueDatePB.DSTaskDueDatePB_Request> testRequestList = new List<DSTaskDueDatePB.DSTaskDueDatePB_Request>();
        DSTaskDueDatePB.DSTaskDueDatePB_Request testRequest = new DSTaskDueDatePB.DSTaskDueDatePB_Request();
        
        testRequest.contactRoleID = instantiateDBTask('Altair Interested Prospect Opportunity','Task').Id; 
        testRequest.dueDate = 15;
        testRequest.subject = 'Test';
        testRequest.assignedTo = u.Id; 
        testRequest.status = 'Test';
        testRequest.taskType = 'Test'; 
        testRequest.priority = 'Test';
        testRequest.businessDaysOption = true; 
        testRequest.dateToday = Date.newInstance(2016, 12, 25);
        testRequest.createOpp = true; 
        
        testRequestList.add(testRequest);
        
        Test.startTest(); 
        DSTaskDueDatePB.createFollowUpTasks(testRequestList);
        Test.stopTest();
    }
    
    @isTest 
    static void defaultTaskOppNotInterested()
    {
        User u = [SELECT Id, IsActive FROM User WHERE IsActive = TRUE LIMIT 1];
        
        List<DSTaskDueDatePB.DSTaskDueDatePB_Request> testRequestList = new List<DSTaskDueDatePB.DSTaskDueDatePB_Request>();
        DSTaskDueDatePB.DSTaskDueDatePB_Request testRequest = new DSTaskDueDatePB.DSTaskDueDatePB_Request();
        
        testRequest.contactRoleID = instantiateDBTask('Altair Not Interested Prospect Opportunity','Task').Id; 
        testRequest.dueDate = 15;
        testRequest.subject = 'Test';
        testRequest.assignedTo = u.Id; 
        testRequest.status = 'Test';
        testRequest.taskType = 'Test'; 
        testRequest.priority = 'Test';
        testRequest.businessDaysOption = true; 
        testRequest.dateToday = Date.newInstance(2016, 12, 25);
        testRequest.createOpp = true; 
        
        testRequestList.add(testRequest);
        
        Test.startTest(); 
        DSTaskDueDatePB.createFollowUpTasks(testRequestList);
        Test.stopTest();
    }
    
    static public Contact_Role__c instantiateDBTask(String lastDisposition, String taskOrEvent)
    {
        Account testAcct = new Account(
            Name = 'Test Account'
        ); 
            
        insert testAcct; 
        
        Contact testContact = new Contact(
        	LastName = 'Test',
            Account = testAcct
        );
        
        insert testContact; 
        
        Contact_Role__c testContactRole;
        
        if (taskOrEvent == 'Task')
        {
            testContactRole = new Contact_Role__c (
                Account__c = testAcct.Id, 
                Contact__c = testContact.Id, 
                Type__c	= 'Student',
                Start_Date__c = Date.newInstance(2016, 12, 9),
                DS_Pending_Task_Date__c = Date.newInstance(2016, 12, 10),
                DS_Last_Disposition__c = lastDisposition
            );
        }
        
        else if (taskOrEvent == 'Event')
        {
            testContactRole = new Contact_Role__c (
                Account__c = testAcct.Id, 
                Contact__c = testContact.Id, 
                Type__c	= 'Student',
                Start_Date__c = Date.newInstance(2016, 12, 9),
                DS_Pending_Event_Date__c = Date.newInstance(2016, 12, 10)
        	);
        }
        
        else
        {
            testContactRole = new Contact_Role__c (
                Account__c = testAcct.Id, 
                Contact__c = testContact.Id, 
                Type__c	= 'Student',
                Start_Date__c = Date.newInstance(2016, 12, 9)
        	);
        }
        
        insert testContactRole; 
        
        //Insert a logged call
        Task loggedCall = new Task(
        	Subject = 'Call',
            Type__c = 'Outbound Call',
            Status = 'Completed',
            WhatId = testContactRole.Id,
            Description = 'Test'
        );
        
        insert loggedCall;
        
        return testContactRole;
    }
}