src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <formula>HYPERLINK(&quot;/&quot; + Id, &quot;Contact Record&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Record</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Contact_Role__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Contact_Role_Phone__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Role Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Eye Care Professional</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accounting</fullName>
                </value>
                <value>
                    <fullName>Board Member/ Officer</fullName>
                </value>
                <value>
                    <fullName>Dean</fullName>
                </value>
                <value>
                    <fullName>Doctor-Employee</fullName>
                </value>
                <value>
                    <fullName>Doctor-Owner</fullName>
                </value>
                <value>
                    <fullName>Doctor-Unspecified</fullName>
                </value>
                <value>
                    <fullName>Group Administrator</fullName>
                </value>
                <value>
                    <fullName>Lab Technician</fullName>
                </value>
                <value>
                    <fullName>Member</fullName>
                </value>
                <value>
                    <fullName>Office Administration</fullName>
                </value>
                <value>
                    <fullName>Office Manager</fullName>
                </value>
                <value>
                    <fullName>Optical Buyer</fullName>
                </value>
                <value>
                    <fullName>Optical Manager</fullName>
                </value>
                <value>
                    <fullName>Optician</fullName>
                </value>
                <value>
                    <fullName>Optician-Owner</fullName>
                </value>
                <value>
                    <fullName>Owner</fullName>
                </value>
                <value>
                    <fullName>Student</fullName>
                </value>
                <value>
                    <fullName>Unspecified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DSAddToQueueVSP_Test.cls
@isTest
private class DSAddToQueueVSP_Test
{
    @isTest static void testCallout1() 
    {
        // Set mock callout class 
       // Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator2());
        
        string res = DSAddToQueueVSP.httpPOSTrecord('http://api.salesforce.com/foo/bar', '', '');   
    }
    
    @isTest static void testCallout2() 
    {
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        
        Account testAccount = new Account (
            Name = 'Test',
            Phone = '5106480346'
        ); 
        
        insert testAccount; 
        
        Contact testContact = new Contact (
            LastName = 'Test',
            Account = testAccount
        );
        
        insert testContact; 
        
        Contact_Role__c testContactRole = new Contact_Role__c(
            Type__c = 'Test',
            Contact__c = testContact.Id, 
            Account__c = testAccount.Id,
            Contact_Role_Phone__c =  '5106480346'
        ); 
        
        insert testContactRole; 
        System.debug('Role Phone: ' + testContactRole.Contact_Role_Phone__c);
        
        User testUser = [SELECT Id FROM User WHERE IsActive = True LIMIT 1];
        
        String contactRoleId = '' + testContactRole.Id;
        String acctId = '' + testAccount.Id;  
        String userId = '' + testUser.Id; 
        
        System.debug(contactRoleId);
        
        //Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator3());
        string res2 = DSAddToQueueVSP.httpPOSTlist('Contact_Role_Phone__c', 'Account__c, Contact__c', contactRoleId, 'Contact_Role__c', testUser.Id, acctId);
    }
}