src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Bypass_VC_Validation_Rules__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass VC Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <formula>HYPERLINK(&quot;/&quot; + Id, &quot;Contact Record&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Record</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Status of Contact.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vision_Care_End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Vision Care End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vision_Care_Term_Reason__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vision Care Term Reason</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2</booleanFilter>
            <filterItems>
                <field>General_Table__c.Table__c</field>
                <operation>equals</operation>
                <value>PRS6</value>
            </filterItems>
            <filterItems>
                <field>General_Table__c.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>General_Table__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Contact_Role__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Eye Care Professional</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/General_Table__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Table__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Table</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>General Table</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>General Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force/src/objects/Network_Relationship__c.object
<CustomObject>
    <description>Custom object to track Payment Relationships between doctors and offices.</description>
    <fields>
        <fullName>Bypass_VC_Validation_Rules__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass VC Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact_Role__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact Role</label>
        <referenceTo>Contact_Role__c</referenceTo>
        <relationshipName>Payment_Relationships</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_End_Date__c</fullName>
        <label>Program End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Program_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup relationship field from Network Relationship to General Table object</description>
        <label>Program ID</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>General_Table__c.Table__c</field>
                <operation>equals</operation>
                <value>PRSP</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>General_Table__c</referenceTo>
        <relationshipLabel>Network Relationships</relationshipLabel>
        <relationshipName>Network_Relationships</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Provider Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Network Relationships</relationshipLabel>
        <relationshipName>Network_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Network Relationship</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Network Relationship Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Network Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force/src/objects/Skip_Trigger__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Skip_Triggers__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Skip all PROS Decommission-related Triggers on Account, Contact, Contact Role, and Network Relationship objects.</description>
        <label>Skip Triggers</label>
        <type>Checkbox</type>
    </fields>
    <label>Skip Trigger</label>
</CustomObject>

src/classes/VSPR25b_ContRoleNetRel.cls
public class VSPR25b_ContRoleNetRel {
    
    public static boolean conRoleNetRelAfterTriggerMethod_recursion = true;
    public void conRoleNetRelAfterTriggerMethod(List<Network_Relationship__c> newTrigger){
        
        if(conRoleNetRelAfterTriggerMethod_recursion){
            conRoleNetRelAfterTriggerMethod_recursion = false;
            
            system.debug('***** entered conRoleNetRelAfterTriggerMethod ***** ');
            
            List<Network_Relationship__c> listNRWithSameContactRole = new List<Network_Relationship__c>(); 
            Set<Network_Relationship__c> uniqueSet = new Set<Network_Relationship__c>();  
            List<Network_Relationship__c> noDups = new List<Network_Relationship__c>();    
            Boolean ProfileMatch = false; 
            Boolean isUpdate = false; 
            Boolean permissionSetFound = false; 
            Id profileId = userinfo.getProfileId();  
            Id currentUserId = userInfo.getUserid(); 
            Set<Id> ids = new Set<Id>();  
            Set<ID> setNetRelRoleIds = new Set<ID>();
            Set<id> conID=new Set<Id>();
            String profileName = [SELECT Id, Name 
                                  FROM Profile 
                                  WHERE Id = :profileId].Name;
            
            List<PermissionSetAssignment> listPSA = [SELECT id, PermissionSetId 
                                                     FROM PermissionSetAssignment 
                                                     WHERE AssigneeId = :currentUserId];  
            Skip_Trigger__c skip = Skip_Trigger__c.getInstance();
            if(skip.Skip_Triggers__c) { return;}    
            
            
            
            for(PermissionSetAssignment PSA : listPSA)  {  
                ids.add(PSA.PermissionSetId); 
            }
            
            List<PermissionSet> listPS = [SELECT name 
                                          FROM PermissionSet 
                                          WHERE id IN:ids];          
            
            for(PermissionSet PS: listPS) { 
                if(PS.Name == 'Credentialing_Data_Manager')  permissionSetFound = true; 
            }   
            
            if(profileName == 'VSP Network Recruitment User' || 
               profileName == 'VSP Network Recruitment Management User' ||
               (permissionSetFound == true )) { ProfileMatch = true; }        
            
            
            for(Network_Relationship__c netRels: newTrigger){  
                if(netRels.Contact_Role__c != null) 
                    setNetRelRoleIds.add(netRels.Contact_Role__c); 
                    conID.add(netRels.Provider_Name__c);
            }   
            
            List<Network_Relationship__c> listTest = [SELECT ID, Program_End_Date__c, Program_ID__r.Name, Contact_Role__c 
                                                      FROM Network_Relationship__c 
                                                      WHERE Program_ID__r.Name = 'VSP' 
                                                      AND Program_End_Date__c != null 
                                                      AND Contact_Role__c IN : setNetRelRoleIds];   
            
            map<String,list<Network_Relationship__c>> mpNRs = new map<String,list<Network_Relationship__c>>();
            for(Network_Relationship__c nr : [SELECT ID, Program_End_Date__c, Program_ID__r.Name,Contact_Role__c 
                                              FROM Network_Relationship__c 
                                              WHERE Contact_Role__c =: setNetRelRoleIds AND ID NOT IN :newTrigger]) {
                                                  if(!mpNRs.containskey(nr.Contact_Role__c)) {
                                                      mpNRs.put(nr.Contact_Role__c,new list<Network_Relationship__c>());
                                                  }
                                                  mpNRs.get(nr.Contact_Role__c).add(nr);
                                              }
            if(listTest.size() > 0) { 
                for(Network_Relationship__c nrOne : listTest) {
                    if(mpNRs.containsKey(nrOne.Contact_Role__c)) listNRWithSameContactRole = mpNRs.get(nrOne.Contact_Role__c); 
                    
                    if(listNRWithSameContactRole.size() >= 1){  
                        for(Network_Relationship__c nrc : listNRWithSameContactRole) {
                            if(nrc.Program_End_Date__c == NULL || nrc.Program_End_Date__c  > nrOne.Program_End_Date__c) { 
                                if(ProfileMatch) { 
                                    if(nrOne.Program_End_Date__c != null && !(nrOne.Program_End_Date__c < Date.Today())) {   
                                        nrc.Program_End_Date__c = nrOne.Program_End_Date__c; uniqueSet.add(nrc); 
                                    } 
                                } 
                            } 
                        }
                    } 
                } 
            }   
            
            for (Network_Relationship__c n : uniqueSet) { 
                noDups.add(n); 
            }if(noDups.size() > 0) { 
                database.update(noDups,false); 
                
                if(!conID.isEmpty()){///update contact and exclude noDups in Query below
                    
                    Map<String,Date> maxEndDateMap = new Map<String,Date>();
                    Map<String,Date> ActivemaxEndDateMap = new Map<String,Date>();
                    Map<String,Date> ActiveBlankEndDateMap = new Map<String,Date>();
                    Set<Contact> updateConSet =new Set<Contact>();
                    List<Network_Relationship__c> ActivemaxEndDateList = 
                        [SELECT id,Program_End_Date__c,Contact_Role__r.Contact__c, Provider_Name__c
                         FROM Network_Relationship__c 
                         WHERE Contact_Role__r.Contact__c in : conID AND Program_End_Date__c !=NULL AND Id NOT IN :noDups
                         ORDER BY Program_End_Date__c ASC];
                    
                    List<Network_Relationship__c> ActiveBlankEndDateList = 
                        [SELECT id,Program_End_Date__c,Contact_Role__r.Contact__c, Provider_Name__c
                         FROM Network_Relationship__c 
                         WHERE Contact_Role__r.Contact__c in : conID AND Program_End_Date__c = NULL AND Id NOT IN :noDups];
                    
                    
                    system.debug('ActivemaxEndDateList ' + ActivemaxEndDateList);
                    system.debug('ActiveBlankEndDateList ' + ActiveBlankEndDateList);
                    
                    for(Network_Relationship__c accX: ActivemaxEndDateList){
                        ActivemaxEndDateMap.put(accX.Provider_Name__c,accX.Program_End_Date__c);
                    }
                    
                    for(Network_Relationship__c accX: ActiveBlankEndDateList){
                        ActiveBlankEndDateMap.put(accX.Provider_Name__c,accX.Program_End_Date__c);
                    }
                    
                    system.debug('ActivemaxEndDateMap' + ActivemaxEndDateMap);
                    system.debug('ActiveBlankEndDateMap '+ ActiveBlankEndDateMap);
                    List<Contact> contoUpdtoActive = 
                        [SELECT id,Vision_Care_End_Date__c, Vision_Care_Term_Reason__c
                         FROM Contact 
                         WHERE Id =: conID]; 
                    
                    
                    List<General_Table__c> GT_List = new List<General_Table__c>();
                    
                    for(General_Table__c GT : [SELECT id FROM General_Table__c WHERE Name = '1PRC' AND Table__c = 'PRS6' AND Status__c = 'Active']){
                        GT_List.add(GT);
                    }        
                    
                    for(Contact actCon: contoUpdtoActive){                 
                        if(ActiveBlankEndDateMap.keySet().contains(actCon.Id)){
                            actCon.Vision_Care_End_Date__c = null;
                            actCon.Bypass_VC_Validation_Rules__c = true;
                            updateConSet.add(actCon);
                        }
                        else{
                            if(!GT_List.isEmpty()){
                                actCon.Vision_Care_End_Date__c = ActivemaxEndDateMap.get(actCon.Id);
                                actCon.Vision_Care_Term_Reason__c = GT_List[0].id;
                                actCon.Bypass_VC_Validation_Rules__c = true;
                                updateConSet.add(actCon);  
                            }
                            else{
                                actCon.Vision_Care_End_Date__c = ActivemaxEndDateMap.get(actCon.Id);
                                actCon.Bypass_VC_Validation_Rules__c = true;
                                updateConSet.add(actCon);  
                                
                            }
                        }                    
                    }
                    List<Contact> updateCon = new List<Contact>(updateConSet);
                    if(!updateCon.isEmpty()){
                        update updateCon;
                    } 
                }
                
            } 
            
            system.debug('***** exiting conRoleNetRelAfterTriggerMethod ***** ');
        }
    } 
}