src/objects/Contact_Role__c.object
<CustomObject>
    <fields>
        <fullName>DS_Datetime_of_Last_Disposition__c</fullName>
        <description>DialSource V3 &quot;Datetime of Last Disposition&quot; field for the Contact Role custom object</description>
        <encryptionScheme>None</encryptionScheme>
        <label>DS Datetime of Last Disposition</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DS_Last_Disposition__c</fullName>
        <description>DialSource V3 &quot;Last Disposition&quot; field for the Contact Role custom object</description>
        <encryptionScheme>None</encryptionScheme>
        <label>DS Last Disposition</label>
        <length>140</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DS_Total_Call_Count__c</fullName>
        <description>DialSource V3 field &quot;Total Call Count&quot; for the Contact Role custom object</description>
        <label>DS Total Call Count</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DSUpdateFieldsCustomVSP.cls
global class DSUpdateFieldsCustomVSP {
  private Map<Id,String> records;
  List<List<sObject>> objects = new List<List<sObject>>();
  string kind;
  
  public DSUpdateFieldsCustomVSP(Map<Id,String> records, string kind){
      this.records = records;
      this.kind = kind; 
      try{
          this.objects.add([SELECT Id, DS_Datetime_of_Last_Disposition__c, DS_Last_Disposition__c, DS_Total_Call_Count__c FROM Contact_Role__c WHERE Id IN: records.keySet() FOR UPDATE]);   
      }
      catch(exception e){
          System.debug('Failed to collect records.  Error: ' + e);
      }
  }
  
  public void updateFields(){
      
      if(kind == 'insert'){
          //iterate through objects and update fields
          System.debug('objects: ' + objects);
          for(List<sObject> l : objects){
                   for(sObject o : l){
                     if(o != null){

//Increase total call count by 1
                         if(o.get('DS_Total_Call_Count__c') == null){
                             o.put('DS_Total_Call_Count__c', 1);
                         }
                         else{
                             o.put('DS_Total_Call_Count__c', (Decimal)o.get('DS_Total_Call_Count__c') + 1);
                         }
                     }
                  }      
                  try{
                       update l;
                  }
                  catch(exception e){
                      System.debug('Failed to update list.  Error: ' + e);
                  }            
              }
      }
      
      if(kind == 'update'){
          //iterate through objects and update fields
          System.debug('objects: ' + objects);
          for(List<sObject> l : objects){
                   for(sObject o : l){
                     if(o != null){
                         
                         //Update DS Last Disposition 
                         o.put('DS_Last_Disposition__c', records.get(o.id));
                             
                         //Update DS Date of Last Disposition
                         o.put('DS_Datetime_of_Last_Disposition__c', DateTime.now());       
                     }
                  }      
                  try{
                      update l;
                  }
                  catch(exception e){
                      System.debug('Failed to update list.  Error: ' + e.getLineNumber() + ' ' + e.getCause());
                  }            
              }
      }
  }
}