src/objects/Contact_Role__c.object
<CustomObject>
    <fields>
        <fullName>VSP_Network_Provider__c</fullName>
        <defaultValue>false</defaultValue>
        <label>VSP Network Provider</label>
        <type>Checkbox</type>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force/src/objects/Network_Relationship__c.object
<CustomObject>
    <description>Custom object to track Payment Relationships between doctors and offices.</description>
    <fields>
        <fullName>Contact_Role__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact Role</label>
        <referenceTo>Contact_Role__c</referenceTo>
        <relationshipName>Payment_Relationships</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Effective_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Program Effective Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Program_End_Date__c</fullName>
        <label>Program End Date</label>
        <type>Date</type>
    </fields>
    <label>Network Relationship</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Network Relationship Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Network Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force/src/objects/Skip_Trigger__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Skip_Triggers__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Skip all PROS Decommission-related Triggers on Account, Contact, Contact Role, and Network Relationship objects.</description>
        <label>Skip Triggers</label>
        <type>Checkbox</type>
    </fields>
    <label>Skip Trigger</label>
</CustomObject>

src/classes/VSPR25b_CheckVSPnetworkProvider.cls
public class VSPR25b_CheckVSPnetworkProvider {
    
    public static boolean VSPR19b_checkVSPnetworkProviderMethod_recursion = true;
    public void VSPR19b_checkVSPnetworkProviderMethod(List<Network_Relationship__c> oldRecs, List<Network_Relationship__c> newRecs, Map<Id,Network_Relationship__c> oldRecsMap){
        
        if(VSPR19b_checkVSPnetworkProviderMethod_recursion || test.isRunningTest()){
            VSPR19b_checkVSPnetworkProviderMethod_recursion = false;
            
            system.debug('***** entered VSPR19b_checkVSPnetworkProviderMethod ***** ');
            Skip_Trigger__c skip = Skip_Trigger__c.getInstance();
            if(skip.Skip_Triggers__c) { return;}    
            
            Set<Contact_Role__c> cRolesToUpdateSet = new Set<Contact_Role__c>();
            if(trigger.isUpdate){
                
                List<Network_Relationship__c> netRel = 
                    [SELECT Id, Name, Program_Effective_Date__c, Program_End_Date__c, Contact_Role__r.Name, 
                     Contact_Role__r.Id, Contact_Role__r.VSP_Network_Provider__c, Contact_Role__c
                     FROM Network_Relationship__c 
                     WHERE Id =: newRecs];
                
                Set<string> cRoles = new Set<string>();
                for (Network_Relationship__c x : netRel){
                    if(x.Contact_Role__c != NULL){
                        cRoles.add(x.Contact_Role__c);
                    }
                }  
                
                /*
                List<Network_Relationship__c> netRelLst = 
                [SELECT Id, Program_End_Date__c, Program_Effective_Date__c, Contact_Role__c
                FROM Network_Relationship__c 
                WHERE Contact_Role__c =: cRoles 
                AND (Program_End_Date__c = NULL OR Program_End_Date__c >= TODAY)
                AND Program_Effective_Date__c <= TODAY];  */ 
                
                map<string,Integer> count1 = new Map<string,Integer>();
                AggregateResult[] netRelCounts = 
                    [SELECT Contact_Role__c Id, COUNT(Id) netRelCount 
                     FROM Network_Relationship__c 
                     WHERE Contact_Role__c =: cRoles 
                     AND (Program_End_Date__c = NULL OR Program_End_Date__c >= TODAY)
                     AND Program_Effective_Date__c <= TODAY
                     GROUP BY Contact_Role__c];
                system.debug('netRelCounts: '+netRelCounts);
                for(AggregateResult ar : netRelCounts){
                    count1.put((string)ar.get('Id'), (Integer)ar.get('netRelCount'));
                }
                system.debug('count1: '+count1);   
                
                for(Network_Relationship__c nr: newRecs){      
                    if(oldRecsMap.get(nr.Id).Program_End_Date__c != nr.Program_End_Date__c){
                        if(count1.get(nr.Contact_Role__c) > 0){
                            Contact_Role__c crX = new Contact_Role__c(Id=nr.Contact_Role__c);
                            crX.VSP_Network_Provider__c = TRUE;
                            cRolesToUpdateSet.add(crX);  
                        }else{
                            Contact_Role__c crX = new Contact_Role__c(Id=nr.Contact_Role__c);
                            crX.VSP_Network_Provider__c = FALSE;
                            cRolesToUpdateSet.add(crX);
                        }                      
                    }            
                }
            }
            
            if(trigger.isDelete){
                
                List<Network_Relationship__c> netRel = 
                    [SELECT Id, Name, Program_Effective_Date__c, Program_End_Date__c, Contact_Role__r.Name, 
                     Contact_Role__r.Id, Contact_Role__r.VSP_Network_Provider__c, Contact_Role__c
                     FROM Network_Relationship__c 
                     WHERE Id =: oldRecs];
                
                Map<Id, Network_Relationship__c> netRelMap = new Map<Id, Network_Relationship__c>([SELECT Id, Contact_Role__r.Id FROM Network_Relationship__c WHERE 
                                                                                                   Id =: oldRecs AND Contact_Role__c != NULL]);
                Set<string> cRoles = new Set<string>();
                for (Network_Relationship__c x : netRel){
                    if(x.Contact_Role__c != NULL){
                        cRoles.add(x.Contact_Role__c);
                    }
                }  
                
                /*
                List<Network_Relationship__c> netRelLst = 
                [SELECT Id, Program_End_Date__c, Program_Effective_Date__c, Contact_Role__c
                FROM Network_Relationship__c 
                WHERE Contact_Role__c =: cRoles 
                AND (Program_End_Date__c = NULL OR Program_End_Date__c >= TODAY)
                AND Program_Effective_Date__c <= TODAY];*/
                
                map<string,Integer> count1 = new Map<string,Integer>();
                AggregateResult[] netRelCounts = 
                    [SELECT Contact_Role__c Id, COUNT(Id) netRelCount 
                     FROM Network_Relationship__c 
                     WHERE Contact_Role__c =: cRoles 
                     AND (Program_End_Date__c = NULL OR Program_End_Date__c >= TODAY)
                     AND Program_Effective_Date__c <= TODAY
                     GROUP BY Contact_Role__c];
                system.debug('netRelCounts: '+netRelCounts);
                for(AggregateResult ar : netRelCounts){
                    count1.put((string)ar.get('Id'), (Integer)ar.get('netRelCount'));
                }
                system.debug('count1: '+count1);   
                
                for(Network_Relationship__c nr: oldRecs){      
                    if(oldRecsMap.get(nr.Id).Program_End_Date__c != nr.Program_End_Date__c){
                        if(count1.get(nr.Contact_Role__c) > 0){
                            Contact_Role__c crX = new Contact_Role__c(Id=nr.Contact_Role__c);
                            crX.VSP_Network_Provider__c = TRUE;
                            cRolesToUpdateSet.add(crX);  
                        }else{
                            Contact_Role__c crX = new Contact_Role__c(Id=nr.Contact_Role__c);
                            crX.VSP_Network_Provider__c = FALSE;
                            cRolesToUpdateSet.add(crX);
                        }                      
                    }            
                }
            }  
            
            List<Contact_Role__c> cRolesToUpdate = new List<Contact_Role__c>(cRolesToUpdateSet);
            if(!cRolesToUpdate.isEmpty()){
                update cRolesToUpdate;
            }
        }
    }
}