src/objects/Knowledge__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <page>Knowledge_VFP</page>
            <template>Page</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <fields>
        <fullName>Additional_Benefits__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Additional Benefits</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Additional_Information__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Additional Information</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Article_Details__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Article Details</label>
        <length>41000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Benefit_Effective_Data__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Date that enrolled benifits become effective</inlineHelpText>
        <label>Benefit Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Benefit__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Client-specific benefits</inlineHelpText>
        <label>Benefit</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Change_Cancel__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Change/Cancel</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Confirmation__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Confirmation</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Contacts__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Contacts</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Details__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Details</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Doctor_Network__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Doctor Network</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Eligibility__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>client requirements for eligibility</inlineHelpText>
        <label>Eligibility</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Enrollment_End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Date that open enrollments closes for members</inlineHelpText>
        <label>Enrollment End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Enrollment_Start_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Date that enrollment opens up for members</inlineHelpText>
        <label>Enrollment Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Exam__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Exam</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Frame__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Frame</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>General_Description__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>General Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>How_To_Enroll__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>How To Enroll</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Keywords__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Keywords</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Lab__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Lab</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Lens_Enhancements__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Lens Enhancements</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Lens__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Lens</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Premiums_and_Billing__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Premiums and Billing</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Procedure__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Procedure</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Review_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Review Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Support_Queue_Steps__c</fullName>
        <description>Restrict visibility by Profile - visible to all users across the company EXCEPT Processors, CSR&apos;s, Hybrid CSR&apos;s and CART</description>
        <encryptionScheme>None</encryptionScheme>
        <label>SQ/QQ Steps</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Topic_Links__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Topic Links</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Version_Comments__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Version Comments</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
    <recordTypes>
        <fullName>Additional_Benefits</fullName>
        <active>true</active>
        <label>Additional Benefits</label>
    </recordTypes>
    <recordTypes>
        <fullName>C_G_Article</fullName>
        <active>true</active>
        <label>C&amp;G Article</label>
    </recordTypes>
    <recordTypes>
        <fullName>Core_Benefit</fullName>
        <active>true</active>
        <label>Core Benefit</label>
    </recordTypes>
    <recordTypes>
        <fullName>External_Publication</fullName>
        <active>true</active>
        <label>External Publication</label>
    </recordTypes>
    <recordTypes>
        <fullName>Multi_Topic</fullName>
        <active>true</active>
        <label>Multi Topic</label>
    </recordTypes>
    <recordTypes>
        <fullName>Multi_Topic_Details</fullName>
        <active>true</active>
        <label>Multi Topic Details</label>
    </recordTypes>
    <recordTypes>
        <fullName>Open_Enrollment</fullName>
        <active>true</active>
        <label>Open Enrollment</label>
    </recordTypes>
    <recordTypes>
        <fullName>Procedure</fullName>
        <active>true</active>
        <label>Procedure</label>
    </recordTypes>
    <recordTypes>
        <fullName>Single_Topic</fullName>
        <active>true</active>
        <label>Single Topic</label>
    </recordTypes>
    <recordTypes>
        <fullName>Support_Queue</fullName>
        <active>true</active>
        <label>Support Queue</label>
    </recordTypes>
    <recordTypes>
        <fullName>Universal_Service</fullName>
        <active>true</active>
        <label>Universal Service</label>
    </recordTypes>
</CustomObject>

src/objects/QNews__c.object
<CustomObject>
    <description>Container for published version comments for Customer Care knowledge articles</description>
    <fields>
        <fullName>Article_Title__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Article Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Article_Type__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Article Type</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ForSharePointService__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ForSharePointService</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Version_Comments__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Version Comments</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Version_History_Version_Id__c</fullName>
        <description>Sourced from Article Type_VersionHistory.VersionId</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Version History Version Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>QNews</label>
    <nameField>
        <displayFormat>QN-{0}</displayFormat>
        <label>QNews ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QNews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/QNewsAttachmentUtility.cls
public with sharing class QNewsAttachmentUtility{

    public void saveAttachmentToQNews(List<QNews__c> lstQNews){
        List<Attachment> attachments = new List<Attachment>();
        try{
            for(QNews__c qnewsObj:lstQNews){
                if(qnewsObj.ForSharePointService__c==true && qnewsObj.Article_Type__c!='') {
                    String strContent = '<HTML><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><title>HTML TO WORD</title></head><BODY >';
                    if(qnewsObj.Article_Type__c.equalsIgnoreCase('Additional_Benefits')){
                        for(Knowledge__kav obj:[Select Id,Title,ArticleNumber,VersionNumber,LastPublishedDate,Version_Comments__c,Exam__c,Lens__c,Lens_Enhancements__c,Frame__c,Contacts__c,Doctor_Network__c,Lab__c,Support_Queue_Steps__c from Knowledge__kav where Id=:qnewsObj.Version_History_Version_Id__c]){
                            strContent = strContent + '<P>' + 'Title' + ': ' +obj.Title + '</P>';
                            strContent = strContent + '<P>' + 'ArticleNumber' + ': ' +obj.ArticleNumber + '</P>';
                            strContent = strContent + '<P>' + 'VersionNumber' + ': ' +obj.VersionNumber + '</P>';
                            strContent = strContent + '<P>' + 'LastPublishedDate' + ': ' +obj.LastPublishedDate + '</P>';
                            strContent = strContent + '<P>' + 'Exam' + ': ' +obj.Exam__c + '</P>';
                            strContent = strContent + '<P>' + 'Lens' + ': ' +obj.Lens__c + '</P>';
                            strContent = strContent + '<P>' + 'Lens Enhancement ' + ': ' +obj.Lens_Enhancements__c + '</P>';
                            strContent = strContent + '<P>' + 'Frame' + ': ' +obj.Frame__c + '</P>';
                            strContent = strContent + '<P>' + 'Contacts" value' + ': ' +obj.Contacts__c + '</P>';
                            strContent = strContent + '<P>' + 'Doctor Network' + ': ' +obj.Doctor_Network__c + '</P>';
                            strContent = strContent + '<P>' + 'Lab' + ': ' +obj.Lab__c + '</P>';
                            strContent = strContent + '<P>' + 'Supportqueue Steps' + ': ' +obj.Support_Queue_Steps__c + '</P>';
                            strContent = strContent + '<P>' + 'Version Comments' + ': ' +obj.Version_Comments__c + '</P>';
                        }
                    }
                    
                    if(qnewsObj.Article_Type__c.equalsIgnoreCase('Single_Topic')){
                        for(Knowledge__kav obj:[Select Id,Title,ArticleNumber,VersionNumber,LastPublishedDate,Version_Comments__c,Article_Details__c,Support_Queue_Steps__c from Knowledge__kav where id=:qnewsObj.Version_History_Version_Id__c]){
                            strContent = strContent + '<P>' + 'Title' + ': ' +obj.Title + '</P>';
                            strContent = strContent + '<P>' + 'ArticleNumber' + ': ' +obj.ArticleNumber + '</P>';
                            strContent = strContent + '<P>' + 'VersionNumber' + ': ' +obj.VersionNumber + '</P>';
                            strContent = strContent + '<P>' + 'LastPublishedDate' + ': ' +obj.LastPublishedDate + '</P>';
                            strContent = strContent + '<P>' + 'Article Details' + ': ' +obj.Article_Details__c + '</P>';
                            strContent = strContent + '<P>' + 'SupportQueueSteps' + ': ' +obj.Support_Queue_Steps__c + '</P>';
                            strContent = strContent + '<P>' + 'Version Comments' + ': ' +obj.Version_Comments__c + '</P>';
                        }
                    }
                    
                    if(qnewsObj.Article_Type__c.equalsIgnoreCase('Support_Queue')){
                        for(Knowledge__kav obj:[Select Id,Title,ArticleNumber,VersionNumber,LastPublishedDate,Version_Comments__c,Article_Details__c,Support_Queue_Steps__c from Knowledge__kav where id=:qnewsObj.Version_History_Version_Id__c]){
                            strContent = strContent + '<P>' + 'Title' + ': ' +obj.Title + '</P>';
                            strContent = strContent + '<P>' + 'ArticleNumber' + ': ' +obj.ArticleNumber + '</P>';
                            strContent = strContent + '<P>' + 'VersionNumber' + ': ' +obj.VersionNumber + '</P>';
                            strContent = strContent + '<P>' + 'LastPublishedDate' + ': ' +obj.LastPublishedDate + '</P>';
                            strContent = strContent + '<P>' + 'Article Details' + ': ' +obj.Article_Details__c + '</P>';
                            strContent = strContent + '<P>' + 'SupportQueueSteps' + ': ' +obj.Support_Queue_Steps__c + '</P>';
                            strContent = strContent + '<P>' + 'Version Comments' + ': ' +obj.Version_Comments__c + '</P>';
                        }
                    }
                    
                    if(qnewsObj.Article_Type__c.equalsIgnoreCase('Universal_Service')){
                        for(Knowledge__kav obj:[Select Id,Title,ArticleNumber,VersionNumber,LastPublishedDate,Version_Comments__c,Article_Details__c,Support_Queue_Steps__c from Knowledge__kav where id=:qnewsObj.Version_History_Version_Id__c]){
                            strContent = strContent + '<P>' + 'Title' + ': ' +obj.Title + '</P>';
                            strContent = strContent + '<P>' + 'ArticleNumber' + ': ' +obj.ArticleNumber + '</P>';
                            strContent = strContent + '<P>' + 'VersionNumber' + ': ' +obj.VersionNumber + '</P>';
                            strContent = strContent + '<P>' + 'LastPublishedDate' + ': ' +obj.LastPublishedDate + '</P>';
                            strContent = strContent + '<P>' + 'Article Details' + ': ' +obj.Article_Details__c + '</P>';
                            strContent = strContent + '<P>' + 'SupportQueueSteps' + ': ' +obj.Support_Queue_Steps__c + '</P>';
                            strContent = strContent + '<P>' + 'Version Comments' + ': ' +obj.Version_Comments__c + '</P>';
                        }
                    }
                    
                    if(qnewsObj.Article_Type__c.equalsIgnoreCase('C_G_Article')){
                        for(Knowledge__kav obj:[Select Id,Title,ArticleNumber,VersionNumber,LastPublishedDate,Version_Comments__c,Article_Details__c,Support_Queue_Steps__c from Knowledge__kav where id=:qnewsObj.Version_History_Version_Id__c]){
                            strContent = strContent + '<P>' + 'Title' + ': ' +obj.Title + '</P>';
                            strContent = strContent + '<P>' + 'ArticleNumber' + ': ' +obj.ArticleNumber + '</P>';
                            strContent = strContent + '<P>' + 'VersionNumber' + ': ' +obj.VersionNumber + '</P>';
                            strContent = strContent + '<P>' + 'LastPublishedDate' + ': ' +obj.LastPublishedDate + '</P>';
                            strContent = strContent + '<P>' + 'Article Details' + ': ' +obj.Article_Details__c + '</P>';
                            strContent = strContent + '<P>' + 'SupportQueueSteps' + ': ' +obj.Support_Queue_Steps__c + '</P>';
                            strContent = strContent + '<P>' + 'Version Comments' + ': ' +obj.Version_Comments__c + '</P>';
                        }
                    }
                    
                    if(qnewsObj.Article_Type__c.equalsIgnoreCase('Procedure')){
                        for(Knowledge__kav obj:[Select Id,Title,ArticleNumber,VersionNumber,LastPublishedDate,Procedure__c,Additional_Information__c,Keywords__c, Review_Date__c  from Knowledge__kav where id=:qnewsObj.Version_History_Version_Id__c]){
                            strContent = strContent + '<P>' + 'Title' + ': ' +obj.Title + '</P>';
                            strContent = strContent + '<P>' + 'ArticleNumber' + ': ' +obj.ArticleNumber + '</P>';
                            strContent = strContent + '<P>' + 'VersionNumber' + ': ' +obj.VersionNumber + '</P>';
                            strContent = strContent + '<P>' + 'LastPublishedDate' + ': ' +obj.LastPublishedDate + '</P>';
                            strContent = strContent + '<P>' + 'Procedure' + ': ' +obj.Procedure__c + '</P>';
                            strContent = strContent + '<P>' + 'Additional Information' + ': ' +obj.Additional_Information__c + '</P>';
                            strContent = strContent + '<P>' + 'Keywords' + ': ' +obj.Keywords__c + '</P>';
                            strContent = strContent + '<P>' + 'Review Date' + ': ' +obj.Review_Date__c + '</P>';
                        }
                    }
                    
                    if(qnewsObj.Article_Type__c.equalsIgnoreCase('External_Publication')){
                        for(Knowledge__kav obj:[Select Id,Title,ArticleNumber,VersionNumber,LastPublishedDate,Details__c, Version_Comments__c  from Knowledge__kav where id=:qnewsObj.Version_History_Version_Id__c]){
                            strContent = strContent + '<P>' + 'Title' + ': ' +obj.Title + '</P>';
                            strContent = strContent + '<P>' + 'ArticleNumber' + ': ' +obj.ArticleNumber + '</P>';
                            strContent = strContent + '<P>' + 'VersionNumber' + ': ' +obj.VersionNumber + '</P>';
                            strContent = strContent + '<P>' + 'LastPublishedDate' + ': ' +obj.LastPublishedDate + '</P>';
                            strContent = strContent + '<P>' + 'Details' + ': ' +obj.Details__c + '</P>';
                            strContent = strContent + '<P>' + 'Version Comments' + ': ' +obj.Version_Comments__c + '</P>';
                        }
                    }
                    
                    if(qnewsObj.Article_Type__c.equalsIgnoreCase('Core_Benefit')){
                        for(Knowledge__kav obj:[Select Id,Title,ArticleNumber,VersionNumber,LastPublishedDate,Version_Comments__c,Exam__c,Lens__c,Lens_Enhancements__c,Frame__c,Contacts__c,Doctor_Network__c,Lab__c,Support_Queue_Steps__c,Additional_Benefits__c from Knowledge__kav where id=:qnewsObj.Version_History_Version_Id__c]){
                            strContent = strContent + '<P>' + 'Title' + ': ' +obj.Title + '</P>';
                            strContent = strContent + '<P>' + 'ArticleNumber' + ': ' +obj.ArticleNumber + '</P>';
                            strContent = strContent + '<P>' + 'VersionNumber' + ': ' +obj.VersionNumber + '</P>';
                            strContent = strContent + '<P>' + 'LastPublishedDate' + ': ' +obj.LastPublishedDate + '</P>';
                            strContent = strContent + '<P>' + 'Exam' + ': ' +obj.Exam__c + '</P>';
                            strContent = strContent + '<P>' + 'Lens' + ': ' +obj.Lens__c + '</P>';
                            strContent = strContent + '<P>' + 'Lens Enhancement ' + ': ' +obj.Lens_Enhancements__c + '</P>';
                            strContent = strContent + '<P>' + 'Frame' + ': ' +obj.Frame__c + '</P>';
                            strContent = strContent + '<P>' + 'Contacts" value' + ': ' +obj.Contacts__c + '</P>';
                            strContent = strContent + '<P>' + 'Doctor Network' + ': ' +obj.Doctor_Network__c + '</P>';
                            strContent = strContent + '<P>' + 'Lab' + ': ' +obj.Lab__c + '</P>';
                            strContent = strContent + '<P>' + 'Additional Benefits' + ': ' +obj.Additional_Benefits__c + '</P>';
                            strContent = strContent + '<P>' + 'SupportQueueSteps' + ': ' +obj.Support_Queue_Steps__c + '</P>';
                            strContent = strContent + '<P>' + 'Version Comments' + ': ' +obj.Version_Comments__c + '</P>';
                        }
                    }
                    
                    if(qnewsObj.Article_Type__c.equalsIgnoreCase('Multi_Topic')){
                        for(Knowledge__kav obj:[Select Id,Title,ArticleNumber,VersionNumber,LastPublishedDate,Version_Comments__c,Article_Details__c,Topic_Links__c,Support_Queue_Steps__c from Knowledge__kav where id=:qnewsObj.Version_History_Version_Id__c]){
                            strContent = strContent + '<P>' + 'Title' + ': ' +obj.Title + '</P>';
                            strContent = strContent + '<P>' + 'ArticleNumber' + ': ' +obj.ArticleNumber + '</P>';
                            strContent = strContent + '<P>' + 'VersionNumber' + ': ' +obj.VersionNumber + '</P>';
                            strContent = strContent + '<P>' + 'LastPublishedDate' + ': ' +obj.LastPublishedDate + '</P>';
                            strContent = strContent + '<P>' + 'Article Details' + ': ' +obj.Article_Details__c + '</P>';
                            strContent = strContent + '<P>' + 'Topic Links' + ': ' +obj.Topic_Links__c + '</P>';
                            strContent = strContent + '<P>' + 'Support Queue Steps ' + ': ' +obj.Support_Queue_Steps__c + '</P>';
                            strContent = strContent + '<P>' + 'Version Comments' + ': ' +obj.Version_Comments__c + '</P>';
                        }
                    }
                    
                    if(qnewsObj.Article_Type__c.equalsIgnoreCase('Multi_Topic_Details')){
                        for(Knowledge__kav obj:[Select Id,Title,ArticleNumber,VersionNumber,LastPublishedDate,Version_Comments__c,Article_Details__c,Support_Queue_Steps__c from Knowledge__kav where id=:qnewsObj.Version_History_Version_Id__c]){
                            strContent = strContent + '<P>' + 'Title' + ': ' +obj.Title + '</P>';
                            strContent = strContent + '<P>' + 'ArticleNumber' + ': ' +obj.ArticleNumber + '</P>';
                            strContent = strContent + '<P>' + 'VersionNumber' + ': ' +obj.VersionNumber + '</P>';
                            strContent = strContent + '<P>' + 'LastPublishedDate' + ': ' +obj.LastPublishedDate + '</P>';
                            strContent = strContent + '<P>' + 'Article Details' + ': ' +obj.Article_Details__c + '</P>';
                            strContent = strContent + '<P>' + 'Support Queue Steps ' + ': ' +obj.Support_Queue_Steps__c + '</P>';
                            strContent = strContent + '<P>' + 'Version Comments' + ': ' +obj.Version_Comments__c + '</P>';
                        }
                    }
                    
                    if(qnewsObj.Article_Type__c.equalsIgnoreCase('Open_Enrollment')){
                        for(Knowledge__kav obj:[Select Id,Title,ArticleNumber,VersionNumber,LastPublishedDate,Version_Comments__c,Enrollment_Start_Date__c,Enrollment_End_Date__c,Benefit_Effective_Data__c,General_Description__c,Benefit__c,Eligibility__c,How_To_Enroll__c,Premiums_and_Billing__c,Confirmation__c,Change_Cancel__c,Support_Queue_Steps__c from Knowledge__kav where id=:qnewsObj.Version_History_Version_Id__c]){
                            strContent = strContent + '<P>' + 'Title' + ': ' +obj.Title + '</P>';
                            strContent = strContent + '<P>' + 'ArticleNumber' + ': ' +obj.ArticleNumber + '</P>';
                            strContent = strContent + '<P>' + 'VersionNumber' + ': ' +obj.VersionNumber + '</P>';
                            strContent = strContent + '<P>' + 'LastPublishedDate' + ': ' +obj.LastPublishedDate + '</P>';
                            strContent = strContent + '<P>' + 'Enrollment Start Date' + ': ' +obj.Enrollment_Start_Date__c + '</P>';
                            strContent = strContent + '<P>' + 'Enrollment End Date ' + ': ' +obj.Enrollment_End_Date__c + '</P>';
                            strContent = strContent + '<P>' + 'Benefits Effective Date ' + ': ' +obj.Benefit_Effective_Data__c + '</P>';
                            strContent = strContent + '<P>' + 'General Description ' + ': ' +obj.General_Description__c + '</P>';
                            strContent = strContent + '<P>' + 'Benefits ' + ': ' +obj.Benefit__c + '</P>';
                            strContent = strContent + '<P>' + 'Eligibility ' + ': ' +obj.Eligibility__c + '</P>';
                            strContent = strContent + '<P>' + 'How to Enroll ' + ': ' +obj.How_To_Enroll__c + '</P>';
                            strContent = strContent + '<P>' + 'Premiums and Billing ' + ': ' +obj.Premiums_and_Billing__c + '</P>';
                            strContent = strContent + '<P>' + 'Confirmation ' + ': ' +obj.Confirmation__c + '</P>';
                            strContent = strContent + '<P>' + 'Change or Cancel ' + ': ' +obj.Change_Cancel__c + '</P>';
                            strContent = strContent + '<P>' + 'Support Queue Steps ' + ': ' +obj.Support_Queue_Steps__c + '</P>';
                            strContent = strContent + '<P>' + 'Version Comments' + ': ' +obj.Version_Comments__c + '</P>';
                        }
                    }
                    
                    strContent = strContent + '</BODY></HTML>';
                    Attachment attachmentPDF = new Attachment();
                    attachmentPDF.parentId = qnewsObj.Id;
                    //attachmentPDF.Name = qnewsObj.Article_Title__c + '.doc';
                    attachmentPDF.Name = qnewsObj.Article_Title__c;
                    system.debug('attachmentPDF.Name = '+qnewsObj.Article_Title__c);
                    attachmentPDF.body = Blob.valueOf(strContent); 
                    attachments.add(attachmentPDF);
                    //insert attachmentPDF;
                    
                    system.debug('-----attachmentPDF--------'+attachmentPDF);
                }
            }
            if(attachments!=null && attachments.size()>0)
                insert attachments;
        }
        catch(Exception e)
        {
            system.debug('--------Exception occured---------'+e);
        }
    }
}