src/objects/MPM4_BASE__Milestone1_Milestone__c.object
<CustomObject>
</CustomObject>

force/src/objects/MPM4_BASE__Milestone1_Milestone__c.object
    <fields>
        <fullName>MPM4_BASE__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The project this milestone is assigned to. If this is a sub-milestone this field is empty.</inlineHelpText>
        <label>Project</label>
        <referenceTo>MPM4_BASE__Milestone1_Project__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Project_Milestones</relationshipName>
        <type>Lookup</type>
    </fields>

src/objects/MPM4_BASE__Milestone1_Project__c.object
<CustomObject>
</CustomObject>

force/src/objects/MPM4_BASE__Milestone1_Project__c.object
    <fields>
        <fullName>MPM4_BASE__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>

force/src/objects/MPM4_BASE__Milestone1_Task__c.object
<CustomObject>
    <description>Passage Technology - Milestones PM+ Free Edition - An activity that has hours, budget, and is assigned to a User.</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MPM4_BASE__Project_Milestone__c</fullName>
        <inlineHelpText>The milestone that this task is assigned to.</inlineHelpText>
        <label>Milestone</label>
        <referenceTo>MPM4_BASE__Milestone1_Milestone__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MPM4_BASE__Project__c</fullName>
        <formula>HYPERLINK(&quot;/&quot; &amp; MPM4_BASE__Project_Milestone__r.MPM4_BASE__Project__c, MPM4_BASE__Project_Milestone__r.MPM4_BASE__Project__r.Name,&apos;_self&apos;)</formula>
        <inlineHelpText>A link to the Project which this task is included in via its milestone.</inlineHelpText>
        <label>Project</label>
        <type>Text</type>
    </fields>
    <label>Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MPM_Plus_Task_Customization_Behaviour.cls
@isTest
public class MPM_Plus_Task_Customization_Behaviour {
	
    static testmethod void shouldUpdateTaskWithAccountWhenNewTaskIsCreated(){
        Account testAccount = new Account(Name='Test Account');
        insert testAccount;
        
		MPM4_BASE__Milestone1_Project__c testProject = new MPM4_BASE__Milestone1_Project__c(Name='Test Project', MPM4_BASE__Account__c=testAccount.Id);
        insert testProject;
        
        MPM4_BASE__Milestone1_Milestone__c testMilestone = new MPM4_BASE__Milestone1_Milestone__c(Name='Test Milestone', MPM4_BASE__Project__c=testProject.Id);
        insert testMilestone;
        
        MPM4_BASE__Milestone1_Task__c testTask = new MPM4_BASE__Milestone1_Task__c(Name='Test Task', MPM4_BASE__Project_Milestone__c=testMilestone.Id);
        insert testTask;
        
        MPM4_BASE__Milestone1_Task__c verifyAccountOnTask = [SELECT Account_Name__c FROM MPM4_BASE__Milestone1_Task__c WHERE Id = :testTask.Id LIMIT 1];
        
        System.assertEquals(testAccount.Id, verifyAccountOnTask.Account_Name__c);
	}
    
    static testmethod void shouldUpdateMPMPlusTaskWithAccountWhenAssignedToProject() {
        Account testAccount = new Account(Name='Test Account');
        insert testAccount;
        
		MPM4_BASE__Milestone1_Project__c testProject = new MPM4_BASE__Milestone1_Project__c(Name='Test Project');
        insert testProject;
        
        MPM4_BASE__Milestone1_Milestone__c testMilestone = new MPM4_BASE__Milestone1_Milestone__c(Name='Test Milestone', MPM4_BASE__Project__c=testProject.Id);
        insert testMilestone;
        
        MPM4_BASE__Milestone1_Task__c testTask = new MPM4_BASE__Milestone1_Task__c(Name='Test Task', MPM4_BASE__Project_Milestone__c=testMilestone.Id);
        insert testTask;
        
        MPM4_BASE__Milestone1_Task__c verifyAccountOnTask = [SELECT Account_Name__c FROM MPM4_BASE__Milestone1_Task__c WHERE Id = :testTask.Id LIMIT 1];
        
        System.assertNotEquals(testAccount.Id, verifyAccountOnTask.Account_Name__c);
        
        testProject.MPM4_BASE__Account__c = testAccount.Id;
        upsert testProject;
        
        verifyAccountOnTask = [SELECT Account_Name__c FROM MPM4_BASE__Milestone1_Task__c WHERE Id = :testTask.Id LIMIT 1];
        
        System.assertEquals(testAccount.Id, verifyAccountOnTask.Account_Name__c);
    }
}