src/objects/Sales_Goals__c.object
<CustomObject>
    <description>Used to store monthly and quarterly sales goals per user.</description>
    <fields>
        <fullName>Goal_Timeline__c</fullName>
        <label>Goal Timeline</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Annually</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Goal_Type__c</fullName>
        <label>Goal Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Dollars</fullName>
                </value>
                <value>
                    <fullName>Volume</fullName>
                </value>
                <value>
                    <fullName>Locations</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Goal_Year__c</fullName>
        <defaultValue>&quot;2015&quot;</defaultValue>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Enter the 4-digit goal year (i.e., &quot;2015&quot;)</inlineHelpText>
        <label>Goal Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Goal__c</fullName>
        <label>Goal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <label>Line of Business</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Altair</fullName>
                </value>
                <value>
                    <fullName>Marchon</fullName>
                </value>
                <value>
                    <fullName>Optics</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Territory_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Territory Code</label>
        <length>22</length>
        <type>Text</type>
    </fields>
    <label>Sales Goal</label>
    <nameField>
        <displayFormat>GOAL-{00000}</displayFormat>
        <label>Sales Goal Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Goals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SalesGoalsTrigger_Test.cls
/**
 * Class Name: SalesGoalsTrigger_Test
 * Associated Trigger Name: SalesGoalsTrigger
 * @author: Katherine Boothe
 * Date: July 12, 2017
 * @description: Test Class for Sales Goal object Trigger.
 */
@isTest
public class SalesGoalsTrigger_Test {
    public static testmethod void SalesGoalsTriggerTestMethod1(){
        test.startTest();
        Sales_Goals__c goals = new Sales_Goals__c();
        goals.Goal__c = 10000.00;
        goals.Goal_Type__c = 'Dollars';
        goals.Goal_Timeline__c = 'Quarterly';
        goals.Goal_Year__c = '2017';
        goals.Line_of_Business__c = 'Optics';
        goals.Territory_Code__c = 'VE01';
        insert goals;
        system.assertNotEquals(null,goals.Id);
        
        test.stopTest();
         
    }    

        public static testmethod void SalesGoalsTriggerTestMethod2(){
        test.startTest();
        Sales_Goals__c goals = new Sales_Goals__c();
        goals.Goal__c = 10000.00;
        goals.Goal_Type__c = 'Dollars';
        goals.Goal_Timeline__c = 'Quarterly';
        goals.Goal_Year__c = '2017';
        goals.Line_of_Business__c = 'Optics';
        goals.Territory_Code__c = null;
        insert goals;
        system.assertNotEquals(null,goals.Id);
        
        test.stopTest();
         
    }    

}